import { Sign, type SignProps, type SignShape } from "@/registry/0db/ui/sign"

// Generated by scripts/build-signs.mjs from Lucide's user (ISC).
const shape: SignShape = {"word":"person","line":[[["M",5,21],["L",5,18.8],["L",5.1,18],["L",5.3,17.6],["L",5.5,17.1],["L",5.9,16.5],["L",6.3,16],["L",6.9,15.6],["L",7.8,15.2],["L",8.8,15],["L",15,15],["L",16,15.1],["L",16.9,15.5],["L",17.7,16],["L",18.3,16.7],["L",18.7,17.6],["L",18.9,18.3],["L",19,19],["L",19,21]],[["O",12,7,4,180,180]],[["O",12,7,4,180,-180]]]}

/** The sign for "person": the word set along its strokes. */
function SignUserWords(props: Omit<SignProps, "shape" | "variant">) {
  return <Sign shape={shape} variant="words" {...props} />
}

export { SignUserWords }
