import { Sign, type SignProps, type SignShape } from "@/registry/0db/ui/sign"

// Generated by scripts/build-signs.mjs from Lucide's plus (ISC).
const shape: SignShape = {"word":"add","line":[[["M",5,12],["L",19,12]],[["M",12,5],["L",12,19]]]}

/** The sign for "add": the word ruled in leaders along its strokes. */
function SignPlusDots(props: Omit<SignProps, "shape" | "variant">) {
  return <Sign shape={shape} variant="dots" {...props} />
}

export { SignPlusDots }
