import { Sign, type SignProps, type SignShape } from "@/registry/0db/ui/sign"

// Generated by scripts/build-signs.mjs from Lucide's paperclip (ISC).
const shape: SignShape = {"word":"attach","fill":{"step":2.18,"rows":[[1.1,12.8,19.2],[3.3,10.3,21.5],[5.5,8.2,14.5,17,22.4],[7.6,6,12.3,16.5,17.9,19.1,22.1],[9.8,3.8,10.2,14.3,15.7,19.5,21.7],[12,2,8,12.3,13.5,17.8,23.9],[14.2,0.9,6.2,10.1,11.5,15.7,22.1],[16.4,0.6,6,13.5,19.9],[18.5,1.2,6.7,11.4,17.7],[20.7,2.5,15.5],[22.9,5.3,12.8]]}}

/** The sign for "attach": the word filling its silhouette row by row. */
function SignPaperclipFill(props: Omit<SignProps, "shape" | "variant">) {
  return <Sign shape={shape} variant="fill" {...props} />
}

export { SignPaperclipFill }
