import { Sign, type SignProps, type SignShape } from "@/registry/0db/ui/sign"

// Generated by scripts/build-signs.mjs from Lucide's shield (ISC).
const shape: SignShape = {"word":"protect","fill":{"step":2.18,"rows":[[1.1,9.6,14.4],[3.3,4.1,19.9],[5.5,1.8,22.2],[7.6,1.5,22.5],[9.8,1.5,22.5],[12,1.5,22.5],[14.2,1.7,22.3],[16.4,2.2,21.8],[18.5,3.5,20.5],[20.7,5.5,18.5],[22.9,9.2,14.8]]}}

/** The sign for "protect": the word filling its silhouette row by row. */
function SignShieldFill(props: Omit<SignProps, "shape" | "variant">) {
  return <Sign shape={shape} variant="fill" {...props} />
}

export { SignShieldFill }
