import { Sign, type SignProps, type SignShape } from "@/registry/0db/ui/sign"

// Generated by scripts/build-signs.mjs from Lucide's pencil (ISC).
const shape: SignShape = {"word":"edit","fill":{"step":2.18,"rows":[[1.1,16.1,22.3],[3.3,13.8,24],[5.5,11.7,14.8,17.4,24],[7.6,9.6,15.7,19.3,23.2],[9.8,7.4,18,19,21.1],[12,5.2,18.9],[14.2,3,16.6],[16.4,1.2,14.4],[18.5,0.5,12.2],[20.7,0,10.1],[22.9,0.3,6.3]]}}

/** The sign for "edit": the word filling its silhouette row by row. */
function SignPencilFill(props: Omit<SignProps, "shape" | "variant">) {
  return <Sign shape={shape} variant="fill" {...props} />
}

export { SignPencilFill }
