import { Sign, type SignProps, type SignShape } from "@/registry/0db/ui/sign"

// Generated by scripts/build-signs.mjs from a drawing made for 0dB.
const shape: SignShape = {"word":"next","line":[[["M",2.5,12],["L",17.5,12]],[["M",12.5,4],["L",20,11]],[["M",12.5,20],["L",20,13]]],"mirror":true}

/** The sign for "next": the word set along its strokes. */
function SignArrowRightWords(props: Omit<SignProps, "shape" | "variant">) {
  return <Sign shape={shape} variant="words" {...props} />
}

export { SignArrowRightWords }
