import { Sign, type SignProps, type SignShape } from "@/registry/0db/ui/sign"

// Generated by scripts/build-signs.mjs from Lucide's link (ISC).
const shape: SignShape = {"word":"link","fill":{"step":2.18,"rows":[[1.1,13.6,20.3],[3.3,10.9,22.9],[5.5,9.4,24],[7.6,7.4,10.3,11.9,24],[9.8,4.2,10,14.9,23.6],[12,2.2,9,11.2,12.9,15,21.8],[14.2,0.4,9.1,14,19.8],[16.4,0,12.1,13.7,16.6],[18.5,0,14.5],[20.7,1.1,13.1],[22.9,3.7,10.4]]}}

/** The sign for "link": the word filling its silhouette row by row. */
function SignLinkFill(props: Omit<SignProps, "shape" | "variant">) {
  return <Sign shape={shape} variant="fill" {...props} />
}

export { SignLinkFill }
