import { Sign, type SignProps, type SignShape } from "@/registry/0db/ui/sign"

// Generated by scripts/build-signs.mjs from Lucide's octagon-alert (ISC).
const shape: SignShape = {"word":"danger","line":[[["M",21.8,7.9],["L",21.9,8.2],["L",22,8.7],["L",22,15.3],["L",21.9,15.8],["L",21.8,16.1]],[["M",7.9,21.8],["L",8.2,21.9],["L",8.7,22],["L",15.3,22],["L",15.8,21.9],["L",16.1,21.8]],[["M",2.2,16.1],["L",2.1,15.8],["L",2,15.3],["L",2,8.7],["L",2.1,8.2],["L",2.2,7.9]],[["M",7.9,2.2],["L",8.2,2.1],["L",8.7,2],["L",15.3,2],["L",15.8,2.1],["L",16.1,2.2]],[["M",16.1,2.2],["L",16.4,2.3],["L",16.7,2.6],["L",21.4,7.3],["L",21.7,7.6],["L",21.8,7.9]],[["M",16.1,21.8],["L",16.4,21.7],["L",16.7,21.4],["L",21.4,16.7],["L",21.7,16.4],["L",21.8,16.1]],[["M",2.2,16.1],["L",2.3,16.4],["L",2.6,16.7],["L",7.3,21.4],["L",7.6,21.7],["L",7.9,21.8]],[["M",2.2,7.9],["L",2.3,7.6],["L",2.6,7.3],["L",7.3,2.6],["L",7.6,2.3],["L",7.9,2.2]],[["M",12,8],["L",12,12]],[["M",12,16],["L",12,16]]]}

/** The sign for "danger": the word set along its strokes. */
function SignOctagonAlertWords(props: Omit<SignProps, "shape" | "variant">) {
  return <Sign shape={shape} variant="words" {...props} />
}

export { SignOctagonAlertWords }
