import { Sign, type SignProps, type SignShape } from "@/registry/0db/ui/sign"

// Generated by scripts/build-signs.mjs from Lucide's frame (ISC).
const shape: SignShape = {"word":"frame","fill":{"step":2.18,"rows":[[1.1,4.1,7.9,16.1,19.9],[3.3,3.5,8.5,15.5,20.5],[5.5,0,4,8,16,20,24],[7.6,1.1,4.9,7.1,16.9,19.1,22.9],[9.8,3.5,20.5],[12,3.5,20.5],[14.2,3.5,20.5],[16.4,1.1,4.9,7.1,16.9,19.1,22.9],[18.5,0,4,8,16,20,24],[20.7,3.5,8.5,15.5,20.5],[22.9,4.1,7.9,16.1,19.9]]}}

/** The sign for "frame": the word filling its silhouette row by row. */
function SignFrameFill(props: Omit<SignProps, "shape" | "variant">) {
  return <Sign shape={shape} variant="fill" {...props} />
}

export { SignFrameFill }
