import { Sign, type SignProps, type SignShape } from "@/registry/0db/ui/sign"

// Generated by scripts/build-signs.mjs from Lucide's cloud-fog (ISC).
const shape: SignShape = {"word":"fog","fill":{"step":2.09,"rows":[[1.5,6.5,11.7],[3.6,2.6,15.4],[5.7,0.9,17.1],[7.8,0,22],[9.9,0,23.6],[12,0,24],[14.1,0.8,24],[16.2,2.4,7.7,16.3,23],[18.3,5.4,7.9,16.1,18.1],[20.4,6.9,19.1],[22.5,7.7,18.3]]}}

/** The sign for "fog": the word filling its silhouette row by row. */
function SignCloudFogFill(props: Omit<SignProps, "shape" | "variant">) {
  return <Sign shape={shape} variant="fill" {...props} />
}

export { SignCloudFogFill }
