import { Sign, type SignProps, type SignShape } from "@/registry/0db/ui/sign"

// Generated by scripts/build-signs.mjs from Lucide's chevron-down (ISC).
const shape: SignShape = {"word":"unfold","fill":{"step":2.2,"rows":[[7.6,4.5,7.5,16.5,19.5],[9.8,4,9.7,14.3,20],[12,6.1,11.9,12.1,17.9],[14.2,8.3,15.7],[16.4,10.5,13.5]]}}

/** The sign for "unfold": the word filling its silhouette row by row. */
function SignChevronDownFill(props: Omit<SignProps, "shape" | "variant">) {
  return <Sign shape={shape} variant="fill" {...props} />
}

export { SignChevronDownFill }
