import { Sign, type SignProps, type SignShape } from "@/registry/0db/ui/sign"

// Generated by scripts/build-signs.mjs from Lucide's badge-percent (ISC).
const shape: SignShape = {"word":"sale","fill":{"step":2.18,"rows":[[1.1,8.5,15.4],[3.3,3.7,20.3],[5.5,2.1,21.9],[7.6,1.4,8.7,9.3,14.7,15.3,22.6],[9.8,0.2,8.1,9.9,12.3,15.9,23.8],[12,0,10.1,13.9,24],[14.2,0.2,8.1,11.7,14.1,15.9,23.8],[16.4,1.4,8.7,9.3,14.7,15.3,22.6],[18.5,2.1,21.9],[20.7,3.7,20.2],[22.9,8.6,15.5]]}}

/** The sign for "sale": the word filling its silhouette row by row. */
function SignPercentFill(props: Omit<SignProps, "shape" | "variant">) {
  return <Sign shape={shape} variant="fill" {...props} />
}

export { SignPercentFill }
