import { Sign, type SignProps, type SignShape } from "@/registry/0db/ui/sign"

// Generated by scripts/build-signs.mjs from Lucide's award (ISC).
const shape: SignShape = {"word":"award","fill":{"step":2.18,"rows":[[1.1,8.2,15.8],[3.3,5.5,18.5],[5.5,4.2,19.8],[7.6,3.6,20.4],[9.8,3.9,20.1],[12,5,7.7,10.3,13.7,16.3,19],[14.2,5.8,7.8,16.2,18.2],[16.4,5.5,18.5],[18.5,5.1,18.9],[20.7,4.7,19.3],[22.9,5.4,9.7,14.3,18.6]]}}

/** The sign for "award": the word filling its silhouette row by row. */
function SignAwardFill(props: Omit<SignProps, "shape" | "variant">) {
  return <Sign shape={shape} variant="fill" {...props} />
}

export { SignAwardFill }
