import { Sign, type SignProps, type SignShape } from "@/registry/0db/ui/sign"

// Generated by scripts/build-signs.mjs from Lucide's zoom-in (ISC).
const shape: SignShape = {"word":"zoom","fill":{"step":2.08,"rows":[[1.6,7.6,14.4],[3.7,4.1,17.9],[5.8,2.3,19.7],[7.9,1.2,10.1,11.9,20.8],[10,0.7,7.2,14.8,21.3],[12,0.7,7.3,14.7,21.3],[14.1,1.2,10.1,11.9,20.8],[16.2,2.3,15.6,17.9,20.3],[18.3,4.1,16.5,17.6,21.2],[20.4,7.9,14.1,17.5,23.1],[22.5,19.5,22.5]]}}

/** The sign for "zoom": the word filling its silhouette row by row. */
function SignZoomInFill(props: Omit<SignProps, "shape" | "variant">) {
  return <Sign shape={shape} variant="fill" {...props} />
}

export { SignZoomInFill }
