import { Sign, type SignProps, type SignShape } from "@/registry/0db/ui/sign"

// Generated by scripts/build-signs.mjs from Lucide's circle-check (ISC).
const shape: SignShape = {"word":"success","line":[[["O",12,12,10,180,180]],[["O",12,12,10,180,-180]],[["M",10.6,14.4],["L",16,9]],[["M",8,12],["L",10.5,14.5],["L",10.6,14.4]]]}

/** The sign for "success": the word ruled in leaders along its strokes. */
function SignCircleCheckDots(props: Omit<SignProps, "shape" | "variant">) {
  return <Sign shape={shape} variant="dots" {...props} />
}

export { SignCircleCheckDots }
