import { Sign, type SignProps, type SignShape } from "@/registry/0db/ui/sign"

// Generated by scripts/build-signs.mjs from Lucide's wrench (ISC).
const shape: SignShape = {"word":"repair","fill":{"step":2.18,"rows":[[1.1,12.1,19.5],[3.3,9.4,15.8,18.2,20.4],[5.5,8.2,13.8,17.5,19.6,20.9,23.7],[7.6,7.6,13.5,16.5,17.5,21.1,24],[9.8,7.6,14.9,19.1,24],[12,6.1,23.1],[14.2,3.9,21.1],[16.4,1.7,13.5],[18.5,0,11.2],[20.7,0,9.1],[22.9,1.2,6.9]]}}

/** The sign for "repair": the word filling its silhouette row by row. */
function SignWrenchFill(props: Omit<SignProps, "shape" | "variant">) {
  return <Sign shape={shape} variant="fill" {...props} />
}

export { SignWrenchFill }
