import { Sign, type SignProps, type SignShape } from "@/registry/0db/ui/sign"

// Generated by scripts/build-signs.mjs from Lucide's ban (ISC).
const shape: SignShape = {"word":"block","fill":{"step":2.18,"rows":[[1.1,7.2,16.8],[3.3,3.7,20.3],[5.5,1.8,4.8,7.4,22.2],[7.6,0.6,5.7,9.5,23.4],[9.8,0,7.9,11.7,24],[12,0,10.1,13.9,24],[14.2,0,12.3,16.1,24],[16.4,0.6,14.5,18.3,23.4],[18.5,1.8,16.6,19.2,22.2],[20.7,3.7,20.3],[22.9,7.2,16.8]]}}

/** The sign for "block": the word filling its silhouette row by row. */
function SignBanFill(props: Omit<SignProps, "shape" | "variant">) {
  return <Sign shape={shape} variant="fill" {...props} />
}

export { SignBanFill }
