import { Sign, type SignProps, type SignShape } from "@/registry/0db/ui/sign"

// Generated by scripts/build-signs.mjs from Lucide's key (ISC).
const shape: SignShape = {"word":"key","line":[[["O",15.5,7.5,5.5,180,180]],[["O",15.5,7.5,5.5,180,-180]],[["M",2,21],["L",11.6,11.4]],[["M",7,21.6],["L",7.3,21.5],["L",7.7,21.3],["L",9.5,19.5],["L",9.9,19],["L",10,18.8],["L",10.1,18.5]],[["M",4,19],["L",6.3,21.3],["L",6.7,21.5],["L",7,21.6]],[["M",7.5,15.5],["L",9.8,17.8],["L",10,18.2],["L",10.1,18.5]]]}

/** The sign for "key": the word ruled in leaders along its strokes. */
function SignKeyDots(props: Omit<SignProps, "shape" | "variant">) {
  return <Sign shape={shape} variant="dots" {...props} />
}

export { SignKeyDots }
