import { Sign, type SignProps, type SignShape } from "@/registry/0db/ui/sign"

// Generated by scripts/build-signs.mjs from Lucide's smartphone (ISC).
const shape: SignShape = {"word":"mobile","fill":{"step":2.18,"rows":[[1.1,4.4,19.6],[3.3,2.7,21.2],[5.5,2.5,21.5],[7.6,2.5,21.5],[9.8,2.5,21.5],[12,2.5,21.5],[14.2,2.5,21.5],[16.4,2.5,10.9,13.1,21.5],[18.5,2.5,10.5,13.5,21.5],[20.7,2.7,21.2],[22.9,4.4,19.6]]}}

/** The sign for "mobile": the word filling its silhouette row by row. */
function SignSmartphoneFill(props: Omit<SignProps, "shape" | "variant">) {
  return <Sign shape={shape} variant="fill" {...props} />
}

export { SignSmartphoneFill }
