import { Sign, type SignProps, type SignShape } from "@/registry/0db/ui/sign"

// Generated by scripts/build-signs.mjs from Lucide's keyboard (ISC).
const shape: SignShape = {"word":"keys","fill":{"step":2.1,"rows":[[2.6,2,22],[4.7,0,24],[6.8,0,5.5,6.5,9.5,10.5,13.5,14.5,17.5,18.5,24],[8.9,0,5.2,6.8,9.2,10.8,13.2,14.8,17.2,18.8,24],[11,0,7.3,8.7,11.3,12.7,15.3,16.7,24],[13.1,0,7.3,8.7,11.3,12.7,15.3,16.7,24],[15.2,0,6.2,17.8,24],[17.3,0,6.5,17.5,24],[19.4,0,24],[21.5,2,22]]}}

/** The sign for "keys": the word filling its silhouette row by row. */
function SignKeyboardFill(props: Omit<SignProps, "shape" | "variant">) {
  return <Sign shape={shape} variant="fill" {...props} />
}

export { SignKeyboardFill }
