import { Sign, type SignProps, type SignShape } from "@/registry/0db/ui/sign"

// Generated by scripts/build-signs.mjs from Lucide's lamp (ISC).
const shape: SignShape = {"word":"lamp","fill":{"step":2.18,"rows":[[1.1,6.2,17.8],[3.3,4.7,19.3],[5.5,3.9,20.1],[7.6,2.9,21.1],[9.8,2,22],[12,2,10.3,13.7,22],[14.2,9.5,11.3,12.7,14.5],[16.4,8.4,11.1,12.9,15.6],[18.5,6.1,10.6,13.6,17.9],[20.7,5.6,18.4],[22.9,6.6,17.4]]}}

/** The sign for "lamp": the word filling its silhouette row by row. */
function SignLampFill(props: Omit<SignProps, "shape" | "variant">) {
  return <Sign shape={shape} variant="fill" {...props} />
}

export { SignLampFill }
