import { Sign, type SignProps, type SignShape } from "@/registry/0db/ui/sign"

// Generated by scripts/build-signs.mjs from Lucide's chevron-down (ISC).
const shape: SignShape = {"word":"unfold","line":[[["M",6,9],["L",12,15]],[["M",12,15],["L",18,9]]]}

/** The sign for "unfold": the word set along its strokes. */
function SignChevronDownWords(props: Omit<SignProps, "shape" | "variant">) {
  return <Sign shape={shape} variant="words" {...props} />
}

export { SignChevronDownWords }
