import { Sign, type SignProps, type SignShape } from "@/registry/0db/ui/sign"

// Generated by scripts/build-signs.mjs from Lucide's align-left (ISC).
const shape: SignShape = {"word":"left","fill":{"step":2.11,"rows":[[3.6,1.7,22.3],[5.7,0.9,23.1],[12,0.6,17.4],[18.3,0.9,19.1],[20.4,1.7,18.3]]}}

/** The sign for "left": the word filling its silhouette row by row. */
function SignAlignLeftFill(props: Omit<SignProps, "shape" | "variant">) {
  return <Sign shape={shape} variant="fill" {...props} />
}

export { SignAlignLeftFill }
