import { Sign, type SignProps, type SignShape } from "@/registry/0db/ui/sign"

// Generated by scripts/build-signs.mjs from Lucide's banknote (ISC).
const shape: SignShape = {"word":"cash","line":[[["M",2.5,6.7],["L",2.9,6.4],["L",3.3,6.1],["L",4,6],["L",20,6],["L",20.7,6.1],["L",21.3,6.5]],[["M",2.7,17.5],["L",3.3,17.9],["L",4,18],["L",20,18],["L",20.5,17.9],["L",20.9,17.8],["L",21.5,17.3]],[["M",21.3,6.5],["L",21.8,7.1],["L",21.9,7.5],["L",22,8],["L",22,16],["L",21.9,16.7],["L",21.5,17.3]],[["M",2.7,17.5],["L",2.2,16.9],["L",2.1,16.5],["L",2,16],["L",2,8],["L",2.1,7.3],["L",2.5,6.7]],[["O",12,12,2,180,180]],[["O",12,12,2,180,-180]],[["M",6,12],["L",6,12]],[["M",18,12],["L",18,12]]]}

/** The sign for "cash": the word ruled in leaders along its strokes. */
function SignBanknoteDots(props: Omit<SignProps, "shape" | "variant">) {
  return <Sign shape={shape} variant="dots" {...props} />
}

export { SignBanknoteDots }
