import { Sign, type SignProps, type SignShape } from "@/registry/0db/ui/sign"

// Generated by scripts/build-signs.mjs from Lucide's dog (ISC).
const shape: SignShape = {"word":"dog","fill":{"step":2.09,"rows":[[1.5,4.8,9.6,14.6,19.5],[3.6,2.4,21.9],[5.7,1.3,9.3,11.3,12.9,14.9,23],[7.8,0.5,7.5,9.4,15,16.8,23.7],[9.9,0.1,3.5,9.1,15.2,20.3,24],[12,1.5,3.3,7.3,16.9,20.7,22.7],[14.1,1.6,7.2,8.8,15.2,16.8,22.4],[16.2,1.8,10.6,13.5,22.2],[18.3,2.7,11.5,12.5,21.3],[20.4,4.3,19.7],[22.5,8.2,15.6]]}}

/** The sign for "dog": the word filling its silhouette row by row. */
function SignDogFill(props: Omit<SignProps, "shape" | "variant">) {
  return <Sign shape={shape} variant="fill" {...props} />
}

export { SignDogFill }
