import { Sign, type SignProps, type SignShape } from "@/registry/0db/ui/sign"

// Generated by scripts/build-signs.mjs from Lucide's info (ISC).
const shape: SignShape = {"word":"info","line":[[["O",12,12,10,180,180]],[["O",12,12,10,180,-180]],[["M",12,12],["L",12,16]],[["M",12,8],["L",12,8]]]}

/** The sign for "info": the word set along its strokes. */
function SignInfoWords(props: Omit<SignProps, "shape" | "variant">) {
  return <Sign shape={shape} variant="words" {...props} />
}

export { SignInfoWords }
