import { Sign, type SignProps, type SignShape } from "@/registry/0db/ui/sign"

// Generated by scripts/build-signs.mjs from Lucide's medal (ISC).
const shape: SignShape = {"word":"medal","fill":{"step":2.18,"rows":[[1.1,3.2,20.8],[3.3,1.4,4.6,7.2,16.8,19.4,22.6],[5.5,0.2,5.6,8.5,15.5,18.4,23.8],[7.6,0.5,6.9,17.1,23.5],[9.8,1.8,8.3,11.1,12.9,15.7,22.2],[12,3,8.1,15.9,21],[14.2,4.3,6.7,9.7,14.3,17.3,19.7],[16.4,4.6,10.6,12.9,19.4],[18.5,4.9,11.1,12.9,19.1],[20.7,5.9,18.1],[22.9,8.3,15.7]]}}

/** The sign for "medal": the word filling its silhouette row by row. */
function SignMedalFill(props: Omit<SignProps, "shape" | "variant">) {
  return <Sign shape={shape} variant="fill" {...props} />
}

export { SignMedalFill }
