import { Sign, type SignProps, type SignShape } from "@/registry/0db/ui/sign"

// Generated by scripts/build-signs.mjs from Lucide's door-open (ISC).
const shape: SignShape = {"word":"door","fill":{"step":2.18,"rows":[[1.1,6.8,17.5],[3.3,3.2,9.1,10.9,20.8],[5.5,2.6,9.1,10.9,21.4],[7.6,2.5,9.1,10.9,21.5],[9.8,2.5,9.1,10.9,21.5],[12,2.5,9.1,10.9,13.3,14.7,21.5],[14.2,2.5,9.1,10.9,21.5],[16.4,2.5,9.1,10.9,21.5],[18.5,2.5,4.7,5.3,9.1,10.9,18.7,19.3,21.5],[20.7,0,4.1,5.9,9.1,10.9,18.1,19.9,24],[22.9,2,22]]}}

/** The sign for "door": the word filling its silhouette row by row. */
function SignDoorOpenFill(props: Omit<SignProps, "shape" | "variant">) {
  return <Sign shape={shape} variant="fill" {...props} />
}

export { SignDoorOpenFill }
