import { Sign, type SignProps, type SignShape } from "@/registry/0db/ui/sign"

// Generated by scripts/build-signs.mjs from Lucide's landmark (ISC).
const shape: SignShape = {"word":"bank","line":[[["M",3,6.6],["L",3.1,6.8],["L",3.3,7],["L",3.5,7],["L",20.5,7],["L",20.7,7],["L",20.9,6.8],["L",21,6.6]],[["M",3,22],["L",21,22]],[["M",12,2],["L",12.5,2.1],["L",12.9,2.2],["L",20.7,6.1],["L",20.9,6.2],["L",21,6.4],["L",21,6.6]],[["M",3,6.6],["L",3,6.4],["L",3.1,6.2],["L",3.3,6.1],["L",11.1,2.2],["L",11.5,2.1],["L",12,2]],[["M",10,18],["L",10,11]],[["M",14,11],["L",14,18]],[["M",18,11],["L",18,18]],[["M",6,18],["L",6,11]]]}

/** The sign for "bank": the word ruled in leaders along its strokes. */
function SignLandmarkDots(props: Omit<SignProps, "shape" | "variant">) {
  return <Sign shape={shape} variant="dots" {...props} />
}

export { SignLandmarkDots }
