import { Sign, type SignProps, type SignShape } from "@/registry/0db/ui/sign"

// Generated by scripts/build-signs.mjs from Lucide's scissors (ISC).
const shape: SignShape = {"word":"cut","fill":{"step":2.09,"rows":[[1.5,3.8,8.2],[3.6,1.4,10.6,17.4,22.3],[5.7,0.6,11.4,15.4,21.2],[7.8,1.1,11.3,13.3,19.1],[9.9,2.9,17],[12,5,7,7.9,10.6,12.9,15.9],[14.1,2.9,17],[16.2,1.1,11.3,13.3,19.1],[18.3,0.6,11.4,15.4,21.2],[20.4,1.4,10.6,17.4,22.3],[22.5,3.8,8.2]]}}

/** The sign for "cut": the word filling its silhouette row by row. */
function SignScissorsFill(props: Omit<SignProps, "shape" | "variant">) {
  return <Sign shape={shape} variant="fill" {...props} />
}

export { SignScissorsFill }
