import { Sign, type SignProps, type SignShape } from "@/registry/0db/ui/sign"

// Generated by scripts/build-signs.mjs from Lucide's chevron-left (ISC).
const shape: SignShape = {"word":"before","fill":{"step":2.13,"rows":[[4.6,13.7,16.3],[6.7,11.4,17.1],[8.8,9.3,15],[10.9,7.2,12.9],[13.1,7.2,12.9],[15.2,9.3,15.1],[17.3,11.5,17.1],[19.4,13.7,16.3]]},"mirror":true}

/** The sign for "before": the word filling its silhouette row by row. */
function SignChevronLeftFill(props: Omit<SignProps, "shape" | "variant">) {
  return <Sign shape={shape} variant="fill" {...props} />
}

export { SignChevronLeftFill }
