import { Sign, type SignProps, type SignShape } from "@/registry/0db/ui/sign"

// Generated by scripts/build-signs.mjs from Lucide's coins (ISC).
const shape: SignShape = {"word":"coins","fill":{"step":2.18,"rows":[[1.1,12.1,19.9],[3.3,9.4,22.6],[5.5,8.2,14.1,16.9,23.8],[7.6,7.6,15.1,16.9,24],[9.8,2.9,9.3,11.5,15.1,16.9,24],[12,0.9,10,13.7,23.1],[14.2,0,5.2,8.3,12,15.4,21],[16.4,0,6.8,9.6,16],[18.5,0.2,8.1,9.9,15.8],[20.7,1.4,14.6],[22.9,4,11.9]]}}

/** The sign for "coins": the word filling its silhouette row by row. */
function SignCoinsFill(props: Omit<SignProps, "shape" | "variant">) {
  return <Sign shape={shape} variant="fill" {...props} />
}

export { SignCoinsFill }
