import { Sign, type SignProps, type SignShape } from "@/registry/0db/ui/sign"

// Generated by scripts/build-signs.mjs from Lucide's magnet (ISC).
const shape: SignShape = {"word":"magnet","fill":{"step":2.18,"rows":[[1.1,9.9,18.5],[3.3,6.8,21.7],[5.5,4.7,23.2],[7.6,2.5,4.7,6.5,11.5,16.2,24],[9.8,0.4,4.9,8.7,9.3,13.1,14.7,16.9,24],[12,0,7.1,10.9,13.1,16.6,24],[14.2,1.3,6.1,8.7,10.9,14.6,23.2],[16.4,3.7,9,15.3,21.5],[18.5,6.6,9.7,10.1,13.6,16.2,19.3],[20.7,7.8,17.2],[22.9,10,15]]}}

/** The sign for "magnet": the word filling its silhouette row by row. */
function SignMagnetFill(props: Omit<SignProps, "shape" | "variant">) {
  return <Sign shape={shape} variant="fill" {...props} />
}

export { SignMagnetFill }
