import { Sign, type SignProps, type SignShape } from "@/registry/0db/ui/sign"

// Generated by scripts/build-signs.mjs from Lucide's layers (ISC).
const shape: SignShape = {"word":"layers","fill":{"step":2.18,"rows":[[1.1,9.2,14.8],[3.3,4.3,19.7],[5.5,0.3,23.7],[7.6,0,2.5,6,18,21.5,24],[9.8,0.9,3,10.8,13.2,21,23.1],[12,0,2.7,4.6,7.6,16.4,19.4,21.3,24],[14.2,0.9,2.5,9.3,14.7,21.5,23.1],[16.4,0,6.3,17.7,24],[18.5,0.3,11.1,12.9,23.7],[20.7,4.3,19.7],[22.9,9.2,14.8]]}}

/** The sign for "layers": the word filling its silhouette row by row. */
function SignLayersFill(props: Omit<SignProps, "shape" | "variant">) {
  return <Sign shape={shape} variant="fill" {...props} />
}

export { SignLayersFill }
