import { Sign, type SignProps, type SignShape } from "@/registry/0db/ui/sign"

// Generated by scripts/build-signs.mjs from Lucide's eye (ISC).
const shape: SignShape = {"word":"view","fill":{"step":2.11,"rows":[[3.6,8.8,15.1],[5.7,4.3,19.7],[7.8,2,10.2,13.8,22],[9.9,0.5,8.2,15.8,23.5],[12,0,7.9,10.1,13.9,16.1,24],[14.1,0.5,8.2,15.8,23.5],[16.2,2,10.2,13.8,22],[18.3,4.3,19.7],[20.4,8.9,15.2]]}}

/** The sign for "view": the word filling its silhouette row by row. */
function SignEyeFill(props: Omit<SignProps, "shape" | "variant">) {
  return <Sign shape={shape} variant="fill" {...props} />
}

export { SignEyeFill }
