import { Sign, type SignProps, type SignShape } from "@/registry/0db/ui/sign"

// Generated by scripts/build-signs.mjs from Lucide's external-link (ISC).
const shape: SignShape = {"word":"visit","fill":{"step":2.09,"rows":[[1.5,13.5,22.5],[3.6,12.6,18.5,21,23.5],[5.7,1.6,16.4,20.2,23.5],[7.8,0.6,14.3,18.1,23.5],[9.9,0.5,12.2,16,23],[12,0.5,10.1,13.9,19.9],[14.1,0.5,9.3,11.8,20.5],[16.2,0.5,20.5],[18.3,0.5,20.5],[20.4,1,20],[22.5,3,18]]}}

/** The sign for "visit": the word filling its silhouette row by row. */
function SignExternalLinkFill(props: Omit<SignProps, "shape" | "variant">) {
  return <Sign shape={shape} variant="fill" {...props} />
}

export { SignExternalLinkFill }
