import { Sign, type SignProps, type SignShape } from "@/registry/0db/ui/sign"

// Generated by scripts/build-signs.mjs from Lucide's trash-2 (ISC).
const shape: SignShape = {"word":"delete","line":[[["M",3,6],["L",21,6]],[["M",5,6],["L",5,20],["L",5.1,20.7],["L",5.4,21.1],["L",5.7,21.5]],[["M",19,6],["L",19,20],["L",18.9,20.7],["L",18.5,21.3]],[["M",5.7,21.5],["L",6.3,21.9],["L",7,22],["L",17,22],["L",17.5,21.9],["L",17.9,21.8],["L",18.5,21.3]],[["M",8.5,2.7],["L",9.1,2.2],["L",9.5,2.1],["L",10,2],["L",14.2,2],["L",14.8,2.2],["L",15.3,2.5]],[["M",10,17],["L",10,11]],[["M",14,11],["L",14,17]],[["M",15.3,2.5],["L",15.7,3],["L",15.9,3.5],["L",16,4],["L",16,6]],[["M",8,6],["L",8,3.8],["L",8.1,3.3],["L",8.5,2.7]]]}

/** The sign for "delete": the word ruled in leaders along its strokes. */
function SignTrashDots(props: Omit<SignProps, "shape" | "variant">) {
  return <Sign shape={shape} variant="dots" {...props} />
}

export { SignTrashDots }
