import { Sign, type SignProps, type SignShape } from "@/registry/0db/ui/sign"

// Generated by scripts/build-signs.mjs from Lucide's ticket (ISC).
const shape: SignShape = {"word":"ticket","fill":{"step":2.11,"rows":[[3.6,2,22],[5.7,0,12.1,13.9,24],[7.8,0,12.1,13.9,24],[9.9,0,12.3,13.7,24],[12,1.4,12.1,13.9,22.7],[14.1,0,12.3,13.7,24],[16.2,0,12.1,13.9,24],[18.3,0,12.1,13.9,24],[20.4,2.1,22]]}}

/** The sign for "ticket": the word filling its silhouette row by row. */
function SignTicketFill(props: Omit<SignProps, "shape" | "variant">) {
  return <Sign shape={shape} variant="fill" {...props} />
}

export { SignTicketFill }
