import { Sign, type SignProps, type SignShape } from "@/registry/0db/ui/sign"

// Generated by scripts/build-signs.mjs from Lucide's rotate-cw (ISC).
const shape: SignShape = {"word":"rotate","fill":{"step":2.09,"rows":[[1.5,9,15.1,19.7,22.3],[3.6,4.9,23.5],[5.7,2.8,17.5,20.9,23.5],[7.8,1.6,15,21.4,23.4],[9.9,0.9,22.6],[12,0.5,23.4],[14.1,0.9,23.1],[16.2,1.6,22.4],[18.3,2.8,21.2],[20.4,5,19.2],[22.5,9,15]]}}

/** The sign for "rotate": the word filling its silhouette row by row. */
function SignRotateFill(props: Omit<SignProps, "shape" | "variant">) {
  return <Sign shape={shape} variant="fill" {...props} />
}

export { SignRotateFill }
