import { Sign, type SignProps, type SignShape } from "@/registry/0db/ui/sign"

// Generated by scripts/build-signs.mjs from Lucide's credit-card (ISC).
const shape: SignShape = {"word":"card","line":[[["M",2,10],["L",22,10]],[["M",2.5,5.7],["L",2.9,5.4],["L",3.3,5.1],["L",4,5],["L",20,5],["L",20.7,5.1],["L",21.3,5.5]],[["M",2.7,18.5],["L",3.3,18.9],["L",4,19],["L",20,19],["L",20.5,18.9],["L",20.9,18.8],["L",21.5,18.3]],[["M",21.3,5.5],["L",21.8,6.1],["L",21.9,6.5],["L",22,7],["L",22,17],["L",21.9,17.7],["L",21.5,18.3]],[["M",2.7,18.5],["L",2.2,17.9],["L",2.1,17.5],["L",2,17],["L",2,7],["L",2.1,6.3],["L",2.5,5.7]],[["M",6,14],["L",8,14]]]}

/** The sign for "card": the word set along its strokes. */
function SignCreditCardWords(props: Omit<SignProps, "shape" | "variant">) {
  return <Sign shape={shape} variant="words" {...props} />
}

export { SignCreditCardWords }
