import { Sign, type SignProps, type SignShape } from "@/registry/0db/ui/sign"

// Generated by scripts/build-signs.mjs from Lucide's users (ISC).
const shape: SignShape = {"word":"team","line":[[["M",2,21],["L",2,18.8],["L",2.1,18],["L",2.3,17.6],["L",2.5,17.1],["L",2.9,16.5],["L",3.3,16],["L",3.9,15.6],["L",4.8,15.2],["L",5.8,15],["L",12,15],["L",13,15.1],["L",13.9,15.5],["L",14.7,16],["L",15.3,16.7],["L",15.7,17.6],["L",15.9,18.3],["L",16,19],["L",16,21]],[["O",9,7,4,180,180]],[["O",9,7,4,180,-180]],[["M",19,15.1],["L",19.9,15.5],["L",20.5,15.9],["L",21,16.4],["L",21.5,17.2],["L",21.8,17.8],["L",22,18.5],["L",22,21]],[["M",16,10.9],["L",16.7,10.6],["L",17.3,10.3],["L",17.9,9.8],["L",18.2,9.4],["L",18.6,8.8],["L",18.8,8.3],["L",18.9,7.6],["L",19,7]],[["M",16,3.1],["L",16.5,3.3],["L",17.1,3.6],["L",17.7,4.1],["L",18.2,4.6],["L",18.6,5.2],["L",18.8,5.7],["L",18.9,6.4],["L",19,7]]]}

/** The sign for "team": the word ruled in leaders along its strokes. */
function SignUsersDots(props: Omit<SignProps, "shape" | "variant">) {
  return <Sign shape={shape} variant="dots" {...props} />
}

export { SignUsersDots }
