import { Sign, type SignProps, type SignShape } from "@/registry/0db/ui/sign"

// Generated by scripts/build-signs.mjs from Lucide's history (ISC).
const shape: SignShape = {"word":"history","fill":{"step":2.09,"rows":[[1.5,1.7,4.3,8.8,15],[3.6,0.5,19.1],[5.7,0.5,3.1,6.3,11.2,12.8,21.2],[7.8,0.6,2.6,9,10.9,13.1,22.4],[9.9,1.4,10.9,13.1,23.1],[12,0.6,10.9,15.5,23.5],[14.1,0.9,12.7,17,23.1],[16.2,1.7,22.4],[18.3,2.8,21.1],[20.4,4.8,19],[22.5,9,15]]}}

/** The sign for "history": the word filling its silhouette row by row. */
function SignHistoryFill(props: Omit<SignProps, "shape" | "variant">) {
  return <Sign shape={shape} variant="fill" {...props} />
}

export { SignHistoryFill }
