import { Sign, type SignProps, type SignShape } from "@/registry/0db/ui/sign"

// Generated by scripts/build-signs.mjs from Lucide's circle-help (ISC).
const shape: SignShape = {"word":"help","line":[[["O",12,12,10,180,180]],[["O",12,12,10,180,-180]],[["M",9.1,9],["L",9.3,8.5],["L",9.6,8],["L",10.1,7.6],["L",10.5,7.3],["L",11,7.2],["L",11.6,7],["L",12.2,7],["L",12.7,7.1],["L",13.1,7.3],["L",13.6,7.5],["L",14,7.9],["L",14.4,8.4],["L",14.7,8.8],["L",14.8,9.3],["L",14.9,9.8],["L",14.9,10.4]],[["M",11.9,13],["L",13.1,12.4],["L",13.9,11.9],["L",14.3,11.5],["L",14.6,11],["L",14.9,10.4]],[["M",12,17],["L",12,17]]]}

/** The sign for "help": the word set along its strokes. */
function SignCircleHelpWords(props: Omit<SignProps, "shape" | "variant">) {
  return <Sign shape={shape} variant="words" {...props} />
}

export { SignCircleHelpWords }
