import { Sign, type SignProps, type SignShape } from "@/registry/0db/ui/sign"

// Generated by scripts/build-signs.mjs from Lucide's bold (ISC).
const shape: SignShape = {"word":"bold","fill":{"step":2.1,"rows":[[2.6,5.5,16.1],[4.7,3.7,19.1],[6.8,3.5,20.2],[8.9,3.5,20.3],[11,3.5,5.8,17.4,19.7],[13.1,3.5,5.8,17.8,20.4],[15.2,3.5,21.3],[17.3,3.5,21.2],[19.4,3.7,20.1],[21.5,5.5,17.1]]}}

/** The sign for "bold": the word filling its silhouette row by row. */
function SignBoldFill(props: Omit<SignProps, "shape" | "variant">) {
  return <Sign shape={shape} variant="fill" {...props} />
}

export { SignBoldFill }
