import { Sign, type SignProps, type SignShape } from "@/registry/0db/ui/sign"

// Generated by scripts/build-signs.mjs from Lucide's target (ISC).
const shape: SignShape = {"word":"target","fill":{"step":2.18,"rows":[[1.1,7.2,16.8],[3.3,3.7,20.3],[5.5,1.8,8.5,15.5,22.2],[7.6,0.6,6.3,10.8,13.2,17.7,23.4],[9.8,0,5.3,7.7,9.6,14.4,16.3,18.7,24],[12,0,5.1,6.9,9.2,11.1,12.9,14.8,17.1,18.9,24],[14.2,0,5.3,7.7,9.6,14.4,16.3,18.7,24],[16.4,0.6,6.3,10.8,13.2,17.7,23.4],[18.5,1.8,8.5,15.5,22.2],[20.7,3.7,20.3],[22.9,7.2,16.8]]}}

/** The sign for "target": the word filling its silhouette row by row. */
function SignTargetFill(props: Omit<SignProps, "shape" | "variant">) {
  return <Sign shape={shape} variant="fill" {...props} />
}

export { SignTargetFill }
