import { Sign, type SignProps, type SignShape } from "@/registry/0db/ui/sign"

// Generated by scripts/build-signs.mjs from Lucide's bell-ring (ISC).
const shape: SignShape = {"word":"ring","fill":{"step":2.18,"rows":[[1.1,2.1,5.9,8.2,15.8,18.1,21.9],[3.3,0.9,6.3,8.1,15.9,17.7,23.1],[5.5,0,5.2,8.2,15.8,18.8,24],[7.6,0,4.9,7.1,16.9,19.1,24],[9.8,3.3,5.1,6.9,17.1,18.9,20.7],[12,3.1,20.9],[14.2,1.6,22.4],[16.4,0.7,8.7,15.1,23.3],[18.5,2.7,9.3,14.5,21.3],[20.7,8,16],[22.9,9.3,14.7]]}}

/** The sign for "ring": the word filling its silhouette row by row. */
function SignBellRingFill(props: Omit<SignProps, "shape" | "variant">) {
  return <Sign shape={shape} variant="fill" {...props} />
}

export { SignBellRingFill }
