import { Sign, type SignProps, type SignShape } from "@/registry/0db/ui/sign"

// Generated by scripts/build-signs.mjs from Lucide's euro (ISC).
const shape: SignShape = {"word":"euro","line":[[["M",6,12],["L",6,11],["L",6.3,9.8],["L",6.7,8.6],["L",7.2,7.6],["L",7.9,6.8],["L",8.8,5.9],["L",9.6,5.3],["L",10.7,4.7],["L",11.6,4.3],["L",12.8,4.1],["L",13.8,4],["L",15,4.1],["L",16,4.3],["L",17.2,4.8],["L",18.1,5.3],["L",19,6]],[["M",6,12],["L",6.1,13.2],["L",6.3,14.3],["L",6.7,15.4],["L",7.3,16.3],["L",7.9,17.2],["L",8.9,18.2],["L",9.7,18.8],["L",10.7,19.3],["L",11.8,19.7],["L",12.9,19.9],["L",14,20],["L",15,19.9],["L",16,19.7],["L",17.1,19.3],["L",18.1,18.7],["L",19,18]],[["M",4,10],["L",16,10]],[["M",4,14],["L",13,14]]]}

/** The sign for "euro": the word ruled in leaders along its strokes. */
function SignEuroDots(props: Omit<SignProps, "shape" | "variant">) {
  return <Sign shape={shape} variant="dots" {...props} />
}

export { SignEuroDots }
