import { Sign, type SignProps, type SignShape } from "@/registry/0db/ui/sign"

// Generated by scripts/build-signs.mjs from Lucide's save (ISC).
const shape: SignShape = {"word":"save","line":[[["M",3.7,20.5],["L",4.3,20.9],["L",5,21],["L",19,21],["L",19.5,20.9],["L",19.9,20.8],["L",20.5,20.3]],[["M",3.7,20.5],["L",3.2,19.9],["L",3.1,19.5],["L",3,19],["L",3,5],["L",3.1,4.3],["L",3.5,3.7]],[["M",3.5,3.7],["L",3.9,3.4],["L",4.3,3.1],["L",5,3],["L",15.2,3],["L",15.9,3.1]],[["M",20.9,8.1],["L",21,8.8],["L",21,19],["L",20.9,19.7],["L",20.5,20.3]],[["M",7.3,13.3],["L",7.6,13.1],["L",8,13],["L",16,13],["L",16.4,13.1],["L",16.7,13.3]],[["M",7.3,7.7],["L",7.6,7.9],["L",8,8],["L",15,8]],[["M",16.7,13.3],["L",16.9,13.6],["L",17,14],["L",17,21]],[["M",7,21],["L",7,14],["L",7.1,13.6],["L",7.3,13.3]],[["M",15.9,3.1],["L",16.4,3.4],["L",17.9,4.9],["L",20.4,7.4],["L",20.7,7.7],["L",20.9,8.1]],[["M",7.3,7.7],["L",7.1,7.4],["L",7,7],["L",7,3]]]}

/** The sign for "save": the word ruled in leaders along its strokes. */
function SignSaveDots(props: Omit<SignProps, "shape" | "variant">) {
  return <Sign shape={shape} variant="dots" {...props} />
}

export { SignSaveDots }
