import { Sign, type SignProps, type SignShape } from "@/registry/0db/ui/sign"

// Generated by scripts/build-signs.mjs from Lucide's database (ISC).
const shape: SignShape = {"word":"data","fill":{"step":2.18,"rows":[[1.1,4.9,19],[3.3,1.3,22.6],[5.5,0.5,2.8,5.4,18.5,21.2,23.5],[7.6,0.5,3.3,20.5,23.5],[9.8,0.5,23.5],[12,0.5,3.1,4.4,19.6,20.9,23.5],[14.2,0.5,3,21,23.5],[16.4,0.5,9.8,14,23.5],[18.5,0.6,23.4],[20.7,1.3,22.7],[22.9,4.8,19.2]]}}

/** The sign for "data": the word filling its silhouette row by row. */
function SignDatabaseFill(props: Omit<SignProps, "shape" | "variant">) {
  return <Sign shape={shape} variant="fill" {...props} />
}

export { SignDatabaseFill }
