import { Sign, type SignProps, type SignShape } from "@/registry/0db/ui/sign"

// Generated by scripts/build-signs.mjs from Lucide's hard-drive (ISC).
const shape: SignShape = {"word":"drive","line":[[["M",2.1,12],["L",21.9,12]],[["M",2.5,19.3],["L",2.9,19.6],["L",3.2,19.8],["L",3.5,19.9],["L",4,20],["L",20,20],["L",20.7,19.9],["L",21.3,19.5]],[["M",2.5,19.3],["L",2.2,18.9],["L",2,18.2],["L",2,12.5],["L",2.1,12],["L",2.2,11.6],["L",5.5,5.1],["L",5.6,4.8],["L",5.9,4.5],["L",6.3,4.2]],[["M",17.9,4.4],["L",18.3,4.7],["L",18.6,5.1],["L",21.9,11.8],["L",22,12.5],["L",22,15.1]],[["M",6.3,4.2],["L",6.8,4.1],["L",7.2,4],["L",16.8,4],["L",17.2,4.1],["L",17.5,4.1],["L",17.9,4.4]],[["M",22,15.1],["L",22,18.2],["L",21.8,18.9],["L",21.3,19.5]],[["M",10,16],["L",10,16]],[["M",6,16],["L",6,16]]]}

/** The sign for "drive": the word ruled in leaders along its strokes. */
function SignHardDriveDots(props: Omit<SignProps, "shape" | "variant">) {
  return <Sign shape={shape} variant="dots" {...props} />
}

export { SignHardDriveDots }
