import { Sign, type SignProps, type SignShape } from "@/registry/0db/ui/sign"

// Generated by scripts/build-signs.mjs from Lucide's power (ISC).
const shape: SignShape = {"word":"power","fill":{"step":2.18,"rows":[[1.1,10,14],[3.3,9.5,14.5],[5.5,3.9,7.3,9.5,14.5,16.7,20.1],[7.6,2.2,7.5,9.5,14.5,16.5,21.8],[9.8,1.2,6,9.5,14.5,18,22.9],[12,0.7,5.5,9.6,14.4,18.5,23.4],[14.2,0.7,5.6,18.5,23.3],[16.4,1.3,6.2,17.9,22.7],[18.5,2.4,7.8,16.3,21.7],[20.7,4.2,20],[22.9,7.5,16.7]]}}

/** The sign for "power": the word filling its silhouette row by row. */
function SignPowerFill(props: Omit<SignProps, "shape" | "variant">) {
  return <Sign shape={shape} variant="fill" {...props} />
}

export { SignPowerFill }
