import { Sign, type SignProps, type SignShape } from "@/registry/0db/ui/sign"

// Generated by scripts/build-signs.mjs from Lucide's waves (ISC).
const shape: SignShape = {"word":"sea","fill":{"step":2.1,"rows":[[2.6,7.3,11.5,17.5,21.4],[4.7,0,24],[6.8,1.1,7.9,11.1,17.9,21.3,22.7],[11,0.2,3.9,5.1,13.9,15.1,23.8],[13.1,0.2,8.9,10.1,18.8,20.1,23.8],[17.3,1.3,2.7,6.1,12.9,16.1,22.9],[19.4,0,24],[21.5,2.4,6.7,12.3,16.7]]}}

/** The sign for "sea": the word filling its silhouette row by row. */
function SignWavesFill(props: Omit<SignProps, "shape" | "variant">) {
  return <Sign shape={shape} variant="fill" {...props} />
}

export { SignWavesFill }
