import { Sign, type SignProps, type SignShape } from "@/registry/0db/ui/sign"

// Generated by scripts/build-signs.mjs from Lucide's coffee (ISC).
const shape: SignShape = {"word":"coffee","fill":{"step":2.14,"rows":[[1.1,4.1,7.9,8.1,11.9,12.1,15.9],[3.2,3.5,8.9,11.1,16.5],[5.3,3.9,9.2,10.8,16.1],[7.5,1.3,4.7,15.5,16.2,17.7,21.8],[9.6,0.5,5.7,14.6,15.9,18.1,23.7],[11.8,0.5,15.9,18.1,24],[13.9,0.5,15.9,18.1,24],[16,0.5,15.5,18.7,22.4],[18.2,0.8,19.1],[20.3,1.9,18.1],[22.4,4.9,15.1]]}}

/** The sign for "coffee": the word filling its silhouette row by row. */
function SignCoffeeFill(props: Omit<SignProps, "shape" | "variant">) {
  return <Sign shape={shape} variant="fill" {...props} />
}

export { SignCoffeeFill }
