import { Sign, type SignProps, type SignShape } from "@/registry/0db/ui/sign"

// Generated by scripts/build-signs.mjs from Lucide's wifi (ISC).
const shape: SignShape = {"word":"wifi","fill":{"step":2,"rows":[[3.5,8.3,15.7],[5.5,3.2,20.8],[7.5,0.4,23.6],[9.5,0,7.1,16.9,24],[11.5,3,5.3,18.7,21],[13.5,2.9,10.9,13.1,21.1],[15.5,6.2,9.3,14.7,17.8],[17.5,6.7,17.3],[19.5,9.8,14.2],[21.5,10.7,13.3]]}}

/** The sign for "wifi": the word filling its silhouette row by row. */
function SignWifiFill(props: Omit<SignProps, "shape" | "variant">) {
  return <Sign shape={shape} variant="fill" {...props} />
}

export { SignWifiFill }
