import { Sign, type SignProps, type SignShape } from "@/registry/0db/ui/sign"

// Generated by scripts/build-signs.mjs from Lucide's magnet (ISC).
const shape: SignShape = {"word":"magnet","fill":{"step":2.18,"rows":[[1.1,10.1,18.3],[3.3,6.9,21.6],[5.5,4.7,23.2],[7.6,2.5,4.5,6.8,11.2,16.5,24],[9.8,0.4,4.7,13.3,14.5,17.1,24],[12,0,6.8,11.2,12.8,16.8,24],[14.2,1.3,5.7,9,10.7,14.9,23.2],[16.4,3.7,8.9,15.5,21.5],[18.5,6.6,9.3,10.5,13.4,16.5,19.3],[20.7,7.9,17.1],[22.9,10.1,14.9]]}}

/** The sign for "magnet": the word filling its silhouette row by row. */
function SignMagnetFill(props: Omit<SignProps, "shape" | "variant">) {
  return <Sign shape={shape} variant="fill" {...props} />
}

export { SignMagnetFill }
