import { Sign, type SignProps, type SignShape } from "@/registry/0db/ui/sign"

// Generated by scripts/build-signs.mjs from Lucide's beer (ISC).
const shape: SignShape = {"word":"beer","fill":{"step":2.18,"rows":[[1.1,8.3,13.7],[3.3,1.4,20.6],[5.5,0.6,21.4],[7.6,1.4,4.2,18.5,20.6],[9.8,2.5,15.6,19.1,20.5],[12,2.5,7.9,10.1,11.9,14.1,15.5,19.2,22.7],[14.2,2.5,7.9,10.1,11.9,14.1,15.9,18.1,23.4],[16.4,2.5,7.9,10.1,11.9,14.1,15.5,18.7,22.5],[18.5,2.5,7.9,10.1,11.9,14.1,15.8,18.4,19.6],[20.7,2.7,19.2],[22.9,4.4,17.6]]}}

/** The sign for "beer": the word filling its silhouette row by row. */
function SignBeerFill(props: Omit<SignProps, "shape" | "variant">) {
  return <Sign shape={shape} variant="fill" {...props} />
}

export { SignBeerFill }
