import { Sign, type SignProps, type SignShape } from "@/registry/0db/ui/sign"

// Generated by scripts/build-signs.mjs from Lucide's award (ISC).
const shape: SignShape = {"word":"award","fill":{"step":2.18,"rows":[[1.1,8.1,15.9],[3.3,5.4,18.6],[5.5,4.2,19.8],[7.6,3.6,20.4],[9.8,3.9,20.1],[12,4.9,7.9,9.7,14.3,16.1,19.1],[14.2,5.7,8,16,18.3],[16.4,5.5,18.5],[18.5,5.1,18.9],[20.7,4.7,19.3],[22.9,5.3,9.8,14.2,18.7]]}}

/** The sign for "award": the word filling its silhouette row by row. */
function SignAwardFill(props: Omit<SignProps, "shape" | "variant">) {
  return <Sign shape={shape} variant="fill" {...props} />
}

export { SignAwardFill }
