import { Sign, type SignProps, type SignShape } from "@/registry/0db/ui/sign"

// Generated by scripts/build-signs.mjs from Lucide's bell-off (ISC).
const shape: SignShape = {"word":"snooze","line":[[["M",2,2],["L",22,22]],[["M",8.7,3],["L",9.5,2.5],["L",10.5,2.2],["L",11.5,2],["L",12.5,2],["L",13.4,2.2],["L",14.5,2.5],["L",15.5,3.1],["L",16.2,3.7],["L",16.7,4.3],["L",17.1,4.9],["L",17.5,5.6],["L",17.7,6],["L",17.8,6.6],["L",18,7.3],["L",18.1,9.5],["L",18.4,11],["L",18.6,11.7],["L",18.9,12.6],["L",19.3,13.4],["L",19.7,14.1]],[["M",3.1,16.4],["L",3.2,16.6],["L",3.5,16.8],["L",3.8,17],["L",4,17],["L",17,17]],[["M",3.1,16.4],["L",3,16],["L",3.1,15.5],["L",4.2,14.3],["L",4.7,13.6],["L",5.2,12.6],["L",5.5,11.8],["L",5.7,11],["L",5.9,10.1],["L",6,9.1],["L",6,7.3],["L",6.3,6.3]],[["M",11.9,22],["L",12.4,22],["L",12.8,21.8],["L",13.1,21.7],["L",13.4,21.4],["L",13.7,21]],[["M",10.3,21],["L",10.6,21.4],["L",10.9,21.7],["L",11.4,21.9],["L",11.9,22]]]}

/** The sign for "snooze": the word set along its strokes. */
function SignBellOffWords(props: Omit<SignProps, "shape" | "variant">) {
  return <Sign shape={shape} variant="words" {...props} />
}

export { SignBellOffWords }
