import { Sign, type SignProps, type SignShape } from "@/registry/0db/ui/sign"

// Generated by scripts/build-signs.mjs from Lucide's camera (ISC).
const shape: SignShape = {"word":"photo","fill":{"step":2.1,"rows":[[2.6,8,16],[4.7,6,18.1],[6.8,0.6,23.4],[8.9,0,10.6,13.4,24],[11,0,8.4,15.6,24],[13.1,0,8.1,10,14,15.9,24],[15.2,0,8.4,15.6,24],[17.3,0,10.9,13.1,24],[19.4,0,24],[21.5,2,22]]}}

/** The sign for "photo": the word filling its silhouette row by row. */
function SignCameraFill(props: Omit<SignProps, "shape" | "variant">) {
  return <Sign shape={shape} variant="fill" {...props} />
}

export { SignCameraFill }
