import { Sign, type SignProps, type SignShape } from "@/registry/0db/ui/sign"

// Generated by scripts/build-signs.mjs from Lucide's calendar-check (ISC).
const shape: SignShape = {"word":"booked","fill":{"step":2.14,"rows":[[1.1,5,19],[3.2,1.3,7,9,15,17,22.8],[5.3,0.6,7.1,8.9,15.1,16.9,23.4],[7.5,0.5,23.5],[9.6,0.5,2.8,21.1,23.5],[11.8,0.5,14.5,15.5,23.5],[13.9,0.5,8.3,9.8,12.2,15.8,23.5],[16,0.5,8.2,13.9,23.5],[18.2,0.5,10.3,11.7,23.5],[20.3,1,23],[22.4,3,21]]}}

/** The sign for "booked": the word filling its silhouette row by row. */
function SignCalendarCheckFill(props: Omit<SignProps, "shape" | "variant">) {
  return <Sign shape={shape} variant="fill" {...props} />
}

export { SignCalendarCheckFill }
