import { Sign, type SignProps, type SignShape } from "@/registry/0db/ui/sign"

// Generated by scripts/build-signs.mjs from Lucide's pin (ISC).
const shape: SignShape = {"word":"pin","fill":{"step":2.18,"rows":[[1.1,5.3,18.7],[3.3,3.7,20.3],[5.5,4.1,19.9],[7.6,6.4,17.6],[9.8,6.5,17.5],[12,4.8,19.2],[14.2,2.9,21.2],[16.4,2.7,10.1,13.9,21.3],[18.5,4.7,11.1,12.9,19.3],[20.7,9.5,14.5],[22.9,10,14]]}}

/** The sign for "pin": the word filling its silhouette row by row. */
function SignPinFill(props: Omit<SignProps, "shape" | "variant">) {
  return <Sign shape={shape} variant="fill" {...props} />
}

export { SignPinFill }
