import { Sign, type SignProps, type SignShape } from "@/registry/0db/ui/sign"

// Generated by scripts/build-signs.mjs from Lucide's heart-pulse (ISC).
const shape: SignShape = {"word":"health","fill":{"step":2,"rows":[[2.5,5.1,9.9,14.1,19.2],[4.5,1.8,22.2],[6.5,0.4,23.6],[8.5,0,13.2,14.8,24],[10.5,0,12.6,15.7,24],[12.5,0.4,3.3,11.5,12.1,20.7,23.6],[14.5,1.8,9.9,13.7,22.2],[16.5,3.6,10.8,13.1,20.4],[18.5,5.7,18.3],[20.5,7.8,16.2],[22.5,10.2,13.8]]}}

/** The sign for "health": the word filling its silhouette row by row. */
function SignHeartPulseFill(props: Omit<SignProps, "shape" | "variant">) {
  return <Sign shape={shape} variant="fill" {...props} />
}

export { SignHeartPulseFill }
