import { Sign, type SignProps, type SignShape } from "@/registry/0db/ui/sign"

// Generated by scripts/build-signs.mjs from Lucide's footprints (ISC).
const shape: SignShape = {"word":"walk","fill":{"step":2.18,"rows":[[1.1,4.3,10.3],[3.3,2.1,11.9],[5.5,1.1,8.8,10.8,12.4,13.3,20.3],[7.6,0.6,8.2,11.3,12.6,15.7,22.1],[9.8,0.8,11.4,11.6,12.6,15.5,23],[12,1.4,3.7,8.3,10.7,12,23.4],[14.2,1.5,3.8,8.2,10.5,12.7,23.1],[16.4,1.7,10.3,13.4,15.7,20.3,22.5],[18.5,3,9,13.5,16.3,19.7,22.5],[20.7,13.7,22.2],[22.9,15.4,20.6]]}}

/** The sign for "walk": the word filling its silhouette row by row. */
function SignFootprintsFill(props: Omit<SignProps, "shape" | "variant">) {
  return <Sign shape={shape} variant="fill" {...props} />
}

export { SignFootprintsFill }
