import { Sign, type SignProps, type SignShape } from "@/registry/0db/ui/sign"

// Generated by scripts/build-signs.mjs from Lucide's notebook (ISC).
const shape: SignShape = {"word":"notes","fill":{"step":2.18,"rows":[[1.1,3.4,20.6],[3.3,1.7,14.9,17.1,22.2],[5.5,0,2.5,7,14.9,17.1,22.5],[7.6,0.2,2.9,6.1,14.9,17.1,22.5],[9.8,0,2,7,14.9,17.1,22.5],[12,0.5,2.9,5.1,14.9,17.1,22.5],[14.2,0,2,7,14.9,17.1,22.5],[16.4,0.2,2.9,6.1,14.9,17.1,22.5],[18.5,0,2.5,7,14.9,17.1,22.5],[20.7,1.7,14.9,17.1,22.2],[22.9,3.4,20.6]]}}

/** The sign for "notes": the word filling its silhouette row by row. */
function SignNotebookFill(props: Omit<SignProps, "shape" | "variant">) {
  return <Sign shape={shape} variant="fill" {...props} />
}

export { SignNotebookFill }
