import { Sign, type SignProps, type SignShape } from "@/registry/0db/ui/sign"

// Generated by scripts/build-signs.mjs from Lucide's shield-check (ISC).
const shape: SignShape = {"word":"safe","fill":{"step":2.18,"rows":[[1.1,9.4,14.6],[3.3,3.9,20.1],[5.5,1.8,22.2],[7.6,1.5,22.5],[9.8,1.5,13.3,15.8,22.5],[12,1.5,8.3,14.9,22.5],[14.2,1.7,9.3,12.7,22.3],[16.4,2.2,21.8],[18.5,3.5,20.5],[20.7,5.4,18.6],[22.9,9,15]]}}

/** The sign for "safe": the word filling its silhouette row by row. */
function SignShieldCheckFill(props: Omit<SignProps, "shape" | "variant">) {
  return <Sign shape={shape} variant="fill" {...props} />
}

export { SignShieldCheckFill }
