import { Sign, type SignProps, type SignShape } from "@/registry/0db/ui/sign"

// Generated by scripts/build-signs.mjs from Lucide's shirt (ISC).
const shape: SignShape = {"word":"shirt","fill":{"step":2.18,"rows":[[1.1,4.6,10,14,19.4],[3.3,0.6,10.7,13.4,23.4],[5.5,0,24],[7.6,0.2,23.8],[9.8,0.7,4.5,6.9,17.1,19.5,23.3],[12,3.5,5.4,6.6,17.3,18.7,20.5],[14.2,3.5,20.5],[16.4,3.5,20.5],[18.5,3.5,20.5],[20.7,3.7,20.2],[22.9,5.2,18.8]]}}

/** The sign for "shirt": the word filling its silhouette row by row. */
function SignShirtFill(props: Omit<SignProps, "shape" | "variant">) {
  return <Sign shape={shape} variant="fill" {...props} />
}

export { SignShirtFill }
