import { Sign, type SignProps, type SignShape } from "@/registry/0db/ui/sign"

// Generated by scripts/build-signs.mjs from Lucide's book-open (ISC).
const shape: SignShape = {"word":"read","fill":{"step":2.09,"rows":[[1.5,2,10.6,13.4,22],[3.6,0,11.2,13.1,24],[5.7,0,11,13.1,24],[7.8,0,11.1,12.9,24],[9.9,0,11.1,12.9,24],[12,0,11.1,12.9,24],[14.1,0,11.1,12.9,24],[16.2,0,11.1,12.9,24],[18.3,0,11.1,12.9,24],[20.4,1.8,11.1,12.9,22.2],[22.5,10.5,13.5]]}}

/** The sign for "read": the word filling its silhouette row by row. */
function SignBookOpenFill(props: Omit<SignProps, "shape" | "variant">) {
  return <Sign shape={shape} variant="fill" {...props} />
}

export { SignBookOpenFill }
