import { Sign, type SignProps, type SignShape } from "@/registry/0db/ui/sign"

// Generated by scripts/build-signs.mjs from Lucide's shopping-cart (ISC).
const shape: SignShape = {"word":"cart","fill":{"step":2.18,"rows":[[1.1,0.2,5.6],[3.3,0.4,22.1],[5.5,2.3,24],[7.6,2.7,24],[9.8,3.1,23.8],[12,3.5,23.5],[14.2,3.9,6.2,19.1,22.5],[16.4,4.3,21.3],[18.5,4.1,6.4,11.7,14.4,18.9,21.9],[20.7,3.7,12.3,13.7,22.3],[22.9,5.2,10.8,15.2,20.8]]}}

/** The sign for "cart": the word filling its silhouette row by row. */
function SignShoppingCartFill(props: Omit<SignProps, "shape" | "variant">) {
  return <Sign shape={shape} variant="fill" {...props} />
}

export { SignShoppingCartFill }
