import { Sign, type SignProps, type SignShape } from "@/registry/0db/ui/sign"

// Generated by scripts/build-signs.mjs from Lucide's meh (ISC).
const shape: SignShape = {"word":"okay","line":[[["O",12,12,10,180,180]],[["O",12,12,10,180,-180]],[["M",8,16],["L",16,16]],[["M",15,9],["L",15,10]],[["M",9,10],["L",9,9]]]}

/** The sign for "okay": the word set along its strokes. */
function SignMehWords(props: Omit<SignProps, "shape" | "variant">) {
  return <Sign shape={shape} variant="words" {...props} />
}

export { SignMehWords }
