import { Sign, type SignProps, type SignShape } from "@/registry/0db/ui/sign"

// Generated by scripts/build-signs.mjs from Lucide's arrow-up (ISC).
const shape: SignShape = {"word":"up","line":[[["M",12,5],["L",12,19]],[["M",5,12],["L",12,5]],[["M",12,5],["L",19,12]]]}

/** The sign for "up": the word set along its strokes. */
function SignArrowUpWords(props: Omit<SignProps, "shape" | "variant">) {
  return <Sign shape={shape} variant="words" {...props} />
}

export { SignArrowUpWords }
