import { Sign, type SignProps, type SignShape } from "@/registry/0db/ui/sign"

// Generated by scripts/build-signs.mjs from Lucide's eye (ISC).
const shape: SignShape = {"word":"view","fill":{"step":2.11,"rows":[[3.6,8.5,15.5],[5.7,4.1,19.8],[7.8,1.9,10.6,13.4,22.1],[9.9,0.5,8.4,15.6,23.5],[12,0,8.1,10,14,15.9,24],[14.1,0.5,8.4,15.6,23.5],[16.2,1.9,10.6,13.4,22.1],[18.3,4.2,19.9],[20.4,8.5,15.5]]}}

/** The sign for "view": the word filling its silhouette row by row. */
function SignEyeFill(props: Omit<SignProps, "shape" | "variant">) {
  return <Sign shape={shape} variant="fill" {...props} />
}

export { SignEyeFill }
