import { Sign, type SignProps, type SignShape } from "@/registry/0db/ui/sign"

// Generated by scripts/build-signs.mjs from Lucide's mouse (ISC).
const shape: SignShape = {"word":"mouse","fill":{"step":2.18,"rows":[[1.1,7.8,16.2],[3.3,4.9,19.1],[5.5,3.5,11.1,12.9,20.5],[7.6,2.8,11.1,12.9,21.2],[9.8,2.5,11.1,12.9,21.5],[12,2.5,21.5],[14.2,2.5,21.5],[16.4,2.8,21.2],[18.5,3.6,20.4],[20.7,4.9,19.1],[22.9,7.8,16.2]]}}

/** The sign for "mouse": the word filling its silhouette row by row. */
function SignMouseFill(props: Omit<SignProps, "shape" | "variant">) {
  return <Sign shape={shape} variant="fill" {...props} />
}

export { SignMouseFill }
