import { Sign, type SignProps, type SignShape } from "@/registry/0db/ui/sign"

// Generated by scripts/build-signs.mjs from Lucide's save (ISC).
const shape: SignShape = {"word":"save","fill":{"step":2.09,"rows":[[1.5,3.2,17],[3.6,1,5.9,8.1,19.5],[5.7,0.5,5.9,8.1,21.6],[7.8,0.5,6,16,23.2],[9.9,0.5,23.5],[12,0.5,6.5,17.5,23.5],[14.1,0.5,5.9,18.1,23.5],[16.2,0.5,5.9,8.1,15.9,18.1,23.5],[18.3,0.5,5.9,8.1,15.9,18.1,23.5],[20.4,1,5.9,8.1,15.9,18.1,23],[22.5,3.2,20.8]]}}

/** The sign for "save": the word filling its silhouette row by row. */
function SignSaveFill(props: Omit<SignProps, "shape" | "variant">) {
  return <Sign shape={shape} variant="fill" {...props} />
}

export { SignSaveFill }
