import { Sign, type SignProps, type SignShape } from "@/registry/0db/ui/sign"

// Generated by scripts/build-signs.mjs from Lucide's external-link (ISC).
const shape: SignShape = {"word":"visit","fill":{"step":2.09,"rows":[[1.5,13.7,22.3],[3.6,12.6,18.2,21.3,23.5],[5.7,1.6,16.1,20.4,23.5],[7.8,0.6,14.1,18.3,23.5],[9.9,0.5,12,16.2,23],[12,0.5,9.9,14.1,19.9],[14.1,0.5,9,12,20.5],[16.2,0.5,20.5],[18.3,0.5,20.5],[20.4,1,20],[22.5,3.2,17.8]]}}

/** The sign for "visit": the word filling its silhouette row by row. */
function SignExternalLinkFill(props: Omit<SignProps, "shape" | "variant">) {
  return <Sign shape={shape} variant="fill" {...props} />
}

export { SignExternalLinkFill }
