import { Sign, type SignProps, type SignShape } from "@/registry/0db/ui/sign"

// Generated by scripts/build-signs.mjs from Lucide's smile (ISC).
const shape: SignShape = {"word":"happy","line":[[["O",12,12,10,180,180]],[["O",12,12,10,180,-180]],[["M",7.5,15],["L",7.9,15.4],["L",8.4,15.8],["L",9.1,16.2],["L",9.5,16.5],["L",10,16.6],["L",10.7,16.8],["L",11.4,17],["L",12.1,17],["L",12.9,16.9],["L",13.3,16.8],["L",14.1,16.6],["L",14.5,16.5],["L",14.9,16.2],["L",15.6,15.8],["L",16.1,15.4],["L",16.5,15]],[["M",15,9],["L",15,10]],[["M",9,10],["L",9,9]]]}

/** The sign for "happy": the word ruled in leaders along its strokes. */
function SignSmileDots(props: Omit<SignProps, "shape" | "variant">) {
  return <Sign shape={shape} variant="dots" {...props} />
}

export { SignSmileDots }
