import { Sign, type SignProps, type SignShape } from "@/registry/0db/ui/sign"

// Generated by scripts/build-signs.mjs from Lucide's store (ISC).
const shape: SignShape = {"word":"shop","fill":{"step":2.14,"rows":[[1.1,4.3,19.8],[3.2,2.5,21.5],[5.3,1.1,22.9],[7.5,0,24],[9.6,0,3.9,20.1,24],[11.8,1.3,3.3,6.5,7.4,11.6,12.4,16.6,17.5,20.7,22.7],[13.9,1.5,8.9,15.1,22.5],[16,1.5,8.1,15.9,22.5],[18.2,1.5,8.1,9.9,14.1,15.9,22.5],[20.3,2,8.1,9.9,14.1,15.9,22],[22.4,4.1,20]]}}

/** The sign for "shop": the word filling its silhouette row by row. */
function SignStoreFill(props: Omit<SignProps, "shape" | "variant">) {
  return <Sign shape={shape} variant="fill" {...props} />
}

export { SignStoreFill }
