import { Sign, type SignProps, type SignShape } from "@/registry/0db/ui/sign"

// Generated by scripts/build-signs.mjs from Lucide's circle-help (ISC).
const shape: SignShape = {"word":"help","fill":{"step":2.18,"rows":[[1.1,7.4,16.6],[3.3,3.8,20.2],[5.5,1.8,11.1,12.8,22.2],[7.6,0.6,8.3,15.6,23.4],[9.8,0,8.1,10.1,13.7,16,24],[12,0,10.9,15.6,24],[14.2,0,11,13.2,24],[16.4,0.6,10.5,13.5,23.4],[18.5,1.8,10.8,13.2,22.2],[20.7,3.8,20.2],[22.9,7.4,16.6]]}}

/** The sign for "help": the word filling its silhouette row by row. */
function SignCircleHelpFill(props: Omit<SignProps, "shape" | "variant">) {
  return <Sign shape={shape} variant="fill" {...props} />
}

export { SignCircleHelpFill }
