import { Sign, type SignProps, type SignShape } from "@/registry/0db/ui/sign"

// Generated by scripts/build-signs.mjs from Lucide's rss (ISC).
const shape: SignShape = {"word":"feed","line":[[["M",4,4],["L",5.5,4.1],["L",7,4.3],["L",8.7,4.7],["L",10.1,5.2],["L",11.6,5.9],["L",12.9,6.7],["L",14.1,7.6],["L",15.2,8.6],["L",16.4,9.9],["L",17.3,11.1],["L",18.1,12.4],["L",18.8,13.9],["L",19.4,15.6],["L",19.7,17],["L",19.9,18.5],["L",20,20]],[["M",4,11],["L",4.9,11],["L",5.7,11.2],["L",6.6,11.4],["L",7.4,11.7],["L",8.3,12.1],["L",8.9,12.5],["L",9.7,13.1],["L",10.4,13.6],["L",10.9,14.3],["L",11.5,15.1],["L",12,15.9],["L",12.3,16.6],["L",12.6,17.4],["L",12.8,18.3],["L",13,19.1],["L",13,20]],[["O",5,19,1,180,180]],[["O",5,19,1,180,-180]]]}

/** The sign for "feed": the word ruled in leaders along its strokes. */
function SignRssDots(props: Omit<SignProps, "shape" | "variant">) {
  return <Sign shape={shape} variant="dots" {...props} />
}

export { SignRssDots }
