import { Sign, type SignProps, type SignShape } from "@/registry/0db/ui/sign"

// Generated by scripts/build-signs.mjs from Lucide's shopping-basket (ISC).
const shape: SignShape = {"word":"basket","fill":{"step":2.1,"rows":[[2.6,7.5,10.5,13.5,16.5],[4.7,6.1,11.1,12.9,17.9],[6.8,4.9,9.9,14.1,19.1],[8.9,3.7,9.4,14.6,20.3],[11,0,4.5,9.9,14.1,19.5,24],[13.1,1.6,8.3,10.2,13.8,15.7,22.5],[15.2,2,4.4,19.6,22],[17.3,2.5,8.7,10.7,13.3,15.3,21.5],[19.4,3.1,9,10.8,13.2,15,20.9],[21.5,5.1,18.9]]}}

/** The sign for "basket": the word filling its silhouette row by row. */
function SignShoppingBasketFill(props: Omit<SignProps, "shape" | "variant">) {
  return <Sign shape={shape} variant="fill" {...props} />
}

export { SignShoppingBasketFill }
