import { Sign, type SignProps, type SignShape } from "@/registry/0db/ui/sign"

// Generated by scripts/build-signs.mjs from Lucide's video (ISC).
const shape: SignShape = {"word":"video","fill":{"step":2.13,"rows":[[4.6,2.2,15.8],[6.7,0,18,18.5,23.9],[8.8,0,14.9,18.9,24],[10.9,0,14.9,18.3,24],[13.1,0,14.9,18.8,24],[15.2,0,14.9,19,24],[17.3,0,18,19,23.8],[19.4,2.2,15.8]]}}

/** The sign for "video": the word filling its silhouette row by row. */
function SignVideoFill(props: Omit<SignProps, "shape" | "variant">) {
  return <Sign shape={shape} variant="fill" {...props} />
}

export { SignVideoFill }
