import { Sign, type SignProps, type SignShape } from "@/registry/0db/ui/sign"

// Generated by scripts/build-signs.mjs from Lucide's ghost (ISC).
const shape: SignShape = {"word":"ghost","fill":{"step":2.18,"rows":[[1.1,7.6,16.4],[3.3,4.5,19.5],[5.5,3,21],[7.6,2,22],[9.8,1.6,8.1,9.9,14.1,15.9,22.4],[12,1.5,8.2,9.8,14.2,15.8,22.5],[14.2,1.5,22.5],[16.4,1.5,22.5],[18.5,1.5,22.5],[20.7,1.6,22.4],[22.9,2.8,8,9.3,14.6,16,21.2]]}}

/** The sign for "ghost": the word filling its silhouette row by row. */
function SignGhostFill(props: Omit<SignProps, "shape" | "variant">) {
  return <Sign shape={shape} variant="fill" {...props} />
}

export { SignGhostFill }
