import { Sign, type SignProps, type SignShape } from "@/registry/0db/ui/sign"

// Generated by scripts/build-signs.mjs from Lucide's chevron-up (ISC).
const shape: SignShape = {"word":"fold","fill":{"step":2.2,"rows":[[7.6,10.5,13.5],[9.8,8.3,15.7],[12,6.1,11.9,12.1,17.9],[14.2,4,9.7,14.3,20],[16.4,4.5,7.5,16.5,19.5]]}}

/** The sign for "fold": the word filling its silhouette row by row. */
function SignChevronUpFill(props: Omit<SignProps, "shape" | "variant">) {
  return <Sign shape={shape} variant="fill" {...props} />
}

export { SignChevronUpFill }
