import { Sign, type SignProps, type SignShape } from "@/registry/0db/ui/sign"

// Generated by scripts/build-signs.mjs from Lucide's archive (ISC).
const shape: SignShape = {"word":"archive","line":[[["M",2.3,7.7],["L",2.6,7.9],["L",3,8],["L",21,8],["L",21.4,7.9],["L",21.7,7.7]],[["M",2.3,3.3],["L",2.6,3.1],["L",3,3],["L",21,3],["L",21.4,3.1],["L",21.7,3.3]],[["M",4.5,20.3],["L",4.9,20.6],["L",5.2,20.8],["L",5.5,20.9],["L",6,21],["L",18,21],["L",18.7,20.9],["L",19.3,20.5]],[["M",20,8],["L",20,19],["L",19.9,19.5],["L",19.8,19.9],["L",19.3,20.5]],[["M",4.5,20.3],["L",4.1,19.7],["L",4,19],["L",4,8]],[["M",21.7,3.3],["L",21.9,3.6],["L",22,4],["L",22,7],["L",21.9,7.4],["L",21.7,7.7]],[["M",2.3,7.7],["L",2.1,7.4],["L",2,7],["L",2,4],["L",2.1,3.6],["L",2.3,3.3]],[["M",10,12],["L",14,12]]]}

/** The sign for "archive": the word set along its strokes. */
function SignArchiveWords(props: Omit<SignProps, "shape" | "variant">) {
  return <Sign shape={shape} variant="words" {...props} />
}

export { SignArchiveWords }
