import { Sign, type SignProps, type SignShape } from "@/registry/0db/ui/sign"

// Generated by scripts/build-signs.mjs from Lucide's lock-open (ISC).
const shape: SignShape = {"word":"unlock","fill":{"step":2.18,"rows":[[1.1,8.2,15.7],[3.3,5.9,18.1],[5.5,4.8,19.1],[7.6,4.5,18],[9.8,2.7,5.6,16.7,21.3],[12,0.8,5.5,16.8,23.2],[14.2,0.5,23.5],[16.4,0.5,23.5],[18.5,0.5,23.5],[20.7,0.8,23.3],[22.9,2.2,21.7]]}}

/** The sign for "unlock": the word filling its silhouette row by row. */
function SignUnlockFill(props: Omit<SignProps, "shape" | "variant">) {
  return <Sign shape={shape} variant="fill" {...props} />
}

export { SignUnlockFill }
