import { Sign, type SignProps, type SignShape } from "@/registry/0db/ui/sign"

// Generated by scripts/build-signs.mjs from Lucide's inbox (ISC).
const shape: SignShape = {"word":"inbox","fill":{"step":2.1,"rows":[[2.6,5.2,18.8],[4.7,3.2,20.8],[6.8,2.2,21.9],[8.9,1.1,22.9],[11,0.1,2,8.7,15.3,21.8,23.9],[13.1,0,2,10.1,13.9,21.8,24],[15.2,0,8.7,15.3,24],[17.3,0,24],[19.4,0,24],[21.5,2.1,22]]}}

/** The sign for "inbox": the word filling its silhouette row by row. */
function SignInboxFill(props: Omit<SignProps, "shape" | "variant">) {
  return <Sign shape={shape} variant="fill" {...props} />
}

export { SignInboxFill }
