import { Sign, type SignProps, type SignShape } from "@/registry/0db/ui/sign"

// Generated by scripts/build-signs.mjs from Lucide's funnel (ISC).
const shape: SignShape = {"word":"filter","fill":{"step":2.14,"rows":[[1.6,1.3,22.7],[3.7,0,24],[5.8,0.5,23.5],[8,2.5,21.5],[10.1,4.4,19.6],[12.3,6.3,17.7],[14.4,7.5,16.5],[16.5,7.5,16.5],[18.7,7.5,16.5],[20.8,7.9,16.4],[22.9,10.3,15.4]]}}

/** The sign for "filter": the word filling its silhouette row by row. */
function SignFilterFill(props: Omit<SignProps, "shape" | "variant">) {
  return <Sign shape={shape} variant="fill" {...props} />
}

export { SignFilterFill }
