import { Sign, type SignProps, type SignShape } from "@/registry/0db/ui/sign"

// Generated by scripts/build-signs.mjs from Lucide's chevron-right (ISC).
const shape: SignShape = {"word":"after","line":[[["M",9,18],["L",15,12]],[["M",9,6],["L",15,12]]],"mirror":true}

/** The sign for "after": the word set along its strokes. */
function SignChevronRightWords(props: Omit<SignProps, "shape" | "variant">) {
  return <Sign shape={shape} variant="words" {...props} />
}

export { SignChevronRightWords }
