import { Sign, type SignProps, type SignShape } from "@/registry/0db/ui/sign"

// Generated by scripts/build-signs.mjs from Lucide's message-square (ISC).
const shape: SignShape = {"word":"comment","fill":{"step":2.14,"rows":[[1.6,2.2,21.8],[3.7,0,24],[5.8,0,24],[8,0,24],[10.1,0,24],[12.3,0,24],[14.4,0,24],[16.5,0,24],[18.7,0,23.8],[20.8,0,20.7],[22.9,0.6,4.9]]}}

/** The sign for "comment": the word filling its silhouette row by row. */
function SignMessageSquareFill(props: Omit<SignProps, "shape" | "variant">) {
  return <Sign shape={shape} variant="fill" {...props} />
}

export { SignMessageSquareFill }
