import { Sign, type SignProps, type SignShape } from "@/registry/0db/ui/sign"

// Generated by scripts/build-signs.mjs from Lucide's film (ISC).
const shape: SignShape = {"word":"film","fill":{"step":2.09,"rows":[[1.5,3,21],[3.6,1,6.1,7.9,16.1,17.9,23],[5.7,0.5,6.1,7.9,16.1,17.9,23.5],[7.8,0.5,2.9,7.9,16.1,21.1,23.5],[9.9,0.5,6.1,7.9,16.1,17.9,23.5],[12,0.5,3.1,20.9,23.5],[14.1,0.5,6.1,7.9,16.1,17.9,23.5],[16.2,0.5,2.9,7.9,16.1,21.1,23.5],[18.3,0.5,6.1,7.9,16.1,17.9,23.5],[20.4,1,6.1,7.9,16.1,17.9,23],[22.5,3,21]]}}

/** The sign for "film": the word filling its silhouette row by row. */
function SignFilmFill(props: Omit<SignProps, "shape" | "variant">) {
  return <Sign shape={shape} variant="fill" {...props} />
}

export { SignFilmFill }
