import { Sign, type SignProps, type SignShape } from "@/registry/0db/ui/sign"

// Generated by scripts/build-signs.mjs from Lucide's sticky-note (ISC).
const shape: SignShape = {"word":"note","line":[[["M",3.5,20.3],["L",3.1,19.7],["L",3,19],["L",3,5],["L",3.1,4.5],["L",3.2,4.1],["L",3.7,3.5]],[["M",3.5,20.3],["L",4.1,20.8],["L",4.5,20.9],["L",5,21],["L",19,21],["L",19.7,20.9],["L",20.3,20.5]],[["M",20.8,8.1],["L",21,8.5],["L",21,9],["L",21,19],["L",20.9,19.5],["L",20.8,19.9],["L",20.3,20.5]],[["M",3.7,3.5],["L",4.3,3.1],["L",5,3],["L",15,3],["L",15.5,3],["L",15.9,3.2]],[["M",15.9,3.2],["L",16.3,3.4],["L",16.8,3.8],["L",20.3,7.3],["L",20.6,7.7],["L",20.8,8.1]],[["M",15,3],["L",15,8],["L",15.1,8.4],["L",15.3,8.7]],[["M",15.3,8.7],["L",15.6,8.9],["L",16,9],["L",21,9]]]}

/** The sign for "note": the word ruled in leaders along its strokes. */
function SignStickyNoteDots(props: Omit<SignProps, "shape" | "variant">) {
  return <Sign shape={shape} variant="dots" {...props} />
}

export { SignStickyNoteDots }
