import { Sign, type SignProps, type SignShape } from "@/registry/0db/ui/sign"

// Generated by scripts/build-signs.mjs from Lucide's at-sign (ISC).
const shape: SignShape = {"word":"mention","fill":{"step":2.18,"rows":[[1.1,7.2,16.8],[3.3,3.7,20.3],[5.5,1.8,22.2],[7.6,0.6,8.9,16.9,23.4],[9.8,0,7.4,10.6,13.4,16.9,24],[12,0,7.1,9,15,16.9,24],[14.2,0,7.4,10.6,13.4,18,24],[16.4,0.6,8.9,15.1,16.3,18.9,22.7],[18.5,1.9,20.3],[20.7,3.7,20.1],[22.9,7.2,16.7]]}}

/** The sign for "mention": the word filling its silhouette row by row. */
function SignAtSignFill(props: Omit<SignProps, "shape" | "variant">) {
  return <Sign shape={shape} variant="fill" {...props} />
}

export { SignAtSignFill }
