import { Sign, type SignProps, type SignShape } from "@/registry/0db/ui/sign"

// Generated by scripts/build-signs.mjs from Lucide's droplet (ISC).
const shape: SignShape = {"word":"drop","fill":{"step":2.14,"rows":[[1.6,10.5,13.5],[3.7,9.5,14.5],[5.8,8.5,15.5],[8,6.6,17.4],[10.1,4.5,19.5],[12.3,3.2,20.8],[14.4,2.7,21.3],[16.5,2.8,21.2],[18.7,3.6,20.4],[20.8,5,19],[22.9,7.8,16.2]]}}

/** The sign for "drop": the word filling its silhouette row by row. */
function SignDropletFill(props: Omit<SignProps, "shape" | "variant">) {
  return <Sign shape={shape} variant="fill" {...props} />
}

export { SignDropletFill }
