import { Sign, type SignProps, type SignShape } from "@/registry/0db/ui/sign"

// Generated by scripts/build-signs.mjs from Lucide's wine (ISC).
const shape: SignShape = {"word":"wine","fill":{"step":2.18,"rows":[[1.1,7.1,16.9],[3.3,6.2,17.8],[5.5,5.5,18.5],[7.6,4.9,19.1],[9.8,4.6,6.7,17.3,19.4],[12,5,19],[14.2,6.3,10.3,13.7,17.7],[16.4,9.4,10.5,13.5,14.6],[18.5,9.5,14.5],[20.7,6.4,10.5,13.5,17.6],[22.9,6.1,11,13,17.9]]}}

/** The sign for "wine": the word filling its silhouette row by row. */
function SignWineFill(props: Omit<SignProps, "shape" | "variant">) {
  return <Sign shape={shape} variant="fill" {...props} />
}

export { SignWineFill }
