import { Sign, type SignProps, type SignShape } from "@/registry/0db/ui/sign"

// Generated by scripts/build-signs.mjs from Lucide's archive (ISC).
const shape: SignShape = {"word":"archive","fill":{"step":2.09,"rows":[[1.5,1.5,22.5],[3.6,0,24],[5.7,0,24],[7.8,0,2.5,21.5,24],[9.9,1.5,2.7,5.3,18.7,21.3,22.5],[12,1.5,8.9,15.1,22.5],[14.1,1.5,22.5],[16.2,1.5,22.5],[18.3,1.5,22.5],[20.4,2,22],[22.5,4.2,19.8]]}}

/** The sign for "archive": the word filling its silhouette row by row. */
function SignArchiveFill(props: Omit<SignProps, "shape" | "variant">) {
  return <Sign shape={shape} variant="fill" {...props} />
}

export { SignArchiveFill }
