import { Sign, type SignProps, type SignShape } from "@/registry/0db/ui/sign"

// Generated by scripts/build-signs.mjs from Lucide's chart-pie (ISC).
const shape: SignShape = {"word":"pie","fill":{"step":2.18,"rows":[[1.1,7.3,8.7,10.7,16.6],[3.3,3.8,10.9,13.1,20.2],[5.5,1.8,10.9,13.1,22.2],[7.6,0.6,10.9,13.1,23.4],[9.8,0,10.9,13.1,24],[12,0,11,21.3,24],[14.2,0,23],[16.4,0.6,23.4],[18.5,1.8,22.1],[20.7,3.8,20.2],[22.9,7.5,16.6]]}}

/** The sign for "pie": the word filling its silhouette row by row. */
function SignChartPieFill(props: Omit<SignProps, "shape" | "variant">) {
  return <Sign shape={shape} variant="fill" {...props} />
}

export { SignChartPieFill }
