import { Sign, type SignProps, type SignShape } from "@/registry/0db/ui/sign"

// Generated by scripts/build-signs.mjs from Lucide's watch (ISC).
const shape: SignShape = {"word":"watch","fill":{"step":2.18,"rows":[[1.1,7.7,16.2],[3.3,6.3,17.7],[5.5,5.9,8.5,15.5,18.1],[7.6,5.2,7.8,10.8,13.2,16.2,18.8],[9.8,4,11.1,12.9,20],[12,3.6,11.1,14.3,20.4],[14.2,4,12.6,14.4,20],[16.4,5.2,7.8,10.8,13.2,16.4,18.8],[18.5,5.9,8.5,15.5,18.1],[20.7,6.3,17.7],[22.9,7.9,16.2]]}}

/** The sign for "watch": the word filling its silhouette row by row. */
function SignWatchFill(props: Omit<SignProps, "shape" | "variant">) {
  return <Sign shape={shape} variant="fill" {...props} />
}

export { SignWatchFill }
