import { Sign, type SignProps, type SignShape } from "@/registry/0db/ui/sign"

// Generated by scripts/build-signs.mjs from Lucide's database (ISC).
const shape: SignShape = {"word":"data","fill":{"step":2.18,"rows":[[1.1,5.3,18.6],[3.3,1.4,22.6],[5.5,0.5,2.7,5.8,18.1,21.4,23.5],[7.6,0.5,3.1,20.8,23.5],[9.8,0.5,23.5],[12,0.5,2.8,4.9,19.1,21.2,23.5],[14.2,0.5,2.8,21.2,23.5],[16.4,0.5,7.8,15.7,23.5],[18.5,0.6,23.4],[20.7,1.4,22.6],[22.9,5.2,18.8]]}}

/** The sign for "data": the word filling its silhouette row by row. */
function SignDatabaseFill(props: Omit<SignProps, "shape" | "variant">) {
  return <Sign shape={shape} variant="fill" {...props} />
}

export { SignDatabaseFill }
