import { Sign, type SignProps, type SignShape } from "@/registry/0db/ui/sign"

// Generated by scripts/build-signs.mjs from Lucide's image (ISC).
const shape: SignShape = {"word":"image","fill":{"step":2.09,"rows":[[1.5,3.2,20.8],[3.6,1,23],[5.7,0.5,7.5,10.5,23.5],[7.8,0.5,6,12,23.5],[9.9,0.5,6,12,15.4,17.6,23.5],[12,0.5,7.2,10.8,12.9,20,23.5],[14.1,0.5,10.8,15,18,21.3,23.5],[16.2,0.5,8.7,12.9,23.5],[18.3,0.5,6.6,10.9,23.5],[20.4,1,5.7,8.8,23],[22.5,3.2,20.8]]}}

/** The sign for "image": the word filling its silhouette row by row. */
function SignImageFill(props: Omit<SignProps, "shape" | "variant">) {
  return <Sign shape={shape} variant="fill" {...props} />
}

export { SignImageFill }
