import { Sign, type SignProps, type SignShape } from "@/registry/0db/ui/sign"

// Generated by scripts/build-signs.mjs from Lucide's info (ISC).
const shape: SignShape = {"word":"info","fill":{"step":2.18,"rows":[[1.1,7.2,16.8],[3.3,3.7,20.3],[5.5,1.8,22.2],[7.6,0.6,11.1,12.9,23.4],[9.8,0,24],[12,0,11.1,12.9,24],[14.2,0,11.1,12.9,24],[16.4,0.6,11.1,12.9,23.4],[18.5,1.8,22.2],[20.7,3.7,20.3],[22.9,7.2,16.8]]}}

/** The sign for "info": the word filling its silhouette row by row. */
function SignInfoFill(props: Omit<SignProps, "shape" | "variant">) {
  return <Sign shape={shape} variant="fill" {...props} />
}

export { SignInfoFill }
