import { Sign, type SignProps, type SignShape } from "@/registry/0db/ui/sign"

// Generated by scripts/build-signs.mjs from Lucide's redo-2 (ISC).
const shape: SignShape = {"word":"redo","fill":{"step":2.1,"rows":[[2.6,13.5,16.5],[4.7,12.9,18.6],[6.8,13.7,20.7],[8.9,4.5,14.7,19.8,22.4],[11,2.7,21],[13.1,1.8,6.6,13,18.9],[15.2,1.6,6.5,13.2,16.8],[17.3,2.2,7.4],[19.4,3.6,15.1],[21.5,6.8,14.5]]},"mirror":true}

/** The sign for "redo": the word filling its silhouette row by row. */
function SignRedoFill(props: Omit<SignProps, "shape" | "variant">) {
  return <Sign shape={shape} variant="fill" {...props} />
}

export { SignRedoFill }
