import { Sign, type SignProps, type SignShape } from "@/registry/0db/ui/sign"

// Generated by scripts/build-signs.mjs from Lucide's alarm-clock (ISC).
const shape: SignShape = {"word":"alarm","line":[[["O",12,13,8,180,180]],[["O",12,13,8,180,-180]],[["M",2,6],["L",5,3]],[["M",19,3],["L",22,6]],[["M",12,9],["L",12,12.9]],[["M",4,21],["L",6.4,18.7]],[["M",17.6,18.7],["L",20,21]],[["M",12,12.9],["L",12,13],["L",14,15]]]}

/** The sign for "alarm": the word ruled in leaders along its strokes. */
function SignAlarmClockDots(props: Omit<SignProps, "shape" | "variant">) {
  return <Sign shape={shape} variant="dots" {...props} />
}

export { SignAlarmClockDots }
