import { Sign, type SignProps, type SignShape } from "@/registry/0db/ui/sign"

// Generated by scripts/build-signs.mjs from Lucide's at-sign (ISC).
const shape: SignShape = {"word":"mention","fill":{"step":2.18,"rows":[[1.1,7.4,16.6],[3.3,3.8,20.2],[5.5,1.8,22.2],[7.6,0.6,8.6,17.1,23.4],[9.8,0,7.2,11,13,17.1,24],[12,0,6.9,9.1,14.9,17.1,24],[14.2,0,7.2,11,13,18.3,24],[16.4,0.6,8.6,15.4,16,19,22.7],[18.5,1.9,20],[20.7,3.9,20],[22.9,7.3,16.5]]}}

/** The sign for "mention": the word filling its silhouette row by row. */
function SignAtSignFill(props: Omit<SignProps, "shape" | "variant">) {
  return <Sign shape={shape} variant="fill" {...props} />
}

export { SignAtSignFill }
