import { Sign, type SignProps, type SignShape } from "@/registry/0db/ui/sign"

// Generated by scripts/build-signs.mjs from Lucide's castle (ISC).
const shape: SignShape = {"word":"castle","fill":{"step":2.09,"rows":[[1.5,4.7,7.3,8.7,11.3,12.7,15.3,16.7,19.3],[3.6,3.5,6,18,20.5],[5.7,3.5,5.7,18.3,20.5],[7.8,0.3,5,7,17,19,23.7],[9.9,0,1.8,22.2,24],[12,0,1.8,22.2,24],[14.1,0,9.7,14.3,24],[16.2,0,8.2,15.8,24],[18.3,0,7.9,10.1,13.9,16.1,24],[20.4,0,7.9,10.1,13.9,16.1,24],[22.5,2.2,21.8]]}}

/** The sign for "castle": the word filling its silhouette row by row. */
function SignCastleFill(props: Omit<SignProps, "shape" | "variant">) {
  return <Sign shape={shape} variant="fill" {...props} />
}

export { SignCastleFill }
