import { Sign, type SignProps, type SignShape } from "@/registry/0db/ui/sign"

// Generated by scripts/build-signs.mjs from Lucide's frown (ISC).
const shape: SignShape = {"word":"sad","line":[[["O",12,12,10,180,180]],[["O",12,12,10,180,-180]],[["M",9,16],["L",9.8,15.5],["L",10.5,15.2],["L",11.3,15.1],["L",12,15],["L",12.7,15.1],["L",13.5,15.2],["L",14.4,15.6],["L",15,16]],[["M",15,9],["L",15,10]],[["M",9,10],["L",9,9]]]}

/** The sign for "sad": the word ruled in leaders along its strokes. */
function SignFrownDots(props: Omit<SignProps, "shape" | "variant">) {
  return <Sign shape={shape} variant="dots" {...props} />
}

export { SignFrownDots }
