import { Sign, type SignProps, type SignShape } from "@/registry/0db/ui/sign"

// Generated by scripts/build-signs.mjs from Lucide's copy (ISC).
const shape: SignShape = {"word":"copy","fill":{"step":2.18,"rows":[[1.1,1.3,16.7],[3.3,0,18.2],[5.5,0,18.3],[7.6,0,7.5,17.5,23.3],[9.8,0,6.9,9.6,24],[12,0,6.9,9.1,24],[14.2,0,6.9,9.1,24],[16.4,0.7,6.9,9.1,24],[18.5,5.5,24],[20.7,5.8,24],[22.9,7.4,22.6]]}}

/** The sign for "copy": the word filling its silhouette row by row. */
function SignCopyFill(props: Omit<SignProps, "shape" | "variant">) {
  return <Sign shape={shape} variant="fill" {...props} />
}

export { SignCopyFill }
