import { Sign, type SignProps, type SignShape } from "@/registry/0db/ui/sign"

// Generated by scripts/build-signs.mjs from Lucide's timer (ISC).
const shape: SignShape = {"word":"timer","fill":{"step":2.18,"rows":[[1.1,8,16],[3.3,8.4,15.6],[5.5,7,10.2,13.8,17],[7.6,4.2,19.8],[9.8,2.7,14.3,15.7,21.3],[12,1.9,12.1,15.8,22.1],[14.2,1.6,11.2,13.7,22.4],[16.4,2,22],[18.5,2.9,21.1],[20.7,4.5,19.5],[22.9,7.6,16.4]]}}

/** The sign for "timer": the word filling its silhouette row by row. */
function SignTimerFill(props: Omit<SignProps, "shape" | "variant">) {
  return <Sign shape={shape} variant="fill" {...props} />
}

export { SignTimerFill }
