import { Sign, type SignProps, type SignShape } from "@/registry/0db/ui/sign"

// Generated by scripts/build-signs.mjs from Lucide's cloud-lightning (ISC).
const shape: SignShape = {"word":"storm","fill":{"step":2.14,"rows":[[1.6,6.1,12.1],[3.7,2.5,15.5],[5.8,0.9,17.2],[8,0,22.3],[10.1,0,23.7],[12.3,0,11.5,13.8,24],[14.4,1,10.2,13,24],[16.5,2.7,9.6,14.1,22.7],[18.7,9.1,15.5,17.1,19.2],[20.8,9.2,14.2],[22.9,9,13]]}}

/** The sign for "storm": the word filling its silhouette row by row. */
function SignCloudLightningFill(props: Omit<SignProps, "shape" | "variant">) {
  return <Sign shape={shape} variant="fill" {...props} />
}

export { SignCloudLightningFill }
