import { Sign, type SignProps, type SignShape } from "@/registry/0db/ui/sign"

// Generated by scripts/build-signs.mjs from Lucide's link (ISC).
const shape: SignShape = {"word":"link","fill":{"step":2.18,"rows":[[1.1,13.4,20.5],[3.3,10.8,23],[5.5,9.4,24],[7.6,7.5,24],[9.8,4.2,10.1,14.7,23.6],[12,2.1,9.2,10.8,13.1,14.8,21.9],[14.2,0.4,9.3,13.9,19.8],[16.4,0,16.5],[18.5,0,14.5],[20.7,1.1,13.2],[22.9,3.5,10.6]]}}

/** The sign for "link": the word filling its silhouette row by row. */
function SignLinkFill(props: Omit<SignProps, "shape" | "variant">) {
  return <Sign shape={shape} variant="fill" {...props} />
}

export { SignLinkFill }
