import { Sign, type SignProps, type SignShape } from "@/registry/0db/ui/sign"

// Generated by scripts/build-signs.mjs from Lucide's minus (ISC).
const shape: SignShape = {"word":"less","line":[[["M",5,12],["L",19,12]]]}

/** The sign for "less": the word ruled in leaders along its strokes. */
function SignMinusDots(props: Omit<SignProps, "shape" | "variant">) {
  return <Sign shape={shape} variant="dots" {...props} />
}

export { SignMinusDots }
