import { Sign, type SignProps, type SignShape } from "@/registry/0db/ui/sign"

// Generated by scripts/build-signs.mjs from Lucide's keyboard (ISC).
const shape: SignShape = {"word":"keys","line":[[["M",2.5,4.7],["L",2.9,4.4],["L",3.3,4.1],["L",4,4],["L",20,4],["L",20.7,4.1],["L",21.3,4.5]],[["M",2.7,19.5],["L",3.3,19.9],["L",4,20],["L",20,20],["L",20.5,19.9],["L",20.9,19.8],["L",21.5,19.3]],[["M",21.3,4.5],["L",21.8,5.1],["L",21.9,5.5],["L",22,6],["L",22,18],["L",21.9,18.7],["L",21.5,19.3]],[["M",2.7,19.5],["L",2.2,18.9],["L",2.1,18.5],["L",2,18],["L",2,6],["L",2.1,5.3],["L",2.5,4.7]],[["M",7,16],["L",17,16]],[["M",10,8],["L",10,8]],[["M",12,12],["L",12,12]],[["M",14,8],["L",14,8]],[["M",16,12],["L",16,12]],[["M",18,8],["L",18,8]],[["M",6,8],["L",6,8]],[["M",8,12],["L",8,12]]]}

/** The sign for "keys": the word ruled in leaders along its strokes. */
function SignKeyboardDots(props: Omit<SignProps, "shape" | "variant">) {
  return <Sign shape={shape} variant="dots" {...props} />
}

export { SignKeyboardDots }
