import { Sign, type SignProps, type SignShape } from "@/registry/0db/ui/sign"

// Generated by scripts/build-signs.mjs from Lucide's book (ISC).
const shape: SignShape = {"word":"book","fill":{"step":2.18,"rows":[[1.1,3.6,21.3],[3.3,1.9,22.4],[5.5,1.5,22.5],[7.6,1.5,22.5],[9.8,1.5,22.5],[12,1.5,22.5],[14.2,1.5,22.5],[16.4,1.5,4,20.3,22.5],[18.5,1.5,3.7,19.7,22.5],[20.7,1.9,22.4],[22.9,3.7,21.3]]}}

/** The sign for "book": the word filling its silhouette row by row. */
function SignBookFill(props: Omit<SignProps, "shape" | "variant">) {
  return <Sign shape={shape} variant="fill" {...props} />
}

export { SignBookFill }
