import { Sign, type SignProps, type SignShape } from "@/registry/0db/ui/sign"

// Generated by scripts/build-signs.mjs from Lucide's piano (ISC).
const shape: SignShape = {"word":"piano","fill":{"step":2.14,"rows":[[1.1,5,13],[3.2,2,16],[5.3,0.6,17.4],[7.5,0,22.1],[9.6,0,23.9],[11.8,0,1.9,22.1,24],[13.9,0,1.7,22.3,24],[16,0,4.9,7.1,8.9,11.1,12.9,15.1,16.9,19.1,24],[18.2,0,5.1,6.9,9.1,10.9,13.1,14.9,17.1,18.9,24],[20.3,0,24],[22.4,2.3,21.8]]}}

/** The sign for "piano": the word filling its silhouette row by row. */
function SignPianoFill(props: Omit<SignProps, "shape" | "variant">) {
  return <Sign shape={shape} variant="fill" {...props} />
}

export { SignPianoFill }
