import { Sign, type SignProps, type SignShape } from "@/registry/0db/ui/sign"

// Generated by scripts/build-signs.mjs from Lucide's zoom-in (ISC).
const shape: SignShape = {"word":"zoom","line":[[["O",11,11,8,180,180]],[["O",11,11,8,180,-180]],[["M",16.7,16.7],["L",21,21]],[["M",11,14],["L",11,8]],[["M",8,11],["L",14,11]]]}

/** The sign for "zoom": the word set along its strokes. */
function SignZoomInWords(props: Omit<SignProps, "shape" | "variant">) {
  return <Sign shape={shape} variant="words" {...props} />
}

export { SignZoomInWords }
