import { Sign, type SignProps, type SignShape } from "@/registry/0db/ui/sign"

// Generated by scripts/build-signs.mjs from Lucide's save (ISC).
const shape: SignShape = {"word":"save","fill":{"step":2.09,"rows":[[1.5,3,17.2],[3.6,1,6.1,7.9,19.6],[5.7,0.5,6.1,7.9,21.6],[7.8,0.5,6.1,15.8,23.2],[9.9,0.5,23.5],[12,0.5,6.8,17.2,23.5],[14.1,0.5,6.1,17.9,23.5],[16.2,0.5,6.1,7.9,16.1,17.9,23.5],[18.3,0.5,6.1,7.9,16.1,17.9,23.5],[20.4,1,6.1,7.9,16.1,17.9,23],[22.5,3,21]]}}

/** The sign for "save": the word filling its silhouette row by row. */
function SignSaveFill(props: Omit<SignProps, "shape" | "variant">) {
  return <Sign shape={shape} variant="fill" {...props} />
}

export { SignSaveFill }
