import { Sign, type SignProps, type SignShape } from "@/registry/0db/ui/sign"

// Generated by scripts/build-signs.mjs from Lucide's cpu (ISC).
const shape: SignShape = {"word":"chip","fill":{"step":2.18,"rows":[[1.1,5.1,8.9,10.1,13.9,15.1,18.9],[3.3,3.2,5.5,8.8,10.2,13.8,14.8,18.5,20.9],[5.5,0.9,2.6,5.2,5.7,8.4,10.6,13.4,15,18.3,18.8,21.4,23.1],[7.6,0,2.3,5.5,7.1,16.9,18.5,21.8,24],[9.8,0.9,3.3,4.7,6.9,9.1,14.9,17.1,19.3,20.7,23.1],[12,0,2,5.5,6.9,9.1,14.9,17.1,18.5,22,24],[14.2,0.9,3.3,4.7,6.9,9.1,14.9,17.1,19.3,20.7,23.1],[16.4,0,2.3,5.5,7.1,16.9,18.5,21.8,24],[18.5,0.9,2.6,5.2,5.7,8.4,10.6,13.4,15,18.3,18.8,21.4,23.1],[20.7,3.1,5.5,8.8,10.2,13.8,14.8,18.5,20.8],[22.9,5.1,8.9,10.1,13.9,15.1,18.9]]}}

/** The sign for "chip": the word filling its silhouette row by row. */
function SignCpuFill(props: Omit<SignProps, "shape" | "variant">) {
  return <Sign shape={shape} variant="fill" {...props} />
}

export { SignCpuFill }
