import { Sign, type SignProps, type SignShape } from "@/registry/0db/ui/sign"

// Generated by scripts/build-signs.mjs from Lucide's map-pin (ISC).
const shape: SignShape = {"word":"place","fill":{"step":2.18,"rows":[[1.1,7.6,16.4],[3.3,4.5,19.5],[5.5,3,21],[7.6,2,8.5,15.5,22],[9.8,1.6,8.1,10.1,13.9,15.9,22.4],[12,1.9,8.4,15.6,22.1],[14.2,2.7,10.6,13.4,21.3],[16.4,3.9,20.1],[18.5,5.5,18.5],[20.7,7.3,16.7],[22.9,9.6,14.4]]}}

/** The sign for "place": the word filling its silhouette row by row. */
function SignMapPinFill(props: Omit<SignProps, "shape" | "variant">) {
  return <Sign shape={shape} variant="fill" {...props} />
}

export { SignMapPinFill }
