import { Sign, type SignProps, type SignShape } from "@/registry/0db/ui/sign"

// Generated by scripts/build-signs.mjs from Lucide's trophy (ISC).
const shape: SignShape = {"word":"trophy","fill":{"step":2.18,"rows":[[1.1,4.6,19.4],[3.3,0.4,4.6,6.9,17.1,19.4,23.6],[5.5,0,5.1,6.9,17.1,18.9,24],[7.6,0,5.1,6.9,17.1,18.9,24],[9.8,0.4,5.1,6.9,17.1,18.9,23.6],[12,4.4,19.6],[14.2,5.8,9,15,18.2],[16.4,7,9.1,10.9,11.5,12.6,13.1,14.9,17.1],[18.5,5.2,8.7,10.6,13.4,15.3,18.9],[20.7,2.4,21.6],[22.9,2,22]]}}

/** The sign for "trophy": the word filling its silhouette row by row. */
function SignTrophyFill(props: Omit<SignProps, "shape" | "variant">) {
  return <Sign shape={shape} variant="fill" {...props} />
}

export { SignTrophyFill }
