import { Sign, type SignProps, type SignShape } from "@/registry/0db/ui/sign"

// Generated by scripts/build-signs.mjs from Lucide's euro (ISC).
const shape: SignShape = {"word":"euro","fill":{"step":2.1,"rows":[[2.6,10.7,16.9],[4.7,7.1,20.6],[6.8,5.2,21.1],[8.9,2.2,5.6,14.2,17.8],[11,2,5.1,14.3,18],[13.1,2,5.1,10.1,15.4],[15.2,2.2,5.6,9.9,14.8],[17.3,5.3,11,16.6,21.1],[19.4,7.1,20.6],[21.5,10.9,16.9]]}}

/** The sign for "euro": the word filling its silhouette row by row. */
function SignEuroFill(props: Omit<SignProps, "shape" | "variant">) {
  return <Sign shape={shape} variant="fill" {...props} />
}

export { SignEuroFill }
