import { Sign, type SignProps, type SignShape } from "@/registry/0db/ui/sign"

// Generated by scripts/build-signs.mjs from Lucide's fish (ISC).
const shape: SignShape = {"word":"fish","fill":{"step":2.09,"rows":[[1.5,6.5,15.8],[3.6,2.1,3.4,5.6,8.1,10.1,17.8],[5.7,0.2,8.5,16.8,20.2],[7.8,0,5,13,13.7,16.3,22.4],[9.9,0,5.9,9.2,13.2,15.3,23.6],[12,0,5.8,7.7,13.1,14.9,17.2,18.8,24],[14.1,0,5.9,9.1,13.2,15.3,23.6],[16.2,0,5.8,9.1,10.1,12.7,13.7,16.3,22.4],[18.3,0.2,7.3,8,10.2,16.8,20.2],[20.4,2,3.4,7.4,17.8],[22.5,8,15.8]]}}

/** The sign for "fish": the word filling its silhouette row by row. */
function SignFishFill(props: Omit<SignProps, "shape" | "variant">) {
  return <Sign shape={shape} variant="fill" {...props} />
}

export { SignFishFill }
