import { Sign, type SignProps, type SignShape } from "@/registry/0db/ui/sign"

// Generated by scripts/build-signs.mjs from Lucide's code-xml (ISC).
const shape: SignShape = {"word":"code","line":[[["M",9.5,20],["L",14.5,4]],[["M",18,16],["L",22,12]],[["M",18,8],["L",22,12]],[["M",2,12],["L",6,8]],[["M",2,12],["L",6,16]]]}

/** The sign for "code": the word ruled in leaders along its strokes. */
function SignCodeDots(props: Omit<SignProps, "shape" | "variant">) {
  return <Sign shape={shape} variant="dots" {...props} />
}

export { SignCodeDots }
