import { Sign, type SignProps, type SignShape } from "@/registry/0db/ui/sign"

// Generated by scripts/build-signs.mjs from Lucide's triangle-alert (ISC).
const shape: SignShape = {"word":"warning","fill":{"step":2.09,"rows":[[1.5,10.2,13.8],[3.6,8,16],[5.7,6.8,17.2],[7.8,5.6,11.2,12.8,18.4],[9.9,4.4,10.9,13.1,19.6],[12,3.2,10.9,13.1,20.8],[14.1,2,11.1,12.9,22],[16.2,0.8,10.5,13.5,23.2],[18.3,0,10.6,13.4,24],[20.4,0,24],[22.5,2.2,21.8]]}}

/** The sign for "warning": the word filling its silhouette row by row. */
function SignTriangleAlertFill(props: Omit<SignProps, "shape" | "variant">) {
  return <Sign shape={shape} variant="fill" {...props} />
}

export { SignTriangleAlertFill }
