import { Sign, type SignProps, type SignShape } from "@/registry/0db/ui/sign"

// Generated by scripts/build-signs.mjs from Lucide's euro (ISC).
const shape: SignShape = {"word":"euro","fill":{"step":2.1,"rows":[[2.6,10.9,16.7],[4.7,7.2,20.5],[6.8,5.3,21],[8.9,2.3,5.3,14.4,18.2],[11,2.1,4.9,14.5,17.9],[13.1,2.1,5,10.3,15.3],[15.2,2.3,5.3,10.2,14.7],[17.3,5.4,10.9,16.8,21],[19.4,7.2,20.5],[21.5,11.2,16.6]]}}

/** The sign for "euro": the word filling its silhouette row by row. */
function SignEuroFill(props: Omit<SignProps, "shape" | "variant">) {
  return <Sign shape={shape} variant="fill" {...props} />
}

export { SignEuroFill }
