import { Sign, type SignProps, type SignShape } from "@/registry/0db/ui/sign"

// Generated by scripts/build-signs.mjs from Lucide's baby (ISC).
const shape: SignShape = {"word":"baby","fill":{"step":2.08,"rows":[[1.5,8.6,14.6],[3.6,4.8,17.2],[5.7,2.8,11.5,12.5,14.5,16.3,21.2],[7.8,1.6,11.1,16,22.4],[9.9,0.5,23.6],[12,0,8.3,9.7,14.3,15.7,24],[14,0.4,23.6],[16.1,1.6,9.3,14.7,22.4],[18.2,2.9,21.2],[20.3,4.9,19.1],[22.4,8.6,15.4]]}}

/** The sign for "baby": the word filling its silhouette row by row. */
function SignBabyFill(props: Omit<SignProps, "shape" | "variant">) {
  return <Sign shape={shape} variant="fill" {...props} />
}

export { SignBabyFill }
