import { Sign, type SignProps, type SignShape } from "@/registry/0db/ui/sign"

// Generated by scripts/build-signs.mjs from Lucide's flame (ISC).
const shape: SignShape = {"word":"fire","fill":{"step":2.14,"rows":[[1.6,10.7,13.3],[3.7,8.5,14.6],[5.8,7.3,15.6],[8,7.3,17.2],[10.1,7.8,9.8,11.9,19.5],[12.3,3.4,5.1,7.4,9.6,12,20.7],[14.4,2.7,5.4,11.6,21.3],[16.5,2.8,21.2],[18.7,3.6,20.4],[20.8,5.1,19],[22.9,8,16]]}}

/** The sign for "fire": the word filling its silhouette row by row. */
function SignFlameFill(props: Omit<SignProps, "shape" | "variant">) {
  return <Sign shape={shape} variant="fill" {...props} />
}

export { SignFlameFill }
