import { Sign, type SignProps, type SignShape } from "@/registry/0db/ui/sign"

// Generated by scripts/build-signs.mjs from Lucide's hard-drive (ISC).
const shape: SignShape = {"word":"drive","fill":{"step":2.1,"rows":[[2.6,5.4,18.6],[4.7,3.3,20.8],[6.8,2.2,21.8],[8.9,1.2,22.9],[11,0.1,1.9,22.1,23.9],[13.1,0,1.9,22.1,24],[15.2,0,4.5,7.5,8.5,11.5,24],[17.3,0,4.6,7.4,8.6,11.4,24],[19.4,0,24],[21.5,2.3,21.8]]}}

/** The sign for "drive": the word filling its silhouette row by row. */
function SignHardDriveFill(props: Omit<SignProps, "shape" | "variant">) {
  return <Sign shape={shape} variant="fill" {...props} />
}

export { SignHardDriveFill }
