import { Sign, type SignProps, type SignShape } from "@/registry/0db/ui/sign"

// Generated by scripts/build-signs.mjs from Lucide's wind (ISC).
const shape: SignShape = {"word":"wind","fill":{"step":2.1,"rows":[[2.6,9.1,13],[4.7,7.5,15],[6.8,0.3,8.7,13.4,15.5,15.8,23.2],[8.9,0,8.4,12.7,24],[11,0.1,2.3,16,24],[13.1,0.1,2.3,16,22.3],[15.2,0,11.4,15.2,16.9],[17.3,0.3,11.7,15,18.2],[19.4,10.5,18],[21.5,12.1,16]]}}

/** The sign for "wind": the word filling its silhouette row by row. */
function SignWindFill(props: Omit<SignProps, "shape" | "variant">) {
  return <Sign shape={shape} variant="fill" {...props} />
}

export { SignWindFill }
