import { Sign, type SignProps, type SignShape } from "@/registry/0db/ui/sign"

// Generated by scripts/build-signs.mjs from Lucide's menu (ISC).
const shape: SignShape = {"word":"menu","fill":{"step":2.11,"rows":[[3.6,2.7,21.3],[5.7,1.9,22.1],[12,1.6,22.4],[18.3,1.9,22.1],[20.4,2.7,21.3]]}}

/** The sign for "menu": the word filling its silhouette row by row. */
function SignMenuFill(props: Omit<SignProps, "shape" | "variant">) {
  return <Sign shape={shape} variant="fill" {...props} />
}

export { SignMenuFill }
