import { Sign, type SignProps, type SignShape } from "@/registry/0db/ui/sign"

// Generated by scripts/build-signs.mjs from Lucide's pizza (ISC).
const shape: SignShape = {"word":"pizza","fill":{"step":2.18,"rows":[[1.1,13,18.4],[3.3,8.7,19.5],[5.5,6,13.5,18.2,20.1],[7.6,3.8,10,16.7,20.7],[9.8,2.3,8,12.4,15.6,19.1,21.4],[12,1.1,6.5,10.1,14.8,17.6,21.9],[14.2,0.2,5.5,8.4,10,13,14.8,17.4,22.5],[16.4,0,4.8,7.4,10.2,11.8,15.5,21.2,23.2],[18.5,1.6,5.3,6.5,11.9,14.8,18.2,20.8,23.8],[20.7,9.2,12.6,13.4,24],[22.9,17.2,23.3]]}}

/** The sign for "pizza": the word filling its silhouette row by row. */
function SignPizzaFill(props: Omit<SignProps, "shape" | "variant">) {
  return <Sign shape={shape} variant="fill" {...props} />
}

export { SignPizzaFill }
