import { Sign, type SignProps, type SignShape } from "@/registry/0db/ui/sign"

// Generated by scripts/build-signs.mjs from Lucide's music (ISC).
const shape: SignShape = {"word":"music","fill":{"step":2.09,"rows":[[1.5,17.8,22.5],[3.6,7.4,23.5],[5.7,6.5,16.4,18.5,23.5],[7.8,6.5,11.5,18.5,23.5],[9.9,6.5,11.5,18.5,23.5],[12,6.5,11.5,15,19,19.9,23.5],[14.1,2.9,6.8,8,11.5,13.2,18.5,21,23.5],[16.2,1.1,6.6,9,11.5,12.6,23.4],[18.3,0.6,11.4,13.4,22.6],[20.4,1.4,10.6,15.6,20.4],[22.5,3.8,8.2]]}}

/** The sign for "music": the word filling its silhouette row by row. */
function SignMusicFill(props: Omit<SignProps, "shape" | "variant">) {
  return <Sign shape={shape} variant="fill" {...props} />
}

export { SignMusicFill }
