import { Sign, type SignProps, type SignShape } from "@/registry/0db/ui/sign"

// Generated by scripts/build-signs.mjs from Lucide's clipboard (ISC).
const shape: SignShape = {"word":"clip","fill":{"step":2.18,"rows":[[1.1,6.6,17.4],[3.3,3,6.9,8.9,15.1,17.1,21],[5.5,1.7,7.1,16.9,22.3],[7.6,1.5,22.5],[9.8,1.5,22.5],[12,1.5,22.5],[14.2,1.5,22.5],[16.4,1.5,22.5],[18.5,1.5,22.5],[20.7,1.7,22.3],[22.9,3.2,20.7]]}}

/** The sign for "clip": the word filling its silhouette row by row. */
function SignClipboardFill(props: Omit<SignProps, "shape" | "variant">) {
  return <Sign shape={shape} variant="fill" {...props} />
}

export { SignClipboardFill }
