import { Sign, type SignProps, type SignShape } from "@/registry/0db/ui/sign"

// Generated by scripts/build-signs.mjs from Lucide's file-x (ISC).
const shape: SignShape = {"word":"reject","fill":{"step":2.18,"rows":[[1.1,3.4,16.8],[3.3,1.7,12.9,15.1,19.1],[5.5,1.5,12.9,15.1,21.3],[7.6,1.5,12.9,20.3,22.4],[9.8,1.5,22.5],[12,1.5,8.5,11.2,12.8,15.5,22.5],[14.2,1.5,9,15,22.5],[16.4,1.5,8.6,15.4,22.5],[18.5,1.5,8.5,10.6,13.4,15.5,22.5],[20.7,1.7,22.2],[22.9,3.4,20.6]]}}

/** The sign for "reject": the word filling its silhouette row by row. */
function SignFileXFill(props: Omit<SignProps, "shape" | "variant">) {
  return <Sign shape={shape} variant="fill" {...props} />
}

export { SignFileXFill }
