import { Sign, type SignProps, type SignShape } from "@/registry/0db/ui/sign"

// Generated by scripts/build-signs.mjs from Lucide's coins (ISC).
const shape: SignShape = {"word":"coins","line":[[["O",16,8,6,180,180]],[["O",16,8,6,180,-180]],[["M",2,16],["L",2.1,17],["L",2.3,18],["L",2.5,18.4],["L",2.8,19.1],["L",3.4,19.9],["L",4.1,20.6],["L",4.9,21.2],["L",5.9,21.6],["L",7,21.9],["L",8,22],["L",8.6,22],["L",9.2,21.9],["L",10.2,21.6],["L",10.6,21.4],["L",11.3,21],["L",12.1,20.4],["L",12.7,19.7],["L",13.3,18.9],["L",13.5,18.4],["L",13.7,17.7]],[["M",2,16],["L",2,15.3],["L",2.2,14.3],["L",2.6,13.4],["L",3.1,12.5],["L",3.7,11.8],["L",4.5,11.1],["L",5.3,10.6],["L",6.3,10.3]],[["M",16,6],["L",16,10]],[["M",7,14.3],["L",9,17.7]],[["M",6.1,14.8],["L",7,14.3]],[["M",15,6],["L",16,6]]]}

/** The sign for "coins": the word ruled in leaders along its strokes. */
function SignCoinsDots(props: Omit<SignProps, "shape" | "variant">) {
  return <Sign shape={shape} variant="dots" {...props} />
}

export { SignCoinsDots }
