import { Sign, type SignProps, type SignShape } from "@/registry/0db/ui/sign"

// Generated by scripts/build-signs.mjs from Lucide's undo-2 (ISC).
const shape: SignShape = {"word":"undo","fill":{"step":2.1,"rows":[[2.6,7.5,10.5],[4.7,5.4,11.1],[6.8,3.3,10.3],[8.9,1.6,4.2,9.3,19.4],[11,3,21.3],[13.1,5.1,11,17.4,22.2],[15.2,7.2,10.8,17.5,22.4],[17.3,16.6,21.7],[19.4,8.9,20.4],[21.5,9.5,17.2]]},"mirror":true}

/** The sign for "undo": the word filling its silhouette row by row. */
function SignUndoFill(props: Omit<SignProps, "shape" | "variant">) {
  return <Sign shape={shape} variant="fill" {...props} />
}

export { SignUndoFill }
