import { Sign, type SignProps, type SignShape } from "@/registry/0db/ui/sign"

// Generated by scripts/build-signs.mjs from Lucide's wind (ISC).
const shape: SignShape = {"word":"wind","fill":{"step":2.1,"rows":[[2.6,9.3,12.8],[4.7,7.5,15],[6.8,0.4,8.4,13.5,15.5,15.8,23.1],[8.9,0,8.2,13.1,24],[11,0.2,2,16.2,24],[13.1,0.2,2,16.2,22.1],[15.2,0,11.2,15.3,17.4],[17.3,0.4,11.4,15.2,18.2],[19.4,10.5,18],[21.5,12.3,15.8]]}}

/** The sign for "wind": the word filling its silhouette row by row. */
function SignWindFill(props: Omit<SignProps, "shape" | "variant">) {
  return <Sign shape={shape} variant="fill" {...props} />
}

export { SignWindFill }
