import { Sign, type SignProps, type SignShape } from "@/registry/0db/ui/sign"

// Generated by scripts/build-signs.mjs from Lucide's library (ISC).
const shape: SignShape = {"word":"library","fill":{"step":2.1,"rows":[[2.6,2.5,5.5],[4.7,1.5,6.5,10.4,13.6,14.4,17.6],[6.8,1.5,11.2,12.8,18.6],[8.9,1.5,7.1,8.9,11.1,12.9,19.2],[11,1.5,7.1,8.9,14.5,15,19.8],[13.1,1.5,7.1,8.9,14.5,15.6,20.4],[15.2,1.5,7.1,8.9,14.5,16.2,21],[17.3,1.5,7.1,8.9,14.5,16.8,21.6],[19.4,1.5,7.1,8.9,14.5,17.4,22.2],[21.5,2.5,5.5,6.5,9.5,10.5,13.5,18.5,21.5]]}}

/** The sign for "library": the word filling its silhouette row by row. */
function SignLibraryFill(props: Omit<SignProps, "shape" | "variant">) {
  return <Sign shape={shape} variant="fill" {...props} />
}

export { SignLibraryFill }
