import { Sign, type SignProps, type SignShape } from "@/registry/0db/ui/sign"

// Generated by scripts/build-signs.mjs from Lucide's crosshair (ISC).
const shape: SignShape = {"word":"aim","line":[[["O",12,12,10,180,180]],[["O",12,12,10,180,-180]],[["M",18,12],["L",22,12]],[["M",2,12],["L",6,12]],[["M",12,2],["L",12,6]],[["M",12,18],["L",12,22]]]}

/** The sign for "aim": the word ruled in leaders along its strokes. */
function SignCrosshairDots(props: Omit<SignProps, "shape" | "variant">) {
  return <Sign shape={shape} variant="dots" {...props} />
}

export { SignCrosshairDots }
