import { Sign, type SignProps, type SignShape } from "@/registry/0db/ui/sign"

// Generated by scripts/build-signs.mjs from Lucide's cloud (ISC).
const shape: SignShape = {"word":"cloud","fill":{"step":2.11,"rows":[[3.6,6.2,12],[5.7,2.6,15.5],[7.8,0.9,17.1],[9.9,0,22.2],[12,0,23.7],[14.1,0,24],[16.2,0.9,24],[18.3,2.5,22.9],[20.4,6.1,20.1]]}}

/** The sign for "cloud": the word filling its silhouette row by row. */
function SignCloudFill(props: Omit<SignProps, "shape" | "variant">) {
  return <Sign shape={shape} variant="fill" {...props} />
}

export { SignCloudFill }
