import { Sign, type SignProps, type SignShape } from "@/registry/0db/ui/sign"

// Generated by scripts/build-signs.mjs from Lucide's type (ISC).
const shape: SignShape = {"word":"type","fill":{"step":2.1,"rows":[[2.6,3.3,20.7],[4.7,1.7,11.1,12.9,22.3],[6.8,1.6,6.4,9.5,14.5,17.6,22.4],[8.9,3.4,4.7,9.5,14.5,19.3,20.7],[11,9.5,14.5],[13.1,9.5,14.5],[15.2,9.5,14.5],[17.3,9.5,14.5],[19.4,6.9,11.1,12.9,17.1],[21.5,7.5,16.5]]}}

/** The sign for "type": the word filling its silhouette row by row. */
function SignTypeFill(props: Omit<SignProps, "shape" | "variant">) {
  return <Sign shape={shape} variant="fill" {...props} />
}

export { SignTypeFill }
