import { Sign, type SignProps, type SignShape } from "@/registry/0db/ui/sign"

// Generated by scripts/build-signs.mjs from Lucide's sliders-horizontal (ISC).
const shape: SignShape = {"word":"tune","fill":{"step":2.09,"rows":[[1.5,12.7,15.3],[3.6,1.5,12.6,16.1,22.5],[5.7,1,12.5,16.2,23],[7.8,6.9,16],[9.9,5.6,7.3,8.7,14.9],[12,0.6,5.7,9.5,10.9,14.1,23.4],[14.1,5.6,7.9,8.1,16.9],[16.2,6.9,15.9,16.1,18],[18.3,1,14.5,18.2,23],[20.4,1.5,14.7,18.1,22.5],[22.5,14.7,17.3]]}}

/** The sign for "tune": the word filling its silhouette row by row. */
function SignSlidersFill(props: Omit<SignProps, "shape" | "variant">) {
  return <Sign shape={shape} variant="fill" {...props} />
}

export { SignSlidersFill }
