import { Sign, type SignProps, type SignShape } from "@/registry/0db/ui/sign"

// Generated by scripts/build-signs.mjs from Lucide's lock (ISC).
const shape: SignShape = {"word":"lock","fill":{"step":2.18,"rows":[[1.1,8.4,15.5],[3.3,6,18],[5.5,4.8,19.2],[7.6,4.5,19.5],[9.8,2.7,5.3,18.5,21.3],[12,0.9,5.2,18.5,23.1],[14.2,0.5,23.5],[16.4,0.5,23.5],[18.5,0.5,23.5],[20.7,0.8,23.2],[22.9,2.4,21.6]]}}

/** The sign for "lock": the word filling its silhouette row by row. */
function SignLockFill(props: Omit<SignProps, "shape" | "variant">) {
  return <Sign shape={shape} variant="fill" {...props} />
}

export { SignLockFill }
