import { Sign, type SignProps, type SignShape } from "@/registry/0db/ui/sign"

// Generated by scripts/build-signs.mjs from Lucide's bookmark (ISC).
const shape: SignShape = {"word":"bookmark","fill":{"step":2.09,"rows":[[1.5,5.2,18.8],[3.6,3,21],[5.7,2.5,21.5],[7.8,2.5,21.5],[9.9,2.5,21.5],[12,2.5,21.5],[14.1,2.5,21.5],[16.2,2.5,21.5],[18.3,2.5,21.5],[20.4,2.7,11.3,12.7,21.3],[22.5,4.5,7.6,16.4,19.5]]}}

/** The sign for "bookmark": the word filling its silhouette row by row. */
function SignBookmarkFill(props: Omit<SignProps, "shape" | "variant">) {
  return <Sign shape={shape} variant="fill" {...props} />
}

export { SignBookmarkFill }
