import { Sign, type SignProps, type SignShape } from "@/registry/0db/ui/sign"

// Generated by scripts/build-signs.mjs from Lucide's sliders-horizontal (ISC).
const shape: SignShape = {"word":"tune","fill":{"step":2.09,"rows":[[1.5,12.5,15.5],[3.6,1.4,13.3,15.1,22.6],[5.7,0.9,13.1,15.6,23.1],[7.8,6.1,16],[9.9,5.6,7.6,8.4,14.9],[12,0.6,6.6,8.9,11.3,13.7,23.4],[14.1,5.6,16.9],[16.2,6.1,18],[18.3,0.9,15.1,17.6,23.1],[20.4,1.4,15.7,17.1,22.6],[22.5,14.5,17.5]]}}

/** The sign for "tune": the word filling its silhouette row by row. */
function SignSlidersFill(props: Omit<SignProps, "shape" | "variant">) {
  return <Sign shape={shape} variant="fill" {...props} />
}

export { SignSlidersFill }
