import { Sign, type SignProps, type SignShape } from "@/registry/0db/ui/sign"

// Generated by scripts/build-signs.mjs from Lucide's tablet (ISC).
const shape: SignShape = {"word":"tablet","fill":{"step":2.18,"rows":[[1.1,3.4,20.6],[3.3,1.7,22.2],[5.5,1.5,22.5],[7.6,1.5,22.5],[9.8,1.5,22.5],[12,1.5,22.5],[14.2,1.5,22.5],[16.4,1.5,10.9,13.1,22.5],[18.5,1.5,10.5,13.5,22.5],[20.7,1.7,22.2],[22.9,3.4,20.6]]}}

/** The sign for "tablet": the word filling its silhouette row by row. */
function SignTabletFill(props: Omit<SignProps, "shape" | "variant">) {
  return <Sign shape={shape} variant="fill" {...props} />
}

export { SignTabletFill }
