import { Sign, type SignProps, type SignShape } from "@/registry/0db/ui/sign"

// Generated by scripts/build-signs.mjs from Lucide's arrow-down (ISC).
const shape: SignShape = {"word":"down","fill":{"step":2.11,"rows":[[3.6,10.5,13.5],[5.7,9.5,14.5],[7.8,9.5,14.5],[9.9,9.5,14.5],[12,2.6,7.9,9.5,14.5,16.1,21.4],[14.1,4.2,11.1,12.9,19.8],[16.2,6.3,11.1,12.9,17.7],[18.3,8.4,11.1,12.9,15.6],[20.4,10.5,13.5]]}}

/** The sign for "down": the word filling its silhouette row by row. */
function SignArrowDownFill(props: Omit<SignProps, "shape" | "variant">) {
  return <Sign shape={shape} variant="fill" {...props} />
}

export { SignArrowDownFill }
