import { Sign, type SignProps, type SignShape } from "@/registry/0db/ui/sign"

// Generated by scripts/build-signs.mjs from Lucide's tag (ISC).
const shape: SignShape = {"word":"tag","fill":{"step":2.18,"rows":[[1.1,1.2,13.9],[3.3,0,16.2],[5.5,0,18.3],[7.6,0,6.2,8.8,20.5],[9.8,0,22.7],[12,0,24],[14.2,1.3,24],[16.4,3.5,22.4],[18.5,5.7,20.2],[20.7,7.8,18.2],[22.9,10.1,15.8]]}}

/** The sign for "tag": the word filling its silhouette row by row. */
function SignTagFill(props: Omit<SignProps, "shape" | "variant">) {
  return <Sign shape={shape} variant="fill" {...props} />
}

export { SignTagFill }
