import { Sign, type SignProps, type SignShape } from "@/registry/0db/ui/sign"

// Generated by scripts/build-signs.mjs from Lucide's funnel (ISC).
const shape: SignShape = {"word":"filter","fill":{"step":2.14,"rows":[[1.6,1.5,22.5],[3.7,0,24],[5.8,0.6,23.4],[8,2.5,21.5],[10.1,4.5,19.5],[12.3,6.4,17.6],[14.4,7.5,16.5],[16.5,7.5,16.5],[18.7,7.5,16.5],[20.8,7.9,16.4],[22.9,10.5,15.3]]}}

/** The sign for "filter": the word filling its silhouette row by row. */
function SignFilterFill(props: Omit<SignProps, "shape" | "variant">) {
  return <Sign shape={shape} variant="fill" {...props} />
}

export { SignFilterFill }
