import { Sign, type SignProps, type SignShape } from "@/registry/0db/ui/sign"

// Generated by scripts/build-signs.mjs from Lucide's upload (ISC).
const shape: SignShape = {"word":"upload","fill":{"step":2.09,"rows":[[1.5,10.5,13.5],[3.6,8.4,11.1,12.9,15.6],[5.7,6.4,11.1,12.9,17.6],[7.8,4.7,11.1,12.9,19.3],[9.9,9.5,14.5],[12,9.5,14.5],[14.1,1,5,9.5,14.5,19,23],[16.2,0.5,5.5,10.3,13.7,18.5,23.5],[18.3,0.5,5.5,18.5,23.5],[20.4,1,23],[22.5,3,21]]}}

/** The sign for "upload": the word filling its silhouette row by row. */
function SignUploadFill(props: Omit<SignProps, "shape" | "variant">) {
  return <Sign shape={shape} variant="fill" {...props} />
}

export { SignUploadFill }
