import { Sign, type SignProps, type SignShape } from "@/registry/0db/ui/sign"

// Generated by scripts/build-signs.mjs from Lucide's castle (ISC).
const shape: SignShape = {"word":"castle","line":[[["M",2,11],["L",22,11]],[["M",2.7,20.5],["L",3.3,20.9],["L",4,21],["L",20,21],["L",20.5,20.9],["L",20.9,20.8],["L",21.5,20.3]],[["M",6,5],["L",18,5]],[["M",2.7,20.5],["L",2.2,19.9],["L",2.1,19.5],["L",2,19],["L",2,9]],[["M",22,9],["L",22,19],["L",21.9,19.7],["L",21.5,20.3]],[["M",18,3],["L",18,11]],[["M",6,11],["L",6,3]],[["M",12,15],["L",12.7,15.1],["L",13.4,15.4],["L",13.8,15.6],["L",14.2,16],["L",14.6,16.6],["L",14.8,17],["L",15,17.8],["L",15,21]],[["M",9,21],["L",9,17.8],["L",9.2,17],["L",9.4,16.6],["L",9.8,16],["L",10.2,15.6],["L",10.6,15.4],["L",11.3,15.1],["L",12,15]],[["M",10,5],["L",10,3]],[["M",14,3],["L",14,5]]]}

/** The sign for "castle": the word ruled in leaders along its strokes. */
function SignCastleDots(props: Omit<SignProps, "shape" | "variant">) {
  return <Sign shape={shape} variant="dots" {...props} />
}

export { SignCastleDots }
