import { Sign, type SignProps, type SignShape } from "@/registry/0db/ui/sign"

// Generated by scripts/build-signs.mjs from Lucide's plane (ISC).
const shape: SignShape = {"word":"fly","fill":{"step":2.11,"rows":[[1.4,17.8,22.1],[3.5,14.6,23.5],[5.6,1.8,10.9,12.5,23.2],[7.7,0.9,22],[9.8,2.1,7.6,8.1,20.1],[11.9,4,7,9.7,18.8],[14,2.1,5.9,9.1,11,12.8,19],[16.1,0.6,6,7.7,8.2,13.6,19.5],[18.2,2.7,8.1,9.9,19.9],[20.3,5,11.3,13,19.9],[22.4,6.5,9.5,15.3,17.4]]}}

/** The sign for "fly": the word filling its silhouette row by row. */
function SignPlaneFill(props: Omit<SignProps, "shape" | "variant">) {
  return <Sign shape={shape} variant="fill" {...props} />
}

export { SignPlaneFill }
