import { Sign, type SignProps, type SignShape } from "@/registry/0db/ui/sign"

// Generated by scripts/build-signs.mjs from Lucide's send (ISC).
const shape: SignShape = {"word":"send","fill":{"step":2.18,"rows":[[1.1,18,23.8],[3.3,11.6,18.8,22.1,24],[5.5,5.4,16.6,20.5,23.4],[7.6,0.3,14.5,18.3,22.7],[9.8,0,12.3,16.1,22],[12,3.4,10.5,13.9,21.2],[14.2,9,20.5],[16.4,10,19.7],[18.5,10.9,18.9],[20.7,11.7,18.2],[22.9,12.8,17.2]]},"mirror":true}

/** The sign for "send": the word filling its silhouette row by row. */
function SignSendFill(props: Omit<SignProps, "shape" | "variant">) {
  return <Sign shape={shape} variant="fill" {...props} />
}

export { SignSendFill }
