import { Sign, type SignProps, type SignShape } from "@/registry/0db/ui/sign"

// Generated by scripts/build-signs.mjs from Lucide's zap (ISC).
const shape: SignShape = {"word":"flash","fill":{"step":2.18,"rows":[[1.1,11.9,17],[3.3,9.7,18.4],[5.5,7.5,17.8],[7.6,5.3,13.2,15.5,17.4],[9.8,3.1,13,16.8,21.7],[12,1.8,22.2],[14.2,2.3,7.2,11,20.9],[16.4,6.6,8.5,10.8,18.7],[18.5,6.2,16.5],[20.7,5.6,14.3],[22.9,7,12.1]]}}

/** The sign for "flash": the word filling its silhouette row by row. */
function SignZapFill(props: Omit<SignProps, "shape" | "variant">) {
  return <Sign shape={shape} variant="fill" {...props} />
}

export { SignZapFill }
