import { Sign, type SignProps, type SignShape } from "@/registry/0db/ui/sign"

// Generated by scripts/build-signs.mjs from Lucide's smile (ISC).
const shape: SignShape = {"word":"happy","fill":{"step":2.18,"rows":[[1.1,7.4,16.6],[3.3,3.8,20.2],[5.5,1.8,22.2],[7.6,0.6,8.2,9.8,14.2,15.8,23.4],[9.8,0,7.9,10.1,13.9,16.1,24],[12,0,24],[14.2,0,6.5,8.8,15.2,17.5,24],[16.4,0.6,6.7,17.3,23.4],[18.5,1.8,10.9,13,22.2],[20.7,3.8,20.2],[22.9,7.4,16.6]]}}

/** The sign for "happy": the word filling its silhouette row by row. */
function SignSmileFill(props: Omit<SignProps, "shape" | "variant">) {
  return <Sign shape={shape} variant="fill" {...props} />
}

export { SignSmileFill }
