import { Sign, type SignProps, type SignShape } from "@/registry/0db/ui/sign"

// Generated by scripts/build-signs.mjs from a drawing made for 0dB.
const shape: SignShape = {"word":"mail","fill":{"step":1.49,"rows":[[5.2,3.1,20.9],[6.7,5.1,18.9],[8.2,1.5,2.2,7,17,21.8,22.5],[9.7,1.5,4.2,9,15,19.8,22.5],[11.2,1.5,6.1,11,13,17.9,22.5],[12.7,1.5,8.1,15.9,22.5],[14.2,1.5,10,14,22.5],[15.7,1.5,22.5],[17.2,1.5,22.5],[18.7,1.5,22.5]]}}

/** The sign for "mail": the word filling its silhouette row by row. */
function SignMailFill(props: Omit<SignProps, "shape" | "variant">) {
  return <Sign shape={shape} variant="fill" {...props} />
}

export { SignMailFill }
