import { Sign, type SignProps, type SignShape } from "@/registry/0db/ui/sign"

// Generated by scripts/build-signs.mjs from Lucide's sun (ISC).
const shape: SignShape = {"word":"day","fill":{"step":2.18,"rows":[[1.1,10,14],[3.3,3.8,6,9.5,14.5,18,20.2],[5.5,2.8,8.3,9.7,14.3,15.7,21.2],[7.6,4.7,19.3],[9.8,6.2,17.8],[12,0,24],[14.2,6.2,17.8],[16.4,4.7,19.3],[18.5,2.8,8.2,9.7,14.3,15.7,21.2],[20.7,3.8,6,9.5,14.5,18,20.2],[22.9,10,14]]}}

/** The sign for "day": the word filling its silhouette row by row. */
function SignSunFill(props: Omit<SignProps, "shape" | "variant">) {
  return <Sign shape={shape} variant="fill" {...props} />
}

export { SignSunFill }
