import { Sign, type SignProps, type SignShape } from "@/registry/0db/ui/sign"

// Generated by scripts/build-signs.mjs from Lucide's smartphone (ISC).
const shape: SignShape = {"word":"mobile","line":[[["M",5.5,2.7],["L",5.1,3.3],["L",5,4],["L",5,20],["L",5.1,20.7],["L",5.4,21.1],["L",5.7,21.5]],[["M",18.3,2.5],["L",18.6,2.9],["L",18.8,3.2],["L",18.9,3.5],["L",19,4],["L",19,20],["L",18.9,20.7],["L",18.5,21.3]],[["M",5.5,2.7],["L",5.9,2.4],["L",6.3,2.1],["L",7,2],["L",17,2],["L",17.7,2.1],["L",18.3,2.5]],[["M",5.7,21.5],["L",6.3,21.9],["L",7,22],["L",17,22],["L",17.5,21.9],["L",17.9,21.8],["L",18.5,21.3]],[["M",12,18],["L",12,18]]]}

/** The sign for "mobile": the word set along its strokes. */
function SignSmartphoneWords(props: Omit<SignProps, "shape" | "variant">) {
  return <Sign shape={shape} variant="words" {...props} />
}

export { SignSmartphoneWords }
