import { Sign, type SignProps, type SignShape } from "@/registry/0db/ui/sign"

// Generated by scripts/build-signs.mjs from Lucide's calculator (ISC).
const shape: SignShape = {"word":"sum","line":[[["M",19.3,2.5],["L",19.8,3.1],["L",19.9,3.5],["L",20,4],["L",20,20],["L",19.9,20.7],["L",19.5,21.3]],[["M",4.7,21.5],["L",4.2,20.9],["L",4.1,20.5],["L",4,20],["L",4,4],["L",4.1,3.3],["L",4.5,2.7]],[["M",4.5,2.7],["L",4.9,2.4],["L",5.3,2.1],["L",6,2],["L",18,2],["L",18.7,2.1],["L",19.3,2.5]],[["M",4.7,21.5],["L",5.3,21.9],["L",6,22],["L",18,22],["L",18.5,21.9],["L",18.9,21.8],["L",19.5,21.3]],[["M",8,6],["L",16,6]],[["M",16,14],["L",16,18]],[["M",16,10],["L",16,10]],[["M",12,10],["L",12,10]],[["M",8,10],["L",8,10]],[["M",12,14],["L",12,14]],[["M",8,14],["L",8,14]],[["M",12,18],["L",12,18]],[["M",8,18],["L",8,18]]]}

/** The sign for "sum": the word ruled in leaders along its strokes. */
function SignCalculatorDots(props: Omit<SignProps, "shape" | "variant">) {
  return <Sign shape={shape} variant="dots" {...props} />
}

export { SignCalculatorDots }
