import { Sign, type SignProps, type SignShape } from "@/registry/0db/ui/sign"

// Generated by scripts/build-signs.mjs from Lucide's feather (ISC).
const shape: SignShape = {"word":"write","fill":{"step":2.18,"rows":[[1.1,12.1,20],[3.3,9.3,22.6],[5.5,7.2,23.8],[7.6,5,14.5,16.9,24],[9.8,3.1,12.3,16.1,24],[12,2.5,10.1,13.9,23.1],[14.2,2.5,7.9,17.1,21.1],[16.4,2.5,5.7,16.6,19],[18.5,2.5,4.8,7.4,16.8],[20.7,0.4,13.7],[22.9,0,4]]}}

/** The sign for "write": the word filling its silhouette row by row. */
function SignFeatherFill(props: Omit<SignProps, "shape" | "variant">) {
  return <Sign shape={shape} variant="fill" {...props} />
}

export { SignFeatherFill }
