import { Sign, type SignProps, type SignShape } from "@/registry/0db/ui/sign"

// Generated by scripts/build-signs.mjs from Lucide's crop (ISC).
const shape: SignShape = {"word":"crop","line":[[["M",2,6],["L",16,6],["L",16.7,6.1],["L",17.1,6.4],["L",17.5,6.7]],[["M",6.5,17.3],["L",6.9,17.6],["L",7.2,17.8],["L",7.5,17.9],["L",8,18],["L",22,18]],[["M",6.5,17.3],["L",6.1,16.7],["L",6,16],["L",6,2]],[["M",17.5,6.7],["L",17.9,7.3],["L",18,8],["L",18,22]]]}

/** The sign for "crop": the word ruled in leaders along its strokes. */
function SignCropDots(props: Omit<SignProps, "shape" | "variant">) {
  return <Sign shape={shape} variant="dots" {...props} />
}

export { SignCropDots }
