import { Sign, type SignProps, type SignShape } from "@/registry/0db/ui/sign"

// Generated by scripts/build-signs.mjs from Lucide's phone (ISC).
const shape: SignShape = {"word":"call","fill":{"step":2.18,"rows":[[1.1,1.3,9.8],[3.3,0,11.2],[5.5,0,11.5],[7.6,0,11.3],[9.8,0.6,10.4],[12,1.4,11.2],[14.2,2.7,13.6,14,22.9],[16.4,4.2,24],[18.5,6.3,24],[20.7,9,24],[22.9,13.6,22.7]]}}

/** The sign for "call": the word filling its silhouette row by row. */
function SignPhoneFill(props: Omit<SignProps, "shape" | "variant">) {
  return <Sign shape={shape} variant="fill" {...props} />
}

export { SignPhoneFill }
