import { Sign, type SignProps, type SignShape } from "@/registry/0db/ui/sign"

// Generated by scripts/build-signs.mjs from Lucide's hammer (ISC).
const shape: SignShape = {"word":"build","fill":{"step":2.14,"rows":[[1.6,7.5,15.4],[3.7,6.9,18.6],[5.8,8.8,20.6],[8,9.3,21.4],[10.1,8,11.1,14,24],[12.3,5.8,12.4,15.8,23.7],[14.4,3.7,21.5],[16.5,1.6,13.4,16.7,19.3],[18.7,0,11.1],[20.8,0,9],[22.9,1.2,6.9]]}}

/** The sign for "build": the word filling its silhouette row by row. */
function SignHammerFill(props: Omit<SignProps, "shape" | "variant">) {
  return <Sign shape={shape} variant="fill" {...props} />
}

export { SignHammerFill }
