import { Sign, type SignProps, type SignShape } from "@/registry/0db/ui/sign"

// Generated by scripts/build-signs.mjs from Lucide's drum (ISC).
const shape: SignShape = {"word":"drum","fill":{"step":2.18,"rows":[[1.1,0.1,3.9,20.1,23.9],[3.3,0.4,23.6],[5.5,1.3,2.7,7.6,16.4,20.7,22.7],[7.6,0,3.2,9.8,14.2,18.5,24],[9.8,0,1.7,3.8,7.7,11,13,16.3,20.2,22.3,24],[12,0,1.8,8.9,15.1,22.2,24],[14.2,0,4.7,19.3,24],[16.4,0,5.9,8.1,10.9,13.1,15.9,18.1,24],[18.5,0,5.9,8.1,10.9,13.1,15.9,18.1,24],[20.7,1.7,5.9,8.1,10.9,13.1,15.9,18.1,22.3],[22.9,6.1,17.9]]}}

/** The sign for "drum": the word filling its silhouette row by row. */
function SignDrumFill(props: Omit<SignProps, "shape" | "variant">) {
  return <Sign shape={shape} variant="fill" {...props} />
}

export { SignDrumFill }
