import { Sign, type SignProps, type SignShape } from "@/registry/0db/ui/sign"

// Generated by scripts/build-signs.mjs from Lucide's folder (ISC).
const shape: SignShape = {"word":"folder","line":[[["M",2.5,19.3],["L",2.9,19.6],["L",3.2,19.8],["L",3.5,19.9],["L",4,20],["L",20,20],["L",20.7,19.9],["L",21.3,19.5]],[["M",2.5,19.3],["L",2.1,18.7],["L",2,18],["L",2,5],["L",2.1,4.3],["L",2.4,3.9],["L",2.7,3.5]],[["M",21.5,6.7],["L",21.9,7.3],["L",22,8],["L",22,18],["L",21.9,18.5],["L",21.8,18.9],["L",21.3,19.5]],[["M",11.3,5.8],["L",11.6,5.9],["L",12.1,6],["L",20.2,6],["L",20.9,6.2],["L",21.5,6.7]],[["M",2.7,3.5],["L",3.3,3.1],["L",4,3],["L",7.9,3],["L",8.4,3.1],["L",8.8,3.2]],[["M",8.8,3.2],["L",9.1,3.4],["L",9.5,3.7],["L",10.6,5.3],["L",10.9,5.6],["L",11.3,5.8]]]}

/** The sign for "folder": the word ruled in leaders along its strokes. */
function SignFolderDots(props: Omit<SignProps, "shape" | "variant">) {
  return <Sign shape={shape} variant="dots" {...props} />
}

export { SignFolderDots }
