import { Sign, type SignProps, type SignShape } from "@/registry/0db/ui/sign"

// Generated by scripts/build-signs.mjs from Lucide's plane (ISC).
const shape: SignShape = {"word":"fly","fill":{"step":2.11,"rows":[[1.4,18,21.9],[3.5,14.7,23.5],[5.6,1.9,10.4,12.6,23.2],[7.7,0.9,22],[9.8,2.1,7.2,8.5,20.1],[11.9,4.4,6.8,10,18.7],[14,2.1,5.3,9.3,10.7,13,19],[16.1,0.7,5.3,13.9,19.5],[18.2,2.9,7.5,10.5,19.9],[20.3,5,11.2,13,19.9],[22.4,6.7,9.3,15.8,17.1]]}}

/** The sign for "fly": the word filling its silhouette row by row. */
function SignPlaneFill(props: Omit<SignProps, "shape" | "variant">) {
  return <Sign shape={shape} variant="fill" {...props} />
}

export { SignPlaneFill }
