import { Sign, type SignProps, type SignShape } from "@/registry/0db/ui/sign"

// Generated by scripts/build-signs.mjs from Lucide's briefcase (ISC).
const shape: SignShape = {"word":"work","fill":{"step":2.05,"rows":[[1,7.4,16.6],[3.1,5.8,18.2],[5.1,1.3,6.2,17.8,22.8],[7.2,0,6.3,17.7,24],[9.2,0,6.9,9.1,14.9,17.1,24],[11.3,0,6.9,9.1,14.9,17.1,24],[13.3,0,6.9,9.1,14.9,17.1,24],[15.3,0,6.9,9.1,14.9,17.1,24],[17.4,0,6.9,9.1,14.9,17.1,24],[19.4,0,6.9,9.1,14.9,17.1,24],[21.5,2.2,21.8]]}}

/** The sign for "work": the word filling its silhouette row by row. */
function SignBriefcaseFill(props: Omit<SignProps, "shape" | "variant">) {
  return <Sign shape={shape} variant="fill" {...props} />
}

export { SignBriefcaseFill }
