import { Sign, type SignProps, type SignShape } from "@/registry/0db/ui/sign"

// Generated by scripts/build-signs.mjs from Lucide's lightbulb (ISC).
const shape: SignShape = {"word":"idea","line":[[["M",6,8.1],["L",6.1,7],["L",6.2,6.5],["L",6.4,5.8],["L",6.6,5.4],["L",7,4.7],["L",7.4,4.1],["L",7.8,3.8],["L",8.5,3.1],["L",9.1,2.7],["L",9.6,2.5],["L",10.1,2.3],["L",10.8,2.1],["L",11.5,2],["L",12,2],["L",12.5,2],["L",13.2,2.1],["L",13.7,2.2],["L",14.4,2.5],["L",15.3,3],["L",15.8,3.3],["L",16.2,3.8],["L",17,4.6],["L",17.5,5.6],["L",17.8,6.3],["L",17.9,6.8],["L",18,7.5],["L",18,8]],[["M",15,14],["L",15.2,13.4],["L",15.6,12.6],["L",16,12],["L",17,11],["L",17.5,10.2],["L",17.7,9.8],["L",17.9,9.1],["L",18,8.7],["L",18,8]],[["M",6,8.1],["L",6.1,9.1],["L",6.3,9.7],["L",6.5,10.2],["L",7.1,11],["L",8,12],["L",8.4,12.5],["L",8.8,13.3],["L",9,14]],[["M",9,18],["L",15,18]],[["M",10,22],["L",14,22]]]}

/** The sign for "idea": the word ruled in leaders along its strokes. */
function SignLightbulbDots(props: Omit<SignProps, "shape" | "variant">) {
  return <Sign shape={shape} variant="dots" {...props} />
}

export { SignLightbulbDots }
