import { Sign, type SignProps, type SignShape } from "@/registry/0db/ui/sign"

// Generated by scripts/build-signs.mjs from Lucide's shuffle (ISC).
const shape: SignShape = {"word":"shuffle","line":[[["M",2,18],["L",4.2,18],["L",4.9,17.9],["L",5.8,17.6],["L",6.2,17.3],["L",6.8,16.9],["L",7.3,16.3],["L",12.7,7.7],["L",13.4,7],["L",14,6.6],["L",14.8,6.2],["L",15.8,6],["L",22,6]],[["M",12.3,15.8],["L",13,16.6],["L",13.5,17.1],["L",14.2,17.6],["L",15,17.9],["L",16,18],["L",22,18]],[["M",2,6],["L",4.2,6],["L",4.8,6.1],["L",5.4,6.3],["L",6.1,6.6],["L",6.7,7],["L",7.2,7.6],["L",7.6,8.2]],[["M",18,14],["L",22,18]],[["M",18,22],["L",22,18]],[["M",18,2],["L",22,6]],[["M",18,10],["L",22,6]]]}

/** The sign for "shuffle": the word set along its strokes. */
function SignShuffleWords(props: Omit<SignProps, "shape" | "variant">) {
  return <Sign shape={shape} variant="words" {...props} />
}

export { SignShuffleWords }
