import { Sign, type SignProps, type SignShape } from "@/registry/0db/ui/sign"

// Generated by scripts/build-signs.mjs from Lucide's user (ISC).
const shape: SignShape = {"word":"person","fill":{"step":2.08,"rows":[[1.6,9.6,14.4],[3.7,6.9,17.1],[5.8,5.8,18.2],[7.9,5.7,18.3],[10,6.6,10.1,13.9,17.4],[12,7.9,10.2,13.8,16.1],[14.1,5.6,18.4],[16.2,3.5,20.5],[18.3,2.7,7.5,16.5,21.3],[20.4,2.5,7.5,16.5,21.5],[22.5,3.7,6.3,17.7,20.3]]}}

/** The sign for "person": the word filling its silhouette row by row. */
function SignUserFill(props: Omit<SignProps, "shape" | "variant">) {
  return <Sign shape={shape} variant="fill" {...props} />
}

export { SignUserFill }
