import { Sign, type SignProps, type SignShape } from "@/registry/0db/ui/sign"

// Generated by scripts/build-signs.mjs from Lucide's contact (ISC).
const shape: SignShape = {"word":"contact","fill":{"step":2.14,"rows":[[1.1,5,19],[3.2,1.3,7,9,15,17,22.8],[5.3,0.6,7.5,8.5,15.5,16.5,23.4],[7.5,0.5,8.6,15.4,23.5],[9.6,0.5,8.1,10.1,13.9,15.9,23.5],[11.8,0.5,8.3,15.7,23.5],[13.9,0.5,10,14,23.5],[16,0.5,7.4,16.5,23.5],[18.2,0.5,6.1,17.9,23.5],[20.3,1,6.1,7.9,16.1,17.9,23],[22.4,3,21]]}}

/** The sign for "contact": the word filling its silhouette row by row. */
function SignContactFill(props: Omit<SignProps, "shape" | "variant">) {
  return <Sign shape={shape} variant="fill" {...props} />
}

export { SignContactFill }
