import { Sign, type SignProps, type SignShape } from "@/registry/0db/ui/sign"

// Generated by scripts/build-signs.mjs from Lucide's tree-pine (ISC).
const shape: SignShape = {"word":"pine","fill":{"step":2.14,"rows":[[1.6,10.7,13.3],[3.7,8.5,15.5],[5.8,6.6,17.4],[8,5.3,7.6,10,13.6,16.6,18.7],[10.1,5.2,7.5,9.9,13.6,17,18.8],[12.3,3.6,5.8,8,16,18.2,20.4],[14.4,3.4,5.1,8.5,15.5,18.8,20.6],[16.5,2,6,7.1,22],[18.7,1.5,10.1,13.9,22.5],[20.8,4,11,13,20.2],[22.9,10.1,13.9]]}}

/** The sign for "pine": the word filling its silhouette row by row. */
function SignTreePineFill(props: Omit<SignProps, "shape" | "variant">) {
  return <Sign shape={shape} variant="fill" {...props} />
}

export { SignTreePineFill }
