import { Sign, type SignProps, type SignShape } from "@/registry/0db/ui/sign"

// Generated by scripts/build-signs.mjs from Lucide's share-2 (ISC).
const shape: SignShape = {"word":"share","fill":{"step":2.18,"rows":[[1.1,15,21],[3.3,13.1,22.9],[5.5,12.6,13.9,16.9,23.3],[7.6,3.8,8.2,9.7,14,16.9,22.3],[9.8,1.3,7,10.1,13.5],[12,0.6,7.3,9.9,11.5],[14.2,1.3,7,10.1,13.5],[16.4,3.8,8.2,9.7,14,16.9,22.3],[18.5,12.6,13.9,16.9,23.3],[20.7,13.1,22.9],[22.9,15,21]]}}

/** The sign for "share": the word filling its silhouette row by row. */
function SignShareFill(props: Omit<SignProps, "shape" | "variant">) {
  return <Sign shape={shape} variant="fill" {...props} />
}

export { SignShareFill }
