import { Sign, type SignProps, type SignShape } from "@/registry/0db/ui/sign"

// Generated by scripts/build-signs.mjs from Lucide's calendar-plus (ISC).
const shape: SignShape = {"word":"event","line":[[["M",3,9],["L",21,9]],[["M",3.7,3.5],["L",4.3,3.1],["L",5,3],["L",19,3],["L",19.7,3.1],["L",20.1,3.4],["L",20.5,3.7]],[["M",3.5,20.3],["L",3.1,19.7],["L",3,19],["L",3,5],["L",3.1,4.3],["L",3.4,3.9],["L",3.7,3.5]],[["M",3.5,20.3],["L",4.1,20.8],["L",4.8,21],["L",13.3,21]],[["M",20.5,3.7],["L",20.8,4.2],["L",21,4.8],["L",21,11.5]],[["M",16,18],["L",22,18]],[["M",19,15],["L",19,21]],[["M",16,2],["L",16,5]],[["M",8,5],["L",8,2]]]}

/** The sign for "event": the word ruled in leaders along its strokes. */
function SignCalendarPlusDots(props: Omit<SignProps, "shape" | "variant">) {
  return <Sign shape={shape} variant="dots" {...props} />
}

export { SignCalendarPlusDots }
