import { Sign, type SignProps, type SignShape } from "@/registry/0db/ui/sign"

// Generated by scripts/build-signs.mjs from Lucide's key (ISC).
const shape: SignShape = {"word":"key","fill":{"step":2.18,"rows":[[1.1,11.7,19.3],[3.3,9.2,21.8],[5.5,8,23],[7.6,7.6,23.4],[9.8,8.1,22.9],[12,8.1,10.5,12.6,21.6],[14.2,5.9,11.7,12.3,18.7],[16.4,3.7,11.3],[18.5,1.6,12.5],[20.7,0,11.2],[22.9,5.2,8.8]]}}

/** The sign for "key": the word filling its silhouette row by row. */
function SignKeyFill(props: Omit<SignProps, "shape" | "variant">) {
  return <Sign shape={shape} variant="fill" {...props} />
}

export { SignKeyFill }
