import { Sign, type SignProps, type SignShape } from "@/registry/0db/ui/sign"

// Generated by scripts/build-signs.mjs from Lucide's feather (ISC).
const shape: SignShape = {"word":"write","line":[[["M",5.2,10.6],["L",5.3,10.3],["L",5.6,9.9],["L",12.1,3.4],["L",12.9,2.8],["L",13.6,2.5],["L",14.3,2.2],["L",15,2.1],["L",15.7,2],["L",16.2,2],["L",17,2.1],["L",17.5,2.2],["L",18.2,2.4],["L",18.6,2.6],["L",19.3,3],["L",19.9,3.4],["L",20.4,3.9],["L",20.7,4.3],["L",21.2,4.9],["L",21.4,5.4],["L",21.6,5.8],["L",21.8,6.5],["L",22,7.3],["L",22,8]],[["M",2,22],["L",16,8]],[["M",13.4,18.8],["L",13.7,18.7],["L",14.1,18.4],["L",20.2,12.2],["L",20.7,11.7],["L",21.3,10.9],["L",21.7,9.9],["L",21.9,9],["L",22,8]],[["M",9,15],["L",17.5,15]],[["M",5,19],["L",12.7,19],["L",13.1,18.9],["L",13.4,18.8]],[["M",5,19],["L",5,11.3],["L",5.1,10.9],["L",5.2,10.6]]]}

/** The sign for "write": the word set along its strokes. */
function SignFeatherWords(props: Omit<SignProps, "shape" | "variant">) {
  return <Sign shape={shape} variant="words" {...props} />
}

export { SignFeatherWords }
