import { Sign, type SignProps, type SignShape } from "@/registry/0db/ui/sign"

// Generated by scripts/build-signs.mjs from Lucide's bird (ISC).
const shape: SignShape = {"word":"bird","fill":{"step":2.09,"rows":[[1.5,13.6,18.5],[3.6,10.8,21.2],[5.7,9.4,15.5,16.5,22.7],[7.8,8,10.7,12.8,15.1,16.9,19.1,21,24],[9.9,6.5,11.3,13.8,22.5],[12,5,12,13.9,22.1],[14.1,3.5,11.3,13.8,21.4],[16.2,2.1,8.9,12.9,19.9],[18.3,0.6,7.7,14.9,17.4],[20.4,0,4.4,7.5,9.7,10.3,16.5],[22.5,8.5,11.5,12.5,15.5]]}}

/** The sign for "bird": the word filling its silhouette row by row. */
function SignBirdFill(props: Omit<SignProps, "shape" | "variant">) {
  return <Sign shape={shape} variant="fill" {...props} />
}

export { SignBirdFill }
