import { Sign, type SignProps, type SignShape } from "@/registry/0db/ui/sign"

// Generated by scripts/build-signs.mjs from Lucide's banknote (ISC).
const shape: SignShape = {"word":"cash","fill":{"step":2.13,"rows":[[4.6,2.2,21.8],[6.7,0,24],[8.8,0,10.3,13.7,24],[10.9,0,4.6,7.4,9,15,16.6,19.4,24],[13.1,0,4.6,7.4,9,15,16.6,19.4,24],[15.2,0,10.5,13.5,24],[17.3,0,24],[19.4,2.2,21.8]]}}

/** The sign for "cash": the word filling its silhouette row by row. */
function SignBanknoteFill(props: Omit<SignProps, "shape" | "variant">) {
  return <Sign shape={shape} variant="fill" {...props} />
}

export { SignBanknoteFill }
