import { Sign, type SignProps, type SignShape } from "@/registry/0db/ui/sign"

// Generated by scripts/build-signs.mjs from Lucide's life-buoy (ISC).
const shape: SignShape = {"word":"support","fill":{"step":2.18,"rows":[[1.1,7.2,16.8],[3.3,3.7,20.3],[5.5,1.8,4.8,7.4,16.6,19.2,22.2],[7.6,0.6,5.7,18.3,23.4],[9.8,0,7.4,10.6,13.4,16.6,24],[12,0,7.1,9,15,16.9,24],[14.2,0,7.4,10.6,13.4,16.6,24],[16.4,0.6,5.7,18.3,23.4],[18.5,1.8,4.8,7.4,16.6,19.2,22.2],[20.7,3.7,20.3],[22.9,7.2,16.8]]}}

/** The sign for "support": the word filling its silhouette row by row. */
function SignLifeBuoyFill(props: Omit<SignProps, "shape" | "variant">) {
  return <Sign shape={shape} variant="fill" {...props} />
}

export { SignLifeBuoyFill }
