import { Sign, type SignProps, type SignShape } from "@/registry/0db/ui/sign"

// Generated by scripts/build-signs.mjs from Lucide's download (ISC).
const shape: SignShape = {"word":"download","fill":{"step":2.09,"rows":[[1.5,10.5,13.5],[3.6,9.5,14.5],[5.7,9.5,14.5],[7.8,9.5,14.5],[9.9,4.6,11.1,12.9,19.4],[12,6.1,11.1,12.9,17.9],[14.1,1,5,8.2,11.1,12.9,15.8,19,23],[16.2,0.5,5.5,10.3,13.7,18.5,23.5],[18.3,0.5,5.5,18.5,23.5],[20.4,1,23],[22.5,3,21]]}}

/** The sign for "download": the word filling its silhouette row by row. */
function SignDownloadFill(props: Omit<SignProps, "shape" | "variant">) {
  return <Sign shape={shape} variant="fill" {...props} />
}

export { SignDownloadFill }
