import { Sign, type SignProps, type SignShape } from "@/registry/0db/ui/sign"

// Generated by scripts/build-signs.mjs from Lucide's fuel (ISC).
const shape: SignShape = {"word":"fuel","fill":{"step":2.09,"rows":[[1.5,3,14],[3.6,1,16,16.4,19.6],[5.7,0.5,13.1,14.9,21.5],[7.8,0.5,3.1,14.9,23.6],[9.9,0.5,2.9,14.9,24],[12,0.5,13.1,17.5,24],[14.1,0.5,13.1,18.9,24],[16.2,0.5,13.1,14.9,17.1,18.9,24],[18.3,0.5,13.1,14.9,17.2,19,23.9],[20.4,0,13.1,14.9,17.4,17.8,22],[22.5,0.5,16.5]]}}

/** The sign for "fuel": the word filling its silhouette row by row. */
function SignFuelFill(props: Omit<SignProps, "shape" | "variant">) {
  return <Sign shape={shape} variant="fill" {...props} />
}

export { SignFuelFill }
