import { Sign, type SignProps, type SignShape } from "@/registry/0db/ui/sign"

// Generated by scripts/build-signs.mjs from Lucide's redo-2 (ISC).
const shape: SignShape = {"word":"redo","line":[[["M",4,14.5],["L",4.1,13.5],["L",4.3,12.8],["L",4.5,12.1],["L",5.1,11.3],["L",5.7,10.5],["L",6.3,10.1],["L",6.9,9.7],["L",7.8,9.3],["L",8.5,9.1],["L",9.5,9],["L",20,9]],[["M",4,14.5],["L",4,15.2],["L",4.2,16],["L",4.4,16.7],["L",4.7,17.2],["L",5.1,17.7],["L",5.5,18.3],["L",6.1,18.8],["L",6.7,19.2],["L",7.1,19.5],["L",7.8,19.7],["L",8.8,20],["L",9.5,20],["L",13,20]],[["M",15,14],["L",20,9]],[["M",15,4],["L",20,9]]],"mirror":true}

/** The sign for "redo": the word ruled in leaders along its strokes. */
function SignRedoDots(props: Omit<SignProps, "shape" | "variant">) {
  return <Sign shape={shape} variant="dots" {...props} />
}

export { SignRedoDots }
