import { Sign, type SignProps, type SignShape } from "@/registry/0db/ui/sign"

// Generated by scripts/build-signs.mjs from Lucide's printer (ISC).
const shape: SignShape = {"word":"print","fill":{"step":2.18,"rows":[[1.1,4.7,19.3],[3.3,3.6,20.4],[5.5,3.5,20.5],[7.6,2,4.5,19.5,22],[9.8,0,4.2,19.5,24],[12,0,24],[14.2,0,5,19,24],[16.4,0,4.2,7.1,16.9,19.6,24],[18.5,0.9,3.8,7.5,16.5,20,23.1],[20.7,3.6,20.4],[22.9,4.7,19.3]]}}

/** The sign for "print": the word filling its silhouette row by row. */
function SignPrinterFill(props: Omit<SignProps, "shape" | "variant">) {
  return <Sign shape={shape} variant="fill" {...props} />
}

export { SignPrinterFill }
