import { Sign, type SignProps, type SignShape } from "@/registry/0db/ui/sign"

// Generated by scripts/build-signs.mjs from Lucide's circle-alert (ISC).
const shape: SignShape = {"word":"alert","line":[[["O",12,12,10,180,180]],[["O",12,12,10,180,-180]],[["M",12,8],["L",12,12]],[["M",12,16],["L",12,16]]]}

/** The sign for "alert": the word ruled in leaders along its strokes. */
function SignCircleAlertDots(props: Omit<SignProps, "shape" | "variant">) {
  return <Sign shape={shape} variant="dots" {...props} />
}

export { SignCircleAlertDots }
