import { Sign, type SignProps, type SignShape } from "@/registry/0db/ui/sign"

// Generated by scripts/build-signs.mjs from Lucide's crown (ISC).
const shape: SignShape = {"word":"crown","fill":{"step":2.09,"rows":[[1.5,10.4,13.6],[3.6,1.5,3.5,8.9,15.1,20.5,22.5],[5.7,0,6.1,7.8,16.2,17.9,24],[7.8,0.1,6.8,9.6,14.4,17.2,23.9],[9.9,0.7,6.2,9.4,14.6,17.8,23.3],[12,1.3,22.7],[14.1,1.9,22.1],[16.2,2.5,5.4,18.6,21.5],[18.3,3.7,5.8,18.2,20.3],[20.4,2.9,21.1],[22.5,3.5,20.5]]}}

/** The sign for "crown": the word filling its silhouette row by row. */
function SignCrownFill(props: Omit<SignProps, "shape" | "variant">) {
  return <Sign shape={shape} variant="fill" {...props} />
}

export { SignCrownFill }
