import { Sign, type SignProps, type SignShape } from "@/registry/0db/ui/sign"

// Generated by scripts/build-signs.mjs from Lucide's brush (ISC).
const shape: SignShape = {"word":"paint","fill":{"step":2.14,"rows":[[1.1,17.3,22.6],[3.2,15,24],[5.3,12.9,24],[7.5,10.8,22.3],[9.6,8.5,10.5,12.8,20.1],[11.8,6.4,10.7,14.5,18],[13.9,2.4,6.5,9.9,12.7,14.2,16],[16,0.9,7.7,10.9,13.8],[18.2,0.6,9.8,10,12.3],[20.3,0,11.4],[22.4,1.4,8.6]]}}

/** The sign for "paint": the word filling its silhouette row by row. */
function SignBrushFill(props: Omit<SignProps, "shape" | "variant">) {
  return <Sign shape={shape} variant="fill" {...props} />
}

export { SignBrushFill }
