import { Sign, type SignProps, type SignShape } from "@/registry/0db/ui/sign"

// Generated by scripts/build-signs.mjs from Lucide's hard-drive (ISC).
const shape: SignShape = {"word":"drive","fill":{"step":2.1,"rows":[[2.6,5.2,18.8],[4.7,3.2,20.8],[6.8,2.2,21.9],[8.9,1.1,22.9],[11,0.1,2.1,21.9,23.9],[13.1,0,2.1,21.9,24],[15.2,0,5.2,6.8,9.2,10.8,24],[17.3,0,5.5,6.5,9.5,10.5,24],[19.4,0,24],[21.5,2.1,22]]}}

/** The sign for "drive": the word filling its silhouette row by row. */
function SignHardDriveFill(props: Omit<SignProps, "shape" | "variant">) {
  return <Sign shape={shape} variant="fill" {...props} />
}

export { SignHardDriveFill }
