import { Sign, type SignProps, type SignShape } from "@/registry/0db/ui/sign"

// Generated by scripts/build-signs.mjs from Lucide's crown (ISC).
const shape: SignShape = {"word":"crown","line":[[["M",5,21],["L",19,21]],[["M",5.2,16.8],["L",5.6,17],["L",5.8,17],["L",18.2,17],["L",18.5,16.9],["L",18.8,16.8]],[["M",18.8,16.8],["L",19.1,16.5],["L",19.1,16.3],["L",22,6],["L",22,5.8],["L",21.9,5.6],["L",21.8,5.5]],[["M",2.2,5.5],["L",2.1,5.6],["L",2,5.8],["L",2,6],["L",4.9,16.3],["L",5,16.6],["L",5.2,16.8]],[["M",12,3],["L",12.3,3.1],["L",12.4,3.3],["L",15.4,8.9],["L",15.7,9.2],["L",16.1,9.4]],[["M",7.9,9.4],["L",8.3,9.2],["L",8.6,8.9],["L",11.6,3.3],["L",11.7,3.1],["L",12,3]],[["M",2.2,5.5],["L",2.4,5.4],["L",2.6,5.4],["L",2.8,5.5],["L",7.1,9.2],["L",7.5,9.4],["L",7.9,9.4]],[["M",16.1,9.4],["L",16.5,9.4],["L",16.9,9.2],["L",21.2,5.5],["L",21.4,5.4],["L",21.6,5.4],["L",21.8,5.5]]]}

/** The sign for "crown": the word ruled in leaders along its strokes. */
function SignCrownDots(props: Omit<SignProps, "shape" | "variant">) {
  return <Sign shape={shape} variant="dots" {...props} />
}

export { SignCrownDots }
