import { Sign, type SignProps, type SignShape } from "@/registry/0db/ui/sign"

// Generated by scripts/build-signs.mjs from Lucide's aperture (ISC).
const shape: SignShape = {"word":"lens","fill":{"step":2.18,"rows":[[1.1,7.2,16.8],[3.3,3.7,11,13.5,20.3],[5.5,1.8,3.8,5,9.8,12.6,22.2],[7.6,0.6,3.5,6.2,8.6,21.3,23.4],[9.8,0,4.8,10,14,16.7,24],[12,0,6,8.8,15.2,18,24],[14.2,0,7.3,10,14,19.3,24],[16.4,0.6,2.7,15.4,17.8,20.6,23.4],[18.5,1.8,11.4,14.2,19.1,20.3,22.2],[20.7,3.7,10.5,13,20.3],[22.9,7.2,16.8]]}}

/** The sign for "lens": the word filling its silhouette row by row. */
function SignApertureFill(props: Omit<SignProps, "shape" | "variant">) {
  return <Sign shape={shape} variant="fill" {...props} />
}

export { SignApertureFill }
