import { Sign, type SignProps, type SignShape } from "@/registry/0db/ui/sign"

// Generated by scripts/build-signs.mjs from Lucide's rss (ISC).
const shape: SignShape = {"word":"feed","fill":{"step":2.1,"rows":[[2.6,2.5,8.1],[4.7,1.9,13.4],[6.8,8.6,16.2],[8.9,12.4,18.3],[11,1.6,10.2,14.5,19.8],[13.1,5,12.6,16,20.9],[15.2,8.9,14.1,16.8,21.6],[17.3,2.4,7.6,10.1,15,17.3,22.1],[19.4,1.7,8.3,10.5,15.4,17.5,22.4],[21.5,3.3,6.7,11.5,14.5,18.5,21.5]]}}

/** The sign for "feed": the word filling its silhouette row by row. */
function SignRssFill(props: Omit<SignProps, "shape" | "variant">) {
  return <Sign shape={shape} variant="fill" {...props} />
}

export { SignRssFill }
