import { Sign, type SignProps, type SignShape } from "@/registry/0db/ui/sign"

// Generated by scripts/build-signs.mjs from Lucide's train-front (ISC).
const shape: SignShape = {"word":"train","fill":{"step":2.18,"rows":[[1.1,7.8,16.2],[3.3,4.6,6.9,9.1,14.9,17.1,19.4],[5.5,2.9,6.9,9.1,14.9,17.1,21],[7.6,2,6.9,9.4,14.6,17.1,22],[9.8,1.6,7.5,16.5,22.4],[12,1.5,9.5,14.6,22.5],[14.2,1.6,7,10,14,17,22.4],[16.4,2.2,8.2,9.8,14.2,15.8,21.8],[18.5,3.6,5.7,9.3,14.7,18.3,20.4],[20.7,4.3,6.8,8.7,15.3,17.2,19.7],[22.9,4.1,7.9,16.1,19.9]]}}

/** The sign for "train": the word filling its silhouette row by row. */
function SignTrainFill(props: Omit<SignProps, "shape" | "variant">) {
  return <Sign shape={shape} variant="fill" {...props} />
}

export { SignTrainFill }
