import { Sign, type SignProps, type SignShape } from "@/registry/0db/ui/sign"

// Generated by scripts/build-signs.mjs from Lucide's align-justify (ISC).
const shape: SignShape = {"word":"justify","fill":{"step":2.11,"rows":[[3.6,1.5,22.5],[5.7,0.9,23.1],[12,0.6,23.4],[18.3,0.9,23.1],[20.4,1.5,22.5]]}}

/** The sign for "justify": the word filling its silhouette row by row. */
function SignAlignJustifyFill(props: Omit<SignProps, "shape" | "variant">) {
  return <Sign shape={shape} variant="fill" {...props} />
}

export { SignAlignJustifyFill }
