import { Sign, type SignProps, type SignShape } from "@/registry/0db/ui/sign"

// Generated by scripts/build-signs.mjs from Lucide's play (ISC).
const shape: SignShape = {"word":"play","fill":{"step":2.09,"rows":[[1.5,5.2,8.7],[3.6,3,12.4],[5.7,2.5,16],[7.8,2.5,19.6],[9.9,2.5,22.6],[12,2.5,23.4],[14.1,2.5,22.5],[16.2,2.5,19.6],[18.3,2.5,16],[20.4,3,12.4],[22.5,5.2,8.7]]}}

/** The sign for "play": the word filling its silhouette row by row. */
function SignPlayFill(props: Omit<SignProps, "shape" | "variant">) {
  return <Sign shape={shape} variant="fill" {...props} />
}

export { SignPlayFill }
