import { Sign, type SignProps, type SignShape } from "@/registry/0db/ui/sign"

// Generated by scripts/build-signs.mjs from Lucide's send (ISC).
const shape: SignShape = {"word":"send","fill":{"step":2.18,"rows":[[1.1,18.3,23.7],[3.3,11.9,18.6,22.2,24],[5.5,5.4,16.4,20.7,23.4],[7.6,0.3,14.2,18.5,22.7],[9.8,0,12,16.3,21.9],[12,3.7,10.4,14.2,21.2],[14.2,9,11,11.9,20.5],[16.4,10,19.7],[18.5,10.9,18.9],[20.7,11.7,18.2],[22.9,12.9,17.1]]},"mirror":true}

/** The sign for "send": the word filling its silhouette row by row. */
function SignSendFill(props: Omit<SignProps, "shape" | "variant">) {
  return <Sign shape={shape} variant="fill" {...props} />
}

export { SignSendFill }
