import { Sign, type SignProps, type SignShape } from "@/registry/0db/ui/sign"

// Generated by scripts/build-signs.mjs from Lucide's chevron-up (ISC).
const shape: SignShape = {"word":"fold","line":[[["M",12,9],["L",18,15]],[["M",6,15],["L",12,9]]]}

/** The sign for "fold": the word set along its strokes. */
function SignChevronUpWords(props: Omit<SignProps, "shape" | "variant">) {
  return <Sign shape={shape} variant="words" {...props} />
}

export { SignChevronUpWords }
