import { Sign, type SignProps, type SignShape } from "@/registry/0db/ui/sign"

// Generated by scripts/build-signs.mjs from Lucide's repeat (ISC).
const shape: SignShape = {"word":"repeat","line":[[["M",3,18],["L",17,18],["L",18,17.9],["L",18.8,17.6],["L",19.5,17.1],["L",20,16.7],["L",20.4,16.1],["L",20.7,15.4],["L",20.9,14.7],["L",21,14.2],["L",21,13]],[["M",3,11],["L",3,9.8],["L",3.1,9.3],["L",3.3,8.6],["L",3.6,7.9],["L",4,7.3],["L",4.6,6.8],["L",5.4,6.4],["L",6,6.1],["L",7,6],["L",21,6]],[["M",17,2],["L",21,6]],[["M",17,10],["L",21,6]],[["M",3,18],["L",7,22]],[["M",3,18],["L",7,14]]]}

/** The sign for "repeat": the word set along its strokes. */
function SignRepeatWords(props: Omit<SignProps, "shape" | "variant">) {
  return <Sign shape={shape} variant="words" {...props} />
}

export { SignRepeatWords }
