import { Sign, type SignProps, type SignShape } from "@/registry/0db/ui/sign"

// Generated by scripts/build-signs.mjs from Lucide's bath (ISC).
const shape: SignShape = {"word":"bath","fill":{"step":2.09,"rows":[[1.5,4.1,8.1],[3.6,2.1,12.3],[5.7,1.5,11.2],[7.8,1.5,6.5,7.3,8.7],[9.9,1.5,3.6,4.4,6.5],[12,0,2.8,5.7,24],[14.1,1.5,3.6,4.4,22.5],[16.2,1.5,22.5],[18.3,2,5.9,8.6,15.4,17.9,22],[20.4,3.9,6.3,8.1,15.9,17.7,20.2],[22.5,5.5,8.5,15.5,18.5]]}}

/** The sign for "bath": the word filling its silhouette row by row. */
function SignBathFill(props: Omit<SignProps, "shape" | "variant">) {
  return <Sign shape={shape} variant="fill" {...props} />
}

export { SignBathFill }
