import { Sign, type SignProps, type SignShape } from "@/registry/0db/ui/sign"

// Generated by scripts/build-signs.mjs from Lucide's sofa (ISC).
const shape: SignShape = {"word":"sofa","fill":{"step":2.1,"rows":[[2.6,4,20],[4.7,2,11.1,12.9,22],[6.8,1.5,11.1,12.9,22.5],[8.9,0.5,3.2,6.4,11.1,12.9,17.6,20.8,23.6],[11,0,4.9,6.9,11.1,12.9,17.1,19.1,24],[13.1,0,5.1,18.9,24],[15.2,0,24],[17.3,0,3.1,5.6,18.4,20.9,24],[19.4,1.5,3.7,5.1,18.9,20.3,22.5],[21.5,2.5,5.5,18.5,21.5]]}}

/** The sign for "sofa": the word filling its silhouette row by row. */
function SignSofaFill(props: Omit<SignProps, "shape" | "variant">) {
  return <Sign shape={shape} variant="fill" {...props} />
}

export { SignSofaFill }
