import { Sign, type SignProps, type SignShape } from "@/registry/0db/ui/sign"

// Generated by scripts/build-signs.mjs from Lucide's redo-2 (ISC).
const shape: SignShape = {"word":"redo","fill":{"step":2.1,"rows":[[2.6,13.7,16.3],[4.7,12.9,18.5],[6.8,13.6,20.6],[8.9,4.7,14.5,20,22.3],[11,2.8,8.8,13.9,20.9],[13.1,1.9,6.6,13.1,18.8],[15.2,1.6,6.5,13.3,16.7],[17.3,2.3,7.3],[19.4,3.7,15.1],[21.5,7.1,14.3]]},"mirror":true}

/** The sign for "redo": the word filling its silhouette row by row. */
function SignRedoFill(props: Omit<SignProps, "shape" | "variant">) {
  return <Sign shape={shape} variant="fill" {...props} />
}

export { SignRedoFill }
