import { Sign, type SignProps, type SignShape } from "@/registry/0db/ui/sign"

// Generated by scripts/build-signs.mjs from Lucide's map (ISC).
const shape: SignShape = {"word":"map","fill":{"step":2.05,"rows":[[1.7,7,10.8,19.3,20.7],[3.8,3,8.1,9.9,14.8,15.2,23.1],[5.8,0.8,8.1,9.9,14.1,15.9,23.5],[7.9,0.5,8.1,9.9,14.1,15.9,23.5],[9.9,0.5,8.1,9.9,14.1,15.9,23.5],[12,0.5,8.1,9.9,14.1,15.9,23.5],[14.1,0.5,8.1,9.9,14.1,15.9,23.5],[16.1,0.5,8.1,9.9,14.1,15.9,23.5],[18.2,0.5,8.1,9.9,14.1,15.9,23.2],[20.2,0.9,8.8,9.2,14.1,15.9,21],[22.3,3.3,4.7,13.2,17]]}}

/** The sign for "map": the word filling its silhouette row by row. */
function SignMapFill(props: Omit<SignProps, "shape" | "variant">) {
  return <Sign shape={shape} variant="fill" {...props} />
}

export { SignMapFill }
