import { Sign, type SignProps, type SignShape } from "@/registry/0db/ui/sign"

// Generated by scripts/build-signs.mjs from Lucide's plus (ISC).
const shape: SignShape = {"word":"add","fill":{"step":2.11,"rows":[[3.6,10.5,13.5],[5.7,9.5,14.5],[7.8,9.5,14.5],[9.9,9.5,11.3,12.7,14.5],[12,2.6,10.3,13.7,21.4],[14.1,9.5,11.3,12.7,14.5],[16.2,9.5,14.5],[18.3,9.5,14.5],[20.4,10.5,13.5]]}}

/** The sign for "add": the word filling its silhouette row by row. */
function SignPlusFill(props: Omit<SignProps, "shape" | "variant">) {
  return <Sign shape={shape} variant="fill" {...props} />
}

export { SignPlusFill }
