import { Sign, type SignProps, type SignShape } from "@/registry/0db/ui/sign"

// Generated by scripts/build-signs.mjs from Lucide's music (ISC).
const shape: SignShape = {"word":"music","fill":{"step":2.09,"rows":[[1.5,18.4,22.3],[3.6,7.5,23.5],[5.7,6.5,15.8,18.5,23.5],[7.8,6.5,11.5,18.5,23.5],[9.9,6.5,11.5,18.5,23.5],[12,6.5,11.5,15,18.1,20.9,23.5],[14.1,2.9,6.1,9,11.5,13.2,17.9,21.7,23.5],[16.2,1.1,5.9,9.7,11.5,12.6,23.4],[18.3,0.6,11.4,13.4,22.6],[20.4,1.4,10.6,15.8,20.2],[22.5,4,8]]}}

/** The sign for "music": the word filling its silhouette row by row. */
function SignMusicFill(props: Omit<SignProps, "shape" | "variant">) {
  return <Sign shape={shape} variant="fill" {...props} />
}

export { SignMusicFill }
