import { Sign, type SignProps, type SignShape } from "@/registry/0db/ui/sign"

// Generated by scripts/build-signs.mjs from Lucide's pizza (ISC).
const shape: SignShape = {"word":"pizza","fill":{"step":2.18,"rows":[[1.1,12.7,18.5],[3.3,8.6,19.5],[5.5,5.9,13.8,18.1,20.1],[7.6,3.9,10.5,16.2,20.7],[9.8,2.2,8.3,12.1,15.9,18.9,21.4],[12,1.1,6.7,9.8,15,17.3,22],[14.2,0.2,5.7,8.2,10.1,12.8,15,17.3,22.6],[16.4,0,4.9,7.2,10.7,11.3,15.8,21.1,23.2],[18.5,1.6,5.3,6.4,12.1,14.6,18.8,20.5,23.8],[20.7,8.9,24],[22.9,16.8,23.4]]}}

/** The sign for "pizza": the word filling its silhouette row by row. */
function SignPizzaFill(props: Omit<SignProps, "shape" | "variant">) {
  return <Sign shape={shape} variant="fill" {...props} />
}

export { SignPizzaFill }
