import { Sign, type SignProps, type SignShape } from "@/registry/0db/ui/sign"

// Generated by scripts/build-signs.mjs from Lucide's volume-1 (ISC).
const shape: SignShape = {"word":"soft","fill":{"step":2.1,"rows":[[2.6,8.7,11.9],[4.7,6.4,13.4],[6.8,1,13.5],[8.9,0,10.3,11.7,18.5],[11,0,10.1,11.9,19.2],[13.1,0,10.1,11.9,19.2],[15.2,0,10.3,11.7,18.5],[17.3,1,13.5],[19.4,6.4,13.4],[21.5,8.7,11.9]]}}

/** The sign for "soft": the word filling its silhouette row by row. */
function SignVolumeLowFill(props: Omit<SignProps, "shape" | "variant">) {
  return <Sign shape={shape} variant="fill" {...props} />
}

export { SignVolumeLowFill }
