import { Sign, type SignProps, type SignShape } from "@/registry/0db/ui/sign"

// Generated by scripts/build-signs.mjs from Lucide's skip-back (ISC).
const shape: SignShape = {"word":"replay","line":[[["M",3,20],["L",3,4]],[["M",7,12.1],["L",7.1,12.6],["L",7.3,13],["L",7.8,13.6],["L",18,19.7],["L",18.4,19.9],["L",18.7,20],["L",19.2,20],["L",19.6,19.9],["L",20.1,19.7]],[["M",7,12.1],["L",7,11.6],["L",7.2,11.2],["L",7.6,10.6],["L",8,10.3],["L",18.2,4.2],["L",18.7,4],["L",19.2,4],["L",19.6,4.1],["L",19.9,4.2]],[["M",19.9,4.2],["L",20.3,4.5],["L",20.6,4.8],["L",20.9,5.3],["L",21,5.8],["L",21,12]],[["M",21,12],["L",21,18.2],["L",20.9,18.7],["L",20.6,19.2],["L",20.3,19.5],["L",20.1,19.7]]]}

/** The sign for "replay": the word set along its strokes. */
function SignSkipBackWords(props: Omit<SignProps, "shape" | "variant">) {
  return <Sign shape={shape} variant="words" {...props} />
}

export { SignSkipBackWords }
