import { Sign, type SignProps, type SignShape } from "@/registry/0db/ui/sign"

// Generated by scripts/build-signs.mjs from Lucide's hourglass (ISC).
const shape: SignShape = {"word":"wait","fill":{"step":2.18,"rows":[[1.1,3.1,20.9],[3.3,3.4,20.6],[5.5,4.5,19.5],[7.6,5.1,18.9],[9.8,7,10.3,13.7,17],[12,8.5,10,14,15.5],[14.2,7,10.3,13.7,17],[16.4,5.1,18.9],[18.5,4.5,19.5],[20.7,3.4,20.6],[22.9,3.1,20.9]]}}

/** The sign for "wait": the word filling its silhouette row by row. */
function SignHourglassFill(props: Omit<SignProps, "shape" | "variant">) {
  return <Sign shape={shape} variant="fill" {...props} />
}

export { SignHourglassFill }
