import { Sign, type SignProps, type SignShape } from "@/registry/0db/ui/sign"

// Generated by scripts/build-signs.mjs from Lucide's message-circle (ISC).
const shape: SignShape = {"word":"chat","fill":{"step":2.18,"rows":[[1.1,7.4,16.6],[3.3,3.8,20.2],[5.5,1.8,22.2],[7.6,0.6,23.4],[9.8,0,24],[12,0,24],[14.2,0,24],[16.4,0.6,23.4],[18.5,0.4,22.1],[20.7,0,20.2],[22.9,0.7,6.6,7.4,16.7]]}}

/** The sign for "chat": the word filling its silhouette row by row. */
function SignMessageCircleFill(props: Omit<SignProps, "shape" | "variant">) {
  return <Sign shape={shape} variant="fill" {...props} />
}

export { SignMessageCircleFill }
