import { Sign, type SignProps, type SignShape } from "@/registry/0db/ui/sign"

// Generated by scripts/build-signs.mjs from Lucide's target (ISC).
const shape: SignShape = {"word":"target","line":[[["O",12,12,10,180,180]],[["O",12,12,10,180,-180]],[["O",12,12,6,180,180]],[["O",12,12,6,180,-180]],[["O",12,12,2,180,180]],[["O",12,12,2,180,-180]]]}

/** The sign for "target": the word ruled in leaders along its strokes. */
function SignTargetDots(props: Omit<SignProps, "shape" | "variant">) {
  return <Sign shape={shape} variant="dots" {...props} />
}

export { SignTargetDots }
