import { Sign, type SignProps, type SignShape } from "@/registry/0db/ui/sign"

// Generated by scripts/build-signs.mjs from Lucide's trending-up (ISC).
const shape: SignShape = {"word":"rise","line":[[["M",13.5,15.5],["L",22,7]],[["M",2,17],["L",8.5,10.5]],[["M",8.5,10.5],["L",13.5,15.5]],[["M",16,7],["L",22,7]],[["M",22,7],["L",22,13]]]}

/** The sign for "rise": the word ruled in leaders along its strokes. */
function SignTrendingUpDots(props: Omit<SignProps, "shape" | "variant">) {
  return <Sign shape={shape} variant="dots" {...props} />
}

export { SignTrendingUpDots }
