import { Sign, type SignProps, type SignShape } from "@/registry/0db/ui/sign"

// Generated by scripts/build-signs.mjs from Lucide's contact (ISC).
const shape: SignShape = {"word":"contact","line":[[["M",3.5,3.7],["L",3.9,3.4],["L",4.3,3.1],["L",5,3],["L",19,3],["L",19.7,3.1],["L",20.3,3.5]],[["M",20.3,3.5],["L",20.8,4.1],["L",20.9,4.5],["L",21,5],["L",21,19],["L",20.9,19.7],["L",20.5,20.3]],[["M",3.7,20.5],["L",4.3,20.9],["L",5,21],["L",19,21],["L",19.5,20.9],["L",19.9,20.8],["L",20.5,20.3]],[["M",3.7,20.5],["L",3.2,19.9],["L",3.1,19.5],["L",3,19],["L",3,5],["L",3.1,4.3],["L",3.5,3.7]],[["O",12,10,3,180,180]],[["O",12,10,3,180,-180]],[["M",7.5,17.7],["L",7.9,17.4],["L",8.3,17.1],["L",9,17],["L",15.2,17],["L",15.9,17.2],["L",16.3,17.5]],[["M",16.3,17.5],["L",16.8,18.1],["L",16.9,18.5],["L",17,19],["L",17,21]],[["M",7,21],["L",7,18.8],["L",7.1,18.3],["L",7.5,17.7]],[["M",16,2],["L",16,4]],[["M",8,4],["L",8,2]]]}

/** The sign for "contact": the word ruled in leaders along its strokes. */
function SignContactDots(props: Omit<SignProps, "shape" | "variant">) {
  return <Sign shape={shape} variant="dots" {...props} />
}

export { SignContactDots }
