import { Sign, type SignProps, type SignShape } from "@/registry/0db/ui/sign"

// Generated by scripts/build-signs.mjs from Lucide's repeat (ISC).
const shape: SignShape = {"word":"repeat","fill":{"step":2.18,"rows":[[1.1,15,19],[3.3,14.6,21.2],[5.5,3.1,15.6,20.9,23.1],[7.6,1.3,22.3],[9.8,0.6,20.1],[12,1.1,22.9],[14.2,3.9,23.4],[16.4,1.7,22.7],[18.5,0.9,3.1,8.4,20.8],[20.7,2.8,9.4],[22.9,5,9]]}}

/** The sign for "repeat": the word filling its silhouette row by row. */
function SignRepeatFill(props: Omit<SignProps, "shape" | "variant">) {
  return <Sign shape={shape} variant="fill" {...props} />
}

export { SignRepeatFill }
