import { Sign, type SignProps, type SignShape } from "@/registry/0db/ui/sign"

// Generated by scripts/build-signs.mjs from Lucide's arrow-left (ISC).
const shape: SignShape = {"word":"back","line":[[["M",5,12],["L",19,12]],[["M",5,12],["L",12,19]],[["M",5,12],["L",12,5]]],"mirror":true}

/** The sign for "back": the word ruled in leaders along its strokes. */
function SignArrowLeftDots(props: Omit<SignProps, "shape" | "variant">) {
  return <Sign shape={shape} variant="dots" {...props} />
}

export { SignArrowLeftDots }
