import { Sign, type SignProps, type SignShape } from "@/registry/0db/ui/sign"

// Generated by scripts/build-signs.mjs from Lucide's aperture (ISC).
const shape: SignShape = {"word":"lens","line":[[["O",12,12,10,180,180]],[["O",12,12,10,180,-180]],[["M",9.7,8],["L",21.2,8]],[["M",2.8,16],["L",14.3,16]],[["M",14.3,8],["L",20.1,17.9]],[["M",7.4,12],["L",13.1,2.1]],[["M",4,6.1],["L",9.7,16]],[["M",10.9,21.9],["L",16.6,12]]]}

/** The sign for "lens": the word set along its strokes. */
function SignApertureWords(props: Omit<SignProps, "shape" | "variant">) {
  return <Sign shape={shape} variant="words" {...props} />
}

export { SignApertureWords }
