import { Sign, type SignProps, type SignShape } from "@/registry/0db/ui/sign"

// Generated by scripts/build-signs.mjs from Lucide's flower (ISC).
const shape: SignShape = {"word":"flower","fill":{"step":2.09,"rows":[[1.5,4.9,9.9,14.1,19.1],[3.6,2.1,21.9],[5.7,1,10.5,13.5,23],[7.8,0.6,7.2,9.7,10.6,13.4,14.3,16.8,23.4],[9.9,1.3,4.7,5.4,8,16,22.7],[12,1.8,4.2,10,14,19.7,22.3],[14.1,1.3,4.7,5.4,8,16,22.7],[16.2,0.6,7.2,9.7,10.6,13.4,14.3,16.8,23.4],[18.3,1,10.5,13.5,23],[20.4,2.1,21.9],[22.5,4.9,9.9,14.1,19.1]]}}

/** The sign for "flower": the word filling its silhouette row by row. */
function SignFlowerFill(props: Omit<SignProps, "shape" | "variant">) {
  return <Sign shape={shape} variant="fill" {...props} />
}

export { SignFlowerFill }
