import { Sign, type SignProps, type SignShape } from "@/registry/0db/ui/sign"

// Generated by scripts/build-signs.mjs from Lucide's waves (ISC).
const shape: SignShape = {"word":"sea","fill":{"step":2.1,"rows":[[2.6,7.1,11.7,17.1,21.7],[4.7,0,24],[6.8,1,8,10.9,18,21.1,22.9],[11,0.1,4.1,4.9,14,14.9,23.9],[13.1,0.1,9,9.8,19.1,19.8,23.9],[17.3,1.1,2.9,5.9,13,15.9,23],[19.4,0,24],[21.5,2.2,6.9,12.1,16.9]]}}

/** The sign for "sea": the word filling its silhouette row by row. */
function SignWavesFill(props: Omit<SignProps, "shape" | "variant">) {
  return <Sign shape={shape} variant="fill" {...props} />
}

export { SignWavesFill }
