import { Sign, type SignProps, type SignShape } from "@/registry/0db/ui/sign"

// Generated by scripts/build-signs.mjs from Lucide's folder-open (ISC).
const shape: SignShape = {"word":"open","line":[[["M",2.7,19.5],["L",3.3,19.9],["L",4,20],["L",18.5,20],["L",19.2,19.9],["L",19.8,19.5]],[["M",2.7,19.5],["L",2.2,18.9],["L",2.1,18.5],["L",2,18],["L",2,5],["L",2.1,4.3],["L",2.5,3.7]],[["M",8.1,10.4],["L",8.8,10.1],["L",9.2,10],["L",20,10],["L",20.5,10.1],["L",20.9,10.2],["L",21.5,10.7]],[["M",19.8,19.5],["L",20.2,18.9],["L",20.4,18.5],["L",21.9,12.5],["L",22,12],["L",21.9,11.5],["L",21.8,11.1],["L",21.5,10.7]],[["M",11.2,5.8],["L",11.6,5.9],["L",12.1,6],["L",18.2,6],["L",18.9,6.2],["L",19.3,6.5]],[["M",2.5,3.7],["L",3.1,3.2],["L",3.8,3],["L",7.9,3],["L",8.4,3.1],["L",8.7,3.2]],[["M",6,14],["L",7.6,10.9],["L",8.1,10.4]],[["M",19.3,6.5],["L",19.8,7.1],["L",19.9,7.5],["L",20,8],["L",20,10]],[["M",8.7,3.2],["L",9.1,3.4],["L",9.4,3.7],["L",10.5,5.3],["L",10.9,5.6],["L",11.2,5.8]]]}

/** The sign for "open": the word set along its strokes. */
function SignFolderOpenWords(props: Omit<SignProps, "shape" | "variant">) {
  return <Sign shape={shape} variant="words" {...props} />
}

export { SignFolderOpenWords }
