import { Sign, type SignProps, type SignShape } from "@/registry/0db/ui/sign"

// Generated by scripts/build-signs.mjs from Lucide's video (ISC).
const shape: SignShape = {"word":"video","fill":{"step":2.13,"rows":[[4.6,2,16],[6.7,0,18,18.5,23.9],[8.8,0,15.1,18.8,24],[10.9,0,15.1,18,24],[13.1,0,15.1,18.6,24],[15.2,0,15.1,18.9,24],[17.3,0,18,18.9,23.9],[19.4,2,16]]}}

/** The sign for "video": the word filling its silhouette row by row. */
function SignVideoFill(props: Omit<SignProps, "shape" | "variant">) {
  return <Sign shape={shape} variant="fill" {...props} />
}

export { SignVideoFill }
