import { Sign, type SignProps, type SignShape } from "@/registry/0db/ui/sign"

// Generated by scripts/build-signs.mjs from Lucide's server (ISC).
const shape: SignShape = {"word":"server","fill":{"step":2.18,"rows":[[1.1,1.3,22.8],[3.3,0,24],[5.5,0,5.1,6.9,24],[7.6,0,24],[9.8,0.3,3.7,20.3,23.7],[12,1.2,22.8],[14.2,0.3,3.7,20.3,23.8],[16.4,0,24],[18.5,0,5.1,6.9,24],[20.7,0,24],[22.9,1.2,22.7]]}}

/** The sign for "server": the word filling its silhouette row by row. */
function SignServerFill(props: Omit<SignProps, "shape" | "variant">) {
  return <Sign shape={shape} variant="fill" {...props} />
}

export { SignServerFill }
