import { Sign, type SignProps, type SignShape } from "@/registry/0db/ui/sign"

// Generated by scripts/build-signs.mjs from Lucide's navigation (ISC).
const shape: SignShape = {"word":"route","fill":{"step":2.14,"rows":[[1.1,19.4,24],[3.2,14.9,23.9],[5.3,10.5,22.9],[7.5,5.9,21.8],[9.6,1.5,20.8],[11.8,0.9,19.8],[13.9,6.7,18.8],[16,9.4,17.8],[18.2,9.9,16.8],[20.3,10.4,15.8],[22.4,11.5,14.5]]}}

/** The sign for "route": the word filling its silhouette row by row. */
function SignNavigationFill(props: Omit<SignProps, "shape" | "variant">) {
  return <Sign shape={shape} variant="fill" {...props} />
}

export { SignNavigationFill }
