import { Sign, type SignProps, type SignShape } from "@/registry/0db/ui/sign"

// Generated by scripts/build-signs.mjs from Lucide's fuel (ISC).
const shape: SignShape = {"word":"fuel","fill":{"step":2.09,"rows":[[1.5,3.2,13.8],[3.6,1,16,16.5,19.5],[5.7,0.5,12.9,15.1,21.5],[7.8,0.5,2.9,15.1,23.6],[9.9,0.5,2.7,15.1,24],[12,0.5,12.9,17.8,24],[14.1,0.5,12.9,19,24],[16.2,0.5,12.9,15.1,16.9,19.1,24],[18.3,0.5,12.9,15.1,17,19.2,23.9],[20.4,0,12.9,15.1,17.5,18,22],[22.5,0.7,16.3]]}}

/** The sign for "fuel": the word filling its silhouette row by row. */
function SignFuelFill(props: Omit<SignProps, "shape" | "variant">) {
  return <Sign shape={shape} variant="fill" {...props} />
}

export { SignFuelFill }
