import { Sign, type SignProps, type SignShape } from "@/registry/0db/ui/sign"

// Generated by scripts/build-signs.mjs from Lucide's activity (ISC).
const shape: SignShape = {"word":"pulse","fill":{"step":2.18,"rows":[[1.1,7,11],[3.3,6.1,11.9],[5.5,5.5,12.5],[7.6,4.9,13.1],[9.8,4.2,13.8],[12,0,8.1,9.6,14.4,15.9,24],[14.2,10.2,19.8],[16.4,10.9,19.1],[18.5,11.5,18.5],[20.7,12.1,17.9],[22.9,13,17]]}}

/** The sign for "pulse": the word filling its silhouette row by row. */
function SignActivityFill(props: Omit<SignProps, "shape" | "variant">) {
  return <Sign shape={shape} variant="fill" {...props} />
}

export { SignActivityFill }
