import { Sign, type SignProps, type SignShape } from "@/registry/0db/ui/sign"

// Generated by scripts/build-signs.mjs from Lucide's shopping-bag (ISC).
const shape: SignShape = {"word":"bag","fill":{"step":2.18,"rows":[[1.1,4.4,19.6],[3.3,2.5,21.5],[5.5,1,3,21,23],[7.6,0.5,4,20,23.5],[9.8,0.5,7,9.1,14.9,17,23.5],[12,0.5,7.2,10.8,13.3,16.8,23.5],[14.2,0.5,8.3,15.7,23.5],[16.4,0.5,23.5],[18.5,0.5,23.5],[20.7,0.7,23.2],[22.9,2.4,21.6]]}}

/** The sign for "bag": the word filling its silhouette row by row. */
function SignShoppingBagFill(props: Omit<SignProps, "shape" | "variant">) {
  return <Sign shape={shape} variant="fill" {...props} />
}

export { SignShoppingBagFill }
