import { Sign, type SignProps, type SignShape } from "@/registry/0db/ui/sign"

// Generated by scripts/build-signs.mjs from Lucide's flag (ISC).
const shape: SignShape = {"word":"flag","fill":{"step":2.18,"rows":[[1.1,4.1,12.4],[3.3,1.8,22.2],[5.5,1.5,22.5],[7.6,1.5,22.5],[9.8,1.5,22.5],[12,1.5,22.5],[14.2,1.5,22.3],[16.4,1.5,6.5,10.3,20.7],[18.5,1.5,6.5],[20.7,1.5,6.5],[22.9,2,6]]}}

/** The sign for "flag": the word filling its silhouette row by row. */
function SignFlagFill(props: Omit<SignProps, "shape" | "variant">) {
  return <Sign shape={shape} variant="fill" {...props} />
}

export { SignFlagFill }
