import { Sign, type SignProps, type SignShape } from "@/registry/0db/ui/sign"

// Generated by scripts/build-signs.mjs from Lucide's bell (ISC).
const shape: SignShape = {"word":"notify","fill":{"step":2.18,"rows":[[1.1,8,16],[3.3,5.4,18.6],[5.5,4.2,19.8],[7.6,3.6,20.4],[9.8,3.5,20.5],[12,3.1,20.9],[14.2,1.5,22.5],[16.4,0.7,8.8,14.9,23.3],[18.5,2.7,21.3],[20.7,8,16],[22.9,9.2,14.8]]}}

/** The sign for "notify": the word filling its silhouette row by row. */
function SignBellFill(props: Omit<SignProps, "shape" | "variant">) {
  return <Sign shape={shape} variant="fill" {...props} />
}

export { SignBellFill }
