import { Sign, type SignProps, type SignShape } from "@/registry/0db/ui/sign"

// Generated by scripts/build-signs.mjs from Lucide's file-check (ISC).
const shape: SignShape = {"word":"approve","fill":{"step":2.18,"rows":[[1.1,3.3,16.9],[3.3,1.7,13.1,14.9,19.2],[5.5,1.5,13.1,14.9,21.3],[7.6,1.5,13.1,20.1,22.4],[9.8,1.5,22.5],[12,1.5,14.1,15.8,22.5],[14.2,1.5,8.1,10.1,11.9,15.7,22.5],[16.4,1.5,8.5,13.5,22.5],[18.5,1.5,22.5],[20.7,1.7,22.3],[22.9,3.2,20.7]]}}

/** The sign for "approve": the word filling its silhouette row by row. */
function SignFileCheckFill(props: Omit<SignProps, "shape" | "variant">) {
  return <Sign shape={shape} variant="fill" {...props} />
}

export { SignFileCheckFill }
