import { Sign, type SignProps, type SignShape } from "@/registry/0db/ui/sign"

// Generated by scripts/build-signs.mjs from Lucide's copy (ISC).
const shape: SignShape = {"word":"copy","fill":{"step":2.18,"rows":[[1.1,1.2,16.8],[3.3,0,18.2],[5.5,0,18.3],[7.6,0,7.8,17.4,23.3],[9.8,0,7.1,9.3,24],[12,0,7.1,8.9,24],[14.2,0,7.1,8.9,24],[16.4,0.7,7.1,8.9,24],[18.5,5.5,24],[20.7,5.7,24],[22.9,7.2,22.7]]}}

/** The sign for "copy": the word filling its silhouette row by row. */
function SignCopyFill(props: Omit<SignProps, "shape" | "variant">) {
  return <Sign shape={shape} variant="fill" {...props} />
}

export { SignCopyFill }
