import { Sign, type SignProps, type SignShape } from "@/registry/0db/ui/sign"

// Generated by scripts/build-signs.mjs from Lucide's image (ISC).
const shape: SignShape = {"word":"image","fill":{"step":2.09,"rows":[[1.5,3,21],[3.6,1,23],[5.7,0.5,8,10,23.5],[7.8,0.5,6.2,11.8,23.5],[9.9,0.5,6.1,11.9,16.1,17,23.5],[12,0.5,7.4,10.6,13.1,19.8,23.5],[14.1,0.5,11,14.8,18.2,21.1,23.5],[16.2,0.5,8.9,12.7,23.5],[18.3,0.5,6.8,10.6,23.5],[20.4,1,6,8.5,23],[22.5,3,21]]}}

/** The sign for "image": the word filling its silhouette row by row. */
function SignImageFill(props: Omit<SignProps, "shape" | "variant">) {
  return <Sign shape={shape} variant="fill" {...props} />
}

export { SignImageFill }
