import { Sign, type SignProps, type SignShape } from "@/registry/0db/ui/sign"

// Generated by scripts/build-signs.mjs from Lucide's pause (ISC).
const shape: SignShape = {"word":"pause","fill":{"step":2.09,"rows":[[1.5,4.3,10.7,13.3,19.7],[3.6,2.7,9.3,10.7,13.3,14.7,21.3],[5.7,2.5,9.1,10.9,13.1,14.9,21.5],[7.8,2.5,9.1,10.9,13.1,14.9,21.5],[9.9,2.5,9.1,10.9,13.1,14.9,21.5],[12,2.5,9.1,10.9,13.1,14.9,21.5],[14.1,2.5,9.1,10.9,13.1,14.9,21.5],[16.2,2.5,9.1,10.9,13.1,14.9,21.5],[18.3,2.5,9.1,10.9,13.1,14.9,21.5],[20.4,2.7,9.3,10.7,13.3,14.7,21.3],[22.5,4.3,10.7,13.3,19.7]]}}

/** The sign for "pause": the word filling its silhouette row by row. */
function SignPauseFill(props: Omit<SignProps, "shape" | "variant">) {
  return <Sign shape={shape} variant="fill" {...props} />
}

export { SignPauseFill }
