import { Sign, type SignProps, type SignShape } from "@/registry/0db/ui/sign"

// Generated by scripts/build-signs.mjs from Lucide's sticky-note (ISC).
const shape: SignShape = {"word":"note","fill":{"step":2.09,"rows":[[1.5,3,17],[3.6,1,14.1,15.9,19.6],[5.7,0.5,14.1,15.9,21.6],[7.8,0.5,14.1,20.9,23.1],[9.9,0.5,14.6,21.1,23.5],[12,0.5,23.5],[14.1,0.5,23.5],[16.2,0.5,23.5],[18.3,0.5,23.5],[20.4,1,23],[22.5,3.1,21]]}}

/** The sign for "note": the word filling its silhouette row by row. */
function SignStickyNoteFill(props: Omit<SignProps, "shape" | "variant">) {
  return <Sign shape={shape} variant="fill" {...props} />
}

export { SignStickyNoteFill }
