import { Sign, type SignProps, type SignShape } from "@/registry/0db/ui/sign"

// Generated by scripts/build-signs.mjs from Lucide's mic (ISC).
const shape: SignShape = {"word":"speak","fill":{"step":2.18,"rows":[[1.1,9.1,14.9],[3.3,7.2,16.8],[5.5,6.5,17.5],[7.6,6.5,17.5],[9.8,2.7,7.9,10.1,13.9,16.1,21.3],[12,2.6,7.9,10.2,13.8,16.1,21.4],[14.2,3,8.3,15.7,21],[16.4,4,10.4,13.6,20],[18.5,5.8,10.3,13.7,18.2],[20.7,9.5,10.6,13.4,14.5],[22.9,10.1,13.9]]}}

/** The sign for "speak": the word filling its silhouette row by row. */
function SignMicFill(props: Omit<SignProps, "shape" | "variant">) {
  return <Sign shape={shape} variant="fill" {...props} />
}

export { SignMicFill }
