import { Sign, type SignProps, type SignShape } from "@/registry/0db/ui/sign"

// Generated by scripts/build-signs.mjs from Lucide's award (ISC).
const shape: SignShape = {"word":"award","line":[[["O",12,8,6,180,180]],[["O",12,8,6,180,-180]],[["M",15.5,12.9],["L",17,21.4],["L",17,21.7],["L",16.8,21.9],["L",16.7,21.9]],[["M",7.3,21.9],["L",7.2,21.9],["L",7,21.7],["L",7,21.4],["L",8.5,12.9]],[["M",12,19],["L",12.4,19.1],["L",12.6,19.2],["L",16.2,21.9],["L",16.4,22],["L",16.6,22],["L",16.7,21.9]],[["M",7.3,21.9],["L",7.4,22],["L",7.6,22],["L",7.8,21.9],["L",11.4,19.2],["L",11.6,19.1],["L",12,19]]]}

/** The sign for "award": the word set along its strokes. */
function SignAwardWords(props: Omit<SignProps, "shape" | "variant">) {
  return <Sign shape={shape} variant="words" {...props} />
}

export { SignAwardWords }
