import { Sign, type SignProps, type SignShape } from "@/registry/0db/ui/sign"

// Generated by scripts/build-signs.mjs from Lucide's monitor (ISC).
const shape: SignShape = {"word":"desktop","line":[[["M",2.5,3.7],["L",2.9,3.4],["L",3.3,3.1],["L",4,3],["L",20,3],["L",20.7,3.1],["L",21.3,3.5]],[["M",2.7,16.5],["L",3.3,16.9],["L",4,17],["L",20,17],["L",20.5,16.9],["L",20.9,16.8],["L",21.5,16.3]],[["M",21.3,3.5],["L",21.8,4.1],["L",21.9,4.5],["L",22,5],["L",22,15],["L",21.9,15.7],["L",21.5,16.3]],[["M",2.7,16.5],["L",2.2,15.9],["L",2.1,15.5],["L",2,15],["L",2,5],["L",2.1,4.3],["L",2.5,3.7]],[["M",8,21],["L",16,21]],[["M",12,17],["L",12,21]]]}

/** The sign for "desktop": the word ruled in leaders along its strokes. */
function SignMonitorDots(props: Omit<SignProps, "shape" | "variant">) {
  return <Sign shape={shape} variant="dots" {...props} />
}

export { SignMonitorDots }
