import { Sign, type SignProps, type SignShape } from "@/registry/0db/ui/sign"

// Generated by scripts/build-signs.mjs from Lucide's car (ISC).
const shape: SignShape = {"word":"car","fill":{"step":2.13,"rows":[[5.6,3.5,14],[7.7,1.3,16.6],[9.8,0.2,22.2],[11.9,0,24],[14.1,0,5,9,15,19,24],[16.2,0,4,10,14,20,24],[18.3,1.3,4.2,5.8,8.2,9.8,14.2,15.8,18.2,19.8,22.7],[20.4,5.2,8.8,15.2,18.8]]}}

/** The sign for "car": the word filling its silhouette row by row. */
function SignCarFill(props: Omit<SignProps, "shape" | "variant">) {
  return <Sign shape={shape} variant="fill" {...props} />
}

export { SignCarFill }
