import { Sign, type SignProps, type SignShape } from "@/registry/0db/ui/sign"

// Generated by scripts/build-signs.mjs from Lucide's pencil (ISC).
const shape: SignShape = {"word":"edit","line":[[["M",2.2,21.8],["L",2.1,21.8],["L",2,21.6],["L",2,21.4],["L",3.3,17],["L",3.7,16.4],["L",17.2,2.8],["L",17.6,2.5],["L",18,2.3],["L",18.5,2.1],["L",19.2,2],["L",19.7,2],["L",20.4,2.3],["L",20.8,2.5],["L",21.2,2.8]],[["M",2.2,21.8],["L",2.2,21.9],["L",2.4,22],["L",2.6,22],["L",7,20.7],["L",7.6,20.3],["L",21.2,6.8],["L",21.5,6.4],["L",21.7,6],["L",22,5.3],["L",22,4.8]],[["M",15,5],["L",19,9]],[["M",21.2,2.8],["L",21.6,3.3],["L",21.8,3.9],["L",22,4.3],["L",22,4.8]]]}

/** The sign for "edit": the word set along its strokes. */
function SignPencilWords(props: Omit<SignProps, "shape" | "variant">) {
  return <Sign shape={shape} variant="words" {...props} />
}

export { SignPencilWords }
