import { Sign, type SignProps, type SignShape } from "@/registry/0db/ui/sign"

// Generated by scripts/build-signs.mjs from Lucide's beer (ISC).
const shape: SignShape = {"word":"beer","fill":{"step":2.18,"rows":[[1.1,5,5.7,8.2,13.8,16.3,17],[3.3,1.4,20.6],[5.5,0.6,21.4],[7.6,1.4,4.4,18.2,20.7],[9.8,2.5,16.1,18.4,20.5],[12,2.5,8.1,9.9,12.1,13.9,16.1,18.5,22.7],[14.2,2.5,8.1,9.9,12.1,13.9,16.1,17.9,23.4],[16.4,2.5,8.1,9.9,12.1,13.9,16.1,18.1,22.5],[18.5,2.5,8.1,9.9,12.1,13.9,16.2,17.8,19.6],[20.7,2.7,19.2],[22.9,4.3,17.8]]}}

/** The sign for "beer": the word filling its silhouette row by row. */
function SignBeerFill(props: Omit<SignProps, "shape" | "variant">) {
  return <Sign shape={shape} variant="fill" {...props} />
}

export { SignBeerFill }
