import { Sign, type SignProps, type SignShape } from "@/registry/0db/ui/sign"

// Generated by scripts/build-signs.mjs from Lucide's apple (ISC).
const shape: SignShape = {"word":"apple","fill":{"step":2.18,"rows":[[1.1,10.7,14.9],[3.3,6.6,9.4,9.6,11.2,12.8,17.1],[5.5,2.3,9.4,15.4,21.7],[7.6,0.6,10.9,13.1,23.4],[9.8,0,24],[12,0,24],[14.2,0,24],[16.4,0.6,23.4],[18.5,1.6,22.4],[20.7,3,21.1],[22.9,5,11.2,12.8,19]]}}

/** The sign for "apple": the word filling its silhouette row by row. */
function SignAppleFill(props: Omit<SignProps, "shape" | "variant">) {
  return <Sign shape={shape} variant="fill" {...props} />
}

export { SignAppleFill }
