import { Sign, type SignProps, type SignShape } from "@/registry/0db/ui/sign"

// Generated by scripts/build-signs.mjs from Lucide's clipboard (ISC).
const shape: SignShape = {"word":"clip","line":[[["M",19.3,4.5],["L",19.8,5.1],["L",19.9,5.5],["L",20,6],["L",20,20],["L",19.9,20.7],["L",19.5,21.3]],[["M",4.7,21.5],["L",4.2,20.9],["L",4.1,20.5],["L",4,20],["L",4,6],["L",4.1,5.3],["L",4.5,4.7]],[["M",4.7,21.5],["L",5.3,21.9],["L",6,22],["L",18,22],["L",18.5,21.9],["L",18.9,21.8],["L",19.5,21.3]],[["M",8.3,5.7],["L",8.6,5.9],["L",9,6],["L",15,6],["L",15.4,5.9],["L",15.7,5.7]],[["M",8.3,2.3],["L",8.6,2.1],["L",9,2],["L",15,2],["L",15.4,2.1],["L",15.7,2.3]],[["M",4.5,4.7],["L",5.1,4.2],["L",5.5,4.1],["L",6,4],["L",8,4]],[["M",15.7,2.3],["L",15.9,2.6],["L",16,3],["L",16,5],["L",15.9,5.4],["L",15.7,5.7]],[["M",8.3,5.7],["L",8.1,5.4],["L",8,5],["L",8,3],["L",8.1,2.6],["L",8.3,2.3]],[["M",16,4],["L",18.2,4],["L",18.9,4.2],["L",19.3,4.5]]]}

/** The sign for "clip": the word ruled in leaders along its strokes. */
function SignClipboardDots(props: Omit<SignProps, "shape" | "variant">) {
  return <Sign shape={shape} variant="dots" {...props} />
}

export { SignClipboardDots }
