import { Sign, type SignProps, type SignShape } from "@/registry/0db/ui/sign"

// Generated by scripts/build-signs.mjs from Lucide's sofa (ISC).
const shape: SignShape = {"word":"sofa","fill":{"step":2.1,"rows":[[2.6,4.2,19.8],[4.7,2,10.9,13.1,21.9],[6.8,1.5,10.9,13.1,22.5],[8.9,0.6,3,6.7,10.9,13.1,17.4,21,23.5],[11,0,4.6,7.1,10.9,13.1,16.9,19.4,24],[13.1,0,4.9,19.1,24],[15.2,0,24],[17.3,0,2.5,6.2,17.8,21.5,24],[19.4,1.5,2.7,6.1,17.9,21.3,22.5],[21.5,2.7,5.3,18.7,21.3]]}}

/** The sign for "sofa": the word filling its silhouette row by row. */
function SignSofaFill(props: Omit<SignProps, "shape" | "variant">) {
  return <Sign shape={shape} variant="fill" {...props} />
}

export { SignSofaFill }
