import { Sign, type SignProps, type SignShape } from "@/registry/0db/ui/sign"

// Generated by scripts/build-signs.mjs from Lucide's shuffle (ISC).
const shape: SignShape = {"word":"shuffle","fill":{"step":2.18,"rows":[[1.1,16,20],[3.3,15.6,22.2],[5.5,0,7.9,12.2,16.9,21.9,24],[7.6,0.9,9.7,10.2,23.3],[9.8,6.5,10.1,12.1,21.1],[12,7.5,20.1],[14.2,6.1,21.1],[16.4,0.9,9.8,10.2,23.3],[18.5,0,7.8,12.2,16.9,21.9,24],[20.7,15.6,22.2],[22.9,16,20]]}}

/** The sign for "shuffle": the word filling its silhouette row by row. */
function SignShuffleFill(props: Omit<SignProps, "shape" | "variant">) {
  return <Sign shape={shape} variant="fill" {...props} />
}

export { SignShuffleFill }
