import { Sign, type SignProps, type SignShape } from "@/registry/0db/ui/sign"

// Generated by scripts/build-signs.mjs from Lucide's chart-column (ISC).
const shape: SignShape = {"word":"chart","line":[[["M",3.5,20.3],["L",4.1,20.8],["L",4.5,20.9],["L",5,21],["L",21,21]],[["M",3.5,20.3],["L",3.1,19.7],["L",3,19],["L",3,3]],[["M",13,5],["L",13,17]],[["M",18,9],["L",18,17]],[["M",8,17],["L",8,14]]]}

/** The sign for "chart": the word ruled in leaders along its strokes. */
function SignChartDots(props: Omit<SignProps, "shape" | "variant">) {
  return <Sign shape={shape} variant="dots" {...props} />
}

export { SignChartDots }
