import { Sign, type SignProps, type SignShape } from "@/registry/0db/ui/sign"

// Generated by scripts/build-signs.mjs from Lucide's bed (ISC).
const shape: SignShape = {"word":"sleep","fill":{"step":2.1,"rows":[[2.6,0.5,3.5],[4.7,0,4.5],[6.8,0,2.2,3.5,22.3],[8.9,0,1.9,3.8,5.1,6.9,24],[11,0,5.1,6.9,24],[13.1,0,5.1,6.9,24],[15.2,0,5.1,6.9,24],[17.3,0,1.9,3.8,5.2,6.8,20.2,22.1,24],[19.4,0,4.5,19.5,24],[21.5,0.5,3.5,20.5,23.5]]}}

/** The sign for "sleep": the word filling its silhouette row by row. */
function SignBedFill(props: Omit<SignProps, "shape" | "variant">) {
  return <Sign shape={shape} variant="fill" {...props} />
}

export { SignBedFill }
