import { Sign, type SignProps, type SignShape } from "@/registry/0db/ui/sign"

// Generated by scripts/build-signs.mjs from Lucide's bot (ISC).
const shape: SignShape = {"word":"bot","line":[[["M",4.5,8.7],["L",4.9,8.4],["L",5.3,8.1],["L",6,8],["L",18,8],["L",18.7,8.1],["L",19.3,8.5]],[["M",4.7,19.5],["L",5.3,19.9],["L",6,20],["L",18,20],["L",18.5,19.9],["L",18.9,19.8],["L",19.5,19.3]],[["M",19.3,8.5],["L",19.8,9.1],["L",19.9,9.5],["L",20,10],["L",20,18],["L",19.9,18.7],["L",19.5,19.3]],[["M",4.7,19.5],["L",4.2,18.9],["L",4.1,18.5],["L",4,18],["L",4,10],["L",4.1,9.3],["L",4.5,8.7]],[["M",12,4],["L",12,8]],[["M",8,4],["L",12,4]],[["M",2,14],["L",4,14]],[["M",20,14],["L",22,14]],[["M",15,13],["L",15,15]],[["M",9,15],["L",9,13]]]}

/** The sign for "bot": the word set along its strokes. */
function SignBotWords(props: Omit<SignProps, "shape" | "variant">) {
  return <Sign shape={shape} variant="words" {...props} />
}

export { SignBotWords }
