import { Sign, type SignProps, type SignShape } from "@/registry/0db/ui/sign"

// Generated by scripts/build-signs.mjs from a drawing made for 0dB.
const shape: SignShape = {"word":"mail","fill":{"step":1.49,"rows":[[5.2,3.1,20.9],[6.7,5.1,18.9],[8.2,1.5,2.2,7.1,16.9,21.8,22.5],[9.7,1.5,4.2,9.1,14.9,19.8,22.5],[11.2,1.5,6.1,11.1,12.9,17.9,22.5],[12.7,1.5,7.9,16.1,22.5],[14.2,1.5,9.9,14.1,22.5],[15.7,1.5,11.8,12.2,22.5],[17.2,1.5,22.5],[18.7,1.5,22.5]]}}

/** The sign for "mail": the word filling its silhouette row by row. */
function SignMailFill(props: Omit<SignProps, "shape" | "variant">) {
  return <Sign shape={shape} variant="fill" {...props} />
}

export { SignMailFill }
