import { Sign, type SignProps, type SignShape } from "@/registry/0db/ui/sign"

// Generated by scripts/build-signs.mjs from Lucide's gem (ISC).
const shape: SignShape = {"word":"gem","line":[[["M",2,9],["L",22,9]],[["M",12,22],["L",12.5,21.9],["L",12.9,21.8],["L",13.3,21.5],["L",13.6,21.2],["L",21.6,10.2],["L",21.9,9.6],["L",22,8.9]],[["M",2,9.1],["L",2.2,9.8],["L",2.4,10.2],["L",10.4,21.2],["L",10.7,21.5],["L",11.1,21.8],["L",11.5,21.9],["L",12,22]],[["M",8,9],["L",12,22]],[["M",12,22],["L",16,9]],[["M",6.1,3.2],["L",6.5,3.1],["L",7,3],["L",17,3],["L",17.5,3.1],["L",17.9,3.2]],[["M",2,9.1],["L",2.1,8.4],["L",2.4,7.8],["L",5.4,3.8],["L",5.7,3.5],["L",6.1,3.2]],[["M",17.9,3.2],["L",18.3,3.5],["L",18.6,3.8],["L",21.6,7.8],["L",21.9,8.3],["L",22,8.9]],[["M",8,9],["L",10.5,3]],[["M",13.5,3],["L",16,9]]]}

/** The sign for "gem": the word set along its strokes. */
function SignGemWords(props: Omit<SignProps, "shape" | "variant">) {
  return <Sign shape={shape} variant="words" {...props} />
}

export { SignGemWords }
