import { Sign, type SignProps, type SignShape } from "@/registry/0db/ui/sign"

// Generated by scripts/build-signs.mjs from Lucide's chevron-right (ISC).
const shape: SignShape = {"word":"after","fill":{"step":2.13,"rows":[[4.6,7.5,10.5],[6.7,6.9,12.6],[8.8,8.9,14.7],[10.9,11,16.8],[13.1,11,16.8],[15.2,8.9,14.7],[17.3,6.9,12.6],[19.4,7.5,10.5]]},"mirror":true}

/** The sign for "after": the word filling its silhouette row by row. */
function SignChevronRightFill(props: Omit<SignProps, "shape" | "variant">) {
  return <Sign shape={shape} variant="fill" {...props} />
}

export { SignChevronRightFill }
