import { Sign, type SignProps, type SignShape } from "@/registry/0db/ui/sign"

// Generated by scripts/build-signs.mjs from Lucide's calendar-plus (ISC).
const shape: SignShape = {"word":"event","fill":{"step":2.14,"rows":[[1.1,6.1,7.1,8.9,9.9,14.1,15.1,16.9,17.9],[3.2,1.2,6.3,9.7,14.3,17.7,22.8],[5.3,0.6,6.9,9.1,14.9,17.1,23.4],[7.5,0.5,3.3,20.7,23.5],[9.6,0.5,2.7,21.3,23.5],[11.8,0.5,23.3],[13.9,0.5,21.4],[16,0.5,18,20,21.5],[18.2,0.5,17,21,24],[20.3,1,15.7,16.5,18.2,19.8,21.5],[22.4,3.2,14.6,17.7,20.3]]}}

/** The sign for "event": the word filling its silhouette row by row. */
function SignCalendarPlusFill(props: Omit<SignProps, "shape" | "variant">) {
  return <Sign shape={shape} variant="fill" {...props} />
}

export { SignCalendarPlusFill }
