import { Sign, type SignProps, type SignShape } from "@/registry/0db/ui/sign"

// Generated by scripts/build-signs.mjs from Lucide's chevron-left (ISC).
const shape: SignShape = {"word":"before","line":[[["M",9,12],["L",15,18]],[["M",9,12],["L",15,6]]],"mirror":true}

/** The sign for "before": the word ruled in leaders along its strokes. */
function SignChevronLeftDots(props: Omit<SignProps, "shape" | "variant">) {
  return <Sign shape={shape} variant="dots" {...props} />
}

export { SignChevronLeftDots }
