import { Sign, type SignProps, type SignShape } from "@/registry/0db/ui/sign"

// Generated by scripts/build-signs.mjs from Lucide's align-center (ISC).
const shape: SignShape = {"word":"centre","fill":{"step":2.11,"rows":[[3.6,1.7,22.3],[5.7,0.9,23.1],[12,4.6,19.4],[18.3,2.9,21.1],[20.4,3.7,20.3]]}}

/** The sign for "centre": the word filling its silhouette row by row. */
function SignAlignCenterFill(props: Omit<SignProps, "shape" | "variant">) {
  return <Sign shape={shape} variant="fill" {...props} />
}

export { SignAlignCenterFill }
