import { Sign, type SignProps, type SignShape } from "@/registry/0db/ui/sign"

// Generated by scripts/build-signs.mjs from a drawing made for 0dB.
const shape: SignShape = {"word":"mail","line":[[["M",3,6],["L",21,6]],[["M",3,18],["L",21,18]],[["M",21,6],["L",21,18]],[["M",3,6],["L",3,18]],[["M",4,7.5],["L",12,13.2]],[["M",12,13.2],["L",20,7.5]]]}

/** The sign for "mail": the word set along its strokes. */
function SignMailWords(props: Omit<SignProps, "shape" | "variant">) {
  return <Sign shape={shape} variant="words" {...props} />
}

export { SignMailWords }
