import { Sign, type SignProps, type SignShape } from "@/registry/0db/ui/sign"

// Generated by scripts/build-signs.mjs from Lucide's bookmark (ISC).
const shape: SignShape = {"word":"bookmark","line":[[["M",18.3,3.5],["L",18.8,4.1],["L",18.9,4.5],["L",19,5],["L",19,20],["L",18.9,20.4],["L",18.6,20.8]],[["M",5.6,20.9],["L",5.2,20.6],["L",5.1,20.4],["L",5,20],["L",5,5],["L",5.1,4.3],["L",5.5,3.7]],[["M",5.5,3.7],["L",5.9,3.4],["L",6.3,3.1],["L",7,3],["L",17,3],["L",17.7,3.1],["L",18.3,3.5]],[["M",12.1,18],["L",12.6,18.1],["L",13,18.3],["L",17.5,20.9],["L",17.9,21],["L",18.4,20.9],["L",18.6,20.8]],[["M",5.6,20.9],["L",6.1,21],["L",6.5,20.9],["L",11,18.3],["L",11.7,18.1],["L",12.1,18]]]}

/** The sign for "bookmark": the word ruled in leaders along its strokes. */
function SignBookmarkDots(props: Omit<SignProps, "shape" | "variant">) {
  return <Sign shape={shape} variant="dots" {...props} />
}

export { SignBookmarkDots }
