import { Sign, type SignProps, type SignShape } from "@/registry/0db/ui/sign"

// Generated by scripts/build-signs.mjs from a drawing made for 0nlyType.
const shape: SignShape = {"word":"close","fill":{"step":1.98,"rows":[[3.1,5.5,6.4,17.6,18.5],[5.1,3.5,8.4,15.6,20.5],[7,3.7,10.4,13.6,20.3],[9,5.7,18.3],[11,7.7,16.3],[13,7.7,16.3],[15,5.7,18.3],[16.9,3.7,10.4,13.6,20.3],[18.9,3.5,8.4,15.6,20.5],[20.9,5.6,6.4,17.6,18.5]]}}

/** The sign for "close": the word filling its silhouette row by row. */
function SignCloseFill(props: Omit<SignProps, "shape" | "variant">) {
  return <Sign shape={shape} variant="fill" {...props} />
}

export { SignCloseFill }
