import { Sign, type SignProps, type SignShape } from "@/registry/0db/ui/sign"

// Generated by scripts/build-signs.mjs from Lucide's heart (ISC).
const shape: SignShape = {"word":"love","fill":{"step":2,"rows":[[2.5,5.1,9.9,14.1,19.2],[4.5,1.8,22.2],[6.5,0.4,23.6],[8.5,0,24],[10.5,0,24],[12.5,0.4,23.6],[14.5,1.8,22.2],[16.5,3.6,20.4],[18.5,5.7,18.3],[20.5,7.8,16.2],[22.5,10.2,13.8]]}}

/** The sign for "love": the word filling its silhouette row by row. */
function SignHeartFill(props: Omit<SignProps, "shape" | "variant">) {
  return <Sign shape={shape} variant="fill" {...props} />
}

export { SignHeartFill }
