import { Sign, type SignProps, type SignShape } from "@/registry/0db/ui/sign"

// Generated by scripts/build-signs.mjs from Lucide's skip-forward (ISC).
const shape: SignShape = {"word":"skip","line":[[["M",21,4],["L",21,20]],[["M",3.9,19.7],["L",4.4,19.9],["L",4.8,20],["L",5.3,20],["L",5.6,19.9],["L",6,19.7],["L",16.2,13.6],["L",16.7,13],["L",16.9,12.6],["L",17,12.1]],[["M",4.1,4.2],["L",4.4,4.1],["L",4.8,4],["L",5.3,4],["L",5.8,4.2],["L",16,10.3],["L",16.6,10.8],["L",16.8,11.2],["L",17,11.6],["L",17,12.1]],[["M",3,12],["L",3,5.8],["L",3.1,5.3],["L",3.4,4.8],["L",3.7,4.5],["L",4.1,4.2]],[["M",3,12],["L",3,18.2],["L",3.1,18.5],["L",3.2,19],["L",3.5,19.4],["L",3.9,19.7]]]}

/** The sign for "skip": the word ruled in leaders along its strokes. */
function SignSkipForwardDots(props: Omit<SignProps, "shape" | "variant">) {
  return <Sign shape={shape} variant="dots" {...props} />
}

export { SignSkipForwardDots }
