import { Sign, type SignProps, type SignShape } from "@/registry/0db/ui/sign"

// Generated by scripts/build-signs.mjs from Lucide's funnel (ISC).
const shape: SignShape = {"word":"filter","line":[[["M",2.1,3.6],["L",2.4,3.2],["L",2.8,3],["L",3,3],["L",21,3],["L",21.4,3.1],["L",21.8,3.4],["L",21.9,3.6]],[["M",14.1,13.3],["L",14.5,12.7],["L",21.7,4.7],["L",22,4.3],["L",22,3.8],["L",21.9,3.6]],[["M",2.1,3.6],["L",2,4],["L",2,4.3],["L",2.3,4.7],["L",9.5,12.7],["L",9.9,13.3]],[["M",14.1,13.3],["L",14,14],["L",14,21],["L",13.9,21.4],["L",13.6,21.8],["L",13.4,21.9]],[["M",10.2,20.5],["L",10,20.2],["L",10,20],["L",10,14],["L",9.9,13.3]],[["M",10.2,20.5],["L",10.4,20.8],["L",10.6,20.9],["L",12.6,21.9],["L",13,22],["L",13.4,21.9]]]}

/** The sign for "filter": the word ruled in leaders along its strokes. */
function SignFilterDots(props: Omit<SignProps, "shape" | "variant">) {
  return <Sign shape={shape} variant="dots" {...props} />
}

export { SignFilterDots }
