import { Sign, type SignProps, type SignShape } from "@/registry/0db/ui/sign"

// Generated by scripts/build-signs.mjs from Lucide's crosshair (ISC).
const shape: SignShape = {"word":"aim","fill":{"step":2.18,"rows":[[1.1,7.2,16.8],[3.3,3.7,11.1,12.9,20.3],[5.5,1.8,11.1,12.9,22.2],[7.6,0.6,23.4],[9.8,0,24],[12,0,2.1,6.7,17.3,21.7,24],[14.2,0,24],[16.4,0.6,23.4],[18.5,1.8,11.1,12.9,22.2],[20.7,3.7,11.1,12.9,20.3],[22.9,7.2,16.8]]}}

/** The sign for "aim": the word filling its silhouette row by row. */
function SignCrosshairFill(props: Omit<SignProps, "shape" | "variant">) {
  return <Sign shape={shape} variant="fill" {...props} />
}

export { SignCrosshairFill }
