import { Sign, type SignProps, type SignShape } from "@/registry/0db/ui/sign"

// Generated by scripts/build-signs.mjs from Lucide's cast (ISC).
const shape: SignShape = {"word":"cast","fill":{"step":2.1,"rows":[[2.6,2,22],[4.7,0,24],[6.8,0,24],[8.9,0,24],[11,0.1,2.6,3.8,24],[13.1,0.1,2.3,7.7,24],[15.2,0,2.5,3.7,6.1,9.4,24],[17.3,0.3,2.2,6.1,8,10.4,24],[19.4,0,4.6,6.5,8.9,10.7,24],[21.5,0.5,3.5,4.5,7.5,8.5,11.5,12.5,22]]}}

/** The sign for "cast": the word filling its silhouette row by row. */
function SignCastFill(props: Omit<SignProps, "shape" | "variant">) {
  return <Sign shape={shape} variant="fill" {...props} />
}

export { SignCastFill }
