import { Sign, type SignProps, type SignShape } from "@/registry/0db/ui/sign"

// Generated by scripts/build-signs.mjs from Lucide's dog (ISC).
const shape: SignShape = {"word":"dog","fill":{"step":2.09,"rows":[[1.5,5,9.4,14.9,19.3],[3.6,2.5,9,11.6,12.7,15.1,21.8],[5.7,1.3,8.7,15.5,23],[7.8,0.5,7.4,9.5,14.9,17,23.7],[9.9,0.1,3.1,9.3,15.1,20.8,24],[12,1.5,2.9,7.6,16.6,21.1,22.7],[14.1,1.6,6.5,9.5,14.5,17.5,22.4],[16.2,1.8,7.3,8.7,10.3,13.8,15.3,16.7,22.2],[18.3,2.7,11.1,12.9,21.3],[20.4,4.4,19.6],[22.5,8.7,15.1]]}}

/** The sign for "dog": the word filling its silhouette row by row. */
function SignDogFill(props: Omit<SignProps, "shape" | "variant">) {
  return <Sign shape={shape} variant="fill" {...props} />
}

export { SignDogFill }
