import { Sign, type SignProps, type SignShape } from "@/registry/0db/ui/sign"

// Generated by scripts/build-signs.mjs from Lucide's castle (ISC).
const shape: SignShape = {"word":"castle","fill":{"step":2.09,"rows":[[1.5,4.5,7.5,8.5,11.5,12.5,15.5,16.5,19.5],[3.6,3.5,6.4,17.6,20.5],[5.7,3.5,5.9,18.1,20.5],[7.8,0.3,5.1,6.9,17.1,18.9,23.7],[9.9,0,2,22,24],[12,0,2,22,24],[14.1,0,10,14,24],[16.2,0,8.3,15.7,24],[18.3,0,8.1,10,14,15.9,24],[20.4,0,8.1,9.9,14.1,15.9,24],[22.5,2,22]]}}

/** The sign for "castle": the word filling its silhouette row by row. */
function SignCastleFill(props: Omit<SignProps, "shape" | "variant">) {
  return <Sign shape={shape} variant="fill" {...props} />
}

export { SignCastleFill }
