import { Sign, type SignProps, type SignShape } from "@/registry/0db/ui/sign"

// Generated by scripts/build-signs.mjs from Lucide's gift (ISC).
const shape: SignShape = {"word":"gift","fill":{"step":2.14,"rows":[[1.1,4.5,10.7,13.3,19.4],[3.2,2.9,10.3,11.7,12.4,13.7,21.1],[5.3,2.5,4.5,6.7,10.2,13.9,17.3,19.5,21.5],[7.5,0.7,3.9,19.9,23.2],[9.6,0.6,3.9,20.1,23.4],[11.8,1.4,3.4,20.6,22.6],[13.9,1.5,11.1,12.9,22.5],[16,1.5,11.1,12.9,22.5],[18.2,1.5,11.1,12.9,22.5],[20.3,2,11.1,12.9,22],[22.4,4,20]]}}

/** The sign for "gift": the word filling its silhouette row by row. */
function SignGiftFill(props: Omit<SignProps, "shape" | "variant">) {
  return <Sign shape={shape} variant="fill" {...props} />
}

export { SignGiftFill }
