import { Sign, type SignProps, type SignShape } from "@/registry/0db/ui/sign"

// Generated by scripts/build-signs.mjs from Lucide's pill (ISC).
const shape: SignShape = {"word":"dose","line":[[["M",2,17.1],["L",2.1,16.1],["L",2.3,15.3],["L",2.7,14.5],["L",3.3,13.7],["L",13.7,3.3],["L",14.3,2.9],["L",14.9,2.5],["L",15.4,2.3],["L",16.1,2.1],["L",16.6,2],["L",17.3,2],["L",18.1,2.1],["L",18.5,2.2],["L",19.2,2.5],["L",19.7,2.8],["L",20.1,3.1],["L",20.6,3.6],["L",20.9,3.9],["L",21.4,4.6],["L",21.7,5.2],["L",21.8,5.7],["L",22,6.4],["L",22,7.1]],[["M",2,17.1],["L",2.1,17.7],["L",2.2,18.3],["L",2.3,18.8],["L",2.6,19.4],["L",3.1,20.1],["L",3.4,20.4],["L",3.9,20.9],["L",4.3,21.2],["L",5,21.6],["L",5.5,21.8],["L",6.2,21.9],["L",6.7,22],["L",7.3,22],["L",7.9,21.9],["L",8.4,21.8],["L",9.1,21.5],["L",9.7,21.1],["L",10.3,20.7],["L",20.7,10.3],["L",21.1,9.7],["L",21.6,8.9],["L",21.9,7.9],["L",22,7.1]],[["M",8.5,8.5],["L",15.5,15.5]]]}

/** The sign for "dose": the word ruled in leaders along its strokes. */
function SignPillDots(props: Omit<SignProps, "shape" | "variant">) {
  return <Sign shape={shape} variant="dots" {...props} />
}

export { SignPillDots }
