import { Sign, type SignProps, type SignShape } from "@/registry/0db/ui/sign"

// Generated by scripts/build-signs.mjs from a drawing made for 0dB.
const shape: SignShape = {"word":"close","line":[[["M",5,19],["L",19,5]],[["M",5,5],["L",12,12]],[["M",12,12],["L",19,19]]]}

/** The sign for "close": the word set along its strokes. */
function SignCloseWords(props: Omit<SignProps, "shape" | "variant">) {
  return <Sign shape={shape} variant="words" {...props} />
}

export { SignCloseWords }
