import { Sign, type SignProps, type SignShape } from "@/registry/0db/ui/sign"

// Generated by scripts/build-signs.mjs from Lucide's mic (ISC).
const shape: SignShape = {"word":"speak","fill":{"step":2.18,"rows":[[1.1,8.9,15],[3.3,7.1,16.9],[5.5,6.5,17.5],[7.6,6.5,17.5],[9.8,2.7,8.1,9.9,14.1,15.9,21.3],[12,2.6,8.1,10,14,15.9,21.4],[14.2,3,8.5,15.5,21],[16.4,4,11.1,12.9,20],[18.5,5.8,10.9,13.1,18.2],[20.7,9.5,11.3,12.7,14.5],[22.9,10,14]]}}

/** The sign for "speak": the word filling its silhouette row by row. */
function SignMicFill(props: Omit<SignProps, "shape" | "variant">) {
  return <Sign shape={shape} variant="fill" {...props} />
}

export { SignMicFill }
