import { Sign, type SignProps, type SignShape } from "@/registry/0db/ui/sign"

// Generated by scripts/build-signs.mjs from Lucide's paperclip (ISC).
const shape: SignShape = {"word":"attach","fill":{"step":2.18,"rows":[[1.1,12.6,19.4],[3.3,10.2,21.6],[5.5,8.2,14.7,16.9,22.4],[7.6,6,12.6,16.3,22.1],[9.8,3.8,10.5,14.1,16,19.4,21.7],[12,1.9,8.3,12,13.9,17.5,24],[14.2,0.9,6.4,9.8,11.7,15.4,22.1],[16.4,0.6,6.1,8.6,9.4,13.2,19.9],[18.5,1.2,6.9,11.1,17.7],[20.7,2.4,15.6],[22.9,5.2,13]]}}

/** The sign for "attach": the word filling its silhouette row by row. */
function SignPaperclipFill(props: Omit<SignProps, "shape" | "variant">) {
  return <Sign shape={shape} variant="fill" {...props} />
}

export { SignPaperclipFill }
