import { Sign, type SignProps, type SignShape } from "@/registry/0db/ui/sign"

// Generated by scripts/build-signs.mjs from Lucide's sprout (ISC).
const shape: SignShape = {"word":"grow","fill":{"step":2.09,"rows":[[1.5,15.7,21.2],[3.6,12.8,22.4],[5.7,11.9,22.3],[7.8,2.3,13.2,14.8,21.4],[9.9,1.7,10.3,12.3,13.2,14.8,19.3],[12,2.5,10.7,12.7,14.6],[14.1,4.1,10.1,12.1,14.5],[16.2,10.3,15.1],[18.3,10.5,15.4],[20.4,2.9,21.1],[22.5,3.5,20.5]]}}

/** The sign for "grow": the word filling its silhouette row by row. */
function SignSproutFill(props: Omit<SignProps, "shape" | "variant">) {
  return <Sign shape={shape} variant="fill" {...props} />
}

export { SignSproutFill }
