import { Sign, type SignProps, type SignShape } from "@/registry/0db/ui/sign"

// Generated by scripts/build-signs.mjs from Lucide's skip-forward (ISC).
const shape: SignShape = {"word":"skip","fill":{"step":2.1,"rows":[[2.6,3,6.9,19.5,22.5],[4.7,1,10.5,18.5,23.5],[6.8,0.5,14,18.5,23.5],[8.9,0.5,17.5,18.5,23.5],[11,0.5,16.2,17.8,23.5],[13.1,0.5,16.2,17.8,23.5],[15.2,0.5,17.5,18.5,23.5],[17.3,0.5,14,18.5,23.5],[19.4,0.9,10.5,18.5,23.5],[21.5,3,6.9,19.5,22.5]]}}

/** The sign for "skip": the word filling its silhouette row by row. */
function SignSkipForwardFill(props: Omit<SignProps, "shape" | "variant">) {
  return <Sign shape={shape} variant="fill" {...props} />
}

export { SignSkipForwardFill }
