import { Sign, type SignProps, type SignShape } from "@/registry/0db/ui/sign"

// Generated by scripts/build-signs.mjs from Lucide's banknote (ISC).
const shape: SignShape = {"word":"cash","fill":{"step":2.13,"rows":[[4.6,2,22],[6.7,0,24],[8.8,0,10.8,13.2,24],[10.9,0,5.3,6.7,9.1,14.9,17.3,18.7,24],[13.1,0,5.3,6.7,9.1,14.9,17.3,18.7,24],[15.2,0,10.8,13.2,24],[17.3,0,24],[19.4,2,22]]}}

/** The sign for "cash": the word filling its silhouette row by row. */
function SignBanknoteFill(props: Omit<SignProps, "shape" | "variant">) {
  return <Sign shape={shape} variant="fill" {...props} />
}

export { SignBanknoteFill }
