import { Sign, type SignProps, type SignShape } from "@/registry/0db/ui/sign"

// Generated by scripts/build-signs.mjs from Lucide's history (ISC).
const shape: SignShape = {"word":"history","fill":{"step":2.09,"rows":[[1.5,1.5,4.5,8.6,15.4],[3.6,0.5,19.2],[5.7,0.5,3.4,6,11.5,12.5,21.2],[7.8,0.6,2.8,8.8,11.1,12.9,22.4],[9.9,1,11.1,12.9,23.1],[12,0.6,11.1,15.2,23.5],[14.1,0.9,13,16.7,23.1],[16.2,1.7,22.4],[18.3,2.8,21.1],[20.4,4.7,19.2],[22.5,8.6,15.5]]}}

/** The sign for "history": the word filling its silhouette row by row. */
function SignHistoryFill(props: Omit<SignProps, "shape" | "variant">) {
  return <Sign shape={shape} variant="fill" {...props} />
}

export { SignHistoryFill }
