import { Sign, type SignProps, type SignShape } from "@/registry/0db/ui/sign"

// Generated by scripts/build-signs.mjs from Lucide's align-right (ISC).
const shape: SignShape = {"word":"right","line":[[["M",3,5],["L",21,5]],[["M",7,19],["L",21,19]],[["M",9,12],["L",21,12]]]}

/** The sign for "right": the word set along its strokes. */
function SignAlignRightWords(props: Omit<SignProps, "shape" | "variant">) {
  return <Sign shape={shape} variant="words" {...props} />
}

export { SignAlignRightWords }
