import { Sign, type SignProps, type SignShape } from "@/registry/0db/ui/sign"

// Generated by scripts/build-signs.mjs from Lucide's eye-off (ISC).
const shape: SignShape = {"word":"hide","fill":{"step":2.18,"rows":[[1.1,0,4],[3.3,0.4,6.2,10,14.2],[5.5,2.6,5.6,6.2,19.4],[7.6,2.1,4.8,9.5,21.9],[9.8,0.5,7.9,11.7,23.5],[12,0,8.2,13.9,24],[14.2,0.6,8.5,16.1,23.4],[16.4,2.2,11.3,12.5,14.5,18.2,21.6],[18.5,4.6,16.6,18.2,21.4],[20.7,9.7,14.4,17.8,23.6],[22.9,20,24]]}}

/** The sign for "hide": the word filling its silhouette row by row. */
function SignEyeOffFill(props: Omit<SignProps, "shape" | "variant">) {
  return <Sign shape={shape} variant="fill" {...props} />
}

export { SignEyeOffFill }
