import { Sign, type SignProps, type SignShape } from "@/registry/0db/ui/sign"

// Generated by scripts/build-signs.mjs from Lucide's layers (ISC).
const shape: SignShape = {"word":"layers","fill":{"step":2.18,"rows":[[1.1,8.9,15.1],[3.3,4.1,19.9],[5.5,0.3,23.7],[7.6,0,2.6,5.4,18.6,21.4,24],[9.8,0.3,3.4,10.2,13.8,20.6,23.7],[12,0,3,4,8.2,15.8,20,21,24],[14.2,0.9,2.7,8.9,15.1,21.3,23.1],[16.4,0,6.9,17.1,24],[18.5,0.3,23.7],[20.7,4.1,19.9],[22.9,8.9,15.1]]}}

/** The sign for "layers": the word filling its silhouette row by row. */
function SignLayersFill(props: Omit<SignProps, "shape" | "variant">) {
  return <Sign shape={shape} variant="fill" {...props} />
}

export { SignLayersFill }
