import { Sign, type SignProps, type SignShape } from "@/registry/0db/ui/sign"

// Generated by scripts/build-signs.mjs from Lucide's cloud-rain (ISC).
const shape: SignShape = {"word":"rain","fill":{"step":2.14,"rows":[[1.6,6.1,12.1],[3.7,2.5,15.5],[5.8,0.9,17.2],[8,0,22.2],[10.1,0,23.7],[12.3,0,24],[14.4,1,7.1,8.9,15.1,16.9,24],[16.5,2.9,5.1,5.5,7.4,8.6,11.1,12.9,15.1,16.9,22.7],[18.7,5.5,11.1,12.9,18.5],[20.8,6,11.1,12.9,18],[22.9,10,14]]}}

/** The sign for "rain": the word filling its silhouette row by row. */
function SignCloudRainFill(props: Omit<SignProps, "shape" | "variant">) {
  return <Sign shape={shape} variant="fill" {...props} />
}

export { SignCloudRainFill }
