import { Sign, type SignProps, type SignShape } from "@/registry/0db/ui/sign"

// Generated by scripts/build-signs.mjs from a drawing made for 0nlyType.
const shape: SignShape = {"word":"search","line":[[["O",10,10,6.5,180,180]],[["O",10,10,6.5,180,-180]],[["M",15.6,15.6],["L",21.5,21.5]]]}

/** The sign for "search": the word ruled in leaders along its strokes. */
function SignSearchDots(props: Omit<SignProps, "shape" | "variant">) {
  return <Sign shape={shape} variant="dots" {...props} />
}

export { SignSearchDots }
