import { Sign, type SignProps, type SignShape } from "@/registry/0db/ui/sign"

// Generated by scripts/build-signs.mjs from Lucide's lamp (ISC).
const shape: SignShape = {"word":"lamp","fill":{"step":2.18,"rows":[[1.1,6.3,17.7],[3.3,4.8,19.2],[5.5,3.9,20.1],[7.6,2.9,21.1],[9.8,2,22],[12,2,9.9,14.1,22],[14.2,9.5,11.1,12.9,14.5],[16.4,8.6,10.5,13.5,15.2],[18.5,6.1,10.2,13.6,17.9],[20.7,5.6,18.4],[22.9,6.7,17.3]]}}

/** The sign for "lamp": the word filling its silhouette row by row. */
function SignLampFill(props: Omit<SignProps, "shape" | "variant">) {
  return <Sign shape={shape} variant="fill" {...props} />
}

export { SignLampFill }
