import { Sign, type SignProps, type SignShape } from "@/registry/0db/ui/sign"

// Generated by scripts/build-signs.mjs from Lucide's timer-reset (ISC).
const shape: SignShape = {"word":"reset","fill":{"step":2.18,"rows":[[1.1,8,16],[3.3,8.4,15.6],[5.5,6.9,10.1,13.9,16.9],[7.6,4.2,19.8],[9.8,2.7,11.1,12.9,21.3],[12,1.8,11.1,12.9,22.1],[14.2,2.3,11.1,12.9,22.4],[16.4,1.9,4.1,9.9,22],[18.5,1.5,3.9,7.1,21],[20.7,1.5,5.5,7.2,19.6],[22.9,2,6,7.6,16.5]]}}

/** The sign for "reset": the word filling its silhouette row by row. */
function SignTimerResetFill(props: Omit<SignProps, "shape" | "variant">) {
  return <Sign shape={shape} variant="fill" {...props} />
}

export { SignTimerResetFill }
