import { Sign, type SignProps, type SignShape } from "@/registry/0db/ui/sign"

// Generated by scripts/build-signs.mjs from Lucide's cloud-lightning (ISC).
const shape: SignShape = {"word":"storm","fill":{"step":2.14,"rows":[[1.6,6.5,11.6],[3.7,2.5,15.5],[5.8,0.9,17.2],[8,0,22.2],[10.1,0,23.7],[12.3,0,11.2,14,24],[14.4,1,10,13.2,24],[16.5,2.8,9.3,14.2,22.6],[18.7,9.1,11.4,13.2,15.5,17.1,19],[20.8,9.2,14.2],[22.9,9.1,12.9]]}}

/** The sign for "storm": the word filling its silhouette row by row. */
function SignCloudLightningFill(props: Omit<SignProps, "shape" | "variant">) {
  return <Sign shape={shape} variant="fill" {...props} />
}

export { SignCloudLightningFill }
