import { Sign, type SignProps, type SignShape } from "@/registry/0db/ui/sign"

// Generated by scripts/build-signs.mjs from Lucide's trending-up (ISC).
const shape: SignShape = {"word":"rise","fill":{"step":2.14,"rows":[[5.6,14.5,23.5],[7.7,13.9,19.4,22,24],[9.9,6.2,10.8,15.1,18.4,21,24],[12,4.1,12.9,14.1,24],[14.1,2,7.8,9.2,17.8,20.2,23.8],[16.3,0,5.6,11.4,15.6],[18.4,0.5,3.5]]}}

/** The sign for "rise": the word filling its silhouette row by row. */
function SignTrendingUpFill(props: Omit<SignProps, "shape" | "variant">) {
  return <Sign shape={shape} variant="fill" {...props} />
}

export { SignTrendingUpFill }
