import { Sign, type SignProps, type SignShape } from "@/registry/0db/ui/sign"

// Generated by scripts/build-signs.mjs from Lucide's flame (ISC).
const shape: SignShape = {"word":"fire","fill":{"step":2.14,"rows":[[1.6,10.5,13.5],[3.7,8.5,14.6],[5.8,7.3,15.6],[8,7.3,17.3],[10.1,7.6,9.9,11.7,19.5],[12.3,3.3,5.3,7.1,9.9,11.9,20.8],[14.4,2.7,5.7,11.4,21.3],[16.5,2.8,21.2],[18.7,3.6,20.4],[20.8,5,19],[22.9,7.8,16.2]]}}

/** The sign for "fire": the word filling its silhouette row by row. */
function SignFlameFill(props: Omit<SignProps, "shape" | "variant">) {
  return <Sign shape={shape} variant="fill" {...props} />
}

export { SignFlameFill }
