import { Sign, type SignProps, type SignShape } from "@/registry/0db/ui/sign"

// Generated by scripts/build-signs.mjs from Lucide's chart-column (ISC).
const shape: SignShape = {"word":"chart","fill":{"step":2.09,"rows":[[1.5,1.7,4.3],[3.6,0.5,5.5,11.5,14.5],[5.7,0.5,5.5,10.5,15.5],[7.8,0.5,5.5,10.5,15.5,16.3,19.7],[9.9,0.5,5.5,10.5,20.5],[12,0.5,5.5,10.5,20.5],[14.1,0.5,7.1,8.9,12,14,20.5],[16.2,0.5,6.9,9.1,11.9,14.1,20.5],[18.3,0.5,7.2,8.8,12.2,13.8,20.1],[20.4,1,23.1],[22.5,3.3,22.3]]}}

/** The sign for "chart": the word filling its silhouette row by row. */
function SignChartFill(props: Omit<SignProps, "shape" | "variant">) {
  return <Sign shape={shape} variant="fill" {...props} />
}

export { SignChartFill }
