import { Sign, type SignProps, type SignShape } from "@/registry/0db/ui/sign"

// Generated by scripts/build-signs.mjs from Lucide's watch (ISC).
const shape: SignShape = {"word":"watch","line":[[["O",12,12,6,180,180]],[["O",12,12,6,180,-180]],[["M",14.6,2.4],["L",15,2.9],["L",15.3,3.4],["L",16.1,7.7]],[["M",9.4,21.5],["L",10,21.9],["L",10.7,22],["L",13.6,22],["L",14.2,21.8],["L",14.7,21.5]],[["M",7.9,7.7],["L",8.7,3.4],["L",9,2.9],["L",9.3,2.4]],[["M",14.7,21.5],["L",15.1,21],["L",15.3,20.6],["L",16.2,16.3]],[["M",9.3,2.4],["L",9.7,2.2],["L",10.2,2],["L",11,2],["L",13.6,2],["L",14.2,2.2],["L",14.6,2.4]],[["M",7.9,16.4],["L",8.7,20.6],["L",9.1,21.2],["L",9.4,21.5]],[["M",12,10],["L",12,12.2]],[["M",12,12.2],["L",13.6,13.2]]]}

/** The sign for "watch": the word ruled in leaders along its strokes. */
function SignWatchDots(props: Omit<SignProps, "shape" | "variant">) {
  return <Sign shape={shape} variant="dots" {...props} />
}

export { SignWatchDots }
