import { Sign, type SignProps, type SignShape } from "@/registry/0db/ui/sign"

// Generated by scripts/build-signs.mjs from Lucide's file-text (ISC).
const shape: SignShape = {"word":"text","fill":{"step":2.18,"rows":[[1.1,3.3,16.9],[3.3,1.7,13.1,14.9,19.2],[5.5,1.5,13.1,14.9,21.3],[7.6,1.5,7.7,10.3,13.1,20.1,22.4],[9.8,1.5,7.1,10.9,22.5],[12,1.5,7.2,16.8,22.5],[14.2,1.5,7.3,16.7,22.5],[16.4,1.5,7.1,16.9,22.5],[18.5,1.5,22.5],[20.7,1.7,22.3],[22.9,3.2,20.7]]}}

/** The sign for "text": the word filling its silhouette row by row. */
function SignFileTextFill(props: Omit<SignProps, "shape" | "variant">) {
  return <Sign shape={shape} variant="fill" {...props} />
}

export { SignFileTextFill }
