import { Sign, type SignProps, type SignShape } from "@/registry/0db/ui/sign"

// Generated by scripts/build-signs.mjs from Lucide's door-open (ISC).
const shape: SignShape = {"word":"door","line":[[["M",10.3,21.7],["L",10.1,21.5],["L",10,21],["L",10,3],["L",10,2.8],["L",10.1,2.5],["L",10.4,2.2]],[["M",5,21],["L",5,5],["L",5.1,4.3],["L",5.4,3.9],["L",5.7,3.5]],[["M",18.5,3.7],["L",18.9,4.3],["L",19,5],["L",19,21]],[["M",10.3,21.7],["L",10.6,21.9],["L",11.1,22],["L",19,21]],[["M",10.4,2.2],["L",10.7,2.1],["L",10.9,2],["L",11.2,2],["L",17.3,3],["L",18,3.3],["L",18.5,3.7]],[["M",2,21],["L",10,21]],[["M",5.7,3.5],["L",6.3,3.1],["L",6.8,3],["L",10,3]],[["M",19,21],["L",22,21]],[["M",14,12],["L",14,12]]]}

/** The sign for "door": the word ruled in leaders along its strokes. */
function SignDoorOpenDots(props: Omit<SignProps, "shape" | "variant">) {
  return <Sign shape={shape} variant="dots" {...props} />
}

export { SignDoorOpenDots }
