import { Sign, type SignProps, type SignShape } from "@/registry/0db/ui/sign"

// Generated by scripts/build-signs.mjs from Lucide's notebook (ISC).
const shape: SignShape = {"word":"notes","fill":{"step":2.18,"rows":[[1.1,3.3,20.8],[3.3,1.7,15.1,16.9,22.2],[5.5,0,2.6,6.9,15.1,16.9,22.5],[7.6,0.3,3.1,4.9,15.1,16.9,22.5],[9.8,0,2.2,6.8,15.1,16.9,22.5],[12,0,3.1,4.9,15.1,16.9,22.5],[14.2,0,2.2,6.8,15.1,16.9,22.5],[16.4,0.3,3.1,4.9,15.1,16.9,22.5],[18.5,0,2.6,6.9,15.1,16.9,22.5],[20.7,1.7,15.1,16.9,22.3],[22.9,3.2,20.7]]}}

/** The sign for "notes": the word filling its silhouette row by row. */
function SignNotebookFill(props: Omit<SignProps, "shape" | "variant">) {
  return <Sign shape={shape} variant="fill" {...props} />
}

export { SignNotebookFill }
