import { Sign, type SignProps, type SignShape } from "@/registry/0db/ui/sign"

// Generated by scripts/build-signs.mjs from Lucide's bus (ISC).
const shape: SignShape = {"word":"bus","fill":{"step":2.11,"rows":[[4.6,2.2,19.8],[6.7,0,6.9,9.1,13.9,16.1,22.2],[8.8,0,6.9,9.1,13.9,16.1,23],[10.9,0,1.8,21.8,23.6],[13,0,1.8,21.8,24],[15.1,0,5,9,14,18,24],[17.2,0,4,10,13,19,23.6],[19.3,0.5,4.2,5.8,8.2,9.8,13.2,14.8,17.2,18.8,22.5],[21.4,5.2,8.8,14.2,17.8]]}}

/** The sign for "bus": the word filling its silhouette row by row. */
function SignBusFill(props: Omit<SignProps, "shape" | "variant">) {
  return <Sign shape={shape} variant="fill" {...props} />
}

export { SignBusFill }
