import { Sign, type SignProps, type SignShape } from "@/registry/0db/ui/sign"

// Generated by scripts/build-signs.mjs from Lucide's newspaper (ISC).
const shape: SignShape = {"word":"news","fill":{"step":2.18,"rows":[[1.1,5.3,22.7],[3.3,3.7,24],[5.5,3.5,9.4,18.6,24],[7.6,2.1,4.9,6.9,9.1,10.9,17.1,18.9,24],[9.8,0,4.4,6.9,9.1,18.9,24],[12,0,5.1,6.9,24],[14.2,0,5.1,6.9,9.2,18.8,24],[16.4,0,5.1,6.9,24],[18.5,0,5.1,6.9,9.1,15.9,24],[20.7,0,4.7,6.9,24],[22.9,1.2,22.8]]}}

/** The sign for "news": the word filling its silhouette row by row. */
function SignNewspaperFill(props: Omit<SignProps, "shape" | "variant">) {
  return <Sign shape={shape} variant="fill" {...props} />
}

export { SignNewspaperFill }
