import { Sign, type SignProps, type SignShape } from "@/registry/0db/ui/sign"

// Generated by scripts/build-signs.mjs from Lucide's calendar-plus (ISC).
const shape: SignShape = {"word":"event","fill":{"step":2.14,"rows":[[1.1,5,19],[3.2,1.3,7,9,15,17,22.7],[5.3,0.6,7.1,8.9,15.1,16.9,23.4],[7.5,0.5,23.5],[9.6,0.5,2.8,21.1,23.5],[11.8,0.5,23.3],[13.9,0.5,21.4],[16,0.5,18.2,19.8,21.5],[18.2,0.5,17.2,20.8,24],[20.3,1,15.7,16.5,18.5,19.5,21.5],[22.4,3,14.8,17.5,20.5]]}}

/** The sign for "event": the word filling its silhouette row by row. */
function SignCalendarPlusFill(props: Omit<SignProps, "shape" | "variant">) {
  return <Sign shape={shape} variant="fill" {...props} />
}

export { SignCalendarPlusFill }
