import { Sign, type SignProps, type SignShape } from "@/registry/0db/ui/sign"

// Generated by scripts/build-signs.mjs from Lucide's ship (ISC).
const shape: SignShape = {"word":"ship","fill":{"step":2.14,"rows":[[1.1,10,14],[3.2,4.1,10.4,13.6,19.8],[5.3,2.8,10.7,13.3,21.2],[7.5,2.5,21.5],[9.6,2.5,7.2,16.8,21.5],[11.8,1.3,4.2,9.3,11.1,12.9,14.7,19.8,22.7],[13.9,0.6,11.2,12.8,23.4],[16,1,23],[18.2,1.2,3.5,5.4,22.9],[20.3,0,3.9,6,24],[22.4,2.1,6.9,12.1,16.9]]}}

/** The sign for "ship": the word filling its silhouette row by row. */
function SignShipFill(props: Omit<SignProps, "shape" | "variant">) {
  return <Sign shape={shape} variant="fill" {...props} />
}

export { SignShipFill }
