import { Sign, type SignProps, type SignShape } from "@/registry/0db/ui/sign"

// Generated by scripts/build-signs.mjs from Lucide's underline (ISC).
const shape: SignShape = {"word":"underline","fill":{"step":2.1,"rows":[[2.6,4.7,7.3,16.7,19.3],[4.7,3.5,8.5,15.5,20.5],[6.8,3.5,8.5,15.5,20.5],[8.9,3.5,8.5,15.5,20.5],[11,3.7,8.5,15.5,20.3],[13.1,4.4,9.4,14.6,19.6],[15.2,5.8,18.2],[17.3,7.7,16.4],[19.4,1.9,22.1],[21.5,2.7,21.3]]}}

/** The sign for "underline": the word filling its silhouette row by row. */
function SignUnderlineFill(props: Omit<SignProps, "shape" | "variant">) {
  return <Sign shape={shape} variant="fill" {...props} />
}

export { SignUnderlineFill }
