import { Sign, type SignProps, type SignShape } from "@/registry/0db/ui/sign"

// Generated by scripts/build-signs.mjs from Lucide's globe (ISC).
const shape: SignShape = {"word":"world","fill":{"step":2.18,"rows":[[1.1,7.2,16.8],[3.3,3.7,9.4,14.6,20.3],[5.5,1.8,8.3,10.9,13.1,15.7,22.2],[7.6,0.6,7.6,9.9,14.1,16.4,23.4],[9.8,0,7.2,9.2,14.8,16.8,24],[12,0,2.1,21.7,24],[14.2,0,7.2,9.2,14.8,16.8,24],[16.4,0.6,7.6,9.9,14.1,16.4,23.4],[18.5,1.8,8.3,10.9,13.1,15.7,22.2],[20.7,3.7,9.4,14.6,20.3],[22.9,7.2,16.8]]}}

/** The sign for "world": the word filling its silhouette row by row. */
function SignGlobeFill(props: Omit<SignProps, "shape" | "variant">) {
  return <Sign shape={shape} variant="fill" {...props} />
}

export { SignGlobeFill }
