import { Sign, type SignProps, type SignShape } from "@/registry/0db/ui/sign"

// Generated by scripts/build-signs.mjs from Lucide's activity (ISC).
const shape: SignShape = {"word":"pulse","line":[[["M",9,2],["L",9.1,2],["L",9.2,2.2],["L",14.8,21.8],["L",14.9,22],["L",15,22]],[["M",15,22],["L",15.1,22],["L",15.2,21.8],["L",17.7,13.2],["L",18,12.7],["L",18.4,12.3]],[["M",5.8,11.5],["L",6.1,11.2],["L",6.4,10.5],["L",8.8,2.2],["L",8.9,2],["L",9,2]],[["M",2,12],["L",4.7,12],["L",5.2,11.9],["L",5.8,11.5]],[["M",18.4,12.3],["L",18.8,12.1],["L",19.3,12],["L",22,12]]]}

/** The sign for "pulse": the word ruled in leaders along its strokes. */
function SignActivityDots(props: Omit<SignProps, "shape" | "variant">) {
  return <Sign shape={shape} variant="dots" {...props} />
}

export { SignActivityDots }
