import { Sign, type SignProps, type SignShape } from "@/registry/0db/ui/sign"

// Generated by scripts/build-signs.mjs from Lucide's wrench (ISC).
const shape: SignShape = {"word":"repair","fill":{"step":2.18,"rows":[[1.1,12.4,19.4],[3.3,9.5,15.6,18.3,20.4],[5.5,8.2,13.6,17.7,19.4,21.1,23.7],[7.6,7.6,13.4,21.3,24],[9.8,7.7,14.7,19.3,24],[12,6.2,23],[14.2,4,21.1],[16.4,1.8,13.5],[18.5,0,11.2],[20.7,0,9],[22.9,1.4,6.7]]}}

/** The sign for "repair": the word filling its silhouette row by row. */
function SignWrenchFill(props: Omit<SignProps, "shape" | "variant">) {
  return <Sign shape={shape} variant="fill" {...props} />
}

export { SignWrenchFill }
