import { Sign, type SignProps, type SignShape } from "@/registry/0db/ui/sign"

// Generated by scripts/build-signs.mjs from Lucide's bell-off (ISC).
const shape: SignShape = {"word":"snooze","fill":{"step":2.18,"rows":[[1.1,0,4,8,16],[3.3,0.4,18.6],[5.5,2.6,5.8,7.4,19.8],[7.6,3.5,5.8,9.5,20.4],[9.8,3.5,7.9,11.7,20.5],[12,3,10.1,13.9,21.1],[14.2,1.5,12.3,16.1,22],[16.4,0.7,8.8,17.1,20.5],[18.5,2.7,21.4],[20.7,8,16,17.8,23.6],[22.9,9.2,14.8,20,24]]}}

/** The sign for "snooze": the word filling its silhouette row by row. */
function SignBellOffFill(props: Omit<SignProps, "shape" | "variant">) {
  return <Sign shape={shape} variant="fill" {...props} />
}

export { SignBellOffFill }
