import { Sign, type SignProps, type SignShape } from "@/registry/0db/ui/sign"

// Generated by scripts/build-signs.mjs from Lucide's box (ISC).
const shape: SignShape = {"word":"box","fill":{"step":2.18,"rows":[[1.1,9.2,14.8],[3.3,5.3,18.7],[5.5,1.8,22.1],[7.6,0.7,3.1,7.1,16.9,20.9,23.3],[9.8,0.5,5.4,11,13,18.6,23.5],[12,0.5,9.2,14.8,23.5],[14.2,0.5,11.1,12.9,23.5],[16.4,0.7,11.1,12.9,23.3],[18.5,1.8,11.1,12.9,22.2],[20.7,5.3,11.1,12.9,18.7],[22.9,9.2,14.8]]}}

/** The sign for "box": the word filling its silhouette row by row. */
function SignBoxFill(props: Omit<SignProps, "shape" | "variant">) {
  return <Sign shape={shape} variant="fill" {...props} />
}

export { SignBoxFill }
