import { Sign, type SignProps, type SignShape } from "@/registry/0db/ui/sign"

// Generated by scripts/build-signs.mjs from Lucide's clock (ISC).
const shape: SignShape = {"word":"time","line":[[["O",12,12,10,180,180]],[["O",12,12,10,180,-180]],[["M",12,6],["L",12,12]],[["M",12,12],["L",16,14]]]}

/** The sign for "time": the word set along its strokes. */
function SignClockWords(props: Omit<SignProps, "shape" | "variant">) {
  return <Sign shape={shape} variant="words" {...props} />
}

export { SignClockWords }
