import { Sign, type SignProps, type SignShape } from "@/registry/0db/ui/sign"

// Generated by scripts/build-signs.mjs from Lucide's bus (ISC).
const shape: SignShape = {"word":"bus","line":[[["M",2,12],["L",21.6,12]],[["M",2.7,6.5],["L",3.3,6.1],["L",4,6],["L",18,6],["L",18.7,6.1],["L",19.1,6.3],["L",19.5,6.5]],[["M",2,18],["L",2,8],["L",2.1,7.3],["L",2.4,6.9],["L",2.7,6.5]],[["M",19.5,6.5],["L",19.8,6.8],["L",20.1,7.2],["L",20.4,7.8],["L",21.8,12.8],["L",22,13.5],["L",22,14]],[["O",7,18,2,180,180]],[["O",7,18,2,180,-180]],[["O",16,18,2,180,180]],[["O",16,18,2,180,-180]],[["M",8,12],["L",8,6]],[["M",15,6],["L",15,12]],[["M",9,18],["L",14,18]],[["M",21,18],["L",21.8,15.2],["L",22,14.5],["L",22,14]],[["M",18,18],["L",21,18]],[["M",2,18],["L",5,18]]]}

/** The sign for "bus": the word ruled in leaders along its strokes. */
function SignBusDots(props: Omit<SignProps, "shape" | "variant">) {
  return <Sign shape={shape} variant="dots" {...props} />
}

export { SignBusDots }
