import { Sign, type SignProps, type SignShape } from "@/registry/0db/ui/sign"

// Generated by scripts/build-signs.mjs from Lucide's navigation (ISC).
const shape: SignShape = {"word":"route","line":[[["M",3,11],["L",22,2]],[["M",13,21],["L",22,2]],[["M",11,13],["L",13,21]],[["M",3,11],["L",11,13]]]}

/** The sign for "route": the word ruled in leaders along its strokes. */
function SignNavigationDots(props: Omit<SignProps, "shape" | "variant">) {
  return <Sign shape={shape} variant="dots" {...props} />
}

export { SignNavigationDots }
