import { Sign, type SignProps, type SignShape } from "@/registry/0db/ui/sign"

// Generated by scripts/build-signs.mjs from Lucide's credit-card (ISC).
const shape: SignShape = {"word":"card","fill":{"step":2.11,"rows":[[3.6,2,22],[5.7,0,24],[7.8,0,24],[9.9,0,2,22,24],[12,0,24],[14.1,0,5.3,8.7,24],[16.2,0,24],[18.3,0,24],[20.4,2,22]]}}

/** The sign for "card": the word filling its silhouette row by row. */
function SignCreditCardFill(props: Omit<SignProps, "shape" | "variant">) {
  return <Sign shape={shape} variant="fill" {...props} />
}

export { SignCreditCardFill }
