import { Sign, type SignProps, type SignShape } from "@/registry/0db/ui/sign"

// Generated by scripts/build-signs.mjs from Lucide's volume-1 (ISC).
const shape: SignShape = {"word":"soft","line":[[["M",10.6,19.9],["L",10.8,19.7],["L",11,19.5],["L",11,19.3],["L",11,4.7],["L",11,4.5],["L",10.8,4.3],["L",10.6,4.1]],[["M",2.3,15.7],["L",2.1,15.4],["L",2,15],["L",2,9],["L",2.1,8.6],["L",2.3,8.3]],[["M",6,7.9],["L",6.4,7.6],["L",9.8,4.2],["L",10,4.1],["L",10.2,4],["L",10.6,4.1]],[["M",6,16.1],["L",6.4,16.4],["L",9.8,19.8],["L",10,19.9],["L",10.2,20],["L",10.6,19.9]],[["M",2.3,15.7],["L",2.6,15.9],["L",3,16],["L",5.4,16],["L",6,16.1]],[["M",2.3,8.3],["L",2.6,8.1],["L",3,8],["L",5.4,8],["L",6,7.9]],[["M",16,9],["L",16.4,9.6],["L",16.7,10.4],["L",16.9,11.3],["L",17,12]],[["M",16,15],["L",16.4,14.4],["L",16.7,13.6],["L",16.9,12.7],["L",17,12]]]}

/** The sign for "soft": the word set along its strokes. */
function SignVolumeLowWords(props: Omit<SignProps, "shape" | "variant">) {
  return <Sign shape={shape} variant="words" {...props} />
}

export { SignVolumeLowWords }
