import { Sign, type SignProps, type SignShape } from "@/registry/0db/ui/sign"

// Generated by scripts/build-signs.mjs from Lucide's shopping-cart (ISC).
const shape: SignShape = {"word":"cart","line":[[["M",4.6,5],["L",21,5],["L",21.4,5.1],["L",21.8,5.4]],[["M",3.8,2.2],["L",4,2.5],["L",4.2,2.8],["L",6.8,17.2],["L",7,17.5],["L",7.2,17.8]],[["M",6.3,14],["L",19,14],["L",19.2,14],["L",19.7,13.9],["L",20,13.7],["L",20.3,13.5]],[["M",7.2,17.8],["L",7.4,17.9],["L",7.8,18],["L",18,18]],[["M",21.8,5.4],["L",22,5.8],["L",22,6.2],["L",21,12.4],["L",20.8,12.9],["L",20.7,13.1],["L",20.3,13.5]],[["O",18,20,2,180,180]],[["O",18,20,2,180,-180]],[["O",8,20,2,180,180]],[["O",8,20,2,180,-180]],[["M",2.1,2.1],["L",3.4,2],["L",3.8,2.2]]]}

/** The sign for "cart": the word set along its strokes. */
function SignShoppingCartWords(props: Omit<SignProps, "shape" | "variant">) {
  return <Sign shape={shape} variant="words" {...props} />
}

export { SignShoppingCartWords }
