import { Sign, type SignProps, type SignShape } from "@/registry/0db/ui/sign"

// Generated by scripts/build-signs.mjs from Lucide's train-front (ISC).
const shape: SignShape = {"word":"train","fill":{"step":2.18,"rows":[[1.1,7.6,16.4],[3.3,4.5,7.1,8.9,15.1,16.9,19.5],[5.5,2.9,7.1,8.9,15.1,16.9,21],[7.6,2,7.1,9.2,14.8,16.9,22],[9.8,1.6,7.6,16.3,22.4],[12,1.5,10,14.1,22.5],[14.2,1.6,7.2,9.9,14.1,16.8,22.4],[16.4,2.2,8.7,9.3,14.7,15.3,21.8],[18.5,3.6,6.5,8.6,15.4,17.5,20.4],[20.7,4.3,19.7],[22.9,4,8,16,20]]}}

/** The sign for "train": the word filling its silhouette row by row. */
function SignTrainFill(props: Omit<SignProps, "shape" | "variant">) {
  return <Sign shape={shape} variant="fill" {...props} />
}

export { SignTrainFill }
