import { Sign, type SignProps, type SignShape } from "@/registry/0db/ui/sign"

// Generated by scripts/build-signs.mjs from Lucide's layout-grid (ISC).
const shape: SignShape = {"word":"tiles","fill":{"step":2.09,"rows":[[1.5,2.3,10.7,13.3,21.7],[3.6,0.7,9.3,10.7,13.3,14.7,23.3],[5.7,0.5,9.1,10.9,13.1,14.9,23.5],[7.8,0.5,9.1,10.9,13.1,14.9,23.5],[9.9,0.9,4,10.9,13.1,20,23.1],[12,1.5,22.5],[14.1,0.9,4,10.9,13.1,20,23.1],[16.2,0.5,9.1,10.9,13.1,14.9,23.5],[18.3,0.5,9.1,10.9,13.1,14.9,23.5],[20.4,0.7,9.3,10.7,13.3,14.7,23.3],[22.5,2.3,10.7,13.3,21.7]]}}

/** The sign for "tiles": the word filling its silhouette row by row. */
function SignLayoutGridFill(props: Omit<SignProps, "shape" | "variant">) {
  return <Sign shape={shape} variant="fill" {...props} />
}

export { SignLayoutGridFill }
