import { Sign, type SignProps, type SignShape } from "@/registry/0db/ui/sign"

// Generated by scripts/build-signs.mjs from Lucide's book-open (ISC).
const shape: SignShape = {"word":"read","line":[[["M",12,5],["L",12,21]],[["M",21.5,3.7],["L",21.9,4.3],["L",22,5],["L",22,17],["L",21.9,17.5],["L",21.8,17.9],["L",21.3,18.5]],[["M",2.5,18.3],["L",2.1,17.7],["L",2,17],["L",2,5],["L",2.1,4.5],["L",2.2,4.1],["L",2.7,3.5]],[["M",2.5,18.3],["L",3.1,18.8],["L",3.8,19],["L",8.2,19],["L",8.7,19.1],["L",9.4,19.2],["L",10.1,19.5],["L",10.8,19.8],["L",11.3,20.3],["L",12,21]],[["M",12,5],["L",12.7,4.3],["L",13.4,3.7],["L",14.3,3.3],["L",15.3,3.1],["L",16,3],["L",20.2,3],["L",20.9,3.2],["L",21.5,3.7]],[["M",12,21],["L",12.5,20.4],["L",13.2,19.8],["L",13.9,19.5],["L",14.8,19.1],["L",15.8,19],["L",20.2,19],["L",20.7,18.9],["L",21.3,18.5]],[["M",2.7,3.5],["L",3.1,3.2],["L",3.8,3],["L",8,3],["L",8.7,3.1],["L",9.7,3.3],["L",10.6,3.7],["L",11.3,4.3],["L",12,5]]]}

/** The sign for "read": the word set along its strokes. */
function SignBookOpenWords(props: Omit<SignProps, "shape" | "variant">) {
  return <Sign shape={shape} variant="words" {...props} />
}

export { SignBookOpenWords }
