import { Sign, type SignProps, type SignShape } from "@/registry/0db/ui/sign"

// Generated by scripts/build-signs.mjs from Lucide's bot (ISC).
const shape: SignShape = {"word":"bot","fill":{"step":2.1,"rows":[[2.6,6.7,13.3],[4.7,5.9,14.5],[6.8,3.8,6.9,13.9,20.2],[8.9,1.9,6.7,14,22.1],[11,1.5,22.5],[13.1,0.1,1.8,5.5,7.9,10.1,13.9,16.1,18.5,22,23.9],[15.2,0.3,1.8,5.4,7.9,10.1,13.9,16.1,18.6,21.9,23.7],[17.3,1.5,22.5],[19.4,2,22],[21.5,4.2,19.8]]}}

/** The sign for "bot": the word filling its silhouette row by row. */
function SignBotFill(props: Omit<SignProps, "shape" | "variant">) {
  return <Sign shape={shape} variant="fill" {...props} />
}

export { SignBotFill }
