import { Sign, type SignProps, type SignShape } from "@/registry/0db/ui/sign"

// Generated by scripts/build-signs.mjs from Lucide's crop (ISC).
const shape: SignShape = {"word":"crop","fill":{"step":2.18,"rows":[[1.1,4,8],[3.3,3.5,8.5],[5.5,0,4.1,7.9,19.1],[7.6,0.9,5.1,6.9,20.3],[9.8,3.5,20.5],[12,3.5,20.5],[14.2,3.5,20.5],[16.4,3.7,17.1,18.9,23.1],[18.5,4.9,16.1,19.9,24],[20.7,15.5,20.5],[22.9,16,20]]}}

/** The sign for "crop": the word filling its silhouette row by row. */
function SignCropFill(props: Omit<SignProps, "shape" | "variant">) {
  return <Sign shape={shape} variant="fill" {...props} />
}

export { SignCropFill }
