import { Sign, type SignProps, type SignShape } from "@/registry/0db/ui/sign"

// Generated by scripts/build-signs.mjs from Lucide's globe (ISC).
const shape: SignShape = {"word":"world","fill":{"step":2.18,"rows":[[1.1,7.4,16.6],[3.3,3.8,9.2,14.8,20.2],[5.5,1.8,8.2,11.1,12.9,15.8,22.2],[7.6,0.6,7.4,10.1,13.9,16.6,23.4],[9.8,0,7.1,9.4,14.6,16.9,24],[12,0,1.7,22.1,24],[14.2,0,7.1,9.4,14.6,16.9,24],[16.4,0.6,7.4,10.1,13.9,16.6,23.4],[18.5,1.8,8.2,11.1,12.9,15.8,22.2],[20.7,3.8,9.2,14.8,20.2],[22.9,7.4,16.6]]}}

/** The sign for "world": the word filling its silhouette row by row. */
function SignGlobeFill(props: Omit<SignProps, "shape" | "variant">) {
  return <Sign shape={shape} variant="fill" {...props} />
}

export { SignGlobeFill }
