import { Sign, type SignProps, type SignShape } from "@/registry/0db/ui/sign"

// Generated by scripts/build-signs.mjs from Lucide's shopping-basket (ISC).
const shape: SignShape = {"word":"basket","line":[[["M",2,11],["L",22,11]],[["M",4.5,15.5],["L",19.5,15.5]],[["M",5.8,19.6],["L",6.4,19.9],["L",7.1,20],["L",17.1,20],["L",17.8,19.8],["L",18.2,19.6]],[["M",15,11],["L",14,20]],[["M",10,20],["L",9,11]],[["M",18.2,19.6],["L",18.5,19.2],["L",18.8,18.6],["L",20.6,11]],[["M",3.5,11],["L",5.2,18.6],["L",5.4,19],["L",5.8,19.6]],[["M",15,4],["L",19,11]],[["M",5,11],["L",9,4]]]}

/** The sign for "basket": the word ruled in leaders along its strokes. */
function SignShoppingBasketDots(props: Omit<SignProps, "shape" | "variant">) {
  return <Sign shape={shape} variant="dots" {...props} />
}

export { SignShoppingBasketDots }
