import { Sign, type SignProps, type SignShape } from "@/registry/0db/ui/sign"

// Generated by scripts/build-signs.mjs from Lucide's send (ISC).
const shape: SignShape = {"word":"send","line":[[["M",15,22],["L",15.1,22],["L",15.3,21.9],["L",15.5,21.7],["L",22,2.7],["L",22,2.4],["L",21.9,2.2],["L",21.8,2.2]],[["M",2,9],["L",2,8.9],["L",2.1,8.7],["L",2.3,8.5],["L",21.3,2],["L",21.6,2],["L",21.8,2.1],["L",21.8,2.2]],[["M",10.9,13.1],["L",21.9,2.1]],[["M",10.9,13.1],["L",11.1,13.3],["L",11.4,13.8],["L",14.5,21.7],["L",14.7,21.9],["L",14.9,22],["L",15,22]],[["M",2,9],["L",2,9.1],["L",2.1,9.3],["L",2.3,9.5],["L",10.2,12.6],["L",10.6,12.9],["L",10.9,13.1]]],"mirror":true}

/** The sign for "send": the word set along its strokes. */
function SignSendWords(props: Omit<SignProps, "shape" | "variant">) {
  return <Sign shape={shape} variant="words" {...props} />
}

export { SignSendWords }
