import { Sign, type SignProps, type SignShape } from "@/registry/0db/ui/sign"

// Generated by scripts/build-signs.mjs from Lucide's smile (ISC).
const shape: SignShape = {"word":"happy","line":[[["O",12,12,10,180,180]],[["O",12,12,10,180,-180]],[["M",7.5,15],["L",8,15.4],["L",8.4,15.8],["L",9.1,16.2],["L",9.5,16.5],["L",10.2,16.7],["L",10.9,16.9],["L",11.6,17],["L",12.1,17],["L",12.6,17],["L",13.3,16.8],["L",13.9,16.7],["L",14.5,16.5],["L",15.2,16.1],["L",15.6,15.8],["L",16,15.4],["L",16.5,15]],[["M",15,9],["L",15,10]],[["M",9,10],["L",9,9]]]}

/** The sign for "happy": the word set along its strokes. */
function SignSmileWords(props: Omit<SignProps, "shape" | "variant">) {
  return <Sign shape={shape} variant="words" {...props} />
}

export { SignSmileWords }
