import { Sign, type SignProps, type SignShape } from "@/registry/0db/ui/sign"

// Generated by scripts/build-signs.mjs from Lucide's arrow-up (ISC).
const shape: SignShape = {"word":"up","fill":{"step":2.11,"rows":[[3.6,10.5,13.5],[5.7,8.4,11.1,12.9,15.6],[7.8,6.3,11.1,12.9,17.7],[9.9,4.2,11.1,12.9,19.8],[12,2.6,7.9,9.5,14.5,16.1,21.4],[14.1,9.5,14.5],[16.2,9.5,14.5],[18.3,9.5,14.5],[20.4,10.5,13.5]]}}

/** The sign for "up": the word filling its silhouette row by row. */
function SignArrowUpFill(props: Omit<SignProps, "shape" | "variant">) {
  return <Sign shape={shape} variant="fill" {...props} />
}

export { SignArrowUpFill }
