import { Sign, type SignProps, type SignShape } from "@/registry/0db/ui/sign"

// Generated by scripts/build-signs.mjs from Lucide's frown (ISC).
const shape: SignShape = {"word":"sad","fill":{"step":2.18,"rows":[[1.1,7.2,16.8],[3.3,3.7,20.3],[5.5,1.8,22.2],[7.6,0.6,8.7,9.3,14.7,15.3,23.4],[9.8,0,8.1,9.9,14.1,15.9,24],[12,0,24],[14.2,0,9.3,14.7,24],[16.4,0.6,8.1,15.9,23.4],[18.5,1.8,22.2],[20.7,3.7,20.3],[22.9,7.2,16.8]]}}

/** The sign for "sad": the word filling its silhouette row by row. */
function SignFrownFill(props: Omit<SignProps, "shape" | "variant">) {
  return <Sign shape={shape} variant="fill" {...props} />
}

export { SignFrownFill }
