import { Sign, type SignProps, type SignShape } from "@/registry/0db/ui/sign"

// Generated by scripts/build-signs.mjs from Lucide's code-xml (ISC).
const shape: SignShape = {"word":"code","fill":{"step":2.1,"rows":[[2.6,13.2,15.8],[4.7,11.9,16.7],[6.8,4.4,7.6,11.3,19.6],[8.9,2.3,8,10.6,15.4,16,21.7],[11,0.2,5.9,10,14.7,18.1,23.8],[13.1,0.2,5.9,9.3,14,18.1,23.8],[15.2,2.3,8,8.6,13.4,16,21.7],[17.3,4.4,12.7,16.4,19.6],[19.4,7.3,12.1],[21.5,8.2,10.8]]}}

/** The sign for "code": the word filling its silhouette row by row. */
function SignCodeFill(props: Omit<SignProps, "shape" | "variant">) {
  return <Sign shape={shape} variant="fill" {...props} />
}

export { SignCodeFill }
