import { Sign, type SignProps, type SignShape } from "@/registry/0db/ui/sign"

// Generated by scripts/build-signs.mjs from Lucide's grid-3x3 (ISC).
const shape: SignShape = {"word":"grid","fill":{"step":2.09,"rows":[[1.5,3.2,20.8],[3.6,1,7.9,10.1,13.9,16.1,23],[5.7,0.5,7.9,10.1,13.9,16.1,23.5],[7.8,0.5,2.9,21.1,23.5],[9.9,0.5,2.7,21.3,23.5],[12,0.5,7.9,10.1,13.9,16.1,23.5],[14.1,0.5,2.7,21.3,23.5],[16.2,0.5,2.9,21.1,23.5],[18.3,0.5,7.9,10.1,13.9,16.1,23.5],[20.4,1,7.9,10.1,13.9,16.1,23],[22.5,3.2,20.8]]}}

/** The sign for "grid": the word filling its silhouette row by row. */
function SignGridFill(props: Omit<SignProps, "shape" | "variant">) {
  return <Sign shape={shape} variant="fill" {...props} />
}

export { SignGridFill }
