import { Sign, type SignProps, type SignShape } from "@/registry/0db/ui/sign"

// Generated by scripts/build-signs.mjs from Lucide's car (ISC).
const shape: SignShape = {"word":"car","fill":{"step":2.13,"rows":[[5.6,3.3,14.2],[7.7,1.3,16.6],[9.8,0.2,22.2],[11.9,0,24],[14.1,0,5.3,8.7,15.3,18.7,24],[16.2,0,4.1,9.9,14.1,19.9,24],[18.3,1.1,4.5,5.5,8.5,9.5,14.5,15.5,18.5,19.5,22.9],[20.4,5,9,15,19]]}}

/** The sign for "car": the word filling its silhouette row by row. */
function SignCarFill(props: Omit<SignProps, "shape" | "variant">) {
  return <Sign shape={shape} variant="fill" {...props} />
}

export { SignCarFill }
