import { Sign, type SignProps, type SignShape } from "@/registry/0db/ui/sign"

// Generated by scripts/build-signs.mjs from a drawing made for 0nlyType.
const shape: SignShape = {"word":"home","line":[[["M",5,21],["L",19,21]],[["M",2,11.5],["L",12,3]],[["M",12,3],["L",22,11.5]],[["M",5,10],["L",5,21]],[["M",19,10],["L",19,21]]]}

/** The sign for "home": the word set along its strokes. */
function SignHomeWords(props: Omit<SignProps, "shape" | "variant">) {
  return <Sign shape={shape} variant="words" {...props} />
}

export { SignHomeWords }
