import { Sign, type SignProps, type SignShape } from "@/registry/0db/ui/sign"

// Generated by scripts/build-signs.mjs from Lucide's code-xml (ISC).
const shape: SignShape = {"word":"code","fill":{"step":2.1,"rows":[[2.6,13,16],[4.7,11.9,16.7],[6.8,4.3,7.7,11.2,19.7],[8.9,2.2,8,10.6,15.4,16,21.8],[11,0.1,6,9.9,14.7,18,23.9],[13.1,0.1,6,9.3,14.1,18,23.9],[15.2,2.2,8,8.6,13.4,16,21.8],[17.3,4.3,12.8,16.3,19.7],[19.4,7.3,12.1],[21.5,8,11]]}}

/** The sign for "code": the word filling its silhouette row by row. */
function SignCodeFill(props: Omit<SignProps, "shape" | "variant">) {
  return <Sign shape={shape} variant="fill" {...props} />
}

export { SignCodeFill }
