import { Sign, type SignProps, type SignShape } from "@/registry/0db/ui/sign"

// Generated by scripts/build-signs.mjs from Lucide's feather (ISC).
const shape: SignShape = {"word":"write","fill":{"step":2.18,"rows":[[1.1,12.3,19.8],[3.3,9.4,22.5],[5.5,7.2,23.8],[7.6,5,14.2,17,24],[9.8,3.1,12,16.3,24],[12,2.5,9.8,14.2,23],[14.2,2.5,7.7,17.3,21.1],[16.4,2.5,5.5,17,19],[18.5,2.5,4.4,7.6,16.8],[20.7,0.4,13.4],[22.9,0.1,3.9]]}}

/** The sign for "write": the word filling its silhouette row by row. */
function SignFeatherFill(props: Omit<SignProps, "shape" | "variant">) {
  return <Sign shape={shape} variant="fill" {...props} />
}

export { SignFeatherFill }
