import { Sign, type SignProps, type SignShape } from "@/registry/0db/ui/sign"

// Generated by scripts/build-signs.mjs from Lucide's leaf (ISC).
const shape: SignShape = {"word":"leaf","fill":{"step":2.14,"rows":[[1.1,16.6,21.4],[3.2,14.2,22.5],[5.3,6.4,22.9],[7.5,3.7,23.3],[9.6,2.5,23.5],[11.8,1.7,10.5,11.5,23.3],[13.9,1.6,7.2,11.8,22.6],[16,1.9,3.8,9.3,21.6],[18.2,0.4,4.6,6.1,19.9],[20.3,0,4.5,5.7,17.1],[22.4,0.5,3.5]]}}

/** The sign for "leaf": the word filling its silhouette row by row. */
function SignLeafFill(props: Omit<SignProps, "shape" | "variant">) {
  return <Sign shape={shape} variant="fill" {...props} />
}

export { SignLeafFill }
