import { Sign, type SignProps, type SignShape } from "@/registry/0db/ui/sign"

// Generated by scripts/build-signs.mjs from Lucide's gem (ISC).
const shape: SignShape = {"word":"gem","fill":{"step":2.14,"rows":[[1.6,5,19],[3.7,2.9,9,10.9,13.1,15,21.2],[5.8,1.3,8.1,10.6,13.4,15.9,22.7],[8,0,2,21.8,24],[10.1,0,2,21.7,24],[12.3,1.2,7.9,10.1,13.9,16.1,22.8],[14.4,2.8,8.5,10.8,13.2,15.5,21.2],[16.5,4.4,9.2,11.4,12.6,14.8,19.6],[18.7,6,9.9,14.1,18],[20.8,7.5,10.5,13.5,16.5],[22.9,9.2,14.8]]}}

/** The sign for "gem": the word filling its silhouette row by row. */
function SignGemFill(props: Omit<SignProps, "shape" | "variant">) {
  return <Sign shape={shape} variant="fill" {...props} />
}

export { SignGemFill }
