import { Sign, type SignProps, type SignShape } from "@/registry/0db/ui/sign"

// Generated by scripts/build-signs.mjs from Lucide's file-text (ISC).
const shape: SignShape = {"word":"text","fill":{"step":2.18,"rows":[[1.1,3.4,16.8],[3.3,1.7,12.9,15.1,19.1],[5.5,1.5,12.9,15.1,21.3],[7.6,1.5,7.2,10.8,12.9,20.3,22.4],[9.8,1.5,7,11,22.5],[12,1.5,7,17,22.5],[14.2,1.5,7.1,16.9,22.5],[16.4,1.5,6.9,17.1,22.5],[18.5,1.5,7.5,16.5,22.5],[20.7,1.8,22.3],[22.9,3.4,20.6]]}}

/** The sign for "text": the word filling its silhouette row by row. */
function SignFileTextFill(props: Omit<SignProps, "shape" | "variant">) {
  return <Sign shape={shape} variant="fill" {...props} />
}

export { SignFileTextFill }
