import { Sign, type SignProps, type SignShape } from "@/registry/0db/ui/sign"

// Generated by scripts/build-signs.mjs from Lucide's wallet (ISC).
const shape: SignShape = {"word":"wallet","fill":{"step":2.09,"rows":[[1.5,3.2,19.5],[3.6,1,21.3],[5.7,0.5,2.6,20.5,21.9],[7.8,0.5,3,20.5,23.3],[9.9,0.5,23.5],[12,0.5,15.4,21.8,24],[14.1,0.5,15,17.4,24],[16.2,0.5,15.4,21.8,23.9],[18.3,0.5,23.5],[20.4,1,23.3],[22.5,3.3,21.5]]}}

/** The sign for "wallet": the word filling its silhouette row by row. */
function SignWalletFill(props: Omit<SignProps, "shape" | "variant">) {
  return <Sign shape={shape} variant="fill" {...props} />
}

export { SignWalletFill }
