import { Sign, type SignProps, type SignShape } from "@/registry/0db/ui/sign"

// Generated by scripts/build-signs.mjs from Lucide's menu (ISC).
const shape: SignShape = {"word":"menu","line":[[["M",4,5],["L",20,5]],[["M",4,12],["L",20,12]],[["M",4,19],["L",20,19]]]}

/** The sign for "menu": the word ruled in leaders along its strokes. */
function SignMenuDots(props: Omit<SignProps, "shape" | "variant">) {
  return <Sign shape={shape} variant="dots" {...props} />
}

export { SignMenuDots }
