import { Sign, type SignProps, type SignShape } from "@/registry/0db/ui/sign"

// Generated by scripts/build-signs.mjs from Lucide's timer (ISC).
const shape: SignShape = {"word":"timer","fill":{"step":2.18,"rows":[[1.1,8.1,15.9],[3.3,8.4,15.6],[5.5,7,10.1,13.9,17],[7.6,4.2,10.8,13.2,19.8],[9.8,2.7,14,15.9,21.3],[12,1.9,11.8,16,22.1],[14.2,1.6,11,14,22.4],[16.4,2,22],[18.5,2.9,21.1],[20.7,4.6,19.4],[22.9,7.8,16.2]]}}

/** The sign for "timer": the word filling its silhouette row by row. */
function SignTimerFill(props: Omit<SignProps, "shape" | "variant">) {
  return <Sign shape={shape} variant="fill" {...props} />
}

export { SignTimerFill }
