import { Sign, type SignProps, type SignShape } from "@/registry/0db/ui/sign"

// Generated by scripts/build-signs.mjs from Lucide's pause (ISC).
const shape: SignShape = {"word":"pause","line":[[["M",18.7,3.3],["L",18.9,3.6],["L",19,4],["L",19,20],["L",18.9,20.4],["L",18.7,20.7]],[["M",14.3,3.3],["L",14.1,3.6],["L",14,4],["L",14,20],["L",14.1,20.4],["L",14.3,20.7]],[["M",9.7,20.7],["L",9.9,20.4],["L",10,20],["L",10,4],["L",9.9,3.6],["L",9.7,3.3]],[["M",5.3,20.7],["L",5.1,20.4],["L",5,20],["L",5,4],["L",5.1,3.6],["L",5.3,3.3]],[["M",14.3,20.7],["L",14.6,20.9],["L",15,21],["L",18,21],["L",18.4,20.9],["L",18.7,20.7]],[["M",14.3,3.3],["L",14.6,3.1],["L",15,3],["L",18,3],["L",18.4,3.1],["L",18.7,3.3]],[["M",5.3,20.7],["L",5.6,20.9],["L",6,21],["L",9,21],["L",9.4,20.9],["L",9.7,20.7]],[["M",5.3,3.3],["L",5.6,3.1],["L",6,3],["L",9,3],["L",9.4,3.1],["L",9.7,3.3]]]}

/** The sign for "pause": the word set along its strokes. */
function SignPauseWords(props: Omit<SignProps, "shape" | "variant">) {
  return <Sign shape={shape} variant="words" {...props} />
}

export { SignPauseWords }
