import { Sign, type SignProps, type SignShape } from "@/registry/0db/ui/sign"

// Generated by scripts/build-signs.mjs from Lucide's sun (ISC).
const shape: SignShape = {"word":"day","line":[[["O",12,12,4,180,180]],[["O",12,12,4,180,-180]],[["M",12,2],["L",12,4]],[["M",12,20],["L",12,22]],[["M",2,12],["L",4,12]],[["M",20,12],["L",22,12]],[["M",4.9,4.9],["L",6.3,6.3]],[["M",17.7,17.7],["L",19.1,19.1]],[["M",4.9,19.1],["L",6.3,17.7]],[["M",17.7,6.3],["L",19.1,4.9]]]}

/** The sign for "day": the word ruled in leaders along its strokes. */
function SignSunDots(props: Omit<SignProps, "shape" | "variant">) {
  return <Sign shape={shape} variant="dots" {...props} />
}

export { SignSunDots }
