import { Sign, type SignProps, type SignShape } from "@/registry/0db/ui/sign"

// Generated by scripts/build-signs.mjs from Lucide's undo-2 (ISC).
const shape: SignShape = {"word":"undo","line":[[["M",4,9],["L",14.5,9],["L",15.5,9.1],["L",16.2,9.3],["L",17.1,9.7],["L",17.7,10.1],["L",18.4,10.6],["L",18.9,11.3],["L",19.5,12.1],["L",19.7,12.8],["L",19.9,13.5],["L",20,14.5]],[["M",11,20],["L",14.5,20],["L",15.2,20],["L",16.2,19.7],["L",16.9,19.5],["L",17.3,19.2],["L",17.9,18.8],["L",18.5,18.3],["L",18.9,17.7],["L",19.3,17.1],["L",19.6,16.4],["L",19.9,15.7],["L",20,15.1],["L",20,14.5]],[["M",4,9],["L",9,14]],[["M",4,9],["L",9,4]]],"mirror":true}

/** The sign for "undo": the word ruled in leaders along its strokes. */
function SignUndoDots(props: Omit<SignProps, "shape" | "variant">) {
  return <Sign shape={shape} variant="dots" {...props} />
}

export { SignUndoDots }
