import { Sign, type SignProps, type SignShape } from "@/registry/0db/ui/sign"

// Generated by scripts/build-signs.mjs from Lucide's tag (ISC).
const shape: SignShape = {"word":"tag","line":[[["M",2.2,11.9],["L",2.3,12.2],["L",2.6,12.6],["L",11.3,21.3],["L",11.7,21.6],["L",12.1,21.8],["L",12.5,21.9],["L",13,22]],[["M",11.9,2.2],["L",12.2,2.3],["L",12.6,2.6],["L",21.3,11.3],["L",21.6,11.7],["L",21.8,12.1],["L",21.9,12.5],["L",22,13]],[["M",13,22],["L",13.5,21.9],["L",13.9,21.8],["L",14.3,21.6],["L",14.7,21.3],["L",21.4,14.5],["L",21.8,13.9],["L",21.9,13.5],["L",22,13]],[["M",2.2,11.9],["L",2.1,11.6],["L",2,11.2],["L",2,4],["L",2.1,3.5],["L",2.2,3.1],["L",2.7,2.5]],[["M",2.7,2.5],["L",3.3,2.1],["L",4,2],["L",11.2,2],["L",11.6,2.1],["L",11.9,2.2]],[["O",7.5,7.5,0.5,180,180]],[["O",7.5,7.5,0.5,180,-180]]]}

/** The sign for "tag": the word ruled in leaders along its strokes. */
function SignTagDots(props: Omit<SignProps, "shape" | "variant">) {
  return <Sign shape={shape} variant="dots" {...props} />
}

export { SignTagDots }
