import { Sign, type SignProps, type SignShape } from "@/registry/0db/ui/sign"

// Generated by scripts/build-signs.mjs from Lucide's speaker (ISC).
const shape: SignShape = {"word":"sound","fill":{"step":2.18,"rows":[[1.1,3.3,20.8],[3.3,1.7,22.2],[5.5,1.5,11.1,12.9,22.5],[7.6,1.5,22.5],[9.8,1.5,8.7,15.3,22.5],[12,1.5,7.3,10.3,13.7,16.7,22.5],[14.2,1.5,7.1,9,11.2,12.8,15,16.9,22.5],[16.4,1.5,7.4,11.1,12.9,16.6,22.5],[18.5,1.5,9.1,14.9,22.5],[20.7,1.7,22.3],[22.9,3.2,20.7]]}}

/** The sign for "sound": the word filling its silhouette row by row. */
function SignSpeakerFill(props: Omit<SignProps, "shape" | "variant">) {
  return <Sign shape={shape} variant="fill" {...props} />
}

export { SignSpeakerFill }
