import { Sign, type SignProps, type SignShape } from "@/registry/0db/ui/sign"

// Generated by scripts/build-signs.mjs from Lucide's briefcase (ISC).
const shape: SignShape = {"word":"work","line":[[["M",2.5,6.7],["L",2.9,6.4],["L",3.3,6.1],["L",4,6],["L",20,6],["L",20.7,6.1],["L",21.3,6.5]],[["M",2.7,19.5],["L",3.3,19.9],["L",4,20],["L",20,20],["L",20.5,19.9],["L",20.9,19.8],["L",21.5,19.3]],[["M",8,20],["L",8,4],["L",8.1,3.3],["L",8.4,2.9],["L",8.7,2.5]],[["M",15.5,2.7],["L",15.9,3.3],["L",16,4],["L",16,20]],[["M",2.7,19.5],["L",2.2,18.9],["L",2.1,18.5],["L",2,18],["L",2,8],["L",2.1,7.3],["L",2.5,6.7]],[["M",21.3,6.5],["L",21.8,7.1],["L",21.9,7.5],["L",22,8],["L",22,18],["L",21.9,18.7],["L",21.5,19.3]],[["M",8.7,2.5],["L",9.3,2.1],["L",9.8,2],["L",14,2],["L",14.7,2.1],["L",15.1,2.4],["L",15.5,2.7]]]}

/** The sign for "work": the word ruled in leaders along its strokes. */
function SignBriefcaseDots(props: Omit<SignProps, "shape" | "variant">) {
  return <Sign shape={shape} variant="dots" {...props} />
}

export { SignBriefcaseDots }
