import { Sign, type SignProps, type SignShape } from "@/registry/0db/ui/sign"

// Generated by scripts/build-signs.mjs from Lucide's bug (ISC).
const shape: SignShape = {"word":"bug","fill":{"step":2.14,"rows":[[1.1,6.1,9.9,14.1,17.9],[3.2,2.3,3.7,6.3,17.7,20.3,21.7],[5.3,0.7,5.4,6.7,9.4,14.6,17.3,18.6,23.3],[7.5,1.4,5.2,18.6,22.6],[9.6,3.3,4.9,8.1,11.2,12.8,15.9,19.1,20.7],[11.8,0.4,4.1,7.1,10.9,13.1,16.5,19.9,23.6],[13.9,0,4,7.1,10.9,13.1,16.6,20,24],[16,2.9,5,8.3,10.9,13.1,15.7,19,21.1],[18.2,1.6,5.1,8.2,10.9,13.1,15.8,18.9,22.4],[20.3,0.7,5.5,7,11.1,12.9,16.9,18.5,23.3],[22.4,1.7,4.3,19.7,22.3]]}}

/** The sign for "bug": the word filling its silhouette row by row. */
function SignBugFill(props: Omit<SignProps, "shape" | "variant">) {
  return <Sign shape={shape} variant="fill" {...props} />
}

export { SignBugFill }
