import { Sign, type SignProps, type SignShape } from "@/registry/0db/ui/sign"

// Generated by scripts/build-signs.mjs from a drawing made for 0dB.
const shape: SignShape = {"word":"next","fill":{"step":1.79,"rows":[[5.7,11.5,14],[7.5,11.5,16.2],[9.3,11.5,18.4],[11.1,2,20.6],[12.8,2,20.7],[14.6,11.5,18.5],[16.4,11.5,16.3],[18.2,11.5,14.1],[20,11.5,12.1]]},"mirror":true}

/** The sign for "next": the word filling its silhouette row by row. */
function SignArrowRightFill(props: Omit<SignProps, "shape" | "variant">) {
  return <Sign shape={shape} variant="fill" {...props} />
}

export { SignArrowRightFill }
