import { Sign, type SignProps, type SignShape } from "@/registry/0db/ui/sign"

// Generated by scripts/build-signs.mjs from a drawing made for 0dB.
const shape: SignShape = {"word":"search","fill":{"step":2.1,"rows":[[3.1,7.6,12.4],[5.1,4.2,15.8],[7.3,2.8,17.2],[9.4,2.2,17.8],[11.5,2.3,17.7],[13.6,3.2,17.1],[15.7,5.1,18.1],[17.8,15.3,20.2],[19.9,17.4,22.3],[22,19.5,20.4]]}}

/** The sign for "search": the word filling its silhouette row by row. */
function SignSearchFill(props: Omit<SignProps, "shape" | "variant">) {
  return <Sign shape={shape} variant="fill" {...props} />
}

export { SignSearchFill }
