import { Sign, type SignProps, type SignShape } from "@/registry/0db/ui/sign"

// Generated by scripts/build-signs.mjs from Lucide's cloud-fog (ISC).
const shape: SignShape = {"word":"fog","line":[[["M",2,10],["L",2.1,8.7],["L",2.5,7.5],["L",3,6.4],["L",3.7,5.4],["L",4.6,4.5],["L",5.7,3.8],["L",6.8,3.4],["L",8,3.1],["L",9.3,3],["L",10.5,3.2],["L",11.4,3.4],["L",12.6,4],["L",13.6,4.7],["L",14.4,5.6],["L",14.9,6.2],["L",15.2,6.7],["L",15.5,7.3],["L",15.7,8],["L",16.3,8]],[["M",7,17],["L",16,17]],[["M",16.3,8],["L",17.7,8],["L",18.5,8.1],["L",19.4,8.4],["L",20.3,9],["L",21,9.7],["L",21.5,10.5],["L",21.9,11.4],["L",22,12.4]],[["M",9,21],["L",17,21]],[["M",2,10],["L",2,10.7],["L",2.2,11.4],["L",2.5,12.6],["L",2.8,13.3],["L",3.1,13.8],["L",3.5,14.3],["L",4,14.9]],[["M",20,16.2],["L",20.6,15.8],["L",20.9,15.4],["L",21.5,14.6],["L",21.8,13.7],["L",22,13],["L",22,12.4]]]}

/** The sign for "fog": the word ruled in leaders along its strokes. */
function SignCloudFogDots(props: Omit<SignProps, "shape" | "variant">) {
  return <Sign shape={shape} variant="dots" {...props} />
}

export { SignCloudFogDots }
