import { Sign, type SignProps, type SignShape } from "@/registry/0db/ui/sign"

// Generated by scripts/build-signs.mjs from Lucide's disc (ISC).
const shape: SignShape = {"word":"disc","line":[[["O",12,12,10,180,180]],[["O",12,12,10,180,-180]],[["O",12,12,2,180,180]],[["O",12,12,2,180,-180]]]}

/** The sign for "disc": the word ruled in leaders along its strokes. */
function SignDiscDots(props: Omit<SignProps, "shape" | "variant">) {
  return <Sign shape={shape} variant="dots" {...props} />
}

export { SignDiscDots }
