import { Sign, type SignProps, type SignShape } from "@/registry/0db/ui/sign"

// Generated by scripts/build-signs.mjs from Lucide's coffee (ISC).
const shape: SignShape = {"word":"coffee","fill":{"step":2.14,"rows":[[1.1,4,16],[3.2,3.5,9.1,10.9,16.5],[5.3,3.6,9.5,10.5,16.4],[7.5,1.3,4.9,15.4,16.2,17.6,22],[9.6,0.5,16.1,17.9,23.7],[11.8,0.5,16.1,17.9,24],[13.9,0.5,16.1,17.9,24],[16,0.5,16.1,17.9,22.6],[18.2,0.8,19.1],[20.3,1.8,18.1],[22.4,4.6,15.3]]}}

/** The sign for "coffee": the word filling its silhouette row by row. */
function SignCoffeeFill(props: Omit<SignProps, "shape" | "variant">) {
  return <Sign shape={shape} variant="fill" {...props} />
}

export { SignCoffeeFill }
