import { Sign, type SignProps, type SignShape } from "@/registry/0db/ui/sign"

// Generated by scripts/build-signs.mjs from Lucide's trophy (ISC).
const shape: SignShape = {"word":"trophy","fill":{"step":2.18,"rows":[[1.1,4.7,19.3],[3.3,0.5,4,7.5,16.5,20,23.5],[5.5,0,4.2,7.3,16.7,19.8,24],[7.6,0,4.9,7.1,16.9,19.1,24],[9.8,0.5,4.4,7.6,16.4,19.6,23.5],[12,4.4,5.2,6.8,17.2,18.8,19.6],[14.2,5.8,8.5,15.5,18.2],[16.4,6.8,8.3,15.7,17.2],[18.5,5.2,8.1,11.3,12.7,15.9,18.9],[20.7,2.4,21.6],[22.9,2.1,21.9]]}}

/** The sign for "trophy": the word filling its silhouette row by row. */
function SignTrophyFill(props: Omit<SignProps, "shape" | "variant">) {
  return <Sign shape={shape} variant="fill" {...props} />
}

export { SignTrophyFill }
