import { Sign, type SignProps, type SignShape } from "@/registry/0db/ui/sign"

// Generated by scripts/build-signs.mjs from Lucide's trending-up (ISC).
const shape: SignShape = {"word":"rise","fill":{"step":2.14,"rows":[[5.6,14.7,23.3],[7.7,14,19.1,22.4,24],[9.9,6.3,10.7,15.6,18,21.3,24],[12,4.1,12.9,14.1,24],[14.1,2,7.7,9.3,17.7,20.3,23.7],[16.3,0,5.6,11.4,15.6],[18.4,0.7,3.3]]}}

/** The sign for "rise": the word filling its silhouette row by row. */
function SignTrendingUpFill(props: Omit<SignProps, "shape" | "variant">) {
  return <Sign shape={shape} variant="fill" {...props} />
}

export { SignTrendingUpFill }
