import { Sign, type SignProps, type SignShape } from "@/registry/0db/ui/sign"

// Generated by scripts/build-signs.mjs from Lucide's share-2 (ISC).
const shape: SignShape = {"word":"share","fill":{"step":2.18,"rows":[[1.1,14.9,21.1],[3.3,13.1,22.9],[5.5,12.6,14.5,16.2,23.3],[7.6,3.8,8.2,9.7,14.7,16.3,22.4],[9.8,1.3,7.6,9.5,13.7,17,19],[12,0.6,8.4,8.9,12],[14.2,1.3,7.6,9.5,13.7,17,19],[16.4,3.8,8.2,9.7,14.7,16.3,22.4],[18.5,12.6,14.5,16.2,23.3],[20.7,13.1,22.9],[22.9,14.9,21.1]]}}

/** The sign for "share": the word filling its silhouette row by row. */
function SignShareFill(props: Omit<SignProps, "shape" | "variant">) {
  return <Sign shape={shape} variant="fill" {...props} />
}

export { SignShareFill }
