import { Sign, type SignProps, type SignShape } from "@/registry/0db/ui/sign"

// Generated by scripts/build-signs.mjs from Lucide's skip-back (ISC).
const shape: SignShape = {"word":"replay","fill":{"step":2.1,"rows":[[2.6,1.7,4.3,17.3,20.8],[4.7,0.5,5.5,13.7,23],[6.8,0.5,5.5,10.2,23.5],[8.9,0.5,5.5,6.7,23.5],[11,0.5,5.5,8.5,23.5],[13.1,0.5,5.5,8.5,23.5],[15.2,0.5,5.5,6.7,23.5],[17.3,0.5,5.5,10.2,23.5],[19.4,0.5,5.5,13.7,23],[21.5,1.7,4.3,17.3,20.8]]}}

/** The sign for "replay": the word filling its silhouette row by row. */
function SignSkipBackFill(props: Omit<SignProps, "shape" | "variant">) {
  return <Sign shape={shape} variant="fill" {...props} />
}

export { SignSkipBackFill }
