import { Sign, type SignProps, type SignShape } from "@/registry/0db/ui/sign"

// Generated by scripts/build-signs.mjs from Lucide's bus (ISC).
const shape: SignShape = {"word":"bus","fill":{"step":2.11,"rows":[[4.6,2,20],[6.7,0,7.1,8.9,14.1,15.9,22.3],[8.8,0,7.1,8.9,14.1,15.9,23.1],[10.9,0,2,21.6,23.6],[13,0,1.9,21.7,24],[15.1,0,5.3,8.7,14.3,17.7,24],[17.2,0,4.1,9.9,13.1,18.9,23.6],[19.3,0.4,4.5,5.5,8.5,9.5,13.5,14.5,17.5,18.5,22.6],[21.4,5,9,14,18]]}}

/** The sign for "bus": the word filling its silhouette row by row. */
function SignBusFill(props: Omit<SignProps, "shape" | "variant">) {
  return <Sign shape={shape} variant="fill" {...props} />
}

export { SignBusFill }
