import { Sign, type SignProps, type SignShape } from "@/registry/0db/ui/sign"

// Generated by scripts/build-signs.mjs from Lucide's landmark (ISC).
const shape: SignShape = {"word":"bank","fill":{"step":2.18,"rows":[[1.1,9,15],[3.3,4.6,19.4],[5.5,1.1,22.9],[7.6,1.1,4.6,19.4,22.9],[9.8,3.6,9.3,10.7,13.3,14.7,20.4],[12,3.5,9.1,10.9,13.1,14.9,20.5],[14.2,3.5,9.1,10.9,13.1,14.9,20.5],[16.4,3.5,9.1,10.9,13.1,14.9,20.5],[18.5,3.9,9.1,10.9,13.1,14.9,20.1],[20.7,1.4,22.6],[22.9,1,23]]}}

/** The sign for "bank": the word filling its silhouette row by row. */
function SignLandmarkFill(props: Omit<SignProps, "shape" | "variant">) {
  return <Sign shape={shape} variant="fill" {...props} />
}

export { SignLandmarkFill }
