import { Sign, type SignProps, type SignShape } from "@/registry/0db/ui/sign"

// Generated by scripts/build-signs.mjs from Lucide's battery (ISC).
const shape: SignShape = {"word":"battery","fill":{"step":2.13,"rows":[[4.6,2,18],[6.7,0,20],[8.8,0,17.2,18.8,23.7],[10.9,0,17.1,18.9,24],[13.1,0,17.1,18.9,24],[15.2,0,17.3,18.7,23.7],[17.3,0,20],[19.4,2,18]]}}

/** The sign for "battery": the word filling its silhouette row by row. */
function SignBatteryFill(props: Omit<SignProps, "shape" | "variant">) {
  return <Sign shape={shape} variant="fill" {...props} />
}

export { SignBatteryFill }
