import { Sign, type SignProps, type SignShape } from "@/registry/0db/ui/sign"

// Generated by scripts/build-signs.mjs from Lucide's wine (ISC).
const shape: SignShape = {"word":"wine","line":[[["M",7,9.4],["L",7,10.5],["L",7.2,11.5],["L",7.6,12.4],["L",8,13],["L",8.3,13.4],["L",9,14],["L",9.9,14.5],["L",10.8,14.9],["L",11.5,15],["L",12,15],["L",13,14.9],["L",13.9,14.6],["L",14.6,14.3],["L",15,14],["L",15.7,13.4],["L",16.3,12.6],["L",16.5,12.1],["L",16.8,11.5],["L",17,10.5],["L",17,9.4]],[["M",7,10],["L",17,10]],[["M",8,22],["L",16,22]],[["M",15,2],["L",15.9,4.5],["L",16.4,6.3],["L",16.8,8],["L",17,9.4]],[["M",7,9.4],["L",7.2,8],["L",7.6,6.3],["L",8.1,4.5],["L",9,2]],[["M",12,15],["L",12,22]],[["M",9,2],["L",15,2]]]}

/** The sign for "wine": the word ruled in leaders along its strokes. */
function SignWineDots(props: Omit<SignProps, "shape" | "variant">) {
  return <Sign shape={shape} variant="dots" {...props} />
}

export { SignWineDots }
