import { Sign, type SignProps, type SignShape } from "@/registry/0db/ui/sign"

// Generated by scripts/build-signs.mjs from Lucide's circle-x (ISC).
const shape: SignShape = {"word":"error","fill":{"step":2.18,"rows":[[1.1,7.4,16.6],[3.3,3.8,20.2],[5.5,1.8,22.2],[7.6,0.6,8.2,9.8,14.2,15.8,23.4],[9.8,0,8,16,24],[12,0,9.8,14.2,24],[14.2,0,8,16,24],[16.4,0.6,8.2,9.8,14.2,15.8,23.4],[18.5,1.8,22.2],[20.7,3.8,20.2],[22.9,7.4,16.6]]}}

/** The sign for "error": the word filling its silhouette row by row. */
function SignCircleXFill(props: Omit<SignProps, "shape" | "variant">) {
  return <Sign shape={shape} variant="fill" {...props} />
}

export { SignCircleXFill }
