import { Sign, type SignProps, type SignShape } from "@/registry/0db/ui/sign"

// Generated by scripts/build-signs.mjs from Lucide's library (ISC).
const shape: SignShape = {"word":"library","line":[[["M",4,20],["L",4,4]],[["M",16,6],["L",20,20]],[["M",12,6],["L",12,20]],[["M",8,20],["L",8,8]]]}

/** The sign for "library": the word ruled in leaders along its strokes. */
function SignLibraryDots(props: Omit<SignProps, "shape" | "variant">) {
  return <Sign shape={shape} variant="dots" {...props} />
}

export { SignLibraryDots }
