import { Sign, type SignProps, type SignShape } from "@/registry/0db/ui/sign"

// Generated by scripts/build-signs.mjs from Lucide's eraser (ISC).
const shape: SignShape = {"word":"erase","line":[[["M",2,15.1],["L",2,14.6],["L",2.2,14.2],["L",2.6,13.6],["L",12.6,3.6],["L",13.2,3.2],["L",13.9,3]],[["M",7.2,20.8],["L",7.6,21],["L",8,21],["L",21,21]],[["M",12.8,21],["L",21.4,12.4],["L",21.7,12],["L",21.9,11.6],["L",22,10.9]],[["M",5.1,11.1],["L",13.9,19.9]],[["M",13.9,3],["L",14.6,3.1],["L",15,3.3],["L",15.4,3.6],["L",21.4,9.6],["L",21.8,10.2],["L",22,10.9]],[["M",2,15.1],["L",2.2,15.8],["L",2.6,16.4],["L",6.6,20.4],["L",6.9,20.7],["L",7.2,20.8]]]}

/** The sign for "erase": the word ruled in leaders along its strokes. */
function SignEraserDots(props: Omit<SignProps, "shape" | "variant">) {
  return <Sign shape={shape} variant="dots" {...props} />
}

export { SignEraserDots }
