import { Sign, type SignProps, type SignShape } from "@/registry/0db/ui/sign"

// Generated by scripts/build-signs.mjs from Lucide's cast (ISC).
const shape: SignShape = {"word":"cast","line":[[["M",2.5,4.7],["L",2.9,4.4],["L",3.3,4.1],["L",4,4],["L",20,4],["L",20.7,4.1],["L",21.3,4.5]],[["M",21.3,4.5],["L",21.8,5.1],["L",21.9,5.5],["L",22,6],["L",22,18],["L",21.9,18.7],["L",21.5,19.3]],[["M",2,12],["L",2.7,12.1],["L",3.5,12.3],["L",4.2,12.5],["L",4.9,12.8],["L",5.5,13.1],["L",6.2,13.5],["L",6.8,14],["L",7.3,14.5],["L",7.8,15],["L",8.3,15.6],["L",8.7,16.2],["L",9.1,16.9],["L",9.4,17.6],["L",9.6,18.3],["L",9.8,19],["L",10,20]],[["M",14,20],["L",20.2,20],["L",20.9,19.8],["L",21.5,19.3]],[["M",2,16],["L",2.7,16.2],["L",3.4,16.5],["L",4,16.8],["L",4.7,17.5],["L",5.2,18],["L",5.5,18.6],["L",5.8,19.3],["L",6,20]],[["M",2,8],["L",2,5.8],["L",2.1,5.3],["L",2.5,4.7]],[["M",2,20],["L",2,20]]]}

/** The sign for "cast": the word ruled in leaders along its strokes. */
function SignCastDots(props: Omit<SignProps, "shape" | "variant">) {
  return <Sign shape={shape} variant="dots" {...props} />
}

export { SignCastDots }
