import { Sign, type SignProps, type SignShape } from "@/registry/0db/ui/sign"

// Generated by scripts/build-signs.mjs from Lucide's rss (ISC).
const shape: SignShape = {"word":"feed","fill":{"step":2.1,"rows":[[2.6,2.7,7.7],[4.7,1.9,13.2],[6.8,8.9,16.1],[8.9,12.5,18.2],[11,1.6,10.1,14.6,19.7],[13.1,5.5,12.6,16,20.8],[15.2,8.9,14,16.9,21.6],[17.3,2.5,7.5,10.2,14.9,17.3,22.1],[19.4,1.7,8.3,10.5,15.4,17.5,22.4],[21.5,3.4,6.6,11.7,14.3,18.7,21.3]]}}

/** The sign for "feed": the word filling its silhouette row by row. */
function SignRssFill(props: Omit<SignProps, "shape" | "variant">) {
  return <Sign shape={shape} variant="fill" {...props} />
}

export { SignRssFill }
