import { Sign, type SignProps, type SignShape } from "@/registry/0db/ui/sign"

// Generated by scripts/build-signs.mjs from Lucide's server (ISC).
const shape: SignShape = {"word":"server","fill":{"step":2.18,"rows":[[1.1,1.4,22.6],[3.3,0,24],[5.5,0,4.5,7.5,24],[7.6,0,4.9,7.1,24],[9.8,0.3,3.5,20.5,23.7],[12,2,22],[14.2,0.3,3.5,20.5,23.7],[16.4,0,4.9,7.1,24],[18.5,0,4.5,7.5,24],[20.7,0,24],[22.9,1.4,22.6]]}}

/** The sign for "server": the word filling its silhouette row by row. */
function SignServerFill(props: Omit<SignProps, "shape" | "variant">) {
  return <Sign shape={shape} variant="fill" {...props} />
}

export { SignServerFill }
