import { Sign, type SignProps, type SignShape } from "@/registry/0db/ui/sign"

// Generated by scripts/build-signs.mjs from Lucide's infinity (ISC).
const shape: SignShape = {"word":"always","fill":{"step":2.17,"rows":[[6.6,3.6,8.6,15.4,20.4],[8.8,0.8,11.7,12.3,23.1],[10.9,0,10.7,13.3,24],[13.1,0,10.6,13.4,24],[15.3,0.9,11.7,12.3,23.1],[17.4,3.6,8.4,15.6,20.4]]}}

/** The sign for "always": the word filling its silhouette row by row. */
function SignInfinityFill(props: Omit<SignProps, "shape" | "variant">) {
  return <Sign shape={shape} variant="fill" {...props} />
}

export { SignInfinityFill }
