import { Sign, type SignProps, type SignShape } from "@/registry/0db/ui/sign"

// Generated by scripts/build-signs.mjs from Lucide's box (ISC).
const shape: SignShape = {"word":"box","fill":{"step":2.18,"rows":[[1.1,9.3,14.7],[3.3,5.5,18.5],[5.5,1.8,22.2],[7.6,0.7,2.9,7.6,16.4,21.1,23.3],[9.8,0.5,5.1,11.4,12.6,18.9,23.5],[12,0.5,8.7,15.3,23.5],[14.2,0.5,10.9,13.1,23.5],[16.4,0.7,10.9,13.1,23.3],[18.5,1.9,10.9,13.1,22.2],[20.7,5.5,10.9,13.1,18.5],[22.9,9.3,14.7]]}}

/** The sign for "box": the word filling its silhouette row by row. */
function SignBoxFill(props: Omit<SignProps, "shape" | "variant">) {
  return <Sign shape={shape} variant="fill" {...props} />
}

export { SignBoxFill }
