import { Sign, type SignProps, type SignShape } from "@/registry/0db/ui/sign"

// Generated by scripts/build-signs.mjs from Lucide's headphones (ISC).
const shape: SignShape = {"word":"listen","fill":{"step":2.09,"rows":[[1.5,9,15],[3.6,4.9,19.1],[5.7,2.9,8.7,15.3,21.1],[7.8,1.6,6.6,17.4,22.3],[9.9,0.9,5.6,18.3,23.1],[12,0.6,3.3,4.4,5.5,18.5,19.6,20.7,23.4],[14.1,0.5,2.2,5.5,9.6,14.4,18.5,21.8,23.5],[16.2,0.5,10.4,13.6,23.5],[18.3,0.5,10.5,13.5,23.5],[20.4,1,10,14,23],[22.5,3.2,7.8,16.2,20.8]]}}

/** The sign for "listen": the word filling its silhouette row by row. */
function SignHeadphonesFill(props: Omit<SignProps, "shape" | "variant">) {
  return <Sign shape={shape} variant="fill" {...props} />
}

export { SignHeadphonesFill }
