import { Sign, type SignProps, type SignShape } from "@/registry/0db/ui/sign"

// Generated by scripts/build-signs.mjs from Lucide's bot (ISC).
const shape: SignShape = {"word":"bot","fill":{"step":2.1,"rows":[[2.6,6.5,13.5],[4.7,5.9,14.5],[6.8,3.7,7.2,13.5,20.3],[8.9,1.9,6.9,13.8,22.1],[11,1.5,22.5],[13.1,0,2.7,4.9,8.1,9.9,14.1,15.9,19.1,21.3,24],[15.2,0.2,2.8,4.9,8.1,9.9,14.1,15.9,19.1,21.2,23.8],[17.3,1.5,22.5],[19.4,2,22],[21.5,4,20]]}}

/** The sign for "bot": the word filling its silhouette row by row. */
function SignBotFill(props: Omit<SignProps, "shape" | "variant">) {
  return <Sign shape={shape} variant="fill" {...props} />
}

export { SignBotFill }
