import { Sign, type SignProps, type SignShape } from "@/registry/0db/ui/sign"

// Generated by scripts/build-signs.mjs from Lucide's crown (ISC).
const shape: SignShape = {"word":"crown","fill":{"step":2.09,"rows":[[1.5,10.6,13.4],[3.6,1.8,3.2,9,15,20.7,22.3],[5.7,0,6.1,7.8,16.2,17.9,24],[7.8,0.1,5.8,9.7,14.3,18.2,23.9],[9.9,0.7,5.6,9.6,14.4,18.4,23.3],[12,1.3,22.7],[14.1,1.9,22.1],[16.2,2.5,5.3,18.7,21.5],[18.3,3.7,5.4,18.6,20.3],[20.4,2.9,21.1],[22.5,3.7,20.3]]}}

/** The sign for "crown": the word filling its silhouette row by row. */
function SignCrownFill(props: Omit<SignProps, "shape" | "variant">) {
  return <Sign shape={shape} variant="fill" {...props} />
}

export { SignCrownFill }
