import { Sign, type SignProps, type SignShape } from "@/registry/0db/ui/sign"

// Generated by scripts/build-signs.mjs from Lucide's play (ISC).
const shape: SignShape = {"word":"play","line":[[["M",5.9,3.3],["L",6.3,3.1],["L",6.9,3],["L",7.6,3.1],["L",8,3.3],["L",20,10.3],["L",20.4,10.6],["L",20.7,10.9],["L",20.9,11.4],["L",21,11.9]],[["M",6.1,20.8],["L",6.6,21],["L",7.1,21],["L",7.6,20.9],["L",8,20.7],["L",20,13.7],["L",20.5,13.3],["L",20.8,12.8],["L",21,12.4],["L",21,11.9]],[["M",5,12],["L",5,19.2],["L",5.1,19.7],["L",5.4,20.2],["L",5.7,20.5],["L",6.1,20.8]],[["M",5,12],["L",5,4.8],["L",5.1,4.3],["L",5.3,3.9],["L",5.5,3.6],["L",5.9,3.3]]]}

/** The sign for "play": the word set along its strokes. */
function SignPlayWords(props: Omit<SignProps, "shape" | "variant">) {
  return <Sign shape={shape} variant="words" {...props} />
}

export { SignPlayWords }
