import { Sign, type SignProps, type SignShape } from "@/registry/0db/ui/sign"

// Generated by scripts/build-signs.mjs from Lucide's map (ISC).
const shape: SignShape = {"word":"map","line":[[["M",15,5.8],["L",15,20.8]],[["M",9,18.2],["L",9,3.2]],[["M",20.4,3.7],["L",20.7,3.9],["L",20.9,4.2],["L",21,4.6],["L",21,17.4],["L",21,17.6],["L",20.8,17.9]],[["M",3.6,20.3],["L",3.2,20],["L",3.1,19.7],["L",3,19.4],["L",3,6.6],["L",3,6.4],["L",3.2,6.1]],[["M",9,18.2],["L",9.5,18.3],["L",9.9,18.4],["L",14.3,20.6],["L",15,20.8]],[["M",9,3.2],["L",9.7,3.4],["L",14.1,5.6],["L",14.5,5.7],["L",15,5.8]],[["M",15,20.8],["L",15.5,20.7],["L",15.9,20.6],["L",20.4,18.3],["L",20.6,18.2],["L",20.8,17.9]],[["M",3.2,6.1],["L",3.4,5.8],["L",3.6,5.7],["L",8.1,3.4],["L",8.5,3.3],["L",9,3.2]],[["M",15,5.8],["L",15.5,5.7],["L",15.9,5.6],["L",19.6,3.7],["L",20,3.6],["L",20.4,3.7]],[["M",3.6,20.3],["L",4,20.4],["L",4.4,20.3],["L",8.1,18.4],["L",8.5,18.3],["L",9,18.2]]]}

/** The sign for "map": the word ruled in leaders along its strokes. */
function SignMapDots(props: Omit<SignProps, "shape" | "variant">) {
  return <Sign shape={shape} variant="dots" {...props} />
}

export { SignMapDots }
