import { Sign, type SignProps, type SignShape } from "@/registry/0db/ui/sign"

// Generated by scripts/build-signs.mjs from Lucide's align-justify (ISC).
const shape: SignShape = {"word":"justify","line":[[["M",3,5],["L",21,5]],[["M",3,12],["L",21,12]],[["M",3,19],["L",21,19]]]}

/** The sign for "justify": the word set along its strokes. */
function SignAlignJustifyWords(props: Omit<SignProps, "shape" | "variant">) {
  return <Sign shape={shape} variant="words" {...props} />
}

export { SignAlignJustifyWords }
