import { Sign, type SignProps, type SignShape } from "@/registry/0db/ui/sign"

// Generated by scripts/build-signs.mjs from Lucide's building (ISC).
const shape: SignShape = {"word":"office","line":[[["M",4.5,2.7],["L",4.1,3.3],["L",4,4],["L",4,20],["L",4.1,20.7],["L",4.4,21.1],["L",4.7,21.5]],[["M",19.3,2.5],["L",19.6,2.9],["L",19.8,3.2],["L",19.9,3.5],["L",20,4],["L",20,20],["L",19.9,20.7],["L",19.5,21.3]],[["M",4.5,2.7],["L",4.9,2.4],["L",5.3,2.1],["L",6,2],["L",18,2],["L",18.7,2.1],["L",19.3,2.5]],[["M",4.7,21.5],["L",5.3,21.9],["L",6,22],["L",18,22],["L",18.5,21.9],["L",18.9,21.8],["L",19.5,21.3]],[["M",9.3,18.3],["L",9.6,18.1],["L",10,18],["L",14,18],["L",14.4,18.1],["L",14.7,18.3]],[["M",9,22],["L",9,19],["L",9.1,18.6],["L",9.3,18.3]],[["M",14.7,18.3],["L",14.9,18.6],["L",15,19],["L",15,22]],[["M",12,10],["L",12,10]],[["M",12,14],["L",12,14]],[["M",12,6],["L",12,6]],[["M",16,10],["L",16,10]],[["M",16,14],["L",16,14]],[["M",16,6],["L",16,6]],[["M",8,10],["L",8,10]],[["M",8,14],["L",8,14]],[["M",8,6],["L",8,6]]]}

/** The sign for "office": the word ruled in leaders along its strokes. */
function SignBuildingDots(props: Omit<SignProps, "shape" | "variant">) {
  return <Sign shape={shape} variant="dots" {...props} />
}

export { SignBuildingDots }
