import { Sign, type SignProps, type SignShape } from "@/registry/0db/ui/sign"

// Generated by scripts/build-signs.mjs from Lucide's infinity (ISC).
const shape: SignShape = {"word":"always","fill":{"step":2.17,"rows":[[6.6,3.9,8.4,15.6,20.1],[8.8,0.9,11.7,12.3,23.1],[10.9,0,10.5,13.5,24],[13.1,0,10.4,13.6,24],[15.3,0.9,11.7,12.3,23.1],[17.4,3.9,8.2,15.8,20.1]]}}

/** The sign for "always": the word filling its silhouette row by row. */
function SignInfinityFill(props: Omit<SignProps, "shape" | "variant">) {
  return <Sign shape={shape} variant="fill" {...props} />
}

export { SignInfinityFill }
