import { Sign, type SignProps, type SignShape } from "@/registry/0db/ui/sign"

// Generated by scripts/build-signs.mjs from Lucide's align-left (ISC).
const shape: SignShape = {"word":"left","line":[[["M",3,5],["L",21,5]],[["M",3,19],["L",17,19]],[["M",3,12],["L",15,12]]]}

/** The sign for "left": the word ruled in leaders along its strokes. */
function SignAlignLeftDots(props: Omit<SignProps, "shape" | "variant">) {
  return <Sign shape={shape} variant="dots" {...props} />
}

export { SignAlignLeftDots }
