import { Sign, type SignProps, type SignShape } from "@/registry/0db/ui/sign"

// Generated by scripts/build-signs.mjs from Lucide's key (ISC).
const shape: SignShape = {"word":"key","fill":{"step":2.18,"rows":[[1.1,11.9,19.1],[3.3,9.2,21.8],[5.5,8,23],[7.6,7.6,23.4],[9.8,8.1,10.3,12.8,22.9],[12,8.2,10,13.2,21.5],[14.2,6,11.7,12.3,18.7],[16.4,3.8,11.2],[18.5,1.6,12.5],[20.7,0,11.1],[22.9,5.4,8.6]]}}

/** The sign for "key": the word filling its silhouette row by row. */
function SignKeyFill(props: Omit<SignProps, "shape" | "variant">) {
  return <Sign shape={shape} variant="fill" {...props} />
}

export { SignKeyFill }
