import { Sign, type SignProps, type SignShape } from "@/registry/0db/ui/sign"

// Generated by scripts/build-signs.mjs from Lucide's octagon-alert (ISC).
const shape: SignShape = {"word":"danger","fill":{"step":2.18,"rows":[[1.1,6,18],[3.3,3.8,20.2],[5.5,1.6,22.4],[7.6,0,10.9,13.1,24],[9.8,0,10.9,13.1,24],[12,0,10.9,13.1,24],[14.2,0,11.1,12.9,24],[16.4,0,10.5,13.5,24],[18.5,1.6,22.4],[20.7,3.8,20.2],[22.9,6,18]]}}

/** The sign for "danger": the word filling its silhouette row by row. */
function SignOctagonAlertFill(props: Omit<SignProps, "shape" | "variant">) {
  return <Sign shape={shape} variant="fill" {...props} />
}

export { SignOctagonAlertFill }
