import { Sign, type SignProps, type SignShape } from "@/registry/0db/ui/sign"

// Generated by scripts/build-signs.mjs from a drawing made for 0dB.
const shape: SignShape = {"word":"home","fill":{"step":2.04,"rows":[[2.5,11.6,12.4],[4.6,9.3,14.7],[6.6,6.9,17.1],[8.6,4.6,19.4],[10.7,2.2,21.8],[12.7,4,20],[14.8,4,20],[16.8,4,9.9,14.1,20],[18.8,4,9.9,14.1,20],[20.9,4,9.9,14.1,20]]}}

/** The sign for "home": the word filling its silhouette row by row. */
function SignHomeFill(props: Omit<SignProps, "shape" | "variant">) {
  return <Sign shape={shape} variant="fill" {...props} />
}

export { SignHomeFill }
