import { Sign, type SignProps, type SignShape } from "@/registry/0db/ui/sign"

// Generated by scripts/build-signs.mjs from Lucide's cat (ISC).
const shape: SignShape = {"word":"cat","fill":{"step":2.11,"rows":[[1.4,2.7,7.2,16.8,21.2],[3.5,0.8,23.1],[5.6,0.7,23.3],[7.7,1.1,22.9],[9.8,1.4,22.6],[11.9,0.8,23.2],[14,0.7,6.5,9.5,14.5,17.5,23.3],[16.1,1.2,7.1,8.9,10.3,13.8,15.1,16.9,22.8],[18.2,2.3,11.1,12.9,21.7],[20.3,4.3,19.8],[22.4,8.7,15.1]]}}

/** The sign for "cat": the word filling its silhouette row by row. */
function SignCatFill(props: Omit<SignProps, "shape" | "variant">) {
  return <Sign shape={shape} variant="fill" {...props} />
}

export { SignCatFill }
