import { Sign, type SignProps, type SignShape } from "@/registry/0db/ui/sign"

// Generated by scripts/build-signs.mjs from Lucide's trending-down (ISC).
const shape: SignShape = {"word":"fall","line":[[["M",13.5,8.5],["L",22,17]],[["M",2,7],["L",8.5,13.5]],[["M",8.5,13.5],["L",13.5,8.5]],[["M",16,17],["L",22,17]],[["M",22,11],["L",22,17]]]}

/** The sign for "fall": the word set along its strokes. */
function SignTrendingDownWords(props: Omit<SignProps, "shape" | "variant">) {
  return <Sign shape={shape} variant="words" {...props} />
}

export { SignTrendingDownWords }
