import { Sign, type SignProps, type SignShape } from "@/registry/0db/ui/sign"

// Generated by scripts/build-signs.mjs from Lucide's trash-2 (ISC).
const shape: SignShape = {"word":"delete","fill":{"step":2.18,"rows":[[1.1,7.3,16.8],[3.3,5.7,18.2],[5.5,0.9,6.4,17.6,23.1],[7.6,1.9,22.1],[9.8,2.5,9.3,10.7,13.3,14.7,21.5],[12,2.5,9.1,10.9,13.1,14.9,21.5],[14.2,2.5,9.1,10.9,13.1,14.9,21.5],[16.4,2.5,9.1,10.9,13.1,14.9,21.5],[18.5,2.5,21.5],[20.7,2.7,21.3],[22.9,4.3,19.7]]}}

/** The sign for "delete": the word filling its silhouette row by row. */
function SignTrashFill(props: Omit<SignProps, "shape" | "variant">) {
  return <Sign shape={shape} variant="fill" {...props} />
}

export { SignTrashFill }
