import { Sign, type SignProps, type SignShape } from "@/registry/0db/ui/sign"

// Generated by scripts/build-signs.mjs from Lucide's files (ISC).
const shape: SignShape = {"word":"files","fill":{"step":2.18,"rows":[[1.1,8.2,17.9],[3.3,6.7,14.1,15.9,20.2],[5.5,3.4,6.1,6.5,8.2,9.8,14.1,15.9,22.2],[7.6,1.1,8.1,9.9,14.1,21.1,23.4],[9.8,0.5,8.1,9.9,23.5],[12,0.5,8.1,9.9,23.5],[14.2,0.5,8.1,9.9,23.5],[16.4,0.5,8.2,15.9,23],[18.5,0.5,20.6],[20.7,0.7,17],[22.9,2.3,15.8]]}}

/** The sign for "files": the word filling its silhouette row by row. */
function SignFilesFill(props: Omit<SignProps, "shape" | "variant">) {
  return <Sign shape={shape} variant="fill" {...props} />
}

export { SignFilesFill }
