import { Sign, type SignProps, type SignShape } from "@/registry/0db/ui/sign"

// Generated by scripts/build-signs.mjs from Lucide's users (ISC).
const shape: SignShape = {"word":"team","fill":{"step":2.08,"rows":[[1.6,6.6,11.4,14.7,17.4],[3.7,3.9,20.2],[5.8,2.8,11.6,14,21.2],[7.9,2.7,11.5,14,21.2],[10,3.6,7.1,13.5,20.4],[12,4.9,7.2,11.4,19.1],[14.1,2.6,21.4],[16.2,0.5,23.4],[18.3,0,4.5,13.5,18.3,19.5,24],[20.4,0,4.5,13.5,18.5,19.5,24],[22.5,0.7,3.3,14.7,17.3,20.7,23.3]]}}

/** The sign for "team": the word filling its silhouette row by row. */
function SignUsersFill(props: Omit<SignProps, "shape" | "variant">) {
  return <Sign shape={shape} variant="fill" {...props} />
}

export { SignUsersFill }
