import { Sign, type SignProps, type SignShape } from "@/registry/0db/ui/sign"

// Generated by scripts/build-signs.mjs from Lucide's leaf (ISC).
const shape: SignShape = {"word":"leaf","fill":{"step":2.14,"rows":[[1.1,16.7,21.3],[3.2,14.2,22.5],[5.3,6.4,22.9],[7.5,3.8,23.3],[9.6,2.5,23.5],[11.8,1.7,10.1,11.8,23.2],[13.9,1.6,6.8,12,22.6],[16,1.9,3.4,9.6,21.5],[18.2,0.5,3.8,6.8,19.9],[20.3,0,4.5,5.7,17.1],[22.4,0.7,3.3]]}}

/** The sign for "leaf": the word filling its silhouette row by row. */
function SignLeafFill(props: Omit<SignProps, "shape" | "variant">) {
  return <Sign shape={shape} variant="fill" {...props} />
}

export { SignLeafFill }
