import { Sign, type SignProps, type SignShape } from "@/registry/0db/ui/sign"

// Generated by scripts/build-signs.mjs from Lucide's type (ISC).
const shape: SignShape = {"word":"type","line":[[["M",12,4],["L",12,20]],[["M",4.3,4.3],["L",4.6,4.1],["L",5,4],["L",19,4],["L",19.4,4.1],["L",19.7,4.3]],[["M",9,20],["L",15,20]],[["M",4,7],["L",4,5],["L",4.1,4.6],["L",4.3,4.3]],[["M",19.7,4.3],["L",19.9,4.6],["L",20,5],["L",20,7]]]}

/** The sign for "type": the word set along its strokes. */
function SignTypeWords(props: Omit<SignProps, "shape" | "variant">) {
  return <Sign shape={shape} variant="words" {...props} />
}

export { SignTypeWords }
