import { Sign, type SignProps, type SignShape } from "@/registry/0db/ui/sign"

// Generated by scripts/build-signs.mjs from Lucide's brush (ISC).
const shape: SignShape = {"word":"paint","fill":{"step":2.14,"rows":[[1.1,17.1,22.7],[3.2,15,24],[5.3,12.9,24],[7.5,10.7,22.3],[9.6,8.5,10.7,12.5,20.2],[11.8,6.3,10.9,14.4,18.1],[13.9,2.3,6.7,9.7,13.2,13.7,16],[16,0.9,8,10.7,13.9],[18.2,0.5,12.3],[20.3,0,11.4],[22.4,1.2,8.9]]}}

/** The sign for "paint": the word filling its silhouette row by row. */
function SignBrushFill(props: Omit<SignProps, "shape" | "variant">) {
  return <Sign shape={shape} variant="fill" {...props} />
}

export { SignBrushFill }
