import { Sign, type SignProps, type SignShape } from "@/registry/0db/ui/sign"

// Generated by scripts/build-signs.mjs from Lucide's tree-pine (ISC).
const shape: SignShape = {"word":"pine","fill":{"step":2.14,"rows":[[1.6,10.5,13.5],[3.7,8.5,15.5],[5.8,6.6,17.4],[8,5.3,7.8,9.8,14.2,16,18.7],[10.1,5.2,7.6,9.7,14.3,16.4,18.8],[12.3,3.6,20.4],[14.4,3.4,5.8,7.9,16.1,18.1,20.6],[16.5,2,22],[18.7,1.5,10.3,13.7,22.5],[20.8,4,11.1,12.9,20.2],[22.9,10,14]]}}

/** The sign for "pine": the word filling its silhouette row by row. */
function SignTreePineFill(props: Omit<SignProps, "shape" | "variant">) {
  return <Sign shape={shape} variant="fill" {...props} />
}

export { SignTreePineFill }
