import { Sign, type SignProps, type SignShape } from "@/registry/0db/ui/sign"

// Generated by scripts/build-signs.mjs from Lucide's ghost (ISC).
const shape: SignShape = {"word":"ghost","fill":{"step":2.18,"rows":[[1.1,7.8,16.2],[3.3,4.7,19.4],[5.5,2.9,21.1],[7.6,2,22],[9.8,1.6,7.9,10.1,13.9,16.1,22.4],[12,1.5,8,10,14,16,22.5],[14.2,1.5,22.5],[16.4,1.5,22.5],[18.5,1.5,22.5],[20.7,1.6,22.4],[22.9,3,7.9,9.4,14.5,16.1,21.1]]}}

/** The sign for "ghost": the word filling its silhouette row by row. */
function SignGhostFill(props: Omit<SignProps, "shape" | "variant">) {
  return <Sign shape={shape} variant="fill" {...props} />
}

export { SignGhostFill }
