import { Sign, type SignProps, type SignShape } from "@/registry/0db/ui/sign"

// Generated by scripts/build-signs.mjs from Lucide's minus (ISC).
const shape: SignShape = {"word":"less","fill":{"step":2.5,"rows":[[10.8,3.4,20.6],[13.3,3.5,20.5]]}}

/** The sign for "less": the word filling its silhouette row by row. */
function SignMinusFill(props: Omit<SignProps, "shape" | "variant">) {
  return <Sign shape={shape} variant="fill" {...props} />
}

export { SignMinusFill }
