import assert from "node:assert/strict"
import { withComponent } from "./component-browser.mjs"

await withComponent("audio-player", async ({ page, base, restoreAudio, read, settle }) => {
  await page.goto(`${base}/hydration`)
  await settle(() => document.querySelector("audio").readyState >= 1)
  assert.equal(await page.locator('[data-slot="audio-seek"]').isEnabled(), false)
  await page.addScriptTag({ url: "/hydration-bundle.js" })
  await settle(() => !document.querySelector('[data-slot="audio-seek"]').disabled)
  assert.ok(Number(await page.locator('[data-slot="audio-seek"]').getAttribute("max")) > 7)
  assert.match(await read('[data-slot="audio-time"]'), /0:07/)
  await page.goto(`${base}/hydration-error`)
  await settle(() => document.querySelector("audio").error !== null)
  assert.equal(await page.locator("audio").evaluate((el) => el.readyState), 0)
  await page.addScriptTag({ url: "/hydration-bundle.js" })
  await page.waitForFunction(() => document.querySelector('[data-slot="audio-error"]') !== null, null, { timeout: 5000 })
  assert.equal(await read('[data-slot="audio-error"]'), "Recording unavailable. Try Play again.")
  restoreAudio()
  await page.locator('[data-slot="audio-play"]').click()
  await settle(() => document.querySelector("audio").duration > 0 && !document.querySelector("audio").paused)
  assert.equal(await page.locator('[data-slot="audio-error"]').count(), 0)
  await page.goto(base)
  const audio = page.locator("audio")
  await audio.evaluate((el) => { el.preload = "metadata"; el.load() })
  await settle(() => document.querySelector("audio").duration > 0)
  await audio.evaluate((el) => { el.currentTime = 4 })
  await settle(() => document.querySelector('[data-slot="audio-time"]').textContent.includes("0:04"))
  await page.locator('[data-slot="audio-play"]').click()
  await settle(() => !document.querySelector("audio").paused)
  const retiredRecording = await audio.elementHandle()
  await page.getByRole("button", { name: "Source B" }).click()
  assert.equal(await retiredRecording.evaluate((el) => el.paused), true)
  await page.getByRole("button", { name: "Source A" }).click()
  assert.match(await read('[data-slot="audio-time"]'), /0:00/)
  assert.equal(await page.locator('[data-slot="audio-play"]').innerText(), "Play")
  assert.equal(await audio.evaluate((el) => el.currentTime), 0)


})
