// Behavioral regression fixture; not a docs or demonstration route.
import assert from "node:assert/strict"
import { createServer } from "node:http"
import { readFileSync } from "node:fs"
import { build } from "esbuild"
import { chromium } from "playwright"
import { createElement } from "react"
import { renderToString } from "react-dom/server"
import { tsImport } from "tsx/esm/api"

const bundle = await build({ entryPoints: ["tests/fixtures/type-additions.tsx"], bundle: true, write: false, format: "iife", platform: "browser", jsx: "automatic", define: { "process.env.NODE_ENV": '"production"' } })
const hydrationBundle = await build({ entryPoints: ["tests/fixtures/audio-hydration.tsx"], bundle: true, write: false, format: "iife", platform: "browser", jsx: "automatic", define: { "process.env.NODE_ENV": '"production"' } })
const { AudioPlayer } = await tsImport("../registry/0db/ui/audio-player.tsx", import.meta.url)
const prerenderedAudio = renderToString(createElement(AudioPlayer, { src: "/one.wav", label: "Preloaded reading" }))
const failedAudio = renderToString(createElement(AudioPlayer, { src: "/missing.wav", label: "Unavailable reading" }))
const css = ["tokens", "base", "field", "allocation", "audio-player", "masked-value", "shortcut-recorder", "text-search", "time-range", "transfer-list"].map((name) => readFileSync(`registry/0db/styles/${name}.css`, "utf8")).join("\n")
const recording = readFileSync("public/audio/studio-reading.wav")
const server = createServer((req, res) => {
  if (req.url === "/missing.wav") res.writeHead(404).end()
  else if (req.url.endsWith(".wav")) {
    const range = req.headers.range?.match(/^bytes=(\d+)-(\d*)$/)
    const start = range ? Number(range[1]) : 0
    const end = range?.[2] ? Math.min(recording.length - 1, Number(range[2])) : recording.length - 1
    res.writeHead(range ? 206 : 200, { "content-type": "audio/wav", "content-length": end - start + 1, "accept-ranges": "bytes", ...(range ? { "content-range": `bytes ${start}-${end}/${recording.length}` } : {}) }).end(recording.subarray(start, end + 1))
  }
  else if (req.url === "/bundle.js") res.writeHead(200, { "content-type": "text/javascript" }).end(bundle.outputFiles[0].contents)
  else if (req.url === "/hydration-bundle.js") res.writeHead(200, { "content-type": "text/javascript" }).end(hydrationBundle.outputFiles[0].contents)
  else if (req.url === "/hydration") res.writeHead(200, { "content-type": "text/html" }).end(`<html><head><style>${css}</style></head><body><main id="hydrated-audio">${prerenderedAudio}</main></body></html>`)
  else if (req.url === "/hydration-error") res.writeHead(200, { "content-type": "text/html" }).end(`<html><head><style>${css}</style></head><body><main id="hydrated-audio">${failedAudio}</main></body></html>`)
  else res.writeHead(200, { "content-type": "text/html" }).end(`<html><head><style>${css}</style></head><body><main id="fixture"></main><script src="/bundle.js"></script></body></html>`)
})
await new Promise((resolve) => server.listen(0, "127.0.0.1", resolve))
const browser = await chromium.launch()
const page = await browser.newPage({ reducedMotion: "reduce", viewport: { width: 375, height: 900 } })
const errors = []
page.on("pageerror", (error) => errors.push(error.message))
const read = async (selector) => page.locator(selector).innerText()
const settle = (predicate) => page.waitForFunction(predicate)
try {
  await page.goto(`http://127.0.0.1:${server.address().port}/hydration`)
  await settle(() => document.querySelector("audio").readyState >= 1)
  assert.equal(await page.locator('[data-slot="audio-seek"]').isEnabled(), false)
  await page.addScriptTag({ url: "/hydration-bundle.js" })
  await settle(() => !document.querySelector('[data-slot="audio-seek"]').disabled)
  assert.ok(Number(await page.locator('[data-slot="audio-seek"]').getAttribute("max")) > 7)
  assert.match(await read('[data-slot="audio-time"]'), /0:07/)
  await page.goto(`http://127.0.0.1:${server.address().port}/hydration-error`)
  await settle(() => document.querySelector("audio").error !== null)
  assert.equal(await page.locator("audio").evaluate((el) => el.readyState), 0)
  await page.addScriptTag({ url: "/hydration-bundle.js" })
  await page.waitForFunction(() => document.querySelector('[data-slot="audio-error"]') !== null, null, { timeout: 5000 })
  assert.equal(await read('[data-slot="audio-error"]'), "Recording unavailable. Try Play again.")
  await page.goto(`http://127.0.0.1:${server.address().port}`)
  const search = page.locator('[data-slot="text-search"]')
  await search.getByRole("button", { name: "Next", exact: true }).click()
  await search.getByRole("button", { name: "Next", exact: true }).click()
  assert.equal(await search.getByRole("status").innerText(), "3 of 3 matches")
  await search.getByRole("searchbox").fill("and")
  await search.getByRole("searchbox").fill("one")
  assert.equal(await search.getByRole("status").innerText(), "1 of 3 matches")

  const audio = page.locator("audio")
  await audio.evaluate((el) => { el.preload = "metadata"; el.load() })
  await settle(() => document.querySelector("audio").duration > 0)
  await audio.evaluate((el) => { el.currentTime = 4 })
  await settle(() => document.querySelector('[data-slot="audio-time"]').textContent.includes("0:04"))
  await page.locator('[data-slot="audio-play"]').click()
  await settle(() => !document.querySelector("audio").paused)
  const retiredRecording = await audio.elementHandle()
  await page.getByRole("button", { name: "Source B" }).click()
  assert.equal(await retiredRecording.evaluate((el) => el.paused), true)
  await page.getByRole("button", { name: "Source A" }).click()
  assert.match(await read('[data-slot="audio-time"]'), /0:00/)
  assert.equal(await page.locator('[data-slot="audio-play"]').innerText(), "Play")
  assert.equal(await audio.evaluate((el) => el.currentTime), 0)

  const submitted = await page.evaluate(() => Object.fromEntries(new FormData(document.getElementById("settings"))))
  assert.equal(submitted["shares[a]"], "8")
  assert.equal(submitted["shares[b]"], "12")
  assert.equal(JSON.parse(submitted.shortcut).key, "J")
  assert.equal(submitted.from, "09:00")
  assert.equal(submitted.until, "17:30")
  const shares = page.getByRole("group", { name: "External shares" })
  await shares.getByRole("spinbutton", { name: "Research" }).fill("100")
  assert.equal(await shares.getByRole("spinbutton", { name: "Research" }).inputValue(), "28")
  assert.equal(await shares.getByRole("spinbutton", { name: "Type" }).inputValue(), "12")

  const shortcut = page.getByRole("group", { name: "External shortcut" })
  await shortcut.getByRole("button", { name: "Record", exact: true }).click()
  await page.keyboard.down("Control")
  await page.keyboard.down("k")
  await page.keyboard.down("k")
  await page.keyboard.down("k")
  assert.equal(await read('[data-testid="host-keys"]'), "0")
  await page.keyboard.up("k")
  await page.keyboard.down("k")
  await settle(() => document.querySelector('[data-testid="host-keys"]').textContent === "1")
  await page.keyboard.up("k")
  await page.keyboard.up("Control")
  assert.match(await shortcut.locator('[data-slot="shortcut-chord"]').innerText(), /K/)
  await shortcut.getByRole("button", { name: "Record", exact: true }).click()
  await shortcut.getByRole("button", { name: "Cancel", exact: true }).press("Escape")
  assert.equal(await shortcut.getByRole("button", { name: "Record", exact: true }).getAttribute("aria-pressed"), "false")
  await shortcut.getByRole("button", { name: "Clear", exact: true }).click()
  assert.equal(await page.evaluate(() => document.activeElement.dataset.slot), "shortcut-record")
  await page.getByRole("button", { name: "Reset", exact: true }).click()
  await settle(() => document.querySelector('[data-slot="allocation-input"]').value === "8")
  assert.match(await shortcut.locator('[data-slot="shortcut-chord"]').innerText(), /J/)
  await page.evaluate(() => document.getElementById("settings").addEventListener("reset", (e) => e.preventDefault(), { once: true }))
  await shares.getByRole("spinbutton", { name: "Research" }).fill("20")
  await page.getByRole("button", { name: "Reset", exact: true }).click()
  await page.waitForTimeout(20)
  assert.equal(await shares.getByRole("spinbutton", { name: "Research" }).inputValue(), "20")

  const transfer = page.locator('[data-slot="transfer-list"]')
  await transfer.getByLabel("Proof", { exact: true }).check()
  await transfer.getByRole("button", { name: "Include selected" }).click()
  assert.equal(await page.evaluate(() => document.activeElement.dataset.slot), "transfer-heading")
  assert.deepEqual(await page.evaluate(() => new FormData(document.getElementById("membership")).getAll("parts")), ["a", "b"])
  await page.getByRole("button", { name: "Reset membership" }).click()
  await settle(() => document.querySelectorAll('[data-slot="transfer-item"][data-included]').length === 1)

  const balance = page.getByRole("group", { name: "Changing allowance" }).locator("output")
  assert.match(await balance.innerText(), /Unassigned:.*5/s)
  await page.getByRole("button", { name: "Change allowance" }).click()
  assert.match(await balance.innerText(), /Over allowance:.*5/s)
  const decimals = page.getByRole("group", { name: "Decimal shares" })
  assert.equal(await decimals.getAttribute("aria-invalid"), null)
  assert.equal(await decimals.getByRole("spinbutton", { name: "One", exact: true }).getAttribute("max"), "0.1")
  assert.equal(await decimals.getByRole("spinbutton", { name: "Two", exact: true }).getAttribute("max"), "0.2")
  assert.equal(await decimals.evaluate((el) => [...el.querySelectorAll("input")].every((input) => input.validity.valid)), true)

  const initial = page.locator('[data-slot="masked-value"]').first()
  assert.equal(await initial.evaluate((el) => getComputedStyle(el.querySelector("bdi")).animationName), "none")
  const masked = page.locator('[data-slot="masked-value"]').last()
  await masked.getByRole("button", { name: "Reveal Private reading" }).click()
  await masked.getByRole("button", { name: "Hide Private reading" }).click()
  assert.equal(await masked.locator("bdi").count(), 0)
  assert.equal(await page.evaluate(() => document.activeElement.dataset.slot), "masked-value-trigger")
  assert.deepEqual(errors, [])
  console.log("Type additions hold: audio metadata/errors before hydration, search/source A–B–A, external form submission/reset/cancellation, decimal constraints, local chord capture through key release, focus recovery, transfer membership, live balance meaning, initial stillness and reveal interruption.")
} catch (error) {
  console.error(await page.locator("audio").evaluate((el) => ({ src: el.currentSrc, preload: el.preload, ready: el.readyState, network: el.networkState, duration: el.duration, error: el.error?.message })))
  throw error
} finally { await browser.close(); await new Promise((resolve) => server.close(resolve)) }
