import { defineComponent } from "./types"

export default defineComponent({
  name: "tiling",
  title: "Tiling",
  movement: "IV",
  contract: "db-tiling",
  summary: "Tiles on the 12-column grid, held apart by space and one hairline, never boxed. Leave the sheet still, or arrange it yourself: pick up a word, move it, give it room, and keep the layout.",
  underneath: "native",
  props: [
    { name: "variant", type: '"rules" | "crosses"', default: '"rules"', description: "rules: one ink hairline between neighbouring tiles, running a step past the tiling's edge, and none round the outside, so nothing is boxed. crosses: no lines at all; the space holds the tiles apart and a registration cross in the pencil marks every corner of every tile, the outer ones half a gap outside the block, as \"the uncreative\" marks its corners with + signs." },
    { name: "Tile", type: "div", description: "One tile. span is its width in columns out of 12 (default 4), rows the rows it stands through (default 1). In a tiling narrower than 40rem the grid falls to two columns: a tile of 6 or fewer takes one and a wider one both; under 24rem there is one column, and every tile is the whole width and one row high." },
    { name: "place", type: '"start-top" | "end-top" | "start-foot" | "end-foot"', default: '"start-top"', description: "On Tile: the corner its content keeps to, as the poster keeps its notes to the corners; the end corners set the text flush to the end. A child with margin-block-start: auto goes to the foot, so one tile can hold a note at its head and a paragraph at its foot." },
    { name: "TilingEditor", type: "div", description: "Opt-in bento builder with the same rules and crosses variants. Tiling and Tile keep their static server-rendered markup and responsive layout. The editor keeps twelve fixed columns and scrolls on narrow screens, so saved positions mean the same thing everywhere. Pencil construction lines, or dots for crosses, show the available space. A held tile wears accent corner marks; handles are the words move and size." },
    { name: "label", type: "string", description: "Required on TilingEditor. Names the editor, its scrollable editing sheet and its JSON output." },
    { name: "value / defaultValue", type: "TilingLayout", default: "[]", description: "On TilingEditor: controlled or initial uncontrolled layout. Plain serialisable array of { id: string, label: string, column: number, row: number, span: number, rows: number }. Coordinates start at 1 from the inline start; span is 1–12 and rows is at least 1. Use unique non-empty ids and labels, positive whole geometry, and no overlaps. Invalid supplied layouts show an error. Empty space is allowed; a move or resize into another tile or outside the grid is refused and announced." },
    { name: "onValueChange", type: "(value: TilingItem[]) => void", description: "Called for accepted moves, resizes, additions, removals and Escape restoration. Save this JSON to persist an arrangement. In controlled mode, update value from the callback; the editor never replaces the supplied value on its own. External updates do not glide." },
    { name: "renderTile", type: "(tile: TilingItem) => ReactNode", description: "On TilingEditor: optional content separate from the serialisable geometry. By default the tile's label is yours, set large in the expression italic. Content scrolls inside a tile that is made smaller than it. Move and size remain available." },
    { name: "copyLayout", type: "boolean", default: "false", description: "On TilingEditor: offers Copy layout and an expandable, selectable Layout JSON output. If clipboard access is unavailable the output opens and is selected for manual copying." },
    { name: "defaultHeld", type: "string", description: "On TilingEditor: id of a tile to start picked up, for a holding specimen. Otherwise nothing is held or moves on mount." },
    { name: "Keyboard / pointer", type: "interaction", description: "Tab to move. Enter or Space picks up and puts down; arrows move one column or row; Shift + arrows changes column or row span. On size, arrows also resize. Escape restores the tile's picked-up geometry, preserving changes to other tiles; if that space became occupied it stays put and tells you why. RTL mirrors horizontal arrows and pointer travel. Drag either word to move or resize, release to put down; a cancelled pointer restores the tile. Add tile finds free space and focuses its move word; Remove tile removes the held tile and focuses the next handle, or Add tile when empty. Every edit is announced politely with position and size. Keyboard moves glide; reduced motion and pointer edits place tiles directly." },
  ],
})
