import { defineComponent } from "./types"

export default defineComponent({
  name: "tiling",
  title: "Tiling",
  movement: "IV",
  contract: "ot-tiling",
  summary: "Tiles on the 12-column grid, held apart by space and one hairline, never boxed. Leave the sheet still, or drag a tile and pull its corner: the grid makes room for your arrangement.",
  underneath: "native",
  props: [
    { name: "variant", type: '"rules" | "crosses"', default: '"rules"', description: "rules: one ink hairline between neighbouring tiles, running a step past the tiling's edge, and none round the outside, so nothing is boxed. crosses: no lines at all; the space holds the tiles apart and a registration cross in the pencil marks every corner of every tile, the outer ones half a gap outside the block, as \"the uncreative\" marks its corners with + signs." },
    { name: "Tile", type: "TileProps", description: "One tile, with native div props. In a tiling narrower than 40rem the grid falls to two columns: a tile of 6 or fewer takes one and a wider one both; under 24rem there is one column, and every tile is the whole width and one row high." },
    { name: "span", type: "number", default: "4", description: "On Tile: width in columns out of 12. The static grid caps its column span at 12; responsive layouts use this width to choose one or two columns." },
    { name: "rows", type: "number", default: "1", description: "On Tile: how many grid rows it stands through. Below 24rem the static tiling makes every tile one row high. TilingEditor instead keeps the row span in its saved layout." },
    { name: "place", type: '"start-top" | "end-top" | "start-foot" | "end-foot"', default: '"start-top"', description: "On Tile: the corner its content keeps to, as the poster keeps its notes to the corners; the end corners set the text flush to the end. A child with margin-block-start: auto goes to the foot, so one tile can hold a note at its head and a paragraph at its foot." },
    { name: "TilingEditor", type: "div", description: "Opt-in editor. All twelve columns fit the available width, including on touch screens; saved coordinates stay the same. Each tile has its own hairline outline. Faint guides, or construction dots for crosses, show the grid; a dotted accent outline previews the landing cells. Drag the tile body to move it. Pull the visible end corner or an edge to resize; the held tile shows its column × row span. Static Tiling and Tile keep their existing rules and crosses." },
    { name: "label", type: "string", description: "Required on TilingEditor. Names the editor, its scrollable editing sheet and its JSON output." },
    { name: "value / defaultValue", type: "TilingLayout", default: "[]", description: "On TilingEditor: controlled or initial uncontrolled layout. Plain serialisable array of { id: string, label: string, column: number, row: number, span: number, rows: number }. Coordinates start at 1 from the inline start; span is 1–12 and rows is at least 1. Use unique non-empty ids and labels, positive whole geometry, and no overlaps. Invalid supplied layouts show an error. Empty space is allowed. A move onto a matching rectangle swaps the two tiles; other collisions reflow neighbours down without overlap. Movement and resizing stop at the grid edges and a one-cell minimum." },
    { name: "onValueChange", type: "(value: TilingItem[]) => void", description: "Called on pointer release or keyboard drop, and on addition or removal. Previewing and Escape cancellation do not change the saved JSON. In controlled mode, update value from the callback. A new external value cancels the preview and takes priority; external updates do not glide." },
    { name: "renderTile", type: "(tile: TilingItem) => ReactNode", description: "On TilingEditor: optional content separate from the serialisable geometry. By default the tile's label is yours, set large in the expression italic. Content stays clickable until a drag crosses six pixels; a drag suppresses the trailing click. Inputs, editable text and descendants with data-tiling-no-drag keep their own pointer interaction. The corner and edge controls remain outside the content." },
    { name: "copyLayout", type: "boolean", default: "false", description: "On TilingEditor: offers Copy layout and an expandable, selectable Layout JSON output. If clipboard access is unavailable the output opens and is selected for manual copying." },
    { name: "defaultHeld", type: "string", description: "On TilingEditor: id of a tile to start picked up, for a holding specimen. Otherwise nothing is held or moves on mount." },
    { name: "Keyboard / pointer", type: "interaction", description: "Tab to a tile. Enter or Space picks up and drops; arrows move one column or row, Shift + arrows resizes. The corner and edge buttons also support pickup and arrow resizing. Escape discards the entire preview, including neighbour reflow. Drag the body with pointer or touch; release commits, pointer cancellation restores. RTL mirrors horizontal keys, pointer travel and the end corner. Click a tile to select it for Remove tile. Add tile finds free space and focuses it; Remove focuses the next tile, or Add when empty. Position, size and edit results are announced politely. The short keyboard hint appears only while the sheet has focus. Neighbours and drops glide at moderato; reduced motion places them directly." },
  ],
})
