import { Sign, type SignProps, type SignShape } from "@/registry/0nlytype/ui/sign"

// Generated by scripts/build-signs.mjs from Lucide's mountain (ISC).
const shape: SignShape = {"word":"peak","line":[[["M",2,21],["L",22,21]],[["M",2,21],["L",8,3.1]],[["M",16.9,6.1],["L",17,6],["L",22,21]],[["M",8,3.1],["L",8,3],["L",12,11]],[["M",12,11],["L",16.9,6.1]]]}

/** The sign for "peak": the word ruled in leaders along its strokes. */
function SignMountainDots(props: Omit<SignProps, "shape" | "variant">) {
  return <Sign shape={shape} variant="dots" {...props} />
}

export { SignMountainDots }
