import { Sign, type SignProps, type SignShape } from "@/registry/0nlytype/ui/sign"

// Generated by scripts/build-signs.mjs from Lucide's flower (ISC).
const shape: SignShape = {"word":"flower","fill":{"step":2.09,"rows":[[1.5,5.3,9.7,14.3,18.7],[3.6,2.2,11,13.5,21.8],[5.7,1,10.4,13.8,23],[7.8,0.6,7,17,23.4],[9.9,1.3,4.4,5.8,7.8,16.2,18.2,19.6,22.7],[12,2.2,4.1,10.1,13.9,19.9,21.8],[14.1,1.3,4.4,5.8,7.8,16.2,18.2,19.6,22.7],[16.2,0.6,7,17,23.4],[18.3,1,10.4,13.8,23],[20.4,2.2,11,13.5,21.8],[22.5,5.3,9.7,14.3,18.7]]}}

/** The sign for "flower": the word filling its silhouette row by row. */
function SignFlowerFill(props: Omit<SignProps, "shape" | "variant">) {
  return <Sign shape={shape} variant="fill" {...props} />
}

export { SignFlowerFill }
