import { Sign, type SignProps, type SignShape } from "@/registry/0nlytype/ui/sign"

// Generated by scripts/build-signs.mjs from Lucide's check (ISC).
const shape: SignShape = {"word":"check","fill":{"step":2,"rows":[[4.5,18.7,21.3],[6.5,16.6,22.2],[8.5,14.6,20.4],[10.5,2.7,5.3,12.6,18.4],[12.5,1.8,7.4,10.6,16.4],[14.5,3.6,14.4],[16.5,5.6,12.4],[18.5,7.7,10.3]]}}

/** The sign for "check": the word filling its silhouette row by row. */
function SignCheckFill(props: Omit<SignProps, "shape" | "variant">) {
  return <Sign shape={shape} variant="fill" {...props} />
}

export { SignCheckFill }
