import { Sign, type SignProps, type SignShape } from "@/registry/0nlytype/ui/sign"

// Generated by scripts/build-signs.mjs from Lucide's newspaper (ISC).
const shape: SignShape = {"word":"news","fill":{"step":2.18,"rows":[[1.1,5.4,22.6],[3.3,3.8,24],[5.5,3.5,9.2,18.8,24],[7.6,2,3.9,7.3,8.9,19.1,24],[9.8,0,3.8,7.5,9,19,24],[12,0,4.9,7.1,24],[14.2,0,4.9,7.1,9,19,24],[16.4,0,4.9,7.1,9.9,15.1,24],[18.5,0,4.9,7.1,9,16,24],[20.7,0,4.5,7.1,24],[22.9,1.4,22.6]]}}

/** The sign for "news": the word filling its silhouette row by row. */
function SignNewspaperFill(props: Omit<SignProps, "shape" | "variant">) {
  return <Sign shape={shape} variant="fill" {...props} />
}

export { SignNewspaperFill }
