import { Sign, type SignProps, type SignShape } from "@/registry/0nlytype/ui/sign"

// Generated by scripts/build-signs.mjs from Lucide's upload (ISC).
const shape: SignShape = {"word":"upload","line":[[["M",3.7,20.5],["L",4.3,20.9],["L",5,21],["L",19,21],["L",19.5,20.9],["L",19.9,20.8],["L",20.5,20.3]],[["M",12,3],["L",12,15]],[["M",12,3],["L",17,8]],[["M",7,8],["L",12,3]],[["M",3.7,20.5],["L",3.2,19.9],["L",3,19.2],["L",3,15]],[["M",21,15],["L",21,19.2],["L",20.8,19.9],["L",20.5,20.3]]]}

/** The sign for "upload": the word set along its strokes. */
function SignUploadWords(props: Omit<SignProps, "shape" | "variant">) {
  return <Sign shape={shape} variant="words" {...props} />
}

export { SignUploadWords }
