import { Sign, type SignProps, type SignShape } from "@/registry/0nlytype/ui/sign"

// Generated by scripts/build-signs.mjs from Lucide's pencil (ISC).
const shape: SignShape = {"word":"edit","fill":{"step":2.18,"rows":[[1.1,16.3,22.1],[3.3,13.9,23.9],[5.5,11.7,14.5,17.6,24],[7.6,9.6,15.5,19.5,23.2],[9.8,7.4,17.7,19.2,21],[12,5.3,18.8],[14.2,3.1,16.6],[16.4,1.2,14.4],[18.5,0.5,12.2],[20.7,0,10],[22.9,0.4,6]]}}

/** The sign for "edit": the word filling its silhouette row by row. */
function SignPencilFill(props: Omit<SignProps, "shape" | "variant">) {
  return <Sign shape={shape} variant="fill" {...props} />
}

export { SignPencilFill }
