import { Sign, type SignProps, type SignShape } from "@/registry/0nlytype/ui/sign"

// Generated by scripts/build-signs.mjs from Lucide's lock-open (ISC).
const shape: SignShape = {"word":"unlock","fill":{"step":2.18,"rows":[[1.1,8.4,15.6],[3.3,6,18],[5.5,4.8,19.1],[7.6,4.5,17.8],[9.8,2.7,5.3,16.9,21.3],[12,0.9,5.2,17,23.1],[14.2,0.5,23.5],[16.4,0.5,23.5],[18.5,0.5,23.5],[20.7,0.8,23.3],[22.9,2.4,21.6]]}}

/** The sign for "unlock": the word filling its silhouette row by row. */
function SignUnlockFill(props: Omit<SignProps, "shape" | "variant">) {
  return <Sign shape={shape} variant="fill" {...props} />
}

export { SignUnlockFill }
