import { Sign, type SignProps, type SignShape } from "@/registry/0nlytype/ui/sign"

// Generated by scripts/build-signs.mjs from Lucide's tent (ISC).
const shape: SignShape = {"word":"camp","fill":{"step":2.09,"rows":[[1.5,8.7,11.3,12.7,15.3],[3.6,7.9,16.1],[5.7,9.1,14.9],[7.8,8.7,15.3],[9.9,7.5,16.5],[12,6.3,17.7],[14.1,5,11,13,19],[16.2,3.8,9.7,14.3,20.2],[18.3,2.6,8.5,11.7,12.3,15.5,21.4],[20.4,0,8,10.5,13.5,16,24],[22.5,0.7,23.3]]}}

/** The sign for "camp": the word filling its silhouette row by row. */
function SignTentFill(props: Omit<SignProps, "shape" | "variant">) {
  return <Sign shape={shape} variant="fill" {...props} />
}

export { SignTentFill }
