import { Sign, type SignProps, type SignShape } from "@/registry/0nlytype/ui/sign"

// Generated by scripts/build-signs.mjs from Lucide's arrow-left (ISC).
const shape: SignShape = {"word":"back","fill":{"step":2.11,"rows":[[3.6,10.7,13.3],[5.7,8.5,14.1],[7.8,6.4,12.1],[9.9,4.2,11.2],[12,2.6,4.9,10.6,21.4],[14.1,4.2,11.2],[16.2,6.4,12.1],[18.3,8.5,14.1],[20.4,10.7,13.3]]},"mirror":true}

/** The sign for "back": the word filling its silhouette row by row. */
function SignArrowLeftFill(props: Omit<SignProps, "shape" | "variant">) {
  return <Sign shape={shape} variant="fill" {...props} />
}

export { SignArrowLeftFill }
