import { Sign, type SignProps, type SignShape } from "@/registry/0nlytype/ui/sign"

// Generated by scripts/build-signs.mjs from Lucide's battery-low (ISC).
const shape: SignShape = {"word":"low","fill":{"step":2.13,"rows":[[4.6,2.2,17.8],[6.7,0,20],[8.8,0,5.1,6.9,17,19,23.7],[10.9,0,4.9,7.1,16.9,19.1,24],[13.1,0,4.9,7.1,16.9,19.1,24],[15.2,0,5.1,6.9,17.1,18.9,23.7],[17.3,0,20],[19.4,2.2,17.8]]}}

/** The sign for "low": the word filling its silhouette row by row. */
function SignBatteryLowFill(props: Omit<SignProps, "shape" | "variant">) {
  return <Sign shape={shape} variant="fill" {...props} />
}

export { SignBatteryLowFill }
