import { Sign, type SignProps, type SignShape } from "@/registry/0nlytype/ui/sign"

// Generated by scripts/build-signs.mjs from Lucide's volume-2 (ISC).
const shape: SignShape = {"word":"loud","fill":{"step":2.1,"rows":[[2.6,8.9,11.7],[4.7,6.5,13.4,17.5,21.3],[6.8,1.1,13.5,17,22.9],[8.9,0,10,12,13.5,13.7,15.5,17.5,23.8],[11,0,9.9,12.1,15.6,18,24],[13.1,0,9.9,12.1,15.6,18,24],[15.2,0,10,12,13.5,13.7,15.5,17.5,23.8],[17.3,1.1,13.5,17.2,22.9],[19.4,6.5,13.4,17.5,21.3],[21.5,8.9,11.7]]}}

/** The sign for "loud": the word filling its silhouette row by row. */
function SignVolumeFill(props: Omit<SignProps, "shape" | "variant">) {
  return <Sign shape={shape} variant="fill" {...props} />
}

export { SignVolumeFill }
