import { Sign, type SignProps, type SignShape } from "@/registry/0nlytype/ui/sign"

// Generated by scripts/build-signs.mjs from Lucide's tv (ISC).
const shape: SignShape = {"word":"show","fill":{"step":2.18,"rows":[[1.1,5.1,8.9,15.1,18.9],[3.3,5.4,11.1,12.9,18.6],[5.5,2.4,7,17,21.6],[7.6,0,6.4,17.6,24],[9.8,0,24],[12,0,24],[14.2,0,24],[16.4,0,24],[18.5,0,24],[20.7,0,24],[22.9,1.4,22.6]]}}

/** The sign for "show": the word filling its silhouette row by row. */
function SignTvFill(props: Omit<SignProps, "shape" | "variant">) {
  return <Sign shape={shape} variant="fill" {...props} />
}

export { SignTvFill }
