import { Sign, type SignProps, type SignShape } from "@/registry/0nlytype/ui/sign"

// Generated by scripts/build-signs.mjs from Lucide's bed (ISC).
const shape: SignShape = {"word":"sleep","line":[[["M",2,17],["L",22,17]],[["M",2,8],["L",20,8],["L",20.7,8.1],["L",21.3,8.5]],[["M",2,20],["L",2,4]],[["M",21.3,8.5],["L",21.8,9.1],["L",21.9,9.5],["L",22,10],["L",22,20]],[["M",6,17],["L",6,8]]]}

/** The sign for "sleep": the word ruled in leaders along its strokes. */
function SignBedDots(props: Omit<SignProps, "shape" | "variant">) {
  return <Sign shape={shape} variant="dots" {...props} />
}

export { SignBedDots }
