import { Sign, type SignProps, type SignShape } from "@/registry/0nlytype/ui/sign"

// Generated by scripts/build-signs.mjs from Lucide's tent (ISC).
const shape: SignShape = {"word":"camp","line":[[["M",3.5,21],["L",14,3]],[["M",10,3],["L",20.5,21]],[["M",2,21],["L",22,21]],[["M",12,15],["L",15.5,21]],[["M",8.5,21],["L",12,15]]]}

/** The sign for "camp": the word set along its strokes. */
function SignTentWords(props: Omit<SignProps, "shape" | "variant">) {
  return <Sign shape={shape} variant="words" {...props} />
}

export { SignTentWords }
