import { Sign, type SignProps, type SignShape } from "@/registry/0nlytype/ui/sign"

// Generated by scripts/build-signs.mjs from Lucide's ban (ISC).
const shape: SignShape = {"word":"block","line":[[["O",12,12,10,180,180]],[["O",12,12,10,180,-180]],[["M",4.9,4.9],["L",19.1,19.1]]]}

/** The sign for "block": the word ruled in leaders along its strokes. */
function SignBanDots(props: Omit<SignProps, "shape" | "variant">) {
  return <Sign shape={shape} variant="dots" {...props} />
}

export { SignBanDots }
