import { Sign, type SignProps, type SignShape } from "@/registry/0nlytype/ui/sign"

// Generated by scripts/build-signs.mjs from Lucide's cloud-rain (ISC).
const shape: SignShape = {"word":"rain","line":[[["M",2,10],["L",2.1,8.7],["L",2.5,7.5],["L",3,6.4],["L",3.7,5.4],["L",4.6,4.5],["L",5.7,3.8],["L",6.8,3.4],["L",8,3.1],["L",9,3],["L",10.2,3.1],["L",11.4,3.4],["L",12.6,4],["L",13.6,4.7],["L",14.1,5.2],["L",14.6,5.8],["L",15.3,6.8],["L",15.7,8],["L",16.3,8]],[["M",16.3,8],["L",17.7,8],["L",18.5,8.1],["L",19.4,8.4],["L",20.3,9],["L",21,9.7],["L",21.5,10.5],["L",21.9,11.4],["L",22,12.4]],[["M",16,14],["L",16,20]],[["M",8,20],["L",8,14]],[["M",12,16],["L",12,22]],[["M",2,10],["L",2.1,11.2],["L",2.3,11.9],["L",2.5,12.6],["L",3.1,13.7],["L",3.5,14.3],["L",4,14.9]],[["M",20,16.2],["L",20.8,15.6],["L",21.1,15.2],["L",21.5,14.6],["L",21.8,13.7],["L",22,12.9],["L",22,12.4]]]}

/** The sign for "rain": the word ruled in leaders along its strokes. */
function SignCloudRainDots(props: Omit<SignProps, "shape" | "variant">) {
  return <Sign shape={shape} variant="dots" {...props} />
}

export { SignCloudRainDots }
