import { Sign, type SignProps, type SignShape } from "@/registry/0nlytype/ui/sign"

// Generated by scripts/build-signs.mjs from Lucide's door-open (ISC).
const shape: SignShape = {"word":"door","fill":{"step":2.18,"rows":[[1.1,8.7,16.8],[3.3,3.2,8.9,11.1,20.7],[5.5,2.6,8.9,11.1,21.4],[7.6,2.5,8.9,11.1,21.5],[9.8,2.5,8.9,11.1,21.5],[12,2.5,8.9,11.1,12.5,15.5,21.5],[14.2,2.5,8.9,11.1,21.5],[16.4,2.5,8.9,11.1,21.5],[18.5,2.5,3.7,6.3,8.9,11.1,17.7,20.3,21.5],[20.7,0,3.5,6.5,8.9,11.1,17.5,20.5,24],[22.9,8.7,18.3]]}}

/** The sign for "door": the word filling its silhouette row by row. */
function SignDoorOpenFill(props: Omit<SignProps, "shape" | "variant">) {
  return <Sign shape={shape} variant="fill" {...props} />
}

export { SignDoorOpenFill }
