import { Sign, type SignProps, type SignShape } from "@/registry/0nlytype/ui/sign"

// Generated by scripts/build-signs.mjs from Lucide's tv (ISC).
const shape: SignShape = {"word":"show","line":[[["M",2.5,7.7],["L",2.9,7.4],["L",3.3,7.1],["L",4,7],["L",20,7],["L",20.7,7.1],["L",21.3,7.5]],[["M",2.7,21.5],["L",3.3,21.9],["L",4,22],["L",20,22],["L",20.5,21.9],["L",20.9,21.8],["L",21.5,21.3]],[["M",21.3,7.5],["L",21.8,8.1],["L",21.9,8.5],["L",22,9],["L",22,20],["L",21.9,20.7],["L",21.5,21.3]],[["M",2.7,21.5],["L",2.2,20.9],["L",2.1,20.5],["L",2,20],["L",2,9],["L",2.1,8.3],["L",2.5,7.7]],[["M",12,7],["L",17,2]],[["M",7,2],["L",12,7]]]}

/** The sign for "show": the word ruled in leaders along its strokes. */
function SignTvDots(props: Omit<SignProps, "shape" | "variant">) {
  return <Sign shape={shape} variant="dots" {...props} />
}

export { SignTvDots }
