import { Sign, type SignProps, type SignShape } from "@/registry/0nlytype/ui/sign"

// Generated by scripts/build-signs.mjs from Lucide's circle-x (ISC).
const shape: SignShape = {"word":"error","line":[[["O",12,12,10,180,180]],[["O",12,12,10,180,-180]],[["M",9,15],["L",15,9]],[["M",9,9],["L",15,15]]]}

/** The sign for "error": the word ruled in leaders along its strokes. */
function SignCircleXDots(props: Omit<SignProps, "shape" | "variant">) {
  return <Sign shape={shape} variant="dots" {...props} />
}

export { SignCircleXDots }
