import { Sign, type SignProps, type SignShape } from "@/registry/0nlytype/ui/sign"

// Generated by scripts/build-signs.mjs from Lucide's medal (ISC).
const shape: SignShape = {"word":"medal","fill":{"step":2.18,"rows":[[1.1,3.3,20.7],[3.3,1.4,4.5,7.3,16.7,19.5,22.6],[5.5,0.2,5.4,18.6,23.8],[7.6,0.6,6.8,17.2,23.4],[9.8,1.8,8.1,11.3,12.7,15.9,22.2],[12,3.1,7.8,16.2,20.9],[14.2,4.3,6.6,10.1,10.6,12.9,13.9,17.4,19.7],[16.4,4.7,10,13.5,19.3],[18.5,4.9,10.9,13.1,19.1],[20.7,6,18],[22.9,8.5,15.5]]}}

/** The sign for "medal": the word filling its silhouette row by row. */
function SignMedalFill(props: Omit<SignProps, "shape" | "variant">) {
  return <Sign shape={shape} variant="fill" {...props} />
}

export { SignMedalFill }
