import { Sign, type SignProps, type SignShape } from "@/registry/0nlytype/ui/sign"

// Generated by scripts/build-signs.mjs from Lucide's book-open (ISC).
const shape: SignShape = {"word":"read","fill":{"step":2.09,"rows":[[1.5,2.2,10.4,13.6,21.8],[3.6,0,10.4,13.8,24],[5.7,0,10.4,13.8,24],[7.8,0,10.9,13.1,24],[9.9,0,10.9,13.1,24],[12,0,10.9,13.1,24],[14.1,0,10.9,13.1,24],[16.2,0,10.9,13.1,24],[18.3,0,10.9,13.1,24],[20.4,2,10.9,13.1,22],[22.5,10.7,13.3]]}}

/** The sign for "read": the word filling its silhouette row by row. */
function SignBookOpenFill(props: Omit<SignProps, "shape" | "variant">) {
  return <Sign shape={shape} variant="fill" {...props} />
}

export { SignBookOpenFill }
