import { Sign, type SignProps, type SignShape } from "@/registry/0nlytype/ui/sign"

// Generated by scripts/build-signs.mjs from Lucide's monitor (ISC).
const shape: SignShape = {"word":"desktop","fill":{"step":2.09,"rows":[[1.5,2.2,21.8],[3.6,0,24],[5.7,0,24],[7.8,0,24],[9.9,0,24],[12,0,24],[14.1,0,24],[16.2,0,6.5,17.5,24],[18.3,1.8,6.6,17.4,22.2],[20.4,5.9,10.9,13.1,18.1],[22.5,6.7,17.3]]}}

/** The sign for "desktop": the word filling its silhouette row by row. */
function SignMonitorFill(props: Omit<SignProps, "shape" | "variant">) {
  return <Sign shape={shape} variant="fill" {...props} />
}

export { SignMonitorFill }
