import { Sign, type SignProps, type SignShape } from "@/registry/0nlytype/ui/sign"

// Generated by scripts/build-signs.mjs from Lucide's folder (ISC).
const shape: SignShape = {"word":"folder","fill":{"step":2,"rows":[[1.5,2.2,9.7],[3.5,0.1,11.9],[5.5,0,23.2],[7.5,0,24],[9.5,0,24],[11.5,0,24],[13.5,0,24],[15.5,0,24],[17.5,0,24],[19.5,0.1,23.9],[21.5,2.2,21.8]]}}

/** The sign for "folder": the word filling its silhouette row by row. */
function SignFolderFill(props: Omit<SignProps, "shape" | "variant">) {
  return <Sign shape={shape} variant="fill" {...props} />
}

export { SignFolderFill }
