import { Sign, type SignProps, type SignShape } from "@/registry/0nlytype/ui/sign"

// Generated by scripts/build-signs.mjs from Lucide's image (ISC).
const shape: SignShape = {"word":"image","line":[[["M",3.5,3.7],["L",3.9,3.4],["L",4.3,3.1],["L",5,3],["L",19,3],["L",19.7,3.1],["L",20.3,3.5]],[["M",20.3,3.5],["L",20.8,4.1],["L",20.9,4.5],["L",21,5],["L",21,19],["L",20.9,19.7],["L",20.5,20.3]],[["M",3.7,20.5],["L",4.3,20.9],["L",5,21],["L",19,21],["L",19.5,20.9],["L",19.9,20.8],["L",20.5,20.3]],[["M",3.7,20.5],["L",3.2,19.9],["L",3.1,19.5],["L",3,19],["L",3,5],["L",3.1,4.3],["L",3.5,3.7]],[["M",6,21],["L",15.1,11.9],["L",15.5,11.6],["L",15.9,11.4],["L",16.6,11.3]],[["O",9,9,2,180,180]],[["O",9,9,2,180,-180]],[["M",16.6,11.3],["L",17.3,11.5],["L",17.7,11.8],["L",21,15]]]}

/** The sign for "image": the word ruled in leaders along its strokes. */
function SignImageDots(props: Omit<SignProps, "shape" | "variant">) {
  return <Sign shape={shape} variant="dots" {...props} />
}

export { SignImageDots }
