import { Sign, type SignProps, type SignShape } from "@/registry/0nlytype/ui/sign"

// Generated by scripts/build-signs.mjs from Lucide's watch (ISC).
const shape: SignShape = {"word":"watch","fill":{"step":2.18,"rows":[[1.1,7.8,16.1],[3.3,6.4,17.6],[5.5,5.9,8.2,15.8,18.1],[7.6,5.2,7.7,16.3,18.8],[9.8,4,10.9,13.1,20],[12,3.6,10.9,14.5,20.4],[14.2,4,12.1,14.6,20],[16.4,5.2,7.7,16.5,18.8],[18.5,5.9,8.2,15.8,18.1],[20.7,6.4,17.6],[22.9,8.1,16]]}}

/** The sign for "watch": the word filling its silhouette row by row. */
function SignWatchFill(props: Omit<SignProps, "shape" | "variant">) {
  return <Sign shape={shape} variant="fill" {...props} />
}

export { SignWatchFill }
