import { Sign, type SignProps, type SignShape } from "@/registry/0nlytype/ui/sign"

// Generated by scripts/build-signs.mjs from Lucide's car (ISC).
const shape: SignShape = {"word":"car","line":[[["M",2.3,16.7],["L",2.1,16.4],["L",2,16],["L",2,12],["L",2.1,11.3],["L",2.2,10.8],["L",3.6,7.9],["L",3.9,7.5],["L",4.2,7.3]],[["M",13.1,7.2],["L",13.8,7.7],["L",16,10],["L",19,10.7],["L",20.7,11.2],["L",21.2,11.5],["L",21.6,11.9]],[["M",4.2,7.3],["L",4.6,7.1],["L",5,7],["L",12,7],["L",12.5,7],["L",13.1,7.2]],[["O",7,17,2,180,180]],[["O",7,17,2,180,-180]],[["O",17,17,2,180,180]],[["O",17,17,2,180,-180]],[["M",9,17],["L",15,17]],[["M",21.6,11.9],["L",21.9,12.4],["L",22,13],["L",22,16],["L",21.9,16.4],["L",21.7,16.7]],[["M",19,17],["L",21.2,17],["L",21.4,16.9],["L",21.7,16.7]],[["M",2.3,16.7],["L",2.6,16.9],["L",2.8,17],["L",5,17]]]}

/** The sign for "car": the word set along its strokes. */
function SignCarWords(props: Omit<SignProps, "shape" | "variant">) {
  return <Sign shape={shape} variant="words" {...props} />
}

export { SignCarWords }
