import { Sign, type SignProps, type SignShape } from "@/registry/0nlytype/ui/sign"

// Generated by scripts/build-signs.mjs from Lucide's shopping-cart (ISC).
const shape: SignShape = {"word":"cart","fill":{"step":2.18,"rows":[[1.1,0.3,5.5],[3.3,0.4,21.7],[5.5,2.3,24],[7.6,2.7,24],[9.8,3.1,23.8],[12,3.5,23.4],[14.2,3.9,6,19.3,22.5],[16.4,4.3,6.9,10.8,15.2,18.1,20.6],[18.5,4.1,6.3,11.8,14.2,19,21.9],[20.7,3.8,12.2,13.8,22.2],[22.9,5.4,10.6,15.4,20.6]]}}

/** The sign for "cart": the word filling its silhouette row by row. */
function SignShoppingCartFill(props: Omit<SignProps, "shape" | "variant">) {
  return <Sign shape={shape} variant="fill" {...props} />
}

export { SignShoppingCartFill }
