import { Sign, type SignProps, type SignShape } from "@/registry/0nlytype/ui/sign"

// Generated by scripts/build-signs.mjs from Lucide's list (ISC).
const shape: SignShape = {"word":"list","fill":{"step":2.11,"rows":[[3.6,1.7,4.3,6.7,22.3],[5.7,0.9,5.1,5.9,23.1],[12,0.6,5.4,5.6,23.4],[18.3,0.9,5.1,5.9,23.1],[20.4,1.7,4.3,6.7,22.3]]}}

/** The sign for "list": the word filling its silhouette row by row. */
function SignListFill(props: Omit<SignProps, "shape" | "variant">) {
  return <Sign shape={shape} variant="fill" {...props} />
}

export { SignListFill }
