import { Sign, type SignProps, type SignShape } from "@/registry/0nlytype/ui/sign"

// Generated by scripts/build-signs.mjs from Lucide's share-2 (ISC).
const shape: SignShape = {"word":"share","line":[[["O",18,5,3,180,180]],[["O",18,5,3,180,-180]],[["O",6,12,3,180,180]],[["O",6,12,3,180,-180]],[["O",18,19,3,180,180]],[["O",18,19,3,180,-180]],[["M",8.6,13.5],["L",15.4,17.5]],[["M",8.6,10.5],["L",15.4,6.5]]]}

/** The sign for "share": the word set along its strokes. */
function SignShareWords(props: Omit<SignProps, "shape" | "variant">) {
  return <Sign shape={shape} variant="words" {...props} />
}

export { SignShareWords }
