import { Sign, type SignProps, type SignShape } from "@/registry/0nlytype/ui/sign"

// Generated by scripts/build-signs.mjs from Lucide's fuel (ISC).
const shape: SignShape = {"word":"fuel","line":[[["M",3,21],["L",3,5],["L",3.1,4.5],["L",3.2,4.1],["L",3.7,3.5]],[["M",13.5,3.7],["L",13.9,4.3],["L",14,5],["L",14,21]],[["M",2,21],["L",15,21]],[["M",3,9],["L",14,9]],[["M",20,19],["L",20.7,18.9],["L",21.1,18.6],["L",21.6,18.1],["L",21.9,17.5],["L",22,17],["L",22,10],["L",21.9,9.3]],[["M",3.7,3.5],["L",4.3,3.1],["L",5,3],["L",12,3],["L",12.5,3.1],["L",12.9,3.2],["L",13.5,3.7]],[["M",17.3,13.5],["L",17.8,14.1],["L",17.9,14.5],["L",18,15],["L",18,17.2],["L",18.2,17.9],["L",18.6,18.4],["L",19.1,18.8],["L",19.5,18.9],["L",20,19]],[["M",18,5],["L",21.6,8.7],["L",21.9,9.3]],[["M",14,13],["L",16.2,13],["L",16.9,13.2],["L",17.3,13.5]]]}

/** The sign for "fuel": the word set along its strokes. */
function SignFuelWords(props: Omit<SignProps, "shape" | "variant">) {
  return <Sign shape={shape} variant="words" {...props} />
}

export { SignFuelWords }
