import { Sign, type SignProps, type SignShape } from "@/registry/0nlytype/ui/sign"

// Generated by scripts/build-signs.mjs from Lucide's life-buoy (ISC).
const shape: SignShape = {"word":"support","line":[[["O",12,12,10,180,180]],[["O",12,12,10,180,-180]],[["O",12,12,4,180,180]],[["O",12,12,4,180,-180]],[["M",4.9,4.9],["L",9.2,9.2]],[["M",14.8,9.2],["L",19.1,4.9]],[["M",14.8,14.8],["L",19.1,19.1]],[["M",4.9,19.1],["L",9.2,14.8]]]}

/** The sign for "support": the word ruled in leaders along its strokes. */
function SignLifeBuoyDots(props: Omit<SignProps, "shape" | "variant">) {
  return <Sign shape={shape} variant="dots" {...props} />
}

export { SignLifeBuoyDots }
