import { Sign, type SignProps, type SignShape } from "@/registry/0nlytype/ui/sign"

// Generated by scripts/build-signs.mjs from Lucide's compass (ISC).
const shape: SignShape = {"word":"explore","fill":{"step":2.18,"rows":[[1.1,7.4,16.6],[3.3,3.8,20.2],[5.5,1.8,22.2],[7.6,0.6,11.5,17.2,23.4],[9.8,0,8.6,16.8,24],[12,0,7.9,10.5,13.5,16.1,24],[14.2,0,7.2,15.4,24],[16.4,0.6,6.8,12.5,23.4],[18.5,1.8,22.2],[20.7,3.8,20.2],[22.9,7.4,16.6]]}}

/** The sign for "explore": the word filling its silhouette row by row. */
function SignCompassFill(props: Omit<SignProps, "shape" | "variant">) {
  return <Sign shape={shape} variant="fill" {...props} />
}

export { SignCompassFill }
