import { Sign, type SignProps, type SignShape } from "@/registry/0nlytype/ui/sign"

// Generated by scripts/build-signs.mjs from Lucide's trash-2 (ISC).
const shape: SignShape = {"word":"delete","fill":{"step":2.18,"rows":[[1.1,7.4,16.6],[3.3,5.7,7.5,8.5,15.4,16.6,18.2],[5.5,0.9,6.2,17.8,23.1],[7.6,2.1,6.9,17.1,21.9],[9.8,2.5,9.1,10.9,13.1,14.9,21.5],[12,2.5,8.9,11.1,12.9,15.1,21.5],[14.2,2.5,8.9,11.1,12.9,15.1,21.5],[16.4,2.5,8.9,11.1,12.9,15.1,21.5],[18.5,2.5,9.5,10.5,13.5,14.5,21.5],[20.7,2.8,21.3],[22.9,4.4,19.6]]}}

/** The sign for "delete": the word filling its silhouette row by row. */
function SignTrashFill(props: Omit<SignProps, "shape" | "variant">) {
  return <Sign shape={shape} variant="fill" {...props} />
}

export { SignTrashFill }
