import { Sign, type SignProps, type SignShape } from "@/registry/0nlytype/ui/sign"

// Generated by scripts/build-signs.mjs from Lucide's info (ISC).
const shape: SignShape = {"word":"info","fill":{"step":2.18,"rows":[[1.1,7.4,16.6],[3.3,3.8,20.2],[5.5,1.8,22.2],[7.6,0.6,10.5,13.5,23.4],[9.8,0,11.1,12.9,24],[12,0,10.9,13.1,24],[14.2,0,10.9,13.1,24],[16.4,0.6,10.9,13.1,23.4],[18.5,1.8,22.2],[20.7,3.8,20.2],[22.9,7.4,16.6]]}}

/** The sign for "info": the word filling its silhouette row by row. */
function SignInfoFill(props: Omit<SignProps, "shape" | "variant">) {
  return <Sign shape={shape} variant="fill" {...props} />
}

export { SignInfoFill }
