import { Sign, type SignProps, type SignShape } from "@/registry/0nlytype/ui/sign"

// Generated by scripts/build-signs.mjs from Lucide's cast (ISC).
const shape: SignShape = {"word":"cast","fill":{"step":2.1,"rows":[[2.6,2.2,21.8],[4.7,0,24],[6.8,0,24],[8.9,0,24],[11,0.2,2.2,4.7,24],[13.1,0.2,2.1,8,24],[15.2,0,2.2,4.3,5.8,9.7,24],[17.3,0.4,2,6.3,7.7,10.6,24],[19.4,0,4.4,6.7,8.6,10.8,24],[21.5,0.7,3.3,4.7,7.3,8.7,11.3,12.7,21.8]]}}

/** The sign for "cast": the word filling its silhouette row by row. */
function SignCastFill(props: Omit<SignProps, "shape" | "variant">) {
  return <Sign shape={shape} variant="fill" {...props} />
}

export { SignCastFill }
