import { Sign, type SignProps, type SignShape } from "@/registry/0nlytype/ui/sign"

// Generated by scripts/build-signs.mjs from Lucide's hourglass (ISC).
const shape: SignShape = {"word":"wait","line":[[["M",5,22],["L",19,22]],[["M",5,2],["L",19,2]],[["M",12,12],["L",16.4,16.4],["L",16.7,16.8],["L",16.8,17.1]],[["M",7.2,17.1],["L",7.3,16.8],["L",7.6,16.4],["L",12,12]],[["M",7.2,6.9],["L",7.3,7.2],["L",7.6,7.6],["L",12,12]],[["M",12,12],["L",16.4,7.6],["L",16.7,7.2],["L",16.8,6.9]],[["M",16.8,17.1],["L",16.9,17.4],["L",17,17.8],["L",17,22]],[["M",7,22],["L",7,17.8],["L",7.1,17.4],["L",7.2,17.1]],[["M",7.2,6.9],["L",7.1,6.6],["L",7,6.2],["L",7,2]],[["M",17,2],["L",17,6.2],["L",16.9,6.6],["L",16.8,6.9]]]}

/** The sign for "wait": the word ruled in leaders along its strokes. */
function SignHourglassDots(props: Omit<SignProps, "shape" | "variant">) {
  return <Sign shape={shape} variant="dots" {...props} />
}

export { SignHourglassDots }
