import { Sign, type SignProps, type SignShape } from "@/registry/0nlytype/ui/sign"

// Generated by scripts/build-signs.mjs from Lucide's phone (ISC).
const shape: SignShape = {"word":"call","fill":{"step":2.18,"rows":[[1.1,1.4,9.6],[3.3,0,11.2],[5.5,0,11.5],[7.6,0,11.2],[9.8,0.6,10.5],[12,1.5,11.1],[14.2,2.7,13.5,14.2,22.8],[16.4,4.1,24],[18.5,6.3,24],[20.7,9.2,24],[22.9,13.9,22.6]]}}

/** The sign for "call": the word filling its silhouette row by row. */
function SignPhoneFill(props: Omit<SignProps, "shape" | "variant">) {
  return <Sign shape={shape} variant="fill" {...props} />
}

export { SignPhoneFill }
