import { Sign, type SignProps, type SignShape } from "@/registry/0nlytype/ui/sign"

// Generated by scripts/build-signs.mjs from Lucide's cloud-rain (ISC).
const shape: SignShape = {"word":"rain","fill":{"step":2.14,"rows":[[1.6,6.5,11.7],[3.7,2.5,15.5],[5.8,0.9,17.2],[8,0,22.1],[10.1,0,23.7],[12.3,0,24],[14.4,1,6.9,9.1,11.9,12.1,14.9,17.1,24],[16.5,3.1,4.9,5.5,7.2,8.8,10.9,13.1,14.9,17.1,22.7],[18.7,5.5,10.9,13.1,18.5],[20.8,6,11,13,18],[22.9,10.1,13.9]]}}

/** The sign for "rain": the word filling its silhouette row by row. */
function SignCloudRainFill(props: Omit<SignProps, "shape" | "variant">) {
  return <Sign shape={shape} variant="fill" {...props} />
}

export { SignCloudRainFill }
