import { Sign, type SignProps, type SignShape } from "@/registry/0nlytype/ui/sign"

// Generated by scripts/build-signs.mjs from Lucide's download (ISC).
const shape: SignShape = {"word":"download","line":[[["M",3.7,20.5],["L",4.3,20.9],["L",5,21],["L",19,21],["L",19.5,20.9],["L",19.9,20.8],["L",20.5,20.3]],[["M",12,3],["L",12,15]],[["M",7,10],["L",12,15]],[["M",12,15],["L",17,10]],[["M",3.7,20.5],["L",3.2,19.9],["L",3,19.2],["L",3,15]],[["M",21,15],["L",21,19.2],["L",20.8,19.9],["L",20.5,20.3]]]}

/** The sign for "download": the word ruled in leaders along its strokes. */
function SignDownloadDots(props: Omit<SignProps, "shape" | "variant">) {
  return <Sign shape={shape} variant="dots" {...props} />
}

export { SignDownloadDots }
