import { Sign, type SignProps, type SignShape } from "@/registry/0nlytype/ui/sign"

// Generated by scripts/build-signs.mjs from Lucide's chevron-up (ISC).
const shape: SignShape = {"word":"fold","fill":{"step":2.2,"rows":[[7.6,10.7,13.3],[9.8,8.4,15.6],[12,6.2,11.8,12.2,17.8],[14.2,4,9.6,14.4,20],[16.4,4.7,7.3,16.7,19.3]]}}

/** The sign for "fold": the word filling its silhouette row by row. */
function SignChevronUpFill(props: Omit<SignProps, "shape" | "variant">) {
  return <Sign shape={shape} variant="fill" {...props} />
}

export { SignChevronUpFill }
