import { Sign, type SignProps, type SignShape } from "@/registry/0nlytype/ui/sign"

// Generated by scripts/build-signs.mjs from Lucide's scissors (ISC).
const shape: SignShape = {"word":"cut","line":[[["M",8.1,15.9],["L",20,4]],[["O",6,6,3,180,180]],[["O",6,6,3,180,-180]],[["O",6,18,3,180,180]],[["O",6,18,3,180,-180]],[["M",14.8,14.8],["L",20,20]],[["M",8.1,8.1],["L",12,12]]]}

/** The sign for "cut": the word ruled in leaders along its strokes. */
function SignScissorsDots(props: Omit<SignProps, "shape" | "variant">) {
  return <Sign shape={shape} variant="dots" {...props} />
}

export { SignScissorsDots }
