import { Sign, type SignProps, type SignShape } from "@/registry/0nlytype/ui/sign"

// Generated by scripts/build-signs.mjs from Lucide's map (ISC).
const shape: SignShape = {"word":"map","fill":{"step":2.05,"rows":[[1.7,7.2,10.6],[3.8,3,7.9,10.1,14.8,15.2,23.1],[5.8,0.9,7.9,10.1,14,16,23.5],[7.9,0.5,7.9,10.1,13.9,16.1,23.5],[9.9,0.5,7.9,10.1,13.9,16.1,23.5],[12,0.5,7.9,10.1,13.9,16.1,23.5],[14.1,0.5,7.9,10.1,13.9,16.1,23.5],[16.1,0.5,7.9,10.1,13.9,16.1,23.5],[18.2,0.5,8,10,13.9,16.1,23.1],[20.2,0.9,8.8,9,13.9,16.1,21],[22.3,13.2,16.8]]}}

/** The sign for "map": the word filling its silhouette row by row. */
function SignMapFill(props: Omit<SignProps, "shape" | "variant">) {
  return <Sign shape={shape} variant="fill" {...props} />
}

export { SignMapFill }
