import { Sign, type SignProps, type SignShape } from "@/registry/0nlytype/ui/sign"

// Generated by scripts/build-signs.mjs from Lucide's arrow-down (ISC).
const shape: SignShape = {"word":"down","line":[[["M",12,5],["L",12,19]],[["M",12,19],["L",19,12]],[["M",5,12],["L",12,19]]]}

/** The sign for "down": the word set along its strokes. */
function SignArrowDownWords(props: Omit<SignProps, "shape" | "variant">) {
  return <Sign shape={shape} variant="words" {...props} />
}

export { SignArrowDownWords }
