import { Sign, type SignProps, type SignShape } from "@/registry/0nlytype/ui/sign"

// Generated by scripts/build-signs.mjs from Lucide's badge-percent (ISC).
const shape: SignShape = {"word":"sale","fill":{"step":2.18,"rows":[[1.1,8.7,15.3],[3.3,3.9,20.1],[5.5,2.1,21.9],[7.6,1.4,7.7,10.3,14.2,15.8,22.6],[9.8,0.2,7.5,10.5,12,16,23.8],[12,0,9.8,14.2,24],[14.2,0.2,8,12,13.5,16.5,23.8],[16.4,1.4,8.2,9.8,13.7,16.3,22.6],[18.5,2.1,21.9],[20.7,3.9,20.1],[22.9,8.7,15.3]]}}

/** The sign for "sale": the word filling its silhouette row by row. */
function SignPercentFill(props: Omit<SignProps, "shape" | "variant">) {
  return <Sign shape={shape} variant="fill" {...props} />
}

export { SignPercentFill }
