import { Sign, type SignProps, type SignShape } from "@/registry/0nlytype/ui/sign"

// Generated by scripts/build-signs.mjs from Lucide's bed (ISC).
const shape: SignShape = {"word":"sleep","fill":{"step":2.1,"rows":[[2.6,0.7,3.3],[4.7,0,4.5],[6.8,0,1.4,4.4,22.2],[8.9,0,1.3,7.1,24],[11,0,4.9,7.1,24],[13.1,0,4.9,7.1,24],[15.2,0,1.9,3.9,4.9,7.1,20.1,22.1,24],[17.3,0,1.3,4.5,5,7,19.5,22.7,24],[19.4,0,4.5,19.5,24],[21.5,0.7,3.3,20.7,23.3]]}}

/** The sign for "sleep": the word filling its silhouette row by row. */
function SignBedFill(props: Omit<SignProps, "shape" | "variant">) {
  return <Sign shape={shape} variant="fill" {...props} />
}

export { SignBedFill }
