import { Sign, type SignProps, type SignShape } from "@/registry/0nlytype/ui/sign"

// Generated by scripts/build-signs.mjs from Lucide's message-square (ISC).
const shape: SignShape = {"word":"comment","line":[[["M",2.5,3.7],["L",2.9,3.4],["L",3.3,3.1],["L",4,3],["L",20,3],["L",20.7,3.1],["L",21.3,3.5]],[["M",2.4,21.9],["L",2.2,21.7],["L",2,21.5],["L",2,21.3],["L",2,5],["L",2.1,4.3],["L",2.5,3.7]],[["M",6.1,19.2],["L",6.4,19.1],["L",6.8,19],["L",20,19],["L",20.5,18.9],["L",20.9,18.8],["L",21.5,18.3]],[["M",21.3,3.5],["L",21.8,4.1],["L",21.9,4.5],["L",22,5],["L",22,17],["L",21.9,17.7],["L",21.5,18.3]],[["M",2.4,21.9],["L",2.8,22],["L",3,21.9],["L",3.2,21.8],["L",5.4,19.6],["L",5.8,19.3],["L",6.1,19.2]]]}

/** The sign for "comment": the word set along its strokes. */
function SignMessageSquareWords(props: Omit<SignProps, "shape" | "variant">) {
  return <Sign shape={shape} variant="words" {...props} />
}

export { SignMessageSquareWords }
