import { Sign, type SignProps, type SignShape } from "@/registry/0nlytype/ui/sign"

// Generated by scripts/build-signs.mjs from Lucide's baby (ISC).
const shape: SignShape = {"word":"baby","fill":{"step":2.08,"rows":[[1.5,9,14.3],[3.6,4.8,17.2],[5.7,2.8,11.2,12.8,14.3,16.5,21.2],[7.8,1.6,10.9,16.2,22.4],[9.9,0.6,23.5],[12,0,7.5,10.5,13.5,16.5,24],[14,0.4,8.6,9.4,14.6,15.4,23.6],[16.1,1.6,9,15,22.4],[18.2,2.8,21.2],[20.3,4.9,19.1],[22.4,8.8,15.2]]}}

/** The sign for "baby": the word filling its silhouette row by row. */
function SignBabyFill(props: Omit<SignProps, "shape" | "variant">) {
  return <Sign shape={shape} variant="fill" {...props} />
}

export { SignBabyFill }
