import { Sign, type SignProps, type SignShape } from "@/registry/0nlytype/ui/sign"

// Generated by scripts/build-signs.mjs from Lucide's life-buoy (ISC).
const shape: SignShape = {"word":"support","fill":{"step":2.18,"rows":[[1.1,7.4,16.6],[3.3,3.8,20.2],[5.5,1.8,4.4,7.6,16.4,19.6,22.2],[7.6,0.6,5.5,18.5,23.4],[9.8,0,7.2,11,13,16.8,24],[12,0,6.9,9.1,14.9,17.1,24],[14.2,0,7.2,11,13,16.8,24],[16.4,0.6,5.5,18.5,23.4],[18.5,1.8,4.4,7.6,16.4,19.6,22.2],[20.7,3.8,20.2],[22.9,7.4,16.6]]}}

/** The sign for "support": the word filling its silhouette row by row. */
function SignLifeBuoyFill(props: Omit<SignProps, "shape" | "variant">) {
  return <Sign shape={shape} variant="fill" {...props} />
}

export { SignLifeBuoyFill }
