import { Sign, type SignProps, type SignShape } from "@/registry/0nlytype/ui/sign"

// Generated by scripts/build-signs.mjs from Lucide's refresh-cw (ISC).
const shape: SignShape = {"word":"refresh","fill":{"step":2.09,"rows":[[1.5,9,15.2,19.7,22.3],[3.6,4.9,23.5],[5.7,2.9,17.6,20.9,23.5],[7.8,1.7,15,21.4,23.4],[9.9,0.9,22.6],[12,0.6,23.4],[14.1,1.4,23.1],[16.2,0.6,2.6,9,22.3],[18.3,0.5,3.1,6.4,21.1],[20.4,0.5,19.1],[22.5,1.7,4.3,8.8,15]]}}

/** The sign for "refresh": the word filling its silhouette row by row. */
function SignRefreshFill(props: Omit<SignProps, "shape" | "variant">) {
  return <Sign shape={shape} variant="fill" {...props} />
}

export { SignRefreshFill }
