import { Sign, type SignProps, type SignShape } from "@/registry/0nlytype/ui/sign"

// Generated by scripts/build-signs.mjs from Lucide's check (ISC).
const shape: SignShape = {"word":"check","line":[[["M",9,17],["L",20,6]],[["M",4,12],["L",9,17]]]}

/** The sign for "check": the word set along its strokes. */
function SignCheckWords(props: Omit<SignProps, "shape" | "variant">) {
  return <Sign shape={shape} variant="words" {...props} />
}

export { SignCheckWords }
