import { Sign, type SignProps, type SignShape } from "@/registry/0nlytype/ui/sign"

// Generated by scripts/build-signs.mjs from Lucide's coins (ISC).
const shape: SignShape = {"word":"coins","fill":{"step":2.18,"rows":[[1.1,12.2,19.8],[3.3,9.5,22.5],[5.5,8.2,14,17.1,23.8],[7.6,7.6,14.9,17.1,24],[9.8,2.9,9.2,11.7,14.9,17.1,24],[12,1,9.8,14.3,23],[14.2,0,5,8.5,11.6,15.5,21],[16.4,0,5.6,9.8,16.1],[18.5,0.2,7.9,10,15.8],[20.7,1.4,14.5],[22.9,4.2,11.7]]}}

/** The sign for "coins": the word filling its silhouette row by row. */
function SignCoinsFill(props: Omit<SignProps, "shape" | "variant">) {
  return <Sign shape={shape} variant="fill" {...props} />
}

export { SignCoinsFill }
