import { Sign, type SignProps, type SignShape } from "@/registry/0nlytype/ui/sign"

// Generated by scripts/build-signs.mjs from Lucide's list (ISC).
const shape: SignShape = {"word":"list","line":[[["M",8,5],["L",21,5]],[["M",8,12],["L",21,12]],[["M",8,19],["L",21,19]],[["M",3,5],["L",3,5]],[["M",3,12],["L",3,12]],[["M",3,19],["L",3,19]]]}

/** The sign for "list": the word ruled in leaders along its strokes. */
function SignListDots(props: Omit<SignProps, "shape" | "variant">) {
  return <Sign shape={shape} variant="dots" {...props} />
}

export { SignListDots }
