import { Sign, type SignProps, type SignShape } from "@/registry/0nlytype/ui/sign"

// Generated by scripts/build-signs.mjs from Lucide's shuffle (ISC).
const shape: SignShape = {"word":"shuffle","fill":{"step":2.18,"rows":[[1.1,16.1,19.9],[3.3,15.9,22.1],[5.5,0,7.9,12.2,16.7,22.1,24],[7.6,1.1,9.7,10.2,17.7,21.1,23.2],[9.8,6.7,9.5,12.7,21],[12,7.5,9.8,12.2,19.5],[14.2,6.2,21],[16.4,1.1,9.8,10.2,17.7,21.1,23.2],[18.5,0,7.8,12.2,16.7,22,24],[20.7,15.9,22.1],[22.9,16.1,19.9]]}}

/** The sign for "shuffle": the word filling its silhouette row by row. */
function SignShuffleFill(props: Omit<SignProps, "shape" | "variant">) {
  return <Sign shape={shape} variant="fill" {...props} />
}

export { SignShuffleFill }
