import { Sign, type SignProps, type SignShape } from "@/registry/0nlytype/ui/sign"

// Generated by scripts/build-signs.mjs from Lucide's music (ISC).
const shape: SignShape = {"word":"music","line":[[["M",9,18],["L",9,5]],[["M",21,3],["L",21,16]],[["M",9,5],["L",21,3]],[["O",6,18,3,180,180]],[["O",6,18,3,180,-180]],[["O",18,16,3,180,180]],[["O",18,16,3,180,-180]]]}

/** The sign for "music": the word ruled in leaders along its strokes. */
function SignMusicDots(props: Omit<SignProps, "shape" | "variant">) {
  return <Sign shape={shape} variant="dots" {...props} />
}

export { SignMusicDots }
