import { Sign, type SignProps, type SignShape } from "@/registry/0nlytype/ui/sign"

// Generated by scripts/build-signs.mjs from Lucide's aperture (ISC).
const shape: SignShape = {"word":"lens","fill":{"step":2.18,"rows":[[1.1,7.4,16.6],[3.3,3.8,10.9,13.6,20.2],[5.5,1.8,3.6,5.2,9.6,12.7,22.2],[7.6,0.6,3.4,6.5,8.3,21.5,23.4],[9.8,0,4.6,10.2,13.8,17,24],[12,0,5.8,9,15,18.3,24],[14.2,0,7.1,10.2,13.8,19.5,24],[16.4,0.6,2.5,15.7,17.6,20.7,23.4],[18.5,1.8,11.3,14.4,18.9,20.5,22.2],[20.7,3.8,10.4,13.1,20.2],[22.9,7.4,16.6]]}}

/** The sign for "lens": the word filling its silhouette row by row. */
function SignApertureFill(props: Omit<SignProps, "shape" | "variant">) {
  return <Sign shape={shape} variant="fill" {...props} />
}

export { SignApertureFill }
