import { Sign, type SignProps, type SignShape } from "@/registry/0nlytype/ui/sign"

// Generated by scripts/build-signs.mjs from Lucide's calendar (ISC).
const shape: SignShape = {"word":"date","fill":{"step":2.14,"rows":[[1.1,6.1,7.1,8.9,9.9,14.1,15.1,16.9,17.9],[3.2,1.3,6.3,9.7,14.3,17.7,22.8],[5.3,0.6,6.9,9.1,14.9,17.1,23.4],[7.5,0.5,3.3,20.7,23.5],[9.6,0.5,2.7,21.3,23.5],[11.8,0.5,23.5],[13.9,0.5,23.5],[16,0.5,23.5],[18.2,0.5,23.5],[20.3,1,23],[22.4,3.2,20.8]]}}

/** The sign for "date": the word filling its silhouette row by row. */
function SignCalendarFill(props: Omit<SignProps, "shape" | "variant">) {
  return <Sign shape={shape} variant="fill" {...props} />
}

export { SignCalendarFill }
