import { Sign, type SignProps, type SignShape } from "@/registry/0nlytype/ui/sign"

// Generated by scripts/build-signs.mjs from Lucide's external-link (ISC).
const shape: SignShape = {"word":"visit","line":[[["M",10,14],["L",21,3]],[["M",3.7,20.5],["L",4.3,20.9],["L",5,21],["L",16,21],["L",16.5,20.9],["L",16.9,20.8],["L",17.5,20.3]],[["M",3.7,20.5],["L",3.2,19.9],["L",3.1,19.5],["L",3,19],["L",3,8],["L",3.1,7.3],["L",3.5,6.7]],[["M",3.5,6.7],["L",4.1,6.2],["L",4.8,6],["L",11,6]],[["M",18,13],["L",18,19.2],["L",17.8,19.9],["L",17.5,20.3]],[["M",15,3],["L",21,3]],[["M",21,3],["L",21,9]]]}

/** The sign for "visit": the word set along its strokes. */
function SignExternalLinkWords(props: Omit<SignProps, "shape" | "variant">) {
  return <Sign shape={shape} variant="words" {...props} />
}

export { SignExternalLinkWords }
