import { Sign, type SignProps, type SignShape } from "@/registry/0nlytype/ui/sign"

// Generated by scripts/build-signs.mjs from Lucide's store (ISC).
const shape: SignShape = {"word":"shop","fill":{"step":2.14,"rows":[[1.1,4.4,19.6],[3.2,2.5,21.5],[5.3,1.1,22.9],[7.5,0,24],[9.6,0,3.4,20.6,24],[11.8,1.4,3.2,20.8,22.6],[13.9,1.5,8.6,15.4,22.5],[16,1.5,7.9,16.1,22.5],[18.2,1.5,7.9,10.1,13.9,16.1,22.5],[20.3,2,7.9,10.1,13.9,16.1,22],[22.4,4.2,19.8]]}}

/** The sign for "shop": the word filling its silhouette row by row. */
function SignStoreFill(props: Omit<SignProps, "shape" | "variant">) {
  return <Sign shape={shape} variant="fill" {...props} />
}

export { SignStoreFill }
