import { Sign, type SignProps, type SignShape } from "@/registry/0nlytype/ui/sign"

// Generated by scripts/build-signs.mjs from Lucide's notebook (ISC).
const shape: SignShape = {"word":"notes","line":[[["M",16,2],["L",16,22]],[["M",19.3,2.5],["L",19.8,3.1],["L",19.9,3.5],["L",20,4],["L",20,20],["L",19.9,20.7],["L",19.5,21.3]],[["M",4.7,21.5],["L",4.2,20.9],["L",4.1,20.5],["L",4,20],["L",4,4],["L",4.1,3.3],["L",4.5,2.7]],[["M",4.5,2.7],["L",4.9,2.4],["L",5.3,2.1],["L",6,2],["L",18,2],["L",18.7,2.1],["L",19.3,2.5]],[["M",4.7,21.5],["L",5.3,21.9],["L",6,22],["L",18,22],["L",18.5,21.9],["L",18.9,21.8],["L",19.5,21.3]],[["M",2,6],["L",6,6]],[["M",2,10],["L",6,10]],[["M",2,14],["L",6,14]],[["M",2,18],["L",6,18]]]}

/** The sign for "notes": the word set along its strokes. */
function SignNotebookWords(props: Omit<SignProps, "shape" | "variant">) {
  return <Sign shape={shape} variant="words" {...props} />
}

export { SignNotebookWords }
