import { Sign, type SignProps, type SignShape } from "@/registry/0nlytype/ui/sign"

// Generated by scripts/build-signs.mjs from Lucide's ban (ISC).
const shape: SignShape = {"word":"block","fill":{"step":2.18,"rows":[[1.1,7.4,16.6],[3.3,3.8,20.2],[5.5,1.8,4.4,7.6,22.2],[7.6,0.6,5.5,9.8,23.4],[9.8,0,7.7,12,24],[12,0,9.8,14.2,24],[14.2,0,12,16.3,24],[16.4,0.6,14.2,18.5,23.4],[18.5,1.8,16.4,19.6,22.2],[20.7,3.8,20.2],[22.9,7.4,16.6]]}}

/** The sign for "block": the word filling its silhouette row by row. */
function SignBanFill(props: Omit<SignProps, "shape" | "variant">) {
  return <Sign shape={shape} variant="fill" {...props} />
}

export { SignBanFill }
