import { Sign, type SignProps, type SignShape } from "@/registry/0nlytype/ui/sign"

// Generated by scripts/build-signs.mjs from Lucide's clipboard (ISC).
const shape: SignShape = {"word":"clip","fill":{"step":2.18,"rows":[[1.1,6.7,17.3],[3.3,3.2,6.3,9.5,14.5,17.7,20.9],[5.5,1.7,6.5,17.5,22.3],[7.6,1.5,8.9,15.1,22.5],[9.8,1.5,22.5],[12,1.5,22.5],[14.2,1.5,22.5],[16.4,1.5,22.5],[18.5,1.5,22.5],[20.7,1.8,22.3],[22.9,3.4,20.6]]}}

/** The sign for "clip": the word filling its silhouette row by row. */
function SignClipboardFill(props: Omit<SignProps, "shape" | "variant">) {
  return <Sign shape={shape} variant="fill" {...props} />
}

export { SignClipboardFill }
