import { Sign, type SignProps, type SignShape } from "@/registry/0nlytype/ui/sign"

// Generated by scripts/build-signs.mjs from Lucide's lock-open (ISC).
const shape: SignShape = {"word":"unlock","line":[[["M",7,11],["L",7,6.8],["L",7.1,6.3],["L",7.2,5.5],["L",7.6,4.6],["L",8.2,3.8],["L",8.9,3.1],["L",9.7,2.5],["L",10.4,2.3],["L",10.9,2.1],["L",11.9,2],["L",12.4,2],["L",13.1,2.1],["L",14.1,2.4],["L",14.5,2.7],["L",15.1,3.1],["L",15.8,3.8],["L",16.1,4.2],["L",16.5,4.8],["L",16.7,5.3],["L",16.9,6]],[["M",3.5,11.7],["L",3.9,11.4],["L",4.3,11.1],["L",5,11],["L",19,11],["L",19.7,11.1],["L",20.3,11.5]],[["M",3.7,21.5],["L",4.3,21.9],["L",5,22],["L",19,22],["L",19.5,21.9],["L",19.9,21.8],["L",20.5,21.3]],[["M",20.3,11.5],["L",20.8,12.1],["L",20.9,12.5],["L",21,13],["L",21,20],["L",20.9,20.7],["L",20.5,21.3]],[["M",3.7,21.5],["L",3.2,20.9],["L",3.1,20.5],["L",3,20],["L",3,13],["L",3.1,12.3],["L",3.5,11.7]]]}

/** The sign for "unlock": the word set along its strokes. */
function SignUnlockWords(props: Omit<SignProps, "shape" | "variant">) {
  return <Sign shape={shape} variant="words" {...props} />
}

export { SignUnlockWords }
