import { Sign, type SignProps, type SignShape } from "@/registry/0nlytype/ui/sign"

// Generated by scripts/build-signs.mjs from Lucide's bath (ISC).
const shape: SignShape = {"word":"bath","line":[[["M",2,12],["L",22,12]],[["M",4.5,18.3],["L",4.1,17.7],["L",4,17],["L",4,5],["L",4.2,4.3],["L",4.4,3.9],["L",4.9,3.4],["L",5.4,3.1]],[["M",4.5,18.3],["L",5.1,18.8],["L",5.5,18.9],["L",6,19],["L",18,19],["L",18.7,18.9],["L",19.3,18.5]],[["M",20,12],["L",20,17.2],["L",19.8,17.9],["L",19.3,18.5]],[["M",5.4,3.1],["L",5.8,3],["L",6.3,3],["L",7,3.2],["L",7.6,3.6],["L",9,5]],[["M",8,6],["L",10,4]],[["M",17,19],["L",17,21]],[["M",7,21],["L",7,19]]]}

/** The sign for "bath": the word ruled in leaders along its strokes. */
function SignBathDots(props: Omit<SignProps, "shape" | "variant">) {
  return <Sign shape={shape} variant="dots" {...props} />
}

export { SignBathDots }
