import { Sign, type SignProps, type SignShape } from "@/registry/0nlytype/ui/sign"

// Generated by scripts/build-signs.mjs from Lucide's shopping-basket (ISC).
const shape: SignShape = {"word":"basket","fill":{"step":2.1,"rows":[[2.6,7.7,10.3,13.7,16.3],[4.7,6.2,11.1,12.9,17.8],[6.8,5,9.9,14.1,19],[8.9,3.8,9.4,14.6,20.2],[11,0,4.2,10.1,13.9,19.8,24],[13.1,1.6,8.1,10.4,13.6,15.9,22.5],[15.2,2.1,4.2,19.8,22],[17.3,2.5,8.6,10.8,13.2,15.4,21.5],[19.4,3.2,8.8,11,13,15.2,20.8],[21.5,5.3,18.7]]}}

/** The sign for "basket": the word filling its silhouette row by row. */
function SignShoppingBasketFill(props: Omit<SignProps, "shape" | "variant">) {
  return <Sign shape={shape} variant="fill" {...props} />
}

export { SignShoppingBasketFill }
