import { Sign, type SignProps, type SignShape } from "@/registry/0nlytype/ui/sign"

// Generated by scripts/build-signs.mjs from Lucide's kanban (ISC).
const shape: SignShape = {"word":"board","fill":{"step":2.09,"rows":[[1.5,3.7,6.3,10.7,13.3,17.7,20.3],[3.6,2.5,7.5,9.5,14.5,16.5,21.5],[5.7,2.5,7.5,9.5,14.5,16.5,21.5],[7.8,2.5,7.5,9.5,14.5,16.5,21.5],[9.9,2.5,7.5,9.5,14.5,16.5,21.5],[12,2.5,7.5,10.1,13.9,16.5,21.5],[14.1,2.5,7.5,16.5,21.5],[16.2,2.5,7.5,16.5,21.5],[18.3,3.4,6.6,16.5,21.5],[20.4,16.5,21.5],[22.5,17.7,20.3]]}}

/** The sign for "board": the word filling its silhouette row by row. */
function SignKanbanFill(props: Omit<SignProps, "shape" | "variant">) {
  return <Sign shape={shape} variant="fill" {...props} />
}

export { SignKanbanFill }
