import { Sign, type SignProps, type SignShape } from "@/registry/0nlytype/ui/sign"

// Generated by scripts/build-signs.mjs from Lucide's ship (ISC).
const shape: SignShape = {"word":"ship","fill":{"step":2.14,"rows":[[1.1,10.1,13.9],[3.2,4.1,10.2,13.8,19.8],[5.3,2.8,10.5,13.5,21.2],[7.5,2.5,21.5],[9.6,2.5,6.6,17.4,21.5],[11.8,1.4,4,9.9,10.9,13.1,14.1,20,22.6],[13.9,0.6,11,13,23.4],[16,1,19.5,20.1,23],[18.2,1.2,3.2,5.6,18.2,21.3,22.8],[20.3,0,3.7,6.2,19.1,20.3,24],[22.4,2.3,6.7,12.3,16.7]]}}

/** The sign for "ship": the word filling its silhouette row by row. */
function SignShipFill(props: Omit<SignProps, "shape" | "variant">) {
  return <Sign shape={shape} variant="fill" {...props} />
}

export { SignShipFill }
