import { Sign, type SignProps, type SignShape } from "@/registry/0nlytype/ui/sign"

// Generated by scripts/build-signs.mjs from Lucide's files (ISC).
const shape: SignShape = {"word":"files","fill":{"step":2.18,"rows":[[1.1,8.4,17.8],[3.3,6.8,13.9,16.1,20.1],[5.5,3.4,6.1,6.5,8,10,13.9,16.1,22.2],[7.6,1,7.9,10.1,13.9,21.3,23.4],[9.8,0.5,7.9,10.1,23.5],[12,0.5,7.9,10.1,23.5],[14.2,0.5,7.9,10.1,23.5],[16.4,0.5,8,16.1,23],[18.5,0.5,10.4,15.5,20.6],[20.7,0.7,17],[22.9,2.4,15.6]]}}

/** The sign for "files": the word filling its silhouette row by row. */
function SignFilesFill(props: Omit<SignProps, "shape" | "variant">) {
  return <Sign shape={shape} variant="fill" {...props} />
}

export { SignFilesFill }
