import { Sign, type SignProps, type SignShape } from "@/registry/0nlytype/ui/sign"

// Generated by scripts/build-signs.mjs from Lucide's alarm-clock (ISC).
const shape: SignShape = {"word":"alarm","fill":{"step":2.09,"rows":[[1.5,3.7,6.3,17.7,20.3],[3.6,1.5,7.5,8.9,15.1,16.5,22.5],[5.7,0,5.8,8,16,18.2,24],[7.8,1.3,4.6,8,11.1,12.9,16,19.4,22.7],[9.9,2.2,10.9,13.1,21.8],[12,1.7,10.9,13.1,22.3],[14.1,1.7,11.1,15,22.3],[16.2,2.3,13.1,14.9,21.7],[18.3,3,4.6,8,16,19.4,21],[20.4,1.9,4.7,7.7,16.3,19.3,22.1],[22.5,2.7,5.3,9.2,14.8,18.7,21.3]]}}

/** The sign for "alarm": the word filling its silhouette row by row. */
function SignAlarmClockFill(props: Omit<SignProps, "shape" | "variant">) {
  return <Sign shape={shape} variant="fill" {...props} />
}

export { SignAlarmClockFill }
