import { Sign, type SignProps, type SignShape } from "@/registry/0nlytype/ui/sign"

// Generated by scripts/build-signs.mjs from Lucide's folder-open (ISC).
const shape: SignShape = {"word":"open","fill":{"step":2,"rows":[[1.5,2.2,9.6],[3.5,0.1,11.8],[5.5,0,21.2],[7.5,0,22.3],[9.5,0,6.9,21,23.2],[11.5,0,5.8,20.5,24],[13.5,0,5,7.7,24],[15.5,0,5.5,6.5,23.5],[17.5,0,23],[19.5,0.1,22.3],[21.5,2.2,20.3]]}}

/** The sign for "open": the word filling its silhouette row by row. */
function SignFolderOpenFill(props: Omit<SignProps, "shape" | "variant">) {
  return <Sign shape={shape} variant="fill" {...props} />
}

export { SignFolderOpenFill }
