import { Sign, type SignProps, type SignShape } from "@/registry/0nlytype/ui/sign"

// Generated by scripts/build-signs.mjs from Lucide's medal (ISC).
const shape: SignShape = {"word":"medal","line":[[["O",12,17,5,180,180]],[["O",12,17,5,180,-180]],[["M",5.1,2.2],["L",5.5,2.1],["L",6,2],["L",18,2],["L",18.5,2.1],["L",18.9,2.2]],[["M",5.1,2.2],["L",11,12]],[["M",13,12],["L",18.9,2.2]],[["M",16.8,15],["L",21.3,7.1],["L",21.6,6.5],["L",21.6,6]],[["M",2.4,6],["L",2.5,6.7],["L",2.7,7.1],["L",7.2,15]],[["M",8,7],["L",16,7]],[["M",2.4,6],["L",2.5,5.6],["L",2.8,4.9],["L",4.5,2.6],["L",5.1,2.2]],[["M",18.9,2.2],["L",19.5,2.6],["L",21.2,4.9],["L",21.5,5.6],["L",21.6,6]],[["M",12,16.3],["L",12,18]],[["M",11.5,16],["L",12,16],["L",12,16.3]]]}

/** The sign for "medal": the word set along its strokes. */
function SignMedalWords(props: Omit<SignProps, "shape" | "variant">) {
  return <Sign shape={shape} variant="words" {...props} />
}

export { SignMedalWords }
