import { Sign, type SignProps, type SignShape } from "@/registry/0nlytype/ui/sign"

// Generated by scripts/build-signs.mjs from Lucide's type (ISC).
const shape: SignShape = {"word":"type","fill":{"step":2.1,"rows":[[2.6,3.5,20.5],[4.7,1.7,10.5,13.5,22.3],[6.8,1.6,6.4,9.5,11,13,14.5,17.6,22.4],[8.9,9.5,14.5],[11,9.5,14.5],[13.1,9.5,14.5],[15.2,9.5,14.5],[17.3,9.5,11,13,14.5],[19.4,6.9,10.5,13.5,17.1],[21.5,7.7,16.3]]}}

/** The sign for "type": the word filling its silhouette row by row. */
function SignTypeFill(props: Omit<SignProps, "shape" | "variant">) {
  return <Sign shape={shape} variant="fill" {...props} />
}

export { SignTypeFill }
