import { Sign, type SignProps, type SignShape } from "@/registry/0nlytype/ui/sign"

// Generated by scripts/build-signs.mjs from Lucide's dice-5 (ISC).
const shape: SignShape = {"word":"dice","fill":{"step":2.09,"rows":[[1.5,3.2,20.8],[3.6,1,23],[5.7,0.5,23.5],[7.8,0.5,6.5,9.5,14.5,17.5,23.5],[9.9,0.5,7.3,8.7,15.3,16.7,23.5],[12,0.5,10.5,13.5,23.5],[14.1,0.5,7.3,8.7,15.3,16.7,23.5],[16.2,0.5,6.5,9.5,14.5,17.5,23.5],[18.3,0.5,23.5],[20.4,1,23],[22.5,3.2,20.8]]}}

/** The sign for "dice": the word filling its silhouette row by row. */
function SignDiceFill(props: Omit<SignProps, "shape" | "variant">) {
  return <Sign shape={shape} variant="fill" {...props} />
}

export { SignDiceFill }
