import { Sign, type SignProps, type SignShape } from "@/registry/0nlytype/ui/sign"

// Generated by scripts/build-signs.mjs from Lucide's kanban (ISC).
const shape: SignShape = {"word":"board","line":[[["M",19,3],["L",19,21]],[["M",5,17],["L",5,3]],[["M",12,3],["L",12,11]]]}

/** The sign for "board": the word set along its strokes. */
function SignKanbanWords(props: Omit<SignProps, "shape" | "variant">) {
  return <Sign shape={shape} variant="words" {...props} />
}

export { SignKanbanWords }
