import { Sign, type SignProps, type SignShape } from "@/registry/0nlytype/ui/sign"

// Generated by scripts/build-signs.mjs from Lucide's bell-off (ISC).
const shape: SignShape = {"word":"snooze","fill":{"step":2.18,"rows":[[1.1,0.1,3.9,8.2,15.7],[3.3,0.4,6.1,6.3,18.6],[5.5,2.6,5.6,7.6,19.8],[7.6,3.5,5.6,9.8,20.4],[9.8,3.5,7.7,12,20.5],[12,3.1,9.8,14.2,21.1],[14.2,1.6,12,16.3,22.1],[16.4,0.7,8.7,17.4,20.5],[18.5,2.7,9.3,14.5,21.4],[20.7,8,16,17.9,23.6],[22.9,9.3,14.7,20.1,23.9]]}}

/** The sign for "snooze": the word filling its silhouette row by row. */
function SignBellOffFill(props: Omit<SignProps, "shape" | "variant">) {
  return <Sign shape={shape} variant="fill" {...props} />
}

export { SignBellOffFill }
