import { Sign, type SignProps, type SignShape } from "@/registry/0nlytype/ui/sign"

// Generated by scripts/build-signs.mjs from Lucide's arrow-up (ISC).
const shape: SignShape = {"word":"up","fill":{"step":2.11,"rows":[[3.6,10.7,13.3],[5.7,8.5,10.9,13.1,15.5],[7.8,6.4,10.9,13.1,17.6],[9.9,4.2,10.9,13.1,19.8],[12,2.6,7.9,9.5,14.5,16.1,21.4],[14.1,9.5,14.5],[16.2,9.5,14.5],[18.3,9.5,14.5],[20.4,10.7,13.3]]}}

/** The sign for "up": the word filling its silhouette row by row. */
function SignArrowUpFill(props: Omit<SignProps, "shape" | "variant">) {
  return <Sign shape={shape} variant="fill" {...props} />
}

export { SignArrowUpFill }
