import { Sign, type SignProps, type SignShape } from "@/registry/0nlytype/ui/sign"

// Generated by scripts/build-signs.mjs from Lucide's video (ISC).
const shape: SignShape = {"word":"video","line":[[["M",2.5,6.7],["L",2.9,6.4],["L",3.3,6.1],["L",4,6],["L",14,6],["L",14.7,6.1],["L",15.3,6.5]],[["M",2.7,17.5],["L",3.3,17.9],["L",4,18],["L",14,18],["L",14.5,17.9],["L",14.9,17.8],["L",15.5,17.3]],[["M",15.3,6.5],["L",15.8,7.1],["L",15.9,7.5],["L",16,8],["L",16,16],["L",15.9,16.7],["L",15.5,17.3]],[["M",2.7,17.5],["L",2.2,16.9],["L",2.1,16.5],["L",2,16],["L",2,8],["L",2.1,7.3],["L",2.5,6.7]],[["M",21.7,7.4],["L",22,7.7],["L",22,7.9],["L",22,16.1],["L",22,16.3],["L",21.8,16.4],["L",21.7,16.5]],[["M",16,13],["L",21.2,16.5],["L",21.4,16.6],["L",21.6,16.5],["L",21.7,16.5]],[["M",16,10.5],["L",21.2,7.4],["L",21.4,7.4],["L",21.7,7.4]]]}

/** The sign for "video": the word set along its strokes. */
function SignVideoWords(props: Omit<SignProps, "shape" | "variant">) {
  return <Sign shape={shape} variant="words" {...props} />
}

export { SignVideoWords }
