import { Sign, type SignProps, type SignShape } from "@/registry/0nlytype/ui/sign"

// Generated by scripts/build-signs.mjs from Lucide's underline (ISC).
const shape: SignShape = {"word":"underline","line":[[["M",6,4],["L",6,10.5],["L",6.1,11],["L",6.2,11.7],["L",6.6,12.6],["L",7,13.3],["L",7.4,13.9],["L",8.1,14.6],["L",8.7,15],["L",9.6,15.5],["L",10.3,15.8],["L",11.3,16],["L",12,16],["L",12.7,16],["L",13.7,15.8],["L",14.4,15.5],["L",15.3,15],["L",15.9,14.6],["L",16.4,14.1],["L",17,13.3],["L",17.4,12.6],["L",17.7,11.9],["L",17.8,11.5],["L",18,10.5],["L",18,4]],[["M",4,20],["L",20,20]]]}

/** The sign for "underline": the word ruled in leaders along its strokes. */
function SignUnderlineDots(props: Omit<SignProps, "shape" | "variant">) {
  return <Sign shape={shape} variant="dots" {...props} />
}

export { SignUnderlineDots }
