import { Sign, type SignProps, type SignShape } from "@/registry/0nlytype/ui/sign"

// Generated by scripts/build-signs.mjs from Lucide's triangle-alert (ISC).
const shape: SignShape = {"word":"warning","line":[[["M",2.2,19.9],["L",2,19.4],["L",2,18.9],["L",2.1,18.5],["L",2.3,18],["L",10.3,4],["L",10.5,3.6],["L",10.9,3.3],["L",11.4,3.1],["L",11.6,3],["L",12.1,3]],[["M",12.1,3],["L",12.6,3.1],["L",13.1,3.3],["L",13.4,3.6],["L",13.7,4],["L",21.7,18],["L",21.8,18.2],["L",22,18.7],["L",22,19.2],["L",21.9,19.7],["L",21.7,20.1]],[["M",2.2,19.9],["L",2.3,20.1],["L",2.6,20.5],["L",3,20.8],["L",3.5,20.9],["L",4,21],["L",20,21],["L",20.5,20.9],["L",20.9,20.8],["L",21.3,20.5],["L",21.7,20.1]],[["M",12,9],["L",12,13]],[["M",12,17],["L",12,17]]]}

/** The sign for "warning": the word set along its strokes. */
function SignTriangleAlertWords(props: Omit<SignProps, "shape" | "variant">) {
  return <Sign shape={shape} variant="words" {...props} />
}

export { SignTriangleAlertWords }
