import { Sign, type SignProps, type SignShape } from "@/registry/0nlytype/ui/sign"

// Generated by scripts/build-signs.mjs from Lucide's camera (ISC).
const shape: SignShape = {"word":"photo","fill":{"step":2.1,"rows":[[2.6,8.2,15.8],[4.7,6.1,18],[6.8,0.6,23.3],[8.9,0,10,14,24],[11,0,8.2,15.8,24],[13.1,0,8,10.2,13.8,16,24],[15.2,0,8.2,15.8,24],[17.3,0,10.2,13.8,24],[19.4,0,24],[21.5,2.2,21.8]]}}

/** The sign for "photo": the word filling its silhouette row by row. */
function SignCameraFill(props: Omit<SignProps, "shape" | "variant">) {
  return <Sign shape={shape} variant="fill" {...props} />
}

export { SignCameraFill }
