import { Sign, type SignProps, type SignShape } from "@/registry/0nlytype/ui/sign"

// Generated by scripts/build-signs.mjs from Lucide's gem (ISC).
const shape: SignShape = {"word":"gem","fill":{"step":2.14,"rows":[[1.6,5.2,18.8],[3.7,2.8,8.8,11.3,12.7,15.2,21.2],[5.8,1.3,7.9,10.7,13.3,16.1,22.7],[8,0,1.8,22,24],[10.1,0,1.8,21.9,24],[12.3,1.3,7.7,10.3,13.7,16.3,22.7],[14.4,2.8,8.3,10.9,13.1,15.7,21.2],[16.5,4.4,9,11.6,12.4,15,19.6],[18.7,6,9.7,14.3,18],[20.8,7.5,10.3,13.7,16.5],[22.9,9.4,14.6]]}}

/** The sign for "gem": the word filling its silhouette row by row. */
function SignGemFill(props: Omit<SignProps, "shape" | "variant">) {
  return <Sign shape={shape} variant="fill" {...props} />
}

export { SignGemFill }
