import { Sign, type SignProps, type SignShape } from "@/registry/0nlytype/ui/sign"

// Generated by scripts/build-signs.mjs from Lucide's star (ISC).
const shape: SignShape = {"word":"star","fill":{"step":2.15,"rows":[[1.1,9.9,14.1],[3.2,8.6,15.4],[5.4,7.6,16.4],[7.5,0.9,23.1],[9.7,0,24],[11.8,1.3,22.7],[13.9,3.6,20.4],[16.1,4,20],[18.2,3.6,20.4],[20.4,3.3,11.8,12.2,20.7],[22.5,4.7,7.5,16.5,19.3]]}}

/** The sign for "star": the word filling its silhouette row by row. */
function SignStarFill(props: Omit<SignProps, "shape" | "variant">) {
  return <Sign shape={shape} variant="fill" {...props} />
}

export { SignStarFill }
