import { Sign, type SignProps, type SignShape } from "@/registry/0nlytype/ui/sign"

// Generated by scripts/build-signs.mjs from Lucide's trash-2 (ISC).
const shape: SignShape = {"word":"delete","line":[[["M",3,6],["L",21,6]],[["M",5.7,21.5],["L",5.2,20.9],["L",5.1,20.5],["L",5,20],["L",5,6]],[["M",19,6],["L",19,20],["L",18.9,20.7],["L",18.5,21.3]],[["M",5.7,21.5],["L",6.3,21.9],["L",7,22],["L",17,22],["L",17.5,21.9],["L",17.9,21.8],["L",18.5,21.3]],[["M",8.5,2.7],["L",8.9,2.4],["L",9.3,2.1],["L",10,2],["L",14.2,2],["L",14.9,2.2],["L",15.3,2.5]],[["M",10,17],["L",10,11]],[["M",14,11],["L",14,17]],[["M",15.3,2.5],["L",15.8,3.1],["L",15.9,3.5],["L",16,4],["L",16,6]],[["M",8,6],["L",8,3.8],["L",8.1,3.3],["L",8.5,2.7]]]}

/** The sign for "delete": the word set along its strokes. */
function SignTrashWords(props: Omit<SignProps, "shape" | "variant">) {
  return <Sign shape={shape} variant="words" {...props} />
}

export { SignTrashWords }
