import { Sign, type SignProps, type SignShape } from "@/registry/0nlytype/ui/sign"

// Generated by scripts/build-signs.mjs from Lucide's keyboard (ISC).
const shape: SignShape = {"word":"keys","fill":{"step":2.1,"rows":[[2.6,2.2,21.8],[4.7,0,24],[6.8,0,4.6,7.4,8.6,11.4,12.6,15.4,16.6,19.4,24],[8.9,0,4.5,7.5,8.5,11.5,12.5,15.5,16.5,19.5,24],[11,0,6.6,9.4,10.6,13.4,14.6,17.4,24],[13.1,0,6.6,9.4,10.6,13.4,14.6,17.4,24],[15.2,0,6,18,24],[17.3,0,6.1,17.9,24],[19.4,0,24],[21.5,2.2,21.8]]}}

/** The sign for "keys": the word filling its silhouette row by row. */
function SignKeyboardFill(props: Omit<SignProps, "shape" | "variant">) {
  return <Sign shape={shape} variant="fill" {...props} />
}

export { SignKeyboardFill }
