import { Sign, type SignProps, type SignShape } from "@/registry/0nlytype/ui/sign"

// Generated by scripts/build-signs.mjs from Lucide's align-center (ISC).
const shape: SignShape = {"word":"centre","line":[[["M",3,5],["L",21,5]],[["M",5,19],["L",19,19]],[["M",7,12],["L",17,12]]]}

/** The sign for "centre": the word ruled in leaders along its strokes. */
function SignAlignCenterDots(props: Omit<SignProps, "shape" | "variant">) {
  return <Sign shape={shape} variant="dots" {...props} />
}

export { SignAlignCenterDots }
