import { Sign, type SignProps, type SignShape } from "@/registry/0nlytype/ui/sign"

// Generated by scripts/build-signs.mjs from Lucide's map-pin (ISC).
const shape: SignShape = {"word":"place","fill":{"step":2.18,"rows":[[1.1,7.8,16.2],[3.3,4.6,19.4],[5.5,3,11.1,12.9,21],[7.6,2,8.3,15.7,22],[9.8,1.6,8,10.2,13.8,16,22.4],[12,1.9,8.2,15.8,22.1],[14.2,2.7,10,14,21.3],[16.4,3.9,20.1],[18.5,5.5,18.5],[20.7,7.3,16.7],[22.9,9.7,14.3]]}}

/** The sign for "place": the word filling its silhouette row by row. */
function SignMapPinFill(props: Omit<SignProps, "shape" | "variant">) {
  return <Sign shape={shape} variant="fill" {...props} />
}

export { SignMapPinFill }
