import { Sign, type SignProps, type SignShape } from "@/registry/0nlytype/ui/sign"

// Generated by scripts/build-signs.mjs from Lucide's box (ISC).
const shape: SignShape = {"word":"box","line":[[["M",12.1,2],["L",12.6,2.1],["L",13,2.3],["L",20,6.3],["L",20.4,6.5],["L",20.8,7.1]],[["M",3.3,6.9],["L",3.6,6.5],["L",4,6.3],["L",11,2.3],["L",11.7,2],["L",12.1,2]],[["M",11.9,22],["L",12.3,22],["L",13,21.7],["L",20,17.7],["L",20.4,17.5],["L",20.7,17.1]],[["M",3.2,16.9],["L",3.5,17.3],["L",4,17.7],["L",11,21.7],["L",11.4,21.9],["L",11.9,22]],[["M",3.2,16.9],["L",3.1,16.5],["L",3,16],["L",3,8],["L",3.1,7.3],["L",3.3,6.9]],[["M",20.8,7.1],["L",20.9,7.5],["L",21,8],["L",21,16],["L",20.9,16.5],["L",20.7,17.1]],[["M",3.3,7],["L",12,12]],[["M",12,12],["L",20.7,7]],[["M",12,12],["L",12,22]]]}

/** The sign for "box": the word ruled in leaders along its strokes. */
function SignBoxDots(props: Omit<SignProps, "shape" | "variant">) {
  return <Sign shape={shape} variant="dots" {...props} />
}

export { SignBoxDots }
