import { Sign, type SignProps, type SignShape } from "@/registry/0nlytype/ui/sign"

// Generated by scripts/build-signs.mjs from Lucide's navigation (ISC).
const shape: SignShape = {"word":"route","fill":{"step":2.14,"rows":[[1.1,19.6,23.9],[3.2,14.9,23.9],[5.3,10.5,22.8],[7.5,6.1,21.8],[9.6,1.5,20.8],[11.8,1,19.8],[13.9,6.7,18.8],[16,9.4,17.8],[18.2,9.9,16.8],[20.3,10.4,15.8],[22.4,11.7,14.3]]}}

/** The sign for "route": the word filling its silhouette row by row. */
function SignNavigationFill(props: Omit<SignProps, "shape" | "variant">) {
  return <Sign shape={shape} variant="fill" {...props} />
}

export { SignNavigationFill }
