import { Sign, type SignProps, type SignShape } from "@/registry/0nlytype/ui/sign"

// Generated by scripts/build-signs.mjs from Lucide's timer (ISC).
const shape: SignShape = {"word":"timer","line":[[["O",12,14,8,180,180]],[["O",12,14,8,180,-180]],[["M",12,14],["L",15,11]],[["M",10,2],["L",14,2]]]}

/** The sign for "timer": the word ruled in leaders along its strokes. */
function SignTimerDots(props: Omit<SignProps, "shape" | "variant">) {
  return <Sign shape={shape} variant="dots" {...props} />
}

export { SignTimerDots }
