import { Sign, type SignProps, type SignShape } from "@/registry/0nlytype/ui/sign"

// Generated by scripts/build-signs.mjs from Lucide's scissors (ISC).
const shape: SignShape = {"word":"cut","fill":{"step":2.09,"rows":[[1.5,4,8],[3.6,1.4,10.6,17.5,22.2],[5.7,0.6,11.4,15.4,21.1],[7.8,1.1,11.3,13.3,19.1],[9.9,2.9,10.4,12.6,17],[12,8.5,10,13.6,15.5],[14.1,2.9,11,12.5,17],[16.2,1.1,11.3,13.3,19.1],[18.3,0.6,11.4,15.4,21.1],[20.4,1.4,10.6,17.5,22.2],[22.5,4,8]]}}

/** The sign for "cut": the word filling its silhouette row by row. */
function SignScissorsFill(props: Omit<SignProps, "shape" | "variant">) {
  return <Sign shape={shape} variant="fill" {...props} />
}

export { SignScissorsFill }
