import { Sign, type SignProps, type SignShape } from "@/registry/0nlytype/ui/sign"

// Generated by scripts/build-signs.mjs from Lucide's chevron-left (ISC).
const shape: SignShape = {"word":"before","line":[[["M",9,12],["L",15,18]],[["M",9,12],["L",15,6]]],"mirror":true}

/** The sign for "before": the word set along its strokes. */
function SignChevronLeftWords(props: Omit<SignProps, "shape" | "variant">) {
  return <Sign shape={shape} variant="words" {...props} />
}

export { SignChevronLeftWords }
