import { Sign, type SignProps, type SignShape } from "@/registry/0nlytype/ui/sign"

// Generated by scripts/build-signs.mjs from Lucide's moon (ISC).
const shape: SignShape = {"word":"night","fill":{"step":2.09,"rows":[[1.5,9,13],[3.6,5,14.4],[5.7,2.8,13.5],[7.8,1.6,13.5],[9.9,0.9,14.3],[12,0.5,23.2],[14.1,0.9,23.1],[16.2,1.6,22.4],[18.3,2.8,21.1],[20.4,4.9,19.2],[22.5,9,15.1]]}}

/** The sign for "night": the word filling its silhouette row by row. */
function SignMoonFill(props: Omit<SignProps, "shape" | "variant">) {
  return <Sign shape={shape} variant="fill" {...props} />
}

export { SignMoonFill }
