import { Sign, type SignProps, type SignShape } from "@/registry/0nlytype/ui/sign"

// Generated by scripts/build-signs.mjs from Lucide's globe (ISC).
const shape: SignShape = {"word":"world","line":[[["O",12,12,10,180,180]],[["O",12,12,10,180,-180]],[["M",2,12],["L",22,12]],[["M",8,12],["L",8.1,13.4],["L",8.3,14.8],["L",8.6,16.3],["L",9.1,17.4],["L",9.6,18.6],["L",10.3,19.9],["L",11,20.9],["L",12,22]],[["M",8,12],["L",8.1,10.6],["L",8.3,9.2],["L",8.6,7.7],["L",9.1,6.6],["L",9.6,5.4],["L",10.3,4.1],["L",11.2,2.9],["L",12,2]],[["M",12,22],["L",12.8,21.1],["L",13.7,19.9],["L",14.3,18.8],["L",14.9,17.4],["L",15.4,16.3],["L",15.7,14.8],["L",15.9,13.4],["L",16,12]],[["M",12,2],["L",12.8,2.9],["L",13.7,4.1],["L",14.3,5.2],["L",14.9,6.6],["L",15.4,7.7],["L",15.7,9.2],["L",15.9,10.6],["L",16,12]]]}

/** The sign for "world": the word ruled in leaders along its strokes. */
function SignGlobeDots(props: Omit<SignProps, "shape" | "variant">) {
  return <Sign shape={shape} variant="dots" {...props} />
}

export { SignGlobeDots }
