import { Sign, type SignProps, type SignShape } from "@/registry/0nlytype/ui/sign"

// Generated by scripts/build-signs.mjs from Lucide's arrow-down (ISC).
const shape: SignShape = {"word":"down","fill":{"step":2.11,"rows":[[3.6,10.7,13.3],[5.7,9.5,14.5],[7.8,9.5,14.5],[9.9,9.5,14.5],[12,2.6,7.9,9.5,14.5,16.1,21.4],[14.1,4.2,10.9,13.1,19.8],[16.2,6.4,10.9,13.1,17.6],[18.3,8.5,10.9,13.1,15.5],[20.4,10.7,13.3]]}}

/** The sign for "down": the word filling its silhouette row by row. */
function SignArrowDownFill(props: Omit<SignProps, "shape" | "variant">) {
  return <Sign shape={shape} variant="fill" {...props} />
}

export { SignArrowDownFill }
