import { Sign, type SignProps, type SignShape } from "@/registry/0nlytype/ui/sign"

// Generated by scripts/build-signs.mjs from Lucide's laptop (ISC).
const shape: SignShape = {"word":"laptop","fill":{"step":2,"rows":[[3.5,4.2,19.8],[5.5,2.1,21.9],[7.5,1.6,22.5],[9.5,1.5,22.5],[11.5,1.5,22.5],[13.5,1.5,22.5],[15.5,1.5,3.6,20.4,22.5],[17.5,0.8,4.2,19.8,23.2],[19.5,0.3,23.7],[21.5,2.1,21.9]]}}

/** The sign for "laptop": the word filling its silhouette row by row. */
function SignLaptopFill(props: Omit<SignProps, "shape" | "variant">) {
  return <Sign shape={shape} variant="fill" {...props} />
}

export { SignLaptopFill }
