import { Sign, type SignProps, type SignShape } from "@/registry/0nlytype/ui/sign"

// Generated by scripts/build-signs.mjs from Lucide's bell (ISC).
const shape: SignShape = {"word":"notify","fill":{"step":2.18,"rows":[[1.1,8.2,15.8],[3.3,5.5,18.5],[5.5,4.2,19.8],[7.6,3.6,20.4],[9.8,3.5,20.5],[12,3.1,20.9],[14.2,1.6,22.4],[16.4,0.7,8.7,15.1,23.3],[18.5,2.7,9.3,14.5,21.3],[20.7,8,16],[22.9,9.3,14.7]]}}

/** The sign for "notify": the word filling its silhouette row by row. */
function SignBellFill(props: Omit<SignProps, "shape" | "variant">) {
  return <Sign shape={shape} variant="fill" {...props} />
}

export { SignBellFill }
