import { Sign, type SignProps, type SignShape } from "@/registry/0nlytype/ui/sign"

// Generated by scripts/build-signs.mjs from Lucide's eraser (ISC).
const shape: SignShape = {"word":"erase","fill":{"step":2.09,"rows":[[1.5,12.3,15.7],[3.6,9.7,18.3],[5.7,7.6,20.4],[7.8,5.5,22.5],[9.9,3.4,24],[12,1.3,4.6,8.1,24],[14.1,0,6,10.2,22.6],[16.2,0,8.1,12.3,20.5],[18.3,1.6,10.1,16.8,19],[20.4,3.7,12.2,15.6,23.1],[22.5,6.2,22.3]]}}

/** The sign for "erase": the word filling its silhouette row by row. */
function SignEraserFill(props: Omit<SignProps, "shape" | "variant">) {
  return <Sign shape={shape} variant="fill" {...props} />
}

export { SignEraserFill }
