import { Sign, type SignProps, type SignShape } from "@/registry/0nlytype/ui/sign"

// Generated by scripts/build-signs.mjs from Lucide's hammer (ISC).
const shape: SignShape = {"word":"build","fill":{"step":2.14,"rows":[[1.6,7.7,15],[3.7,6.9,18.6],[5.8,8.9,20.6],[8,9.5,11.1,12.9,21.4],[10.1,8,10.5,14.3,24],[12.3,5.9,12.1,15.9,23.6],[14.4,3.8,21.5],[16.5,1.6,13.2,16.9,19.1],[18.7,0,11.1],[20.8,0,9],[22.9,1.4,6.7]]}}

/** The sign for "build": the word filling its silhouette row by row. */
function SignHammerFill(props: Omit<SignProps, "shape" | "variant">) {
  return <Sign shape={shape} variant="fill" {...props} />
}

export { SignHammerFill }
