import { Sign, type SignProps, type SignShape } from "@/registry/0nlytype/ui/sign"

// Generated by scripts/build-signs.mjs from Lucide's fish (ISC).
const shape: SignShape = {"word":"fish","fill":{"step":2.09,"rows":[[1.5,6.7,15.6],[3.6,5.6,7.8,10.3,17.7],[5.7,0.2,4.9,6.6,8.4,16.9,20.2],[7.8,0,4.7,16.5,22.4],[9.9,0,5.8,9.4,13,15.5,23.6],[12,0.2,5.4,7.9,12.9,15.1,16.5,19.5,24],[14.1,0,5.8,9.3,13,15.5,17.1,18.9,23.6],[16.2,0,5.7,16.5,22.4],[18.3,0.2,7.3,8.3,9.5,16.9,20.2],[20.4,7.4,17.7],[22.5,8.2,15.6]]}}

/** The sign for "fish": the word filling its silhouette row by row. */
function SignFishFill(props: Omit<SignProps, "shape" | "variant">) {
  return <Sign shape={shape} variant="fill" {...props} />
}

export { SignFishFill }
