import { Sign, type SignProps, type SignShape } from "@/registry/0nlytype/ui/sign"

// Generated by scripts/build-signs.mjs from Lucide's skip-forward (ISC).
const shape: SignShape = {"word":"skip","fill":{"step":2.1,"rows":[[2.6,3.2,6.7,19.7,22.3],[4.7,1,10.3,18.5,23.5],[6.8,0.5,13.8,18.5,23.5],[8.9,0.5,17.3,18.5,23.5],[11,0.5,15.5,18.5,23.5],[13.1,0.5,15.5,18.5,23.5],[15.2,0.5,17.3,18.5,23.5],[17.3,0.5,13.8,18.5,23.5],[19.4,1,10.3,18.5,23.5],[21.5,3.2,6.7,19.7,22.3]]}}

/** The sign for "skip": the word filling its silhouette row by row. */
function SignSkipForwardFill(props: Omit<SignProps, "shape" | "variant">) {
  return <Sign shape={shape} variant="fill" {...props} />
}

export { SignSkipForwardFill }
