import { Sign, type SignProps, type SignShape } from "@/registry/0nlytype/ui/sign"

// Generated by scripts/build-signs.mjs from Lucide's frame (ISC).
const shape: SignShape = {"word":"frame","line":[[["M",2,6],["L",22,6]],[["M",2,18],["L",22,18]],[["M",6,22],["L",6,2]],[["M",18,2],["L",18,22]]]}

/** The sign for "frame": the word set along its strokes. */
function SignFrameWords(props: Omit<SignProps, "shape" | "variant">) {
  return <Sign shape={shape} variant="words" {...props} />
}

export { SignFrameWords }
