import { Sign, type SignProps, type SignShape } from "@/registry/0nlytype/ui/sign"

// Generated by scripts/build-signs.mjs from Lucide's gift (ISC).
const shape: SignShape = {"word":"gift","fill":{"step":2.14,"rows":[[1.1,4.6,10.6,13.5,19.3],[3.2,2.9,10.1,13.7,21.1],[5.3,2.5,4.4,19.6,21.5],[7.5,0.8,3.7,20,23.2],[9.6,0.6,3.5,20.5,23.4],[11.8,1.5,3.2,20.8,22.5],[13.9,1.5,10.9,13.1,22.5],[16,1.5,10.9,13.1,22.5],[18.2,1.5,10.9,13.1,22.5],[20.3,2,10.9,13.1,22],[22.4,4.2,19.8]]}}

/** The sign for "gift": the word filling its silhouette row by row. */
function SignGiftFill(props: Omit<SignProps, "shape" | "variant">) {
  return <Sign shape={shape} variant="fill" {...props} />
}

export { SignGiftFill }
