import { Sign, type SignProps, type SignShape } from "@/registry/0nlytype/ui/sign"

// Generated by scripts/build-signs.mjs from Lucide's upload (ISC).
const shape: SignShape = {"word":"upload","fill":{"step":2.09,"rows":[[1.5,10.7,13.3],[3.6,8.5,10.9,13.1,15.5],[5.7,6.4,10.9,13.1,17.6],[7.8,4.7,10.9,13.1,19.3],[9.9,9.5,14.5],[12,9.5,14.5],[14.1,1,5,9.5,14.5,19,23],[16.2,0.5,5.5,10.3,13.7,18.5,23.5],[18.3,0.5,5.5,18.5,23.5],[20.4,1,23],[22.5,3.2,20.8]]}}

/** The sign for "upload": the word filling its silhouette row by row. */
function SignUploadFill(props: Omit<SignProps, "shape" | "variant">) {
  return <Sign shape={shape} variant="fill" {...props} />
}

export { SignUploadFill }
