import { Sign, type SignProps, type SignShape } from "@/registry/0nlytype/ui/sign"

// Generated by scripts/build-signs.mjs from Lucide's building (ISC).
const shape: SignShape = {"word":"office","fill":{"step":2.18,"rows":[[1.1,3.4,20.6],[3.3,1.7,22.2],[5.5,1.5,6.5,9.5,10.5,13.5,14.5,17.5,22.5],[7.6,1.5,6.9,9.1,10.9,13.1,14.9,17.1,22.5],[9.8,1.5,6.5,9.5,10.5,13.5,14.5,17.5,22.5],[12,1.5,7.3,8.7,11.3,12.7,15.3,16.7,22.5],[14.2,1.5,6.5,9.5,10.5,13.5,14.5,17.5,22.5],[16.4,1.5,9.9,14.1,22.5],[18.5,1.5,7.9,16.1,22.5],[20.7,1.8,7.9,10.1,13.9,16.1,22.3],[22.9,3.4,20.6]]}}

/** The sign for "office": the word filling its silhouette row by row. */
function SignBuildingFill(props: Omit<SignProps, "shape" | "variant">) {
  return <Sign shape={shape} variant="fill" {...props} />
}

export { SignBuildingFill }
