import { Sign, type SignProps, type SignShape } from "@/registry/0nlytype/ui/sign"

// Generated by scripts/build-signs.mjs from Lucide's square (ISC).
const shape: SignShape = {"word":"stop","line":[[["M",3.5,3.7],["L",3.9,3.4],["L",4.3,3.1],["L",5,3],["L",19,3],["L",19.7,3.1],["L",20.3,3.5]],[["M",20.3,3.5],["L",20.8,4.1],["L",20.9,4.5],["L",21,5],["L",21,19],["L",20.9,19.7],["L",20.5,20.3]],[["M",3.7,20.5],["L",4.3,20.9],["L",5,21],["L",19,21],["L",19.5,20.9],["L",19.9,20.8],["L",20.5,20.3]],[["M",3.7,20.5],["L",3.2,19.9],["L",3.1,19.5],["L",3,19],["L",3,5],["L",3.1,4.3],["L",3.5,3.7]]]}

/** The sign for "stop": the word set along its strokes. */
function SignStopWords(props: Omit<SignProps, "shape" | "variant">) {
  return <Sign shape={shape} variant="words" {...props} />
}

export { SignStopWords }
