import { Sign, type SignProps, type SignShape } from "@/registry/0nlytype/ui/sign"

// Generated by scripts/build-signs.mjs from Lucide's library (ISC).
const shape: SignShape = {"word":"library","fill":{"step":2.1,"rows":[[2.6,2.7,5.3],[4.7,1.5,6.5,10.5,13.5,14.5,17.5],[6.8,1.5,10.5,13.5,18.6],[8.9,1.5,6.9,9.1,10.5,13.5,19.2],[11,1.5,6.9,9.1,14.5,15,19.8],[13.1,1.5,6.9,9.1,14.5,15.6,20.4],[15.2,1.5,6.9,9.1,14.5,16.2,21],[17.3,1.5,6.9,9.1,14.5,16.8,21.6],[19.4,1.5,6.9,9.1,14.5,17.4,22.2],[21.5,2.7,5.3,6.7,9.3,10.7,13.3,18.7,21.3]]}}

/** The sign for "library": the word filling its silhouette row by row. */
function SignLibraryFill(props: Omit<SignProps, "shape" | "variant">) {
  return <Sign shape={shape} variant="fill" {...props} />
}

export { SignLibraryFill }
