import { Sign, type SignProps, type SignShape } from "@/registry/0nlytype/ui/sign"

// Generated by scripts/build-signs.mjs from Lucide's sliders-horizontal (ISC).
const shape: SignShape = {"word":"tune","line":[[["M",3,19],["L",12,19]],[["M",12,12],["L",21,12]],[["M",3,5],["L",10,5]],[["M",14,5],["L",21,5]],[["M",16,19],["L",21,19]],[["M",3,12],["L",8,12]],[["M",14,3],["L",14,7]],[["M",16,17],["L",16,21]],[["M",8,14],["L",8,10]]]}

/** The sign for "tune": the word ruled in leaders along its strokes. */
function SignSlidersDots(props: Omit<SignProps, "shape" | "variant">) {
  return <Sign shape={shape} variant="dots" {...props} />
}

export { SignSlidersDots }
