import { Sign, type SignProps, type SignShape } from "@/registry/0nlytype/ui/sign"

// Generated by scripts/build-signs.mjs from Lucide's file (ISC).
const shape: SignShape = {"word":"file","line":[[["M",4.7,21.5],["L",4.2,20.9],["L",4.1,20.5],["L",4,20],["L",4,4],["L",4.1,3.3],["L",4.5,2.7]],[["M",4.7,21.5],["L",5.3,21.9],["L",6,22],["L",18,22],["L",18.5,21.9],["L",18.9,21.8],["L",19.5,21.3]],[["M",19.8,7.1],["L",20,7.5],["L",20,8],["L",20,20],["L",19.9,20.7],["L",19.5,21.3]],[["M",4.5,2.7],["L",4.9,2.4],["L",5.3,2.1],["L",6,2],["L",14,2],["L",14.5,2],["L",14.9,2.2]],[["M",14.9,2.2],["L",15.3,2.4],["L",15.7,2.7],["L",19.3,6.3],["L",19.6,6.7],["L",19.8,7.1]],[["M",14,2],["L",14,7],["L",14.1,7.4],["L",14.3,7.7]],[["M",14.3,7.7],["L",14.6,7.9],["L",15,8],["L",20,8]]]}

/** The sign for "file": the word set along its strokes. */
function SignFileWords(props: Omit<SignProps, "shape" | "variant">) {
  return <Sign shape={shape} variant="words" {...props} />
}

export { SignFileWords }
