import { Sign, type SignProps, type SignShape } from "@/registry/0nlytype/ui/sign"

// Generated by scripts/build-signs.mjs from Lucide's laptop (ISC).
const shape: SignShape = {"word":"laptop","line":[[["M",2.8,19.6],["L",3.2,19.9],["L",3.6,20],["L",20.4,20],["L",20.8,19.9],["L",21.2,19.6],["L",21.3,19.4]],[["M",3.9,16],["L",20.1,16]],[["M",4.5,5.7],["L",4.9,5.4],["L",5.3,5.1],["L",6,5],["L",18,5],["L",18.7,5.1],["L",19.3,5.5]],[["M",19.3,5.5],["L",19.8,6.1],["L",20,6.8],["L",20,15.8],["L",20.2,16.4],["L",21.4,18.8],["L",21.4,19.2],["L",21.3,19.4]],[["M",2.8,19.6],["L",2.6,19.2],["L",2.6,18.8],["L",3.8,16.4],["L",4,15.8],["L",4,7],["L",4.1,6.3],["L",4.5,5.7]]]}

/** The sign for "laptop": the word ruled in leaders along its strokes. */
function SignLaptopDots(props: Omit<SignProps, "shape" | "variant">) {
  return <Sign shape={shape} variant="dots" {...props} />
}

export { SignLaptopDots }
