// Generated by scripts/build-registry.mjs. Every item's docs meta and example, in registry order.
import linkMeta from "@/content/link"
import * as linkExample from "@/examples/link"
import metaMeta from "@/content/meta"
import * as metaExample from "@/examples/meta"
import kbdMeta from "@/content/kbd"
import * as kbdExample from "@/examples/kbd"
import cornersMeta from "@/content/corners"
import * as cornersExample from "@/examples/corners"
import buttonMeta from "@/content/button"
import * as buttonExample from "@/examples/button"
import spinnerMeta from "@/content/spinner"
import * as spinnerExample from "@/examples/spinner"
import checkboxMeta from "@/content/checkbox"
import * as checkboxExample from "@/examples/checkbox"
import fractionMeta from "@/content/fraction"
import * as fractionExample from "@/examples/fraction"
import radioGroupMeta from "@/content/radio-group"
import * as radioGroupExample from "@/examples/radio-group"
import dialMeta from "@/content/dial"
import * as dialExample from "@/examples/dial"
import picksMeta from "@/content/picks"
import * as picksExample from "@/examples/picks"
import switchMeta from "@/content/switch"
import * as switchExample from "@/examples/switch"
import sliderMeta from "@/content/slider"
import * as sliderExample from "@/examples/slider"
import fieldMeta from "@/content/field"
import * as fieldExample from "@/examples/field"
import selectMeta from "@/content/select"
import * as selectExample from "@/examples/select"
import tabsMeta from "@/content/tabs"
import * as tabsExample from "@/examples/tabs"
import paginationMeta from "@/content/pagination"
import * as paginationExample from "@/examples/pagination"
import breadcrumbMeta from "@/content/breadcrumb"
import * as breadcrumbExample from "@/examples/breadcrumb"
import accordionMeta from "@/content/accordion"
import * as accordionExample from "@/examples/accordion"
import rowsMeta from "@/content/rows"
import * as rowsExample from "@/examples/rows"
import calendarMeta from "@/content/calendar"
import * as calendarExample from "@/examples/calendar"
import badgeMeta from "@/content/badge"
import * as badgeExample from "@/examples/badge"
import noteMeta from "@/content/note"
import * as noteExample from "@/examples/note"
import progressMeta from "@/content/progress"
import * as progressExample from "@/examples/progress"
import toastMeta from "@/content/toast"
import * as toastExample from "@/examples/toast"
import dialogMeta from "@/content/dialog"
import * as dialogExample from "@/examples/dialog"
import emptyMeta from "@/content/empty"
import * as emptyExample from "@/examples/empty"
import toggleMeta from "@/content/toggle"
import * as toggleExample from "@/examples/toggle"
import toggleGroupMeta from "@/content/toggle-group"
import * as toggleGroupExample from "@/examples/toggle-group"
import buttonGroupMeta from "@/content/button-group"
import * as buttonGroupExample from "@/examples/button-group"
import inputGroupMeta from "@/content/input-group"
import * as inputGroupExample from "@/examples/input-group"
import inputOtpMeta from "@/content/input-otp"
import * as inputOtpExample from "@/examples/input-otp"
import comboboxMeta from "@/content/combobox"
import * as comboboxExample from "@/examples/combobox"
import popoverMeta from "@/content/popover"
import * as popoverExample from "@/examples/popover"
import contextMenuMeta from "@/content/context-menu"
import * as contextMenuExample from "@/examples/context-menu"
import dropdownMenuMeta from "@/content/dropdown-menu"
import * as dropdownMenuExample from "@/examples/dropdown-menu"
import menubarMeta from "@/content/menubar"
import * as menubarExample from "@/examples/menubar"
import navigationMenuMeta from "@/content/navigation-menu"
import * as navigationMenuExample from "@/examples/navigation-menu"
import commandMeta from "@/content/command"
import * as commandExample from "@/examples/command"
import sidebarMeta from "@/content/sidebar"
import * as sidebarExample from "@/examples/sidebar"
import cardMeta from "@/content/card"
import * as cardExample from "@/examples/card"
import hoverCardMeta from "@/content/hover-card"
import * as hoverCardExample from "@/examples/hover-card"
import tooltipMeta from "@/content/tooltip"
import * as tooltipExample from "@/examples/tooltip"
import sheetMeta from "@/content/sheet"
import * as sheetExample from "@/examples/sheet"
import drawerMeta from "@/content/drawer"
import * as drawerExample from "@/examples/drawer"
import collapsibleMeta from "@/content/collapsible"
import * as collapsibleExample from "@/examples/collapsible"
import resizableMeta from "@/content/resizable"
import * as resizableExample from "@/examples/resizable"
import scrollAreaMeta from "@/content/scroll-area"
import * as scrollAreaExample from "@/examples/scroll-area"
import scrollbarMeta from "@/content/scrollbar"
import * as scrollbarExample from "@/examples/scrollbar"
import aspectRatioMeta from "@/content/aspect-ratio"
import * as aspectRatioExample from "@/examples/aspect-ratio"
import carouselMeta from "@/content/carousel"
import * as carouselExample from "@/examples/carousel"
import tableMeta from "@/content/table"
import * as tableExample from "@/examples/table"
import chartMeta from "@/content/chart"
import * as chartExample from "@/examples/chart"
import avatarMeta from "@/content/avatar"
import * as avatarExample from "@/examples/avatar"
import itemMeta from "@/content/item"
import * as itemExample from "@/examples/item"
import typographyMeta from "@/content/typography"
import * as typographyExample from "@/examples/typography"
import messageMeta from "@/content/message"
import * as messageExample from "@/examples/message"
import markerMeta from "@/content/marker"
import * as markerExample from "@/examples/marker"
import attachmentMeta from "@/content/attachment"
import * as attachmentExample from "@/examples/attachment"
import threadMeta from "@/content/thread"
import * as threadExample from "@/examples/thread"
import questionnaireMeta from "@/content/questionnaire"
import * as questionnaireExample from "@/examples/questionnaire"
import alertMeta from "@/content/alert"
import * as alertExample from "@/examples/alert"
import skeletonMeta from "@/content/skeleton"
import * as skeletonExample from "@/examples/skeleton"
import datePickerMeta from "@/content/date-picker"
import * as datePickerExample from "@/examples/date-picker"
import activityFeedMeta from "@/content/activity-feed"
import * as activityFeedExample from "@/examples/activity-feed"
import agentChatMeta from "@/content/agent-chat"
import * as agentChatExample from "@/examples/agent-chat"
import agentStateMeta from "@/content/agent-state"
import * as agentStateExample from "@/examples/agent-state"
import appearanceMeta from "@/content/appearance"
import * as appearanceExample from "@/examples/appearance"
import areaChartMeta from "@/content/area-chart"
import * as areaChartExample from "@/examples/area-chart"
import calligramMeta from "@/content/calligram"
import * as calligramExample from "@/examples/calligram"
import commandLineMeta from "@/content/command-line"
import * as commandLineExample from "@/examples/command-line"
import contourMeta from "@/content/contour"
import * as contourExample from "@/examples/contour"
import dataTableMeta from "@/content/data-table"
import * as dataTableExample from "@/examples/data-table"
import dropzoneMeta from "@/content/dropzone"
import * as dropzoneExample from "@/examples/dropzone"
import figureMeta from "@/content/figure"
import * as figureExample from "@/examples/figure"
import formMeta from "@/content/form"
import * as formExample from "@/examples/form"
import gatherMeta from "@/content/gather"
import * as gatherExample from "@/examples/gather"
import gridMeta from "@/content/grid"
import * as gridExample from "@/examples/grid"
import lineChartMeta from "@/content/line-chart"
import * as lineChartExample from "@/examples/line-chart"
import marqueeMeta from "@/content/marquee"
import * as marqueeExample from "@/examples/marquee"
import measureMeta from "@/content/measure"
import * as measureExample from "@/examples/measure"
import melodyMeta from "@/content/melody"
import * as melodyExample from "@/examples/melody"
import modeToggleMeta from "@/content/mode-toggle"
import * as modeToggleExample from "@/examples/mode-toggle"
import numberInputMeta from "@/content/number-input"
import * as numberInputExample from "@/examples/number-input"
import pieChartMeta from "@/content/pie-chart"
import * as pieChartExample from "@/examples/pie-chart"
import radarChartMeta from "@/content/radar-chart"
import * as radarChartExample from "@/examples/radar-chart"
import radialChartMeta from "@/content/radial-chart"
import * as radialChartExample from "@/examples/radial-chart"
import readingTrailMeta from "@/content/reading-trail"
import * as readingTrailExample from "@/examples/reading-trail"
import reverbMeta from "@/content/reverb"
import * as reverbExample from "@/examples/reverb"
import scrollExpandMeta from "@/content/scroll-expand"
import * as scrollExpandExample from "@/examples/scroll-expand"
import segueMeta from "@/content/segue"
import * as segueExample from "@/examples/segue"
import sourceMeta from "@/content/source"
import * as sourceExample from "@/examples/source"
import statMeta from "@/content/stat"
import * as statExample from "@/examples/stat"
import stepsMeta from "@/content/steps"
import * as stepsExample from "@/examples/steps"
import swapyMeta from "@/content/swapy"
import * as swapyExample from "@/examples/swapy"
import textRibbonMeta from "@/content/text-ribbon"
import * as textRibbonExample from "@/examples/text-ribbon"
import tilingMeta from "@/content/tiling"
import * as tilingExample from "@/examples/tiling"
import timerMeta from "@/content/timer"
import * as timerExample from "@/examples/timer"
import tourMeta from "@/content/tour"
import * as tourExample from "@/examples/tour"
import treeMeta from "@/content/tree"
import * as treeExample from "@/examples/tree"
import wakeMeta from "@/content/wake"
import * as wakeExample from "@/examples/wake"
import waterfallMeta from "@/content/waterfall"
import * as waterfallExample from "@/examples/waterfall"
import wordRelayMeta from "@/content/word-relay"
import * as wordRelayExample from "@/examples/word-relay"

export const entries = [
  { meta: linkMeta, example: linkExample, siblings: [], npm: ["@radix-ui/react-slot"] },
  { meta: metaMeta, example: metaExample, siblings: [], npm: [] },
  { meta: kbdMeta, example: kbdExample, siblings: [], npm: [] },
  { meta: cornersMeta, example: cornersExample, siblings: [], npm: ["@radix-ui/react-slot"] },
  { meta: buttonMeta, example: buttonExample, siblings: ["spinner"], npm: ["@radix-ui/react-slot"] },
  { meta: spinnerMeta, example: spinnerExample, siblings: [], npm: [] },
  { meta: checkboxMeta, example: checkboxExample, siblings: ["fraction"], npm: [] },
  { meta: fractionMeta, example: fractionExample, siblings: [], npm: [] },
  { meta: radioGroupMeta, example: radioGroupExample, siblings: [], npm: [] },
  { meta: dialMeta, example: dialExample, siblings: [], npm: [] },
  { meta: picksMeta, example: picksExample, siblings: [], npm: [] },
  { meta: switchMeta, example: switchExample, siblings: [], npm: [] },
  { meta: sliderMeta, example: sliderExample, siblings: [], npm: [] },
  { meta: fieldMeta, example: fieldExample, siblings: [], npm: [] },
  { meta: selectMeta, example: selectExample, siblings: [], npm: [] },
  { meta: tabsMeta, example: tabsExample, siblings: [], npm: ["@radix-ui/react-tabs"] },
  { meta: paginationMeta, example: paginationExample, siblings: [], npm: ["@radix-ui/react-slot"] },
  { meta: breadcrumbMeta, example: breadcrumbExample, siblings: [], npm: ["@radix-ui/react-slot"] },
  { meta: accordionMeta, example: accordionExample, siblings: [], npm: [] },
  { meta: rowsMeta, example: rowsExample, siblings: [], npm: ["@radix-ui/react-slot"] },
  { meta: calendarMeta, example: calendarExample, siblings: [], npm: [] },
  { meta: badgeMeta, example: badgeExample, siblings: [], npm: [] },
  { meta: noteMeta, example: noteExample, siblings: [], npm: [] },
  { meta: progressMeta, example: progressExample, siblings: ["fraction"], npm: [] },
  { meta: toastMeta, example: toastExample, siblings: ["button"], npm: [] },
  { meta: dialogMeta, example: dialogExample, siblings: ["scrollbar"], npm: ["@radix-ui/react-slot"] },
  { meta: emptyMeta, example: emptyExample, siblings: ["button"], npm: [] },
  { meta: toggleMeta, example: toggleExample, siblings: [], npm: ["@radix-ui/react-toggle"] },
  { meta: toggleGroupMeta, example: toggleGroupExample, siblings: [], npm: ["@radix-ui/react-toggle-group"] },
  { meta: buttonGroupMeta, example: buttonGroupExample, siblings: ["button"], npm: [] },
  { meta: inputGroupMeta, example: inputGroupExample, siblings: ["button","field"], npm: [] },
  { meta: inputOtpMeta, example: inputOtpExample, siblings: ["field"], npm: [] },
  { meta: comboboxMeta, example: comboboxExample, siblings: ["badge","command","field","popover"], npm: [] },
  { meta: popoverMeta, example: popoverExample, siblings: [], npm: ["@radix-ui/react-popover"] },
  { meta: contextMenuMeta, example: contextMenuExample, siblings: ["dropdown-menu","popover"], npm: ["@radix-ui/react-context-menu"] },
  { meta: dropdownMenuMeta, example: dropdownMenuExample, siblings: ["kbd","popover"], npm: ["@radix-ui/react-dropdown-menu"] },
  { meta: menubarMeta, example: menubarExample, siblings: ["dropdown-menu","popover"], npm: ["@radix-ui/react-menubar"] },
  { meta: navigationMenuMeta, example: navigationMenuExample, siblings: [], npm: ["@radix-ui/react-navigation-menu"] },
  { meta: commandMeta, example: commandExample, siblings: ["scrollbar"], npm: ["@radix-ui/react-dialog","cmdk"] },
  { meta: sidebarMeta, example: sidebarExample, siblings: ["button","scrollbar","sheet"], npm: ["@radix-ui/react-slot"] },
  { meta: cardMeta, example: cardExample, siblings: ["meta"], npm: ["@radix-ui/react-slot"] },
  { meta: hoverCardMeta, example: hoverCardExample, siblings: [], npm: ["@radix-ui/react-hover-card"] },
  { meta: tooltipMeta, example: tooltipExample, siblings: [], npm: ["@radix-ui/react-tooltip"] },
  { meta: sheetMeta, example: sheetExample, siblings: ["dialog"], npm: ["@radix-ui/react-slot"] },
  { meta: drawerMeta, example: drawerExample, siblings: ["dialog","fraction"], npm: [] },
  { meta: collapsibleMeta, example: collapsibleExample, siblings: ["button"], npm: [] },
  { meta: resizableMeta, example: resizableExample, siblings: [], npm: ["@chenglou/pretext"] },
  { meta: scrollAreaMeta, example: scrollAreaExample, siblings: ["scrollbar"], npm: [] },
  { meta: scrollbarMeta, example: scrollbarExample, siblings: [], npm: [] },
  { meta: aspectRatioMeta, example: aspectRatioExample, siblings: [], npm: [] },
  { meta: carouselMeta, example: carouselExample, siblings: [], npm: [] },
  { meta: tableMeta, example: tableExample, siblings: [], npm: [] },
  { meta: chartMeta, example: chartExample, siblings: [], npm: [] },
  { meta: avatarMeta, example: avatarExample, siblings: [], npm: [] },
  { meta: itemMeta, example: itemExample, siblings: [], npm: [] },
  { meta: typographyMeta, example: typographyExample, siblings: [], npm: ["@radix-ui/react-slot"] },
  { meta: messageMeta, example: messageExample, siblings: ["avatar","badge","spinner"], npm: [] },
  { meta: markerMeta, example: markerExample, siblings: [], npm: [] },
  { meta: attachmentMeta, example: attachmentExample, siblings: ["button"], npm: [] },
  { meta: threadMeta, example: threadExample, siblings: ["marker","scroll-area","scrollbar"], npm: [] },
  { meta: questionnaireMeta, example: questionnaireExample, siblings: ["button","field","fraction","radio-group"], npm: [] },
  { meta: alertMeta, example: alertExample, siblings: ["button"], npm: [] },
  { meta: skeletonMeta, example: skeletonExample, siblings: [], npm: [] },
  { meta: datePickerMeta, example: datePickerExample, siblings: ["calendar","field","popover"], npm: [] },
  { meta: activityFeedMeta, example: activityFeedExample, siblings: ["avatar","collapsible","item","marker"], npm: [] },
  { meta: agentChatMeta, example: agentChatExample, siblings: ["agent-state","attachment","button","dialog","field","kbd","marker","progress","radio-group","thread"], npm: [] },
  { meta: agentStateMeta, example: agentStateExample, siblings: ["marker","spinner"], npm: [] },
  { meta: appearanceMeta, example: appearanceExample, siblings: ["mode-toggle","picks"], npm: [] },
  { meta: areaChartMeta, example: areaChartExample, siblings: ["line-chart"], npm: [] },
  { meta: calligramMeta, example: calligramExample, siblings: [], npm: ["@chenglou/pretext"] },
  { meta: commandLineMeta, example: commandLineExample, siblings: ["radio-group","source"], npm: [] },
  { meta: contourMeta, example: contourExample, siblings: [], npm: ["@chenglou/pretext"] },
  { meta: dataTableMeta, example: dataTableExample, siblings: ["button","pagination","select","table"], npm: [] },
  { meta: dropzoneMeta, example: dropzoneExample, siblings: ["attachment"], npm: ["image"] },
  { meta: figureMeta, example: figureExample, siblings: ["aspect-ratio","meta"], npm: [] },
  { meta: formMeta, example: formExample, siblings: ["button","field"], npm: [] },
  { meta: gatherMeta, example: gatherExample, siblings: [], npm: ["@chenglou/pretext"] },
  { meta: gridMeta, example: gridExample, siblings: [], npm: [] },
  { meta: lineChartMeta, example: lineChartExample, siblings: ["chart"], npm: [] },
  { meta: marqueeMeta, example: marqueeExample, siblings: [], npm: [] },
  { meta: measureMeta, example: measureExample, siblings: [], npm: ["@chenglou/pretext"] },
  { meta: melodyMeta, example: melodyExample, siblings: [], npm: ["@chenglou/pretext"] },
  { meta: modeToggleMeta, example: modeToggleExample, siblings: [], npm: [] },
  { meta: numberInputMeta, example: numberInputExample, siblings: ["button","field"], npm: [] },
  { meta: pieChartMeta, example: pieChartExample, siblings: ["radial-chart"], npm: [] },
  { meta: radarChartMeta, example: radarChartExample, siblings: ["grid"], npm: [] },
  { meta: radialChartMeta, example: radialChartExample, siblings: [], npm: [] },
  { meta: readingTrailMeta, example: readingTrailExample, siblings: ["item","scrollbar"], npm: [] },
  { meta: reverbMeta, example: reverbExample, siblings: [], npm: ["@chenglou/pretext"] },
  { meta: scrollExpandMeta, example: scrollExpandExample, siblings: ["corners","meta"], npm: [] },
  { meta: segueMeta, example: segueExample, siblings: [], npm: [] },
  { meta: sourceMeta, example: sourceExample, siblings: ["button"], npm: ["sugar-high"] },
  { meta: statMeta, example: statExample, siblings: ["fraction"], npm: [] },
  { meta: stepsMeta, example: stepsExample, siblings: ["fraction"], npm: [] },
  { meta: swapyMeta, example: swapyExample, siblings: ["rows"], npm: [] },
  { meta: textRibbonMeta, example: textRibbonExample, siblings: [], npm: ["@chenglou/pretext"] },
  { meta: tilingMeta, example: tilingExample, siblings: [], npm: [] },
  { meta: timerMeta, example: timerExample, siblings: ["button","radial-chart"], npm: [] },
  { meta: tourMeta, example: tourExample, siblings: ["dialog"], npm: [] },
  { meta: treeMeta, example: treeExample, siblings: ["collapsible","item"], npm: [] },
  { meta: wakeMeta, example: wakeExample, siblings: [], npm: ["@chenglou/pretext"] },
  { meta: waterfallMeta, example: waterfallExample, siblings: [], npm: ["@chenglou/pretext"] },
  { meta: wordRelayMeta, example: wordRelayExample, siblings: [], npm: [] },
]
