// Generated by scripts/build-registry.mjs. Every item's docs meta and example, in registry order.
import buttonMeta from "@/content/button"
import * as buttonExample from "@/examples/button"
import spinnerMeta from "@/content/spinner"
import * as spinnerExample from "@/examples/spinner"
import checkboxMeta from "@/content/checkbox"
import * as checkboxExample from "@/examples/checkbox"
import dialogMeta from "@/content/dialog"
import * as dialogExample from "@/examples/dialog"
import tooltipMeta from "@/content/tooltip"
import * as tooltipExample from "@/examples/tooltip"
import sourceMeta from "@/content/source"
import * as sourceExample from "@/examples/source"
import stepsMeta from "@/content/steps"
import * as stepsExample from "@/examples/steps"

export const entries = [
  { meta: buttonMeta, example: buttonExample, siblings: ["spinner"], npm: ["@radix-ui/react-slot"] },
  { meta: spinnerMeta, example: spinnerExample, siblings: [], npm: [] },
  { meta: checkboxMeta, example: checkboxExample, siblings: [], npm: [] },
  { meta: dialogMeta, example: dialogExample, siblings: [], npm: ["@radix-ui/react-slot"] },
  { meta: tooltipMeta, example: tooltipExample, siblings: [], npm: ["@radix-ui/react-tooltip"] },
  { meta: sourceMeta, example: sourceExample, siblings: ["button"], npm: ["sugar-high"] },
  { meta: stepsMeta, example: stepsExample, siblings: [], npm: [] },
]
