import { readFileSync } from "node:fs"
import { createHash } from "node:crypto"
import { sitePath } from "../../lib/site/config.mjs"

export const packageHeaders = (headers) => headers.split("\n").map((line) => line.startsWith("/") ? sitePath(line) : line).join("\n")

/** Docs fonts use files; installed registry fonts keep their portable data URLs. */
export function siteFonts() {
  const files = new Map()
  const faces = []
  for (const pair of ["fonts", "fonts-press", "fonts-paris", "fonts-salon"]) {
    const source = readFileSync(`registry/0nlytype/styles/${pair}.css`, "utf8")
    for (const [face] of source.matchAll(/@font-face \{[^}]+\}/g)) {
      const family = face.match(/font-family: "([^"]+)"/)[1].toLowerCase().replaceAll(" ", "-")
      const style = face.match(/font-style: ([^;]+)/)[1]
      const data = face.match(/url\(data:font\/woff2;base64,([^)]+)\)/)[1]
      const bytes = Buffer.from(data, "base64")
      const hash = createHash("sha256").update(bytes).digest("hex").slice(0, 10)
      const name = `${family}-${style}-${hash}.woff2`
      files.set(name, bytes)
      faces.push(face.replace(/url\(data:font\/woff2;base64,[^)]+\)/, `url("${sitePath(`/fonts/${name}`)}")`)
        .replace("font-display: swap", `font-display: ${pair === "fonts" ? "optional" : "swap"}`))
    }
  }
  return { css: "/* Generated by scripts/build-registry.mjs from the portable registry fonts. */\n\n" + faces.join("\n\n") + "\n", files }
}
