type Script = "check" | "choice" | "switch" | "range" | "number" | "text" | "select" | "tabs" | "toggle" | "accordion" | "details" | "calendar" | "drop" | "chart" | "radial" | "pie" | "radar" | "resize" | "measure" | "action" | "scroll" | "carousel" | "note" | "table" | "wake" | "melody" | "tree" | "swapy" | "tiling" | "relay" | "timer"
type Score = { script: Script; phrase: string } | { script: null; reason: string }
const play = (script: Script, phrase: string): Score => ({ script, phrase })
const rest = (reason: string): Score => ({ script: null, reason })

/** Deliberate coverage, not a selector that clicks whatever happens to be on the page.
 * The same score serves the docs Example and the landing's fitted variations. */
export const DEMO_SCORES: Record<string, Score> = {
  "footnotes": rest("Reference navigation moves the reading position; follow a reference deliberately."),
  "accordion": play("accordion", "The second answer opens, then the first returns"),
  "activity-feed": play("details", "Open the older entries and put them away"),
  "agent-chat": play("text", "Compose a timetable request without sending it"),
  "agent-state": play("action", "Ready, thinking, working, ready"),
  "alert": rest("Messages already say their state; the example actions have no outcome."),
  "appearance": rest("Would change the reader's saved site preferences."),
  "area-chart": play("chart", "Read two months across the series"),
  "aspect-ratio": play("toggle", "Choose a square, then a landscape crop"),
  "attachment": play("action", "Send two more local parts of the example attachment"),
  "avatar": rest("Identity specimen; spreading or hover alone adds no state to explain."),
  "badge": rest("Removing an example tag deliberately moves focus to the next tag."),
  "breadcrumb": rest("Navigation belongs to the reader; no local state change."),
  "button": rest("These example actions are labels without outcomes; no pretend hover."),
  "button-group": rest("Grouped example actions have no local outcomes."),
  "calendar": play("calendar", "Choose an available day and the next one"),
  "calligram": rest("A typographic composition, without an interaction."),
  "card": rest("A linked specimen; no local state to demonstrate."),
  "carousel": play("carousel", "The next project arrives, then the first returns"),
  "chart": play("chart", "Two months answer with their actual figures"),
  "checkbox": play("check", "One task completes, another answers, then both return"),
  "collapsible": play("details", "Read what is folded away, then close it"),
  "combobox": play("text", "Find Garamond and Halden in the actual options"),
  "command": play("text", "Search for Halden in both live indexes"),
  "command-line": play("text", "Fill the synopsis with a component name; never copy or execute"),
  "context-menu": rest("Requires the reader's context click; landing layers are pinned specimens."),
  "contour": rest("Text composition; hover-only emphasis would be decorative."),
  "corners": rest("Framing specimen; simulated hover would not explain an outcome."),
  "data-table": play("table", "Sort the local project rows by kind and year"),
  "date-picker": rest("Opening its portalled calendar would move the reader's focus."),
  "dial": play("range", "Set a nearby tempo, volume and year, with the arc answering"),
  "dialog": rest("Opening a modal would take focus and block the documentation."),
  "drawer": rest("A modal drawer would take focus and cover the documentation."),
  "dropdown-menu": rest("Opening the menu would take keyboard focus; landing menus are pinned."),
  "dropzone": play("drop", "A small local SVG arrives and is accepted by both drop zones"),
  "empty": rest("The empty state is the content; its example actions have no outcomes."),
  "field": play("text", "Write Ada and a short project brief"),
  "figure": play("toggle", "Recrop the photograph using its actual ratio controls"),
  "form": play("text", "Write a name and email without submitting"),
  "fraction": play("action", "Complete one, then one more, of the real tally"),
  "gather": rest("Has its own once-on-arrival entrance; replay would require remounting the text."),
  "grid": rest("A static construction grid, without a control."),
  "hover-card": rest("Portalled supporting content needs the reader's intentional hover."),
  "input-group": play("text", "Search for Halden and write a studio email"),
  "input-otp": play("text", "Type the documented valid code, 246810"),
  "item": rest("Linked rows have no safe local state change."),
  "kbd": rest("A key legend, not an input; no artificial key press."),
  "line-chart": play("chart", "Read two months along the line"),
  "link": rest("Navigation belongs to the reader; no fake hover or navigation."),
  "marker": play("action", "Draw the section marks once and let them settle"),
  "marquee": rest("Already has its own approved, pausable drift and reduced-motion behavior."),
  "measure": play("measure", "Narrow the reading measure and restore it"),
  "melody": play("melody", "Sound a phrase with its own arpeggio, then let it rest"),
  "menubar": rest("Menu activation takes focus; the reader should open it deliberately."),
  "message": play("toggle", "Add and remove a real reaction; leave sending to the reader"),
  "meta": rest("Static metadata, without an interaction."),
  "mode-toggle": rest("Would change the reader's saved day/nocturne preference."),
  "navigation-menu": rest("Navigation and its portalled panels belong to the reader."),
  "note": play("note", "An abbreviation unfolds and a correction replaces its word"),
  "number-input": play("number", "Increase each example by its own step, then return"),
  "pagination": rest("Its local paging example moves keyboard focus after each change."),
  "picks": play("choice", "Choose the next paper, ink and format"),
  "pie-chart": play("pie", "Read two named shares of the whole"),
  "popover": rest("Opening a portal can take focus; landing popovers are pinned."),
  "progress": rest("The docs upload owns a random timed loop that cannot hand over immediately; use its Upload control."),
  "questionnaire": play("choice", "Choose a website, then an identity, without submitting"),
  "radar-chart": play("radar", "Measure two real axes"),
  "radial-chart": play("radial", "Read two named rings"),
  "radio-group": play("choice", "One choice leads, the other variations answer"),
  "reading-trail": rest("Tracks the reader's page scroll; autoplay must not move their page."),
  "resizable": play("resize", "Move the divider with its supported keyboard controls"),
  "reverb": rest("Hover-only echoes; no independent state change to demonstrate."),
  "rows": rest("Navigation rows; no fake hover or automatic navigation."),
  "scroll-area": play("scroll", "Read on inside each bounded scroll area, then return"),
  "scrollbar": play("scroll", "Move only the specimen's local scroll containers"),
  "scroll-expand": rest("Docs plates follow page scroll; autoplay must not move the reader's page."),
  "segue": play("action", "Go to the next local scene, then the one after it"),
  "select": play("select", "Choose actual options, then restore the defaults"),
  "sheet": rest("Opening a modal sheet would take focus and cover the page."),
  "sidebar": rest("App navigation and folding would distract from the docs."),
  "skeleton": rest("A loading placeholder already expresses its state."),
  "slider": play("range", "Volume and brightness rise gently, then return"),
  "source": rest("Copying would overwrite the reader's clipboard."),
  "spinner": rest("Already expresses ongoing work through its own motion."),
  "stat": play("select", "Compare the studio's real example years"),
  "steps": play("action", "Advance the brief together, then return"),
  "swapy": play("swapy", "Pick up a row, move it down, and set it down"),
  "switch": play("switch", "A lead switch changes, the others answer, all return"),
  "table": play("table", "Sort the actual project rows by another column"),
  "tabs": play("tabs", "Read the next panel and return to the first"),
  "text-ribbon": rest("Already has its own approved, pausable drift and reduced-motion behavior."),
  "thread": play("action", "Ask for one local update and let the new message arrive"),
  "tiling": play("tiling", "Pick up the first tile, move a column, then set it down"),
  "timer": play("timer", "Start the local clock, read it, then pause"),
  "toast": rest("Would announce and display a page-wide notification outside the example."),
  "toggle": play("toggle", "Pin, keep and mute, with the variations answering one another"),
  "toggle-group": play("toggle", "A format changes; the other choice groups answer"),
  "tooltip": rest("Transient portalled help belongs to the reader's hover or focus."),
  "tour": rest("A tour would take focus and guide the reader away from the example."),
  "tree": play("tree", "Open a folder in each tree, then close it"),
  "typography": rest("A reading specimen, without an interaction."),
  "wake": play("wake", "Draw one smooth passage through the text, then let it close"),
  "waterfall": rest("A typographic specimen; solo hover alone is not a state demo."),
  "word-relay": play("relay", "Read the next word, hold it, then the next"),
}

