// Writes the pair stylesheets from @fontsource-variable, Latin subset only, as
// data URIs so an install never has to place files in public/ (as 000h does).
// Voices are upright with every axis; expressions are italic only, because
// 0dB only ever sets the expression face in italic.
import { readFileSync, writeFileSync } from "node:fs";

const pairs = {
  fonts: [["archivo", "standard.css", "Archivo"], ["bodoni-moda", "standard-italic.css", "Bodoni Moda"]],
  "fonts-press": [["schibsted-grotesk", "wght.css", "Schibsted Grotesk"], ["newsreader", "standard-italic.css", "Newsreader"]],
  "fonts-paris": [["instrument-sans", "standard.css", "Instrument Sans"], ["eb-garamond", "wght-italic.css", "EB Garamond"]],
  "fonts-salon": [["bricolage-grotesque", "standard.css", "Bricolage Grotesque"], ["cormorant", "wght-italic.css", "Cormorant"]],
};

for (const [out, faces] of Object.entries(pairs)) {
  let css = `/* 0dB · ${out === "fonts" ? "the default pair, Parma" : out.replace("fonts-", "the ") + " pair"}. Latin subset, SIL Open Font License 1.1 (see FONT-NOTICES.md). Generated by scripts/build-fonts.mjs. */\n`;
  for (const [pkg, file, family] of faces) {
    const dir = `node_modules/@fontsource-variable/${pkg}`;
    const src = readFileSync(`${dir}/${file}`, "utf8");
    const block = src.split("/* ").find((b) => /^[a-z-]+-latin-[a-z]+-(normal|italic) \*\//.test(b) && !b.includes("-latin-ext-"));
    if (!block) throw new Error(`no latin block in ${pkg}/${file}`);
    const url = block.match(/url\(\.\/files\/([^)]+)\)/)[1];
    const data = readFileSync(`${dir}/files/${url}`).toString("base64");
    css += block
      .slice(block.indexOf("@font-face"))
      .replace(/font-family: '[^']+'/, `font-family: "${family}"`)
      .replace(/url\([^)]+\) format\('woff2-variations'\)/, `url(data:font/woff2;base64,${data}) format("woff2")`)
      .trim() + "\n";
  }
  writeFileSync(`registry/0db/styles/${out}.css`, css);
  console.log(out, (css.length / 1024).toFixed(0) + "K");
}
